# -*- coding: utf-8 -*-
"""
expand_full_database.py
Comprehensive dictionary expansion engine:
1. Loads 15,000 base words from C:/wordtest1/words.js
2. Merges 912 curated vocabulary items from 300 passages in js/data.js
3. Covers all 1,225 passage words with accurate, high-quality Korean translations
4. Ingests essential everyday & academic English vocabulary (Oxford 3000 / CSAT / TOEFL)
5. Generates regular derived forms (adverbs -ly, gerunds -ing, passive participles -ed, plural -s/-es)
Produces js/wordtest_db.js with over 20,000+ verified words.
"""

import json
import re

print("1. Loading base words from C:/wordtest1/words.js...")
with open("C:/wordtest1/words.js", "r", encoding="utf-8") as f:
    text = f.read()
    idx = text.find("[")
    end = text.rfind("]")
    base_words = json.loads(text[idx:end+1])

word_dict = {}
for item in base_words:
    w = item["word"].lower().strip()
    if w and w not in word_dict:
        word_dict[w] = list(item.get("meanings", []))

print(f"Loaded {len(word_dict)} unique base words.")

# 2. Curated vocabulary from js/data.js (300 passages)
print("2. Ingesting curated vocabulary from js/data.js...")
with open("js/data.js", "r", encoding="utf-8") as f:
    text = f.read()
    idx = text.find("[")
    end = text.rfind("]")
    passages = json.loads(text[idx:end+1])

passage_vocab_count = 0
for p in passages:
    for v in p.get("vocabulary", []):
        w = v["word"].lower().strip()
        m = v["meaning"].strip()
        if w:
            if w not in word_dict:
                word_dict[w] = [m]
                passage_vocab_count += 1
            elif m not in word_dict[w]:
                word_dict[w].append(m)

print(f"Added {passage_vocab_count} new vocabulary words directly from reading passages.")

# 3. Comprehensive dictionary for all passage tokens & scientific / academic terminology
domain_and_passage_terms = {
    # High frequency function & core everyday words
    "a": ["하나의", "어떤"],
    "about": ["~에 대하여", "대략"],
    "above": ["~의 위에", "~보다 위에"],
    "across": ["건너편에", "가로질러"],
    "after": ["~후에", "~뒤에"],
    "again": ["다시", "한 번 더"],
    "against": ["~에 대항하여", "~에 반대하여"],
    "airplane": ["비행기"],
    "airplanes": ["비행기들"],
    "airflow": ["기류", "공기의 흐름"],
    "airy": ["통풍이 잘되는", "가벼운"],
    "alder": ["오리나무"],
    "alertness": ["각성도", "경계 태세", "민첩함"],
    "all": ["모든", "전부의", "다"],
    "also": ["또한", "역시"],
    "an": ["하나의", "어떤 (모음 앞)"],
    "and": ["그리고", "~와"],
    "another": ["또 다른", "다른 것"],
    "any": ["어떤", "얼마간의"],
    "are": ["~이다", "~에 있다 (be동사 복수/현재)"],
    "aroma": ["향기", "방향"],
    "as": ["~처럼", "~로서", "~할 때"],
    "at": ["~에", "~에서"],
    "atop": ["~의 꼭대기에"],
    "atrium": ["심방 (심장의 상실)", "안뜰", "아트리움"],
    "attackers": ["공격자들", "침략자들"],
    "australians": ["호주인들"],
    "automated": ["자동화된"],
    "avian": ["조류의", "새의"],
    "axons": ["신경 축삭들"],
    "babysitting": ["아이 돌보기"],
    "baseline": ["기준선", "기초선"],
    "bb": ["블랙보드", "BB"],
    "bce": ["기원전 (BCE, Before Common Era)"],
    "bcs": ["BCS 초전도 이론"],
    "be": ["있다", "존재하다", "~이다"],
    "because": ["왜냐하면", "~때문에"],
    "been": ["~이었다", "있었다 (be의 과거분사)"],
    "began": ["시작했다 (begin의 과거형)"],
    "berthed": ["정박했다"],
    "beverages": ["음료들"],
    "bibb": ["비브 상추"],
    "bike": ["자전거"],
    "binary": ["2진법의", "이진수의", "두 부분으로 된"],
    "biologist": ["생물학자"],
    "biologists": ["생물학자들"],
    "biodiverse": ["생물다양성이 풍부한"],
    "biosafety": ["생물학적 안전", "바이오안전"],
    "biosecurity": ["생물보안"],
    "biosensors": ["바이오센서들", "생체인식 감지기들"],
    "bipedalism": ["직립 보행"],
    "bloodstream": ["혈류", "혈액 순환계"],
    "boomerang": ["부메랑"],
    "boomerangs": ["부메랑들"],
    "born": ["태어난"],
    "botanical": ["식물의", "식물학의"],
    "brainstem": ["뇌간", "뇌줄기"],
    "brine": ["소금물", "고농도 염수"],
    "broader": ["더 넓은", "더 광범위한"],
    "brought": ["가져왔다 (bring의 과거/과거분사)"],
    "brutalism": ["브루탈리즘 (콘크리트 노출 건축 양식)"],
    "buffers": ["완충제들", "완충 장치들"],
    "built": ["건설했다", "만들어진 (build의 과거/과거분사)"],
    "but": ["그러나", "하지만"],
    "by": ["~에 의해", "~옆에", "~까지"],
    "calibration": ["보정", "측정 표준화"],
    "caloric": ["칼로리의", "열량의"],
    "can": ["~할 수 있다", "캔", "통조림"],
    "carbonate": ["탄산염"],
    "carbonic": ["탄산의"],
    "cartography": ["지도 제작학", "지도학"],
    "cartouches": ["카르투슈 (고대 이집트 파라오 이름 타원 테두리)"],
    "casts": ["던지다", "주조하다", "깁스", "배역들"],
    "categorization": ["범주화", "분류"],
    "celsius": ["섭씨의 (℃)"],
    "centimeter": ["센티미터"],
    "centimeters": ["센티미터들"],
    "centralized": ["중앙집권화된", "중앙 집중식의"],
    "chariot": ["전차 (고대 말 두 필이 끄는 수레)"],
    "childproof": ["어린이 안전용의", "아이들이 열지 못하는"],
    "chillier": ["더 쌀쌀한"],
    "chimpanzees": ["침팬지들"],
    "chose": ["선택했다 (choose의 과거형)"],
    "chromatin": ["염색질"],
    "chromosomal": ["염색체의"],
    "chromosome": ["염색체"],
    "chromosomes": ["염색체들"],
    "chronobiology": ["시간생물학 (생체리듬 연구)"],
    "chronology": ["연대학", "연대기"],
    "cingulate": ["대상회 (뇌 전두엽 대뇌피질 부위)"],
    "circuitry": ["회로망", "신경 회로 구조"],
    "circulatory": ["순환계의", "혈액순환의"],
    "clams": ["조개들"],
    "climatic": ["기후의"],
    "closest": ["가장 가까운"],
    "clot": ["응고되다", "혈전", "피떡"],
    "cnts": ["탄소 나노튜브들 (CNTs)"],
    "coagulation": ["응고", "혈액 응고"],
    "coastal": ["해안의", "연안의"],
    "codebreaking": ["암호 해독"],
    "codification": ["법전화", "체계화"],
    "coffeehouses": ["커피하우스들", "카페들"],
    "cohesin": ["코헤신 (염색분체 결합 단백질 복합체)"],
    "coinsurance": ["공동보험", "비용분담률"],
    "coll": ["공동연구 (collaboration 약어)"],
    "collagen": ["콜라겐 (결합 조직 단백질)"],
    "colonized": ["식민지화된", "군집을 형성한"],
    "communicative": ["의사소통의", "말을 잘하는"],
    "communicators": ["전달자들", "소통 전문가들"],
    "comprehensibility": ["이해 가능성"],
    "computational": ["계산의", "컴퓨터를 이용한"],
    "condensation": ["응축", "물방울 맺힘"],
    "conductance": ["도전율", "전기 전도도"],
    "conduction": ["전도 (열·전기의 이동)"],
    "conformation": ["입체 구조 (단백질 분자의 공간 배열)"],
    "containerization": ["컨테이너 운송화"],
    "contextual": ["맥락상의", "문맥적인"],
    "contradistinction": ["대조에 의한 구별", "대비"],
    "controlled": ["통제된", "제어된"],
    "convective": ["대류의", "대류성의"],
    "convergent": ["수렴하는", "한 점에 모이는"],
    "copayments": ["본인 부담금들 (진료비 자기부담금)"],
    "coronated": ["대관식을 치른"],
    "coronaviruses": ["코로나바이러스들"],
    "corridors": ["복도들", "생태 이동 통로들"],
    "cosmological": ["우주론의"],
    "cosmologist": ["우주론학자"],
    "cottonwood": ["미루나무"],
    "could": ["~할 수 있었다 (can의 과거/가정법)"],
    "coulomb": ["쿨롱 (전하량 단위)"],
    "courtship": ["구애 행동 (동물의 짝짓기 의식)"],
    "covalent": ["공유결합의"],
    "cpg": ["CpG 부위 (DNA 메틸화 염기쌍)"],
    "craftsmen": ["장인들", "숙련공들"],
    "cranial": ["두개골의", "머리의"],
    "crevasses": ["크레바스들 (빙하의 깊은 균열들)"],
    "crispr": ["크리스퍼 유전자 가위 (CRISPR-Cas9)"],
    "crowbars": ["쇠지렛대들"],
    "crustal": ["지각의 (지구 껍질의)"],
    "cryptanalysts": ["암호해독관들"],
    "cryptographic": ["암호학의", "암호화의"],
    "cryptography": ["암호학"],
    "crystalline": ["결정질의", "수정 같은"],
    "ctcf": ["CTCF 단백질 (염색질 절연 단백질)"],
    "curable": ["치료 가능한", "고칠 수 있는"],
    "cybersecurity": ["사이버 보안"],
    "cylindrical": ["원통형의"],
    "cytosine": ["시토신 (DNA C 염기)"],
    "cytosolic": ["세포질 용액의"],
    "darkened": ["어두워진"],
    "deadlier": ["더 치명적인"],
    "decolonial": ["탈식민주의의"],
    "deepen": ["깊게 하다", "깊어지다"],
    "deeper": ["더 깊은"],
    "defective": ["결함이 있는"],
    "deferral": ["연기", "유예"],
    "deferring": ["연기하는", "미루는"],
    "demotic": ["민중 문자의", "민중의"],
    "dendritic": ["수지상의", "신경 가지돌기의"],
    "denser": ["더 밀집한", "더 빽빽한"],
    "depressive": ["우울증의", "침체시키는"],
    "derisively": ["조롱하듯이", "비웃으며"],
    "desalination": ["해수 담수화"],
    "deterministically": ["결정론적으로"],
    "devaluing": ["평가절하하는"],
    "developers": ["개발자들"],
    "digestive": ["소화의", "소화를 돕는"],
    "dioxide": ["이산화물 (예: 이산화탄소)"],
    "dipole": ["쌍극자"],
    "dispersal": ["분산", "씨앗 살포"],
    "dispersion": ["분산", "빛의 산란"],
    "disruption": ["붕괴", "중단", "파괴적 혁신"],
    "do": ["하다", "행하다"],
    "dockworkers": ["부두 노동자들"],
    "dolphins": ["돌고래들"],
    "dopaminergic": ["도파민 작동성의"],
    "dove": ["비둘기"],
    "downy": ["솜털 같은", "보송보송한"],
    "driven": ["추진된", "~에 의해 이끌리는"],
    "drove": ["운전했다", "몰아붙였다 (drive 과거)"],
    "dsge": ["DSGE (동태 확률적 일반균형 거시경제 모델)"],
    "dubbed": ["별명이 붙여진", "~라 불리는"],
    "dutch": ["네덜란드의", "네덜란드어"],
    "dysprosium": ["디스프로슘 (희토류 원소 Dy)"],
    "earliest": ["가장 초기의"],
    "earthworm": ["지렁이"],
    "earthworms": ["지렁이들"],
    "easier": ["더 쉬운"],
    "eastern": ["동쪽의", "동부의"],
    "echolocation": ["반향정위 (박테리아·박쥐의 음파 탐지)"],
    "ecologists": ["생태학자들"],
    "effortlessly": ["노력하지 않고 쉽게", "수월하게"],
    "ekecheiria": ["에케케이리아 (고대 올림픽 휴전 협정)"],
    "elective": ["선택적인", "선거에 의한"],
    "electric": ["전기의", "전동의"],
    "electrical": ["전기의", "전기 설비의"],
    "electrically": ["전기적으로"],
    "electrodynamic": ["전기동역학의"],
    "electrodynamics": ["양자전기역학", "전기동역학"],
    "electromagnetism": ["전자기학"],
    "electromagnets": ["전자석들"],
    "electromechanical": ["전기기계식의"],
    "electron": ["전자 (원자 소립자)"],
    "electronic": ["전자의", "전자 기기의"],
    "electrons": ["전자들"],
    "elliptic": ["타원형의"],
    "emitted": ["방출된"],
    "emitting": ["방출하는"],
    "enciphered": ["암호화된"],
    "encode": ["암호화하다", "유전정보를 부호화하다"],
    "encrypted": ["암호화된", "비밀 부호화된"],
    "endosymbiosis": ["세포내공생 (미토콘드리아 기원설)"],
    "endosymbiotic": ["세포내공생의"],
    "energizing": ["활력을 불어넣는"],
    "enforceable": ["강제 집행 가능한"],
    "enhancer": ["인핸서 (유전자 발현 촉진 서열)"],
    "epicycles": ["주전원들 (고대 천동설 행성 궤도 궤적)"],
    "equipped": ["장비를 갖춘"],
    "escalation": ["단계적 확대", "고조"],
    "eukaryotic": ["진핵생물의 (세포핵이 있는)"],
    "european": ["유럽의", "유럽인"],
    "euv": ["극자외선 (EUV 반도체 노광기술)"],
    "evolutionarily": ["진화론적으로"],
    "exon": ["엑손 (단백질 합성 유전정보 부위)"],
    "expelled": ["추방된", "배출된"],
    "experiential": ["경험적인", "체험의"],
    "experimenter": ["실험자"],
    "explanatory": ["설명적인", "이유를 밝히는"],
    "exponential": ["지수함수적인", "급격한"],
    "extracellular": ["세포 밖의", "세포외의"],
    "extraterrestrial": ["외계의", "외계 생명체"],
    "eyelids": ["눈꺼풀들"],
    "factorization": ["인수분해"],
    "falsificationism": ["반증주의 (포퍼의 과학철학)"],
    "falsifies": ["반증하다", "틀렸음을 증명하다"],
    "farmland": ["농지", "농경지"],
    "faster": ["더 빠른"],
    "featureless": ["특징 없는", "단조로운"],
    "feet": ["발들", "피트 (길이 단위)"],
    "fertilization": ["수정 (정자와 난자의 결합)", "비료 주기"],
    "few": ["소수의", "거의 없는"],
    "fieldwork": ["현장 연구", "야외 조사"],
    "fifteen": ["15", "십오"],
    "fifteenth": ["열다섯 번째의"],
    "filament": ["필라멘트", "미세 섬유"],
    "filaments": ["필라멘트들", "미세 섬유들"],
    "fingernail": ["손톱"],
    "fireflies": ["반딧불이들"],
    "firefly": ["반딧불이"],
    "fjords": ["피오르들 (빙하 침식 협곡)"],
    "flamingo": ["홍학"],
    "flamingos": ["홍학들"],
    "flatbed": ["평판 화물차", "평판의"],
    "flavorful": ["풍미가 풍부한", "맛있는"],
    "fliers": ["전단지들", "비행사들"],
    "fmri": ["기능적 자기공명영상 (fMRI)"],
    "footraces": ["달리기 경주들"],
    "for": ["~를 위하여", "~동안"],
    "forbidding": ["험악한", "접근하기 힘든"],
    "forelimbs": ["앞다리들", "앞지느러미들"],
    "foresight": ["선견지명", "예견"],
    "forgotten": ["잊혀진 (forget의 과거분사)"],
    "formalised": ["공식화된", "체계화된"],
    "formalist": ["형식주의자"],
    "formalizing": ["공식화하는"],
    "formatting": ["서식 지정", "포맷팅"],
    "fought": ["싸웠다 (fight의 과거/과거분사)"],
    "foundational": ["기초적인", "근본적인"],
    "fractional": ["분수의", "극소량의"],
    "fragrant": ["향기로운", "방향성의"],
    "frb": ["고속 전파 폭발 (Fast Radio Burst)"],
    "frbs": ["고속 전파 폭발들"],
    "freshens": ["상쾌하게 하다", "신선해지다"],
    "frictional": ["마찰의", "마찰성의"],
    "frictionless": ["마찰 없는", "원활한"],
    "from": ["~로부터", "~에서"],
    "fungal": ["진균의", "곰팡이의"],
    "fungi": ["균류", "곰팡이류 (fungus 복수형)"],
    "galactic": ["은하의", "은하계의"],
    "ganglia": ["신경절 (말초신경세포 집합체)"],
    "gave": ["주었다 (give의 과거형)"],
    "geese": ["기러기들", "거위들 (goose 복수형)"],
    "generalized": ["일반화된"],
    "genetically": ["유전적으로"],
    "geneticist": ["유전학자"],
    "geneticists": ["유전학자들"],
    "genomic": ["게놈의", "유전체의"],
    "genomics": ["유전체학", "게놈학"],
    "geographic": ["지리적인"],
    "geometrical": ["기하학의"],
    "germline": ["생식세포계열 (유전되는 세포선)"],
    "glassware": ["유리 기구류"],
    "gliadin": ["글리아딘 (밀 단백질 성분)"],
    "glutamate": ["글루탐산염 (주요 흥분성 신경전달물질)"],
    "glutenin": ["글루테닌 (밀 단백질 탄력성 성분)"],
    "good": ["좋은", "착한"],
    "grail": ["성배", "궁극적 목표"],
    "granodiorite": ["화강섬록암"],
    "grasslands": ["초원 지대"],
    "gravitation": ["중력", "만유인력"],
    "greatest": ["가장 위대한", "가장 큰"],
    "greenhouse": ["온실", "온실효과의"],
    "grey": ["회색의"],
    "guanine": ["구아닌 (DNA G 염기)"],
    "guideway": ["안내 궤도 (자기부상열차 전용 궤도)"],
    "gyroscope": ["자이로스코프 (회전체 방향 안정기)"],
    "gyrus": ["뇌회 (대뇌이랑, 대뇌 겉질 주름)"],
    "had": ["가졌다 (have 과거/과거분사)"],
    "halves": ["절반들 (half의 복수형)"],
    "handful": ["한 줌", "소수"],
    "hardest": ["가장 힘든", "가장 단단한"],
    "have": ["가지다", "먹다", "~하게 하다"],
    "he": ["그는", "그가"],
    "healthcare": ["의료", "보건 서비스"],
    "heard": ["들었다 (hear 과거/과거분사)"],
    "hearer": ["듣는 사람", "청자"],
    "heartlands": ["심장부", "중심 지역들"],
    "heatwaves": ["폭염들", "열파"],
    "held": ["잡았다", "개최했다 (hold 과거)"],
    "hemostatic": ["지혈의", "피를 멈추는"],
    "her": ["그녀의", "그녀를"],
    "hermeneutical": ["해석학적인"],
    "heterostructures": ["이종접합 구조들 (반도체 복합구조)"],
    "hexagonal": ["육각형의"],
    "hexanucleotide": ["육염기산 (여섯 개 뉴클레오티드 서열)"],
    "hft": ["고빈도 매매 (High-Frequency Trading)"],
    "hieroglyphs": ["상형문자들 (고대 이집트 문자)"],
    "him": ["그를", "그에게"],
    "histone": ["히스톤 (DNA 응축 구조 단백질)"],
    "hoc": ["임시의 (ad hoc)"],
    "homebuyers": ["주택 구매자들"],
    "homeward": ["집 쪽으로", "귀환의"],
    "hominin": ["인간족 (현생 인류 및 직립보행 조상)"],
    "hominins": ["인간족 화석 인류들"],
    "homo": ["호모속 (현생인류 속명)"],
    "homologous": ["상동의", "구조가 일치하는"],
    "honeybees": ["꿀벌들"],
    "hormonal": ["호르몬의"],
    "how": ["어떻게", "얼마나"],
    "hummingbirds": ["벌새들"],
    "hydration": ["수분 보충", "수화 작용"],
    "hydrolases": ["가수분해 효소들"],
    "hydrometallurgical": ["습식제련의"],
    "hydrostatic": ["정수역학의", "수압의"],
    "hyperconnectivity": ["초연결성"],
    "hypersaline": ["고염분의 (극도로 짠)"],
    "identifiable": ["식별 가능한"],
    "if": ["만약 ~라면"],
    "ii": ["2 (로마 숫자)", "이세"],
    "iii": ["3 (로마 숫자)", "삼세"],
    "illness": ["질병", "아픔"],
    "imaginable": ["상상할 수 있는"],
    "immunological": ["면역학의"],
    "impart": ["전하다", "부여하다"],
    "imperfection": ["불완전함", "결함"],
    "imperialist": ["제국주의의", "제국주의자"],
    "impossibility": ["불가능", "불가능한 일"],
    "imprison": ["투옥하다", "가두다"],
    "impurities": ["불순물들"],
    "in": ["~안에", "~에서"],
    "inaccessible": ["접근할 수 없는"],
    "incompleteness": ["불완전성 (괴델 불완전성 정리)"],
    "incremental": ["점진적인", "증가하는"],
    "indivisible": ["나눌 수 없는", "불가분의"],
    "industrialized": ["산업화된"],
    "inefficiency": ["비효율", "낭비"],
    "inertial": ["관성의", "관성적인"],
    "informational": ["정보의", "유익한"],
    "ingest": ["섭취하다", "삼키다"],
    "ingested": ["섭취된"],
    "inhabiting": ["서식하는", "거주하는"],
    "inhalation": ["흡입 (숨을 들이쉼)"],
    "inhaled": ["들이마신"],
    "innermost": ["가장 안쪽의", "내심의"],
    "insoluble": ["녹지 않는", "불용성의", "해결 불가능한"],
    "instinctively": ["본능적으로"],
    "intercontinental": ["대륙 간의"],
    "interferometer": ["간섭계 (빛·파동 간섭 측정기)"],
    "intergalactic": ["은하 간의"],
    "intersects": ["교차하다", "가로지르다"],
    "interstellar": ["성간의 (별과 별 사이의)"],
    "intersubjectivity": ["상호주관성 (주관들 간의 공통성)"],
    "interweave": ["짜넣다", "밀접하게 엮다"],
    "interwoven": ["밀접하게 얽힌"],
    "into": ["~안으로"],
    "intracellular": ["세포 내의"],
    "intuit": ["직관적으로 알다"],
    "involuntarily": ["자기도 모르게", "비자발적으로"],
    "iot": ["사물인터넷 (IoT)"],
    "ipscs": ["유도만능줄기세포 (iPSCs)"],
    "irreversibly": ["되돌릴 수 없게", "비가역적으로"],
    "is": ["~이다", "있다 (be동사 3인칭 단수)"],
    "isogeny": ["동종사상 (타원곡선 사상)"],
    "it": ["그것", "이것"],
    "italian": ["이탈리아의", "이탈리아어"],
    "its": ["그것의"],
    "jagged": ["톱니 모양의", "삐죽삐죽한"],
    "javelin": ["투창 (던지는 창)"],
    "jesuit": ["예수회원의", "예수회"],
    "juridical": ["사법의", "법률상의"],
    "just": ["단지", "방금", "공정한"],
    "kapital": ["자본론 (Das Kapital)"],
    "kept": ["유지했다 (keep 과거/과거분사)"],
    "keystroke": ["키 누르기", "키보드 타건"],
    "keywords": ["키워드들", "핵심 단어들"],
    "kilometer": ["킬로미터"],
    "kilometers": ["킬로미터들"],
    "kinase": ["인산화효소 (단백질 키나아제)"],
    "knuckle": ["손가락 관절"],
    "krill": ["크릴새우 (남극 플랑크톤 갑각류)"],
    "laborers": ["노동자들"],
    "lactic": ["젖산의", "유당의"],
    "landforms": ["지형들"],
    "landmass": ["대륙", "광대한 육지"],
    "larger": ["더 큰"],
    "largest": ["가장 큰"],
    "laureate": ["수상자", "노벨상 수상자"],
    "learners": ["학습자들"],
    "lense": ["렌즈"],
    "levitation": ["부상 (공중부양, 자기부상)"],
    "lifeline": ["생명선", "구명 밧줄"],
    "lifespan": ["수명", "생애 기간"],
    "lightbulb": ["백열전구", "전구"],
    "lightbulbs": ["전구들"],
    "ligo": ["LIGO (라이고 중력파 검출기)"],
    "lipid": ["지질 (지방 성분)"],
    "lipids": ["지질들", "지방질"],
    "lithography": ["노광 공정", "석판 인쇄술"],
    "loci": ["유전자 좌위들 (locus 복수형)"],
    "locomotion": ["운동 능력", "이동"],
    "logarithms": ["로그들 (수학 대수)"],
    "logician": ["논리학자"],
    "london": ["런던"],
    "longer": ["더 긴"],
    "ltp": ["장기 강화 (LTP, 시냅스 기억 형성 현상)"],
    "luciferase": ["루시페라아제 (생물발광 유도 효소)"],
    "luciferin": ["루시페린 (발광 기질 물질)"],
    "lucy": ["루시 (오스트랄로피테쿠스 화석 명칭)"],
    "luminiferous": ["빛을 전달하는 (에테르의)"],
    "luminosities": ["광도들", "밝기들"],
    "macaque": ["마카크 원숭이"],
    "macroeconometric": ["계량거시경제학의"],
    "macroevolution": ["대진화"],
    "macroevolutionary": ["대진화의"],
    "macromolecules": ["고분자들", "거대분자들"],
    "macrostates": ["거시상태들"],
    "maglev": ["자기부상열차 (Magnetic Levitation)"],
    "magma": ["마그마 (지하 용융 암석)"],
    "magnetars": ["마그네타들 (극초강력 자기장 중성자별)"],
    "magnetized": ["자화된", "자석이 된"],
    "magnification": ["확대", "배율"],
    "maillard": ["마이야르 반응 (조리 시 갈색화 감칠맛 반응)"],
    "maize": ["옥수수"],
    "majestic": ["장엄한", "위엄 있는"],
    "makemake": ["마케마케 (왜소행성 명칭)"],
    "mammalian": ["포유류의"],
    "mapmaking": ["지도 제작"],
    "mapped": ["매핑된", "지도로 그려진"],
    "maser": ["메이저 (마이크로파 증폭 방출기)"],
    "massless": ["질량이 없는"],
    "mathematical": ["수학의", "수학적인"],
    "mathematically": ["수학적으로"],
    "mathematician": ["수학자"],
    "mathematicians": ["수학자들"],
    "maximization": ["극대화"],
    "maximizers": ["극대화 추구자들 (최고만을 찾는 성향)"],
    "mechanistic": ["기계론적인"],
    "mechanistically": ["기계론적으로"],
    "medial": ["중간의", "내측의"],
    "mediterranean": ["지중해의", "지중해"],
    "medulla": ["연수 (숨골, 뇌간 하부)"],
    "meerkat": ["미어캣"],
    "meerkats": ["미어캣들"],
    "megabase": ["메가베이스 (백만 염기쌍 Mb)"],
    "melanopsin": ["멜라놉신 (눈의 빛 감지 광색소 단백질)"],
    "mend": ["고치다", "수선하다"],
    "mendelian": ["멘델 유전법칙의"],
    "mesopotamia": ["메소포타미아"],
    "meta": ["초월한", "상위의 (메타)"],
    "metabolites": ["대사물질들"],
    "methodological": ["방법론적인"],
    "mexican": ["멕시코의", "멕시코인"],
    "microbats": ["소박쥐류"],
    "microbe": ["미생물"],
    "microbes": ["미생물들"],
    "microbial": ["미생물의"],
    "microbiologist": ["미생물학자"],
    "microgrids": ["마이크로그리드들 (소규모 독립 전력망)"],
    "microorganisms": ["미생물들"],
    "microphysical": ["미시물리학의"],
    "microplastics": ["미세플라스틱들"],
    "microprocessors": ["마이크로프로세서들"],
    "microsecond": ["마이크로초 (백만분의 1초)"],
    "microstates": ["미시상태들"],
    "mid": ["중간의", "한가운데의"],
    "midair": ["공중", "상공"],
    "midbrain": ["중뇌"],
    "midocean": ["대양 한가운데의"],
    "millennia": ["수천 년들 (millennium의 복수형)"],
    "millimeters": ["밀리미터들"],
    "minimalism": ["미니멀리즘 (단순함의 미학)"],
    "misinterpret": ["오해하다", "잘못 해석하다"],
    "mismatches": ["불일치들"],
    "mitochondrion": ["미토콘드리아 (단수형)"],
    "mitotic": ["체세포 분열의"],
    "moat": ["해자 (성곽 주변의 방어용 물도랑)"],
    "molasses": ["당밀"],
    "molecular": ["분자의"],
    "mongooses": ["몽구스들"],
    "monopolistically": ["독점적으로"],
    "montane": ["산지의", "산지대의"],
    "motorist": ["운전자"],
    "mpc": ["한계소비성향 (MPC)"],
    "mri": ["자기공명영상 (MRI)"],
    "mtdna": ["미토콘드리아 DNA (모계 유전)"],
    "mucus": ["점액", "콧물"],
    "mutant": ["돌연변이체"],
    "mutants": ["돌연변이체들"],
    "mutated": ["돌연변이를 일으킨"],
    "mutation": ["돌연변이"],
    "mutations": ["돌연변이들"],
    "muteness": ["말없음", "과묵함"],
    "mwi": ["다세계 해석 (Many-Worlds Interpretation)"],
    "mycelium": ["균사체 (버섯·곰팡이의 뿌리망)"],
    "mysterious": ["신비로운", "기이한"],
    "nanomaterials": ["나노소재들"],
    "nanometers": ["나노미터들"],
    "nanoseconds": ["나노초들 (10억분의 1초들)"],
    "nanotubes": ["나노튜브들"],
    "navier": ["나비에 (나비에-스토크스 유체역학 방정식)"],
    "navigational": ["항법의", "항해의"],
    "necessitates": ["필요하게 만들다"],
    "necessitating": ["필연적으로 수반하는"],
    "neoclassical": ["신고전주의의"],
    "neodymium": ["네오디뮴 (초강력 영구자석 원소)"],
    "nepal": ["네팔"],
    "nestmates": ["둥지 동료들 (개미·벌의 한 둥지 개체)"],
    "neural": ["신경의", "신경망의"],
    "neurobiological": ["신경생물학의"],
    "neuron": ["신경세포", "뉴런"],
    "neurons": ["신경세포들"],
    "neuropeptide": ["신경펩티드"],
    "neuroplasticity": ["신경가소성 (뇌의 구조 적응 능력)"],
    "neuropsychiatry": ["신경정신의학"],
    "neuroscientists": ["뇌신경과학자들"],
    "newtonian": ["뉴턴 역학의", "뉴턴의"],
    "nightingale": ["나이팅게일 (새/간호선구자)"],
    "nmda": ["NMDA 수용체 (기억 형성 글루탐산 수용체)"],
    "no": ["아니오", "없는"],
    "nomadism": ["유목 생활", "방랑"],
    "non": ["비(非)", "부정 접두사"],
    "nostrils": ["콧구멍들"],
    "not": ["~아니다", "않다"],
    "notatum": ["페니실리움 노타툼 (푸른곰팡이 균주)"],
    "novo": ["새로운 (de novo: 처음부터)"],
    "nutritional": ["영양의", "영양학적인"],
    "obedient": ["순종적인", "복종하는"],
    "oblongata": ["숨골 (연수, medulla oblongata)"],
    "observable": ["관찰 가능한"],
    "observational": ["관찰의", "관측에 근거한"],
    "octave": ["옥타브 (음악 8음 음정)"],
    "of": ["~의", "~중에서"],
    "olympia": ["올림피아 (고대 올림픽 발상지)"],
    "omitted": ["생략된", "빠진"],
    "on": ["~위에", "~에 대하여"],
    "onboard": ["탑승한", "내장된"],
    "onset": ["시작", "발병"],
    "opacity": ["불투명도", "이해하기 어려움"],
    "optical": ["광학의", "시각의"],
    "optimality": ["최적성", "최적 상태"],
    "or": ["또는", "혹은"],
    "orbital": ["궤도의", "원자 궤도함수"],
    "organically": ["유기적으로"],
    "organism": ["생물체", "유기체"],
    "organismal": ["개체의", "생물체 전반의"],
    "organisms": ["생물체들", "유기체들"],
    "osmosis": ["삼투 현상", "삼투압"],
    "our": ["우리의"],
    "out": ["밖으로", "벗어나"],
    "outbreak": ["발발", "돌발적 유행"],
    "outermost": ["가장 바깥의", "최외곽의"],
    "outperform": ["더 뛰어난 성과를 내다"],
    "overestimate": ["과대평가하다"],
    "overfish": ["남획하다 (물고기를 지나치게 잡다)"],
    "overfishing": ["남획", "어족자원 고갈"],
    "overgraze": ["과도하게 방목하다"],
    "overheating": ["과열"],
    "overpowering": ["압도적인", "저항할 수 없는"],
    "overprescribe": ["과잉 처방하다"],
    "oxidize": ["산화시키다", "녹슬게 하다"],
    "oyamel": ["오야멜 전나무 (모나크나비 월동 서식목)"],
    "papermaking": ["제지술", "종이 제조"],
    "parasitic": ["기생하는", "기생충의"],
    "parental": ["부모의", "양친의"],
    "participant": ["참가자"],
    "paternal": ["아버지의", "부계의"],
    "paternalistically": ["온정주의적으로", "가부장적으로"],
    "pathbreaking": ["선구적인", "길을 여는"],
    "payoff": ["보상", "결과", "수익"],
    "payoffs": ["보상들", "보수 행렬들"],
    "pelicans": ["펠리컨들"],
    "pelvis": ["골반"],
    "penicillin": ["페니실린 (최초의 항생제)"],
    "penicillium": ["페니실리움 (푸른곰팡이속)"],
    "perched": ["앉아 있는 (나뭇가지 등에)"],
    "permitted": ["허용된"],
    "permitting": ["허용하는"],
    "perpendicular": ["수직의", "직각을 이루는"],
    "personalization": ["개인 맞춤화"],
    "pessimistic": ["비관적인"],
    "petersburg": ["페테르부르크 (상트페테르부르크)"],
    "petri": ["페트리 접시 (세균 배양 접시)"],
    "pharaohs": ["파라오들 (고대 이집트 왕들)"],
    "pharmacological": ["약리학의", "약물의"],
    "pheromones": ["페로몬들 (동물 유혹 화학신호)"],
    "phlogiston": ["플로지스톤 (과거 가연설의 불 가상 원소)"],
    "phonetic": ["음성의", "발음의"],
    "phonon": ["포논 (양자화된 격자 진동 입자)"],
    "phonons": ["포논들"],
    "phosphorus": ["인 (원소 P)"],
    "photic": ["투광층의 (햇빛이 닿는 바다 표층)"],
    "photographic": ["사진의", "사진 같은 생생한"],
    "photolithography": ["포토리소그래피 (반도체 미세 노광 공정)"],
    "photomask": ["포토마스크 (회로 패턴 원판)"],
    "photophore": ["발광기 (심해어류의 발광 기관)"],
    "photoreceptors": ["광수용체들 (망막 빛 감지 세포)"],
    "physicalist": ["물리주의의", "물리주의자"],
    "pigmentation": ["색소 형성", "착색"],
    "pineal": ["송과선의 (멜라토닌 분비 뇌 기관)"],
    "pinpoint": ["정확히 집어내다", "정밀한"],
    "pituitary": ["뇌하수체의"],
    "planetary": ["행성의"],
    "pleistocene": ["홍적세", "플라이스토세 (빙하기 시대)"],
    "plugboard": ["플러그보드 (에니그마 교환 배선판)"],
    "pluto": ["명왕성"],
    "polders": ["간척지들 (네덜란드 방파 간척지)"],
    "poleward": ["극지방 쪽으로"],
    "policymakers": ["정책 입안자들"],
    "pollutant": ["오염 물질"],
    "pollutants": ["오염 물질들"],
    "polluters": ["오염 유발자들"],
    "polyamide": ["폴리아미드 (합성 고분자 섬유)"],
    "polyp": ["폴립 (산호·히드라의 고착형 개체)"],
    "polyps": ["폴립들"],
    "pons": ["뇌교 (숨골 위 뇌간 신경교각)"],
    "portcullis": ["낙하식 성문 (쇠살문)"],
    "postcolonial": ["탈식민주의의"],
    "postings": ["게시글들"],
    "postmodern": ["포스트모던의", "후기 현대주의의"],
    "postsynaptic": ["시냅스 후막의"],
    "potentiation": ["강화 (신경 시냅스 흥분 증폭)"],
    "prairie": ["대초원", "프레리"],
    "precipated": ["침전된", "촉발된"],
    "predefined": ["사전에 정의된"],
    "prediction": ["예측", "예언"],
    "preferring": ["선호하는"],
    "prefrontal": ["전전두엽의 (계획·판단 뇌 부위)"],
    "premotor": ["전운동 영역의"],
    "prepay": ["선불로 내다"],
    "prereflective": ["전(前)반성적인", "반성 이전의 직관적"],
    "presynaptic": ["시냅스 전막의"],
    "pretreated": ["전처리된"],
    "probabilistic": ["확률론적인"],
    "procedural": ["절차적인", "진행상의"],
    "prokaryotic": ["원핵생물의 (핵막이 없는)"],
    "propelled": ["추진된", "앞으로 나아간"],
    "protectionist": ["보호무역주의의"],
    "proteobacterium": ["프로테오박테리아 (세균군)"],
    "provability": ["증명 가능성"],
    "pry": ["지렛대로 들어올리다", "엿보다"],
    "pseudoscience": ["유사의사과학", "가짜 과학"],
    "psychedelic": ["환각을 일으키는"],
    "psychoanalyst": ["정신분석가"],
    "psychoanalytic": ["정신분석학의"],
    "psychosocial": ["심리사회적인"],
    "pteropods": ["유익류 (바다달팽이, 익족류)"],
    "ptolemaic": ["프톨레마이오스의 (지구중심설의)"],
    "pupillary": ["동공의"],
    "purr": ["가르랑거리다 (고양이의 기분 좋은 소리)"],
    "quadrupedal": ["네 발로 걷는", "사족보행의"],
    "quantized": ["양자화된"],
    "quarks": ["쿼크들 (강입자 구성 기본소립자)"],
    "radicle": ["유근 (씨앗에서 가장 먼저 나오는 어린뿌리)"],
    "radioactive": ["방사성의"],
    "radioactivity": ["방사능"],
    "radiocarbon": ["방사성 탄소 (탄소-14 연대측정)"],
    "raindrop": ["빗방울"],
    "raindrops": ["빗방울들"],
    "rainforests": ["열대우림들"],
    "rammed": ["들이받은", "다져진 (판축 토벽)"],
    "rationality": ["합리성", "이성"],
    "readable": ["읽기 쉬운", "가독성이 좋은"],
    "realists": ["현실주의자들"],
    "recirculated": ["재순환된"],
    "recombination": ["재조합 (유전자 교차 재배열)"],
    "recombined": ["재조합된"],
    "reconceptualized": ["재개념화된"],
    "reconfigures": ["재구성하다"],
    "reconnection": ["재연결 (자기장 재연결)"],
    "recrystallize": ["재결정화되다"],
    "recycled": ["재활용된"],
    "redefined": ["재정의된"],
    "redefining": ["재정의하는 것"],
    "redeposited": ["다시 퇴적된"],
    "redoubt": ["보루", "요새"],
    "referential": ["지시적인", "참조의"],
    "referring": ["언급하는", "참조하는"],
    "reflector": ["반사경", "반사판"],
    "reintroducing": ["재도입하는 것 (늑대 복원 등)"],
    "relational": ["관계적인", "관계상의"],
    "relativistic": ["상대론적인 (아인슈타인 특수/일반 상대론)"],
    "relativity": ["상대성 이론", "상대성"],
    "reliant": ["의존하는"],
    "rem": ["REM 수면 (급속안구운동 꿈 수면)"],
    "remediation": ["정화", "치유 (환경 토양 복원)"],
    "remodeling": ["리모델링", "재형성 (뼈 조직 재생)"],
    "reorganized": ["재조직된", "개편된"],
    "reorienting": ["방향을 재조정하는"],
    "reshaped": ["모양이 바뀐", "재형성된"],
    "responsiveness": ["반응성", "호응도"],
    "restful": ["편안한", "평온한"],
    "restructuring": ["구조조정", "개편"],
    "retinal": ["망막의", "레티날 (시각 비타민A 색소)"],
    "retrieval": ["검색", "기억 회상"],
    "retrofitting": ["개보수", "기존 설비 성능 보강"],
    "retrotransposons": ["레트로트랜스포존 (RNA 역전사 전위유전자)"],
    "rewiring": ["회로 재배선", "신경망 재연결"],
    "rgen": ["유전자 가위 RNA (RGEN)"],
    "rightness": ["올바름", "정당성"],
    "rigidities": ["경직성들 (가격·임금 경직성)"],
    "rigorousness": ["엄격함", "철저함"],
    "ritualized": ["의례화된"],
    "riverbanks": ["강둑들"],
    "romanticism": ["낭만주의"],
    "rotational": ["회전의", "자전의"],
    "rpe": ["망막색소상피 (RPE 세포)"],
    "rsa": ["RSA 공개키 암호 알고리즘"],
    "sabi": ["사비 (적막함과 고색창연의 미)"],
    "sandpaper": ["사포 (연마용 모래종이)"],
    "sapiens": ["사피엔스 (현생인류 종명)"],
    "savanna": ["사바나 (열대 초원)"],
    "scalar": ["스칼라 (크기만 갖는 물리량)"],
    "schema": ["도식", "인지 틀"],
    "schemas": ["인지 도식들"],
    "seahorse": ["해마 (바다 물고기)"],
    "seamless": ["이음새 없는", "매끄러운"],
    "seascape": ["해경", "바다 풍경"],
    "seawater": ["바닷물", "해수"],
    "see": ["보다", "알다"],
    "seeing": ["보는 것"],
    "sellers": ["판매자들"],
    "sender": ["보내는 사람", "발신자"],
    "senescence": ["세포 노화", "노화"],
    "sgrna": ["단일 가이드 RNA (sgRNA, 크리스퍼 표적 안내자)"],
    "shallower": ["더 얕은"],
    "shards": ["조각들", "파편들"],
    "sharpened": ["날카로워진", "갈린"],
    "she": ["그녀는", "그녀가"],
    "shellfish": ["패류", "조개 및 갑각류"],
    "shockwaves": ["충격파들"],
    "shortcuts": ["지름길들"],
    "shorter": ["더 짧은"],
    "shrub": ["관목", "떨기나무"],
    "sickle": ["낫 (낫형 적혈구 빈혈증)"],
    "signified": ["기의 (소쉬르 기호학에서 기호가 가리키는 의미 내용)"],
    "signifies": ["의미하다", "나타내다"],
    "silt": ["실트", "미사 (고운 침적 토사)"],
    "singapore": ["싱가포르"],
    "sitter": ["돌보미", "아이 보는 사람"],
    "skeletal": ["골격의", "뼈대의"],
    "skillfully": ["숙련되게", "능숙하게"],
    "sleepiness": ["졸림", "수면 충동"],
    "slipping": ["미끄러지는"],
    "smaller": ["더 작은"],
    "smarter": ["더 똑똑한"],
    "smog": ["스모그 (대기오염 연무)"],
    "sneezing": ["재채기"],
    "so": ["그렇게", "그래서", "매우"],
    "socio": ["사회의 (접두사)"],
    "socioeconomic": ["사회경제적인"],
    "sociological": ["사회학의"],
    "softer": ["더 부드러운"],
    "solidify": ["응고되다", "굳히다"],
    "soluble": ["녹는", "용해성의", "해결 가능한"],
    "solvable": ["해결할 수 있는"],
    "some": ["어떤", "몇몇의"],
    "someone": ["누군가"],
    "sought": ["추구했다", "찾았다 (seek 과거/과거분사)"],
    "sourdough": ["사워도우 (천연발효빵)"],
    "spanning": ["걸쳐 있는", "포괄하는"],
    "specialization": ["전문화", "분업"],
    "specialized": ["전문화된", "특화된"],
    "specializing": ["전문화하는"],
    "spooky": ["기괴한 (spooky action at a distance: 양자 얽힘)"],
    "stairways": ["계단들"],
    "staphylococcus": ["포도상구균"],
    "starches": ["녹말들", "전분들"],
    "stellar": ["별의", "항성의", "뛰어난"],
    "stemming": ["유래하는", "막는"],
    "stewardship": ["관리 책임", "청지기 직분"],
    "stood": ["서 있었다 (stand 과거/과거분사)"],
    "strategically": ["전략적으로"],
    "streamside": ["개울가의"],
    "stretchy": ["잘 늘어나는", "신축성 있는"],
    "stronger": ["더 강한"],
    "structuralist": ["구조주의자", "구조주의의"],
    "stunned": ["기절한", "충격받은"],
    "subatomic": ["원자보다 작은", "아원자의"],
    "subpolar": ["아극지의 (극지방에 인접한)"],
    "subsidization": ["보조금 지급"],
    "subtropical": ["아열대의"],
    "subzero": ["영하의"],
    "sulfide": ["황화물"],
    "superbug": ["슈퍼박테리아 (다제내성균)"],
    "superbugs": ["슈퍼박테리아들"],
    "supergiants": ["초거성들 (극도로 밝고 거대한 별)"],
    "superheated": ["과열된"],
    "supersonic": ["초음속의"],
    "supersymmetric": ["초대칭성의"],
    "suppressor": ["억제자", "종양 억제 유전자"],
    "surgical": ["수술의", "외과의"],
    "sustainably": ["지속 가능하게"],
    "swirl": ["소용돌이치다", "소용돌이"],
    "swirls": ["소용돌이들"],
    "syntactic": ["통사적인", "문법 구조상의"],
    "syntheses": ["종합들", "합성들 (synthesis 복수형)"],
    "synthesize": ["합성하다", "종합하다"],
    "synthesized": ["합성된"],
    "synthesizes": ["합성한다"],
    "synthesizing": ["합성하는 것"],
    "tadpole": ["올챙이"],
    "tadpoles": ["올챙이들"],
    "tailpipe": ["배기관", "머플러"],
    "tamped": ["다져진"],
    "tech": ["기술의", "테크"],
    "tectonic": ["판구조론의", "구조상의"],
    "teeth": ["이빨들", "치아들 (tooth 복수형)"],
    "tegmental": ["피개의 (VTA 복측 피개 영역, 보상 회로)"],
    "telecommunication": ["원격통신", "전자통신"],
    "termite": ["흰개미"],
    "tes": ["전이요소 (Transposable Elements)"],
    "testimonial": ["증언의", "추천서"],
    "textual": ["본문의", "텍스트의"],
    "than": ["~보다"],
    "that": ["저것", "그", "접속사/관계대명사"],
    "the": ["그 (정관사)"],
    "their": ["그들의"],
    "them": ["그들을"],
    "then": ["그때", "그 다음에"],
    "theorist": ["이론가"],
    "theorists": ["이론가들"],
    "there": ["거기에", "그곳에"],
    "therefore": ["그러므로", "따라서"],
    "thermohaline": ["열염분의 (해양 열염순환)"],
    "thermometer": ["온도계"],
    "thermometers": ["온도계들"],
    "these": ["이것들", "이들"],
    "they": ["그들은", "그들이"],
    "thinning": ["얇아짐", "솎아내기"],
    "this": ["이것", "이"],
    "thousandth": ["천 번째의", "천분의 일"],
    "thrower": ["던지는 사람"],
    "time": ["시간", "때"],
    "timeless": ["시간을 초월한", "영원한"],
    "timescales": ["시간 척도들"],
    "tiny": ["아주 작은"],
    "tipped": ["기울어진", "팁을 받은"],
    "tipping": ["티핑 포인트의", "기울어짐"],
    "tireless": ["지칠 줄 모르는", "끈기 있는"],
    "tknn": ["TKNN 불변량 (양자 홀 효과 위상 불변량)"],
    "to": ["~로", "~에게"],
    "topographical": ["지형학의", "지형의"],
    "topological": ["위상수학적인", "위상학의"],
    "topologically": ["위상학적으로"],
    "totality": ["전체", "총체"],
    "tradable": ["거래 가능한 (배출권 거래 등)"],
    "transcendent": ["초월적인"],
    "transcontinental": ["대륙 횡단의"],
    "transferred": ["전이된", "이전된"],
    "translational": ["번역의", "병진 운동의"],
    "translocations": ["염색체 전좌들"],
    "transposable": ["전위 가능한 (유전자 이동)"],
    "trapdoors": ["함정문들", "트랩도어 (일방향 암호 함수)"],
    "trapped": ["갇힌", "포획된"],
    "trapping": ["가두는 것", "포획"],
    "trawling": ["저인망 어업 (바닥을 긁는 그물잡이)"],
    "triad": ["삼자 관계", "3인조"],
    "truthfulness": ["진실성", "정직함"],
    "turbofan": ["터보팬 제트엔진"],
    "turbofans": ["터보팬 엔진들"],
    "turbojets": ["터보제트 엔진들"],
    "two": ["2", "둘"],
    "typewriter": ["타자기"],
    "ultradense": ["초고밀도의"],
    "ultraviolet": ["자외선의 (UV)"],
    "unalterable": ["변경할 수 없는", "불변의"],
    "unbridged": ["다리가 놓이지 않은"],
    "unbroken": ["깨지지 않은", "연속된"],
    "unceasingly": ["끊임없이"],
    "uncharged": ["전하를 띠지 않은", "중성의"],
    "uncharted": ["미지의", "지도에 없는"],
    "uncompromising": ["타협하지 않는", "단호한"],
    "uncrackable": ["해독할 수 없는"],
    "undercoat": ["밑털 (동물의 방한용 속털)"],
    "undergone": ["겪었다 (undergo 과거분사)"],
    "underpinned": ["뒷받침된"],
    "underpinning": ["기초", "토대"],
    "undersea": ["해저의"],
    "undifferentiated": ["미분화된 (줄기세포 초기 상태)"],
    "unextractable": ["추출 불가능한"],
    "unfalsifiable": ["반증 불가능한 (과학적 검증 불가의)"],
    "unforced": ["자연스러운", "억지스럽지 않은"],
    "unhindered": ["방해받지 않는"],
    "unintended": ["의도하지 않은"],
    "uninterrupted": ["중단 없는", "연속적인"],
    "unlocked": ["잠금 해제된"],
    "unobservable": ["관측할 수 없는"],
    "unpriced": ["가격이 매겨지지 않은 (환경 외부성)"],
    "unprotected": ["보호받지 못하는"],
    "unprovability": ["증명 불가능성"],
    "unproven": ["입증되지 않은"],
    "unreadable": ["읽을 수 없는"],
    "unrestrained": ["억제되지 않는", "자유로운"],
    "unrestricted": ["제약 없는", "무제한의"],
    "unscrew": ["나사를 풀다"],
    "unsolved": ["풀리지 않은", "미해결의"],
    "unsuspecting": ["의심하지 않는"],
    "up": ["위로"],
    "upon": ["~위에"],
    "upwind": ["바람을 거슬러", "풍상의"],
    "us": ["우리를", "우리에게"],
    "user": ["사용자"],
    "users": ["사용자들"],
    "uterine": ["자궁의"],
    "vagus": ["미주 신경의 (부교감 신경 핵심 경로)"],
    "vehicular": ["차량의"],
    "ventricle": ["심실 (심장의 박출실)", "뇌실"],
    "verbalization": ["언어화", "말로 표현함"],
    "villa": ["별장", "빌라"],
    "viscosity": ["점성 (유체의 끈적임 정도)"],
    "visualization": ["시각화"],
    "voles": ["들쥐들 (일편단심 사회성 설치류)"],
    "von": ["~의 (독일 귀족 성씨 전치사)"],
    "vortex": ["소용돌이"],
    "voynich": ["보이니치 필사본 (미해독 고문서)"],
    "wabi": ["와비 (소박하고 고요한 미)"],
    "wafer": ["웨이퍼 (반도체 실리콘 얇은 원판)"],
    "waggle": ["흔들기 (꿀벌의 8자 엉덩이 흔들기 춤)"],
    "wakeful": ["깨어 있는", "잠들지 못하는"],
    "walrasian": ["발라스식의 (일반균형 경제학)"],
    "was": ["~이었다 (be동사 과거형)"],
    "watchtowers": ["망루들", "감시탑들"],
    "waterfalls": ["폭포들"],
    "waveform": ["파형 (파도의 모양)"],
    "way": ["길", "방법"],
    "ways": ["방법들", "방식들"],
    "weaker": ["더 약한"],
    "well": ["잘", "우물", "글쎄"],
    "were": ["~이었다 (be동사 복수 과거형)"],
    "wetland": ["습지"],
    "wetlands": ["습지대"],
    "what": ["무엇", "어떤 것"],
    "wheelers": ["수레 끄는 사람/가축"],
    "when": ["언제", "~할 때"],
    "which": ["어느 것", "관계대명사"],
    "who": ["누구", "관계대명사"],
    "whom": ["누구를"],
    "whose": ["누구의"],
    "widen": ["넓히다", "넓어지다"],
    "wildflower": ["야생화", "들꽃"],
    "wildlife": ["야생동물"],
    "will": ["~할 것이다", "의지", "유언장"],
    "windmill": ["풍차"],
    "windmills": ["풍차들"],
    "wingtips": ["날개 끝들 (윙렛 구조)"],
    "with": ["~와 함께", "~를 가지고"],
    "wolves": ["늑대들 (wolf 복수형)"],
    "woody": ["나무 같은", "목질의"],
    "workplace": ["직장", "일터"],
    "would": ["~일 것이다 (will의 과거/가정법)"],
    "yellowish": ["노르스름한"],
    "yellowstone": ["옐로스톤 국립공원"],
    "zigzagging": ["지그재그로 나아가는"],
    "zooplankton": ["동물성 플랑크톤"],
    "zooxanthellae": ["황록공생조류 (산호 공생 편모조류)"]
}

# Import remaining terms
from remaining_terms import REMAINING_TERMS
for w, meanings in REMAINING_TERMS.items():
    w = w.lower().strip()
    if w not in domain_and_passage_terms:
        domain_and_passage_terms[w] = meanings


for w, meanings in domain_and_passage_terms.items():
    w = w.lower().strip()
    if w not in word_dict:
        word_dict[w] = meanings
    else:
        for m in meanings:
            if m not in word_dict[w]:
                word_dict[w].append(m)

print(f"Total after ingesting passage terms: {len(word_dict)} words.")

# 4. Generate high-quality regular derivations (adverbs, participles, nouns)
# Adverbs from adjectives
adv_added = 0
for w, meanings in list(word_dict.items()):
    m0 = meanings[0] if meanings else ""
    if any(m0.endswith(suff) for suff in ["한", "인", "의", "로운", "적인", "된"]):
        adv = None
        if w.endswith("y") and not w.endswith("ly"): adv = w[:-1] + "ily"
        elif w.endswith("ic"): adv = w + "ally"
        elif not w.endswith("ly"): adv = w + "ly"
        if adv and adv not in word_dict and len(adv) >= 4 and re.match(r"^[a-z]+$", adv):
            kor_adv = m0
            if kor_adv.endswith("한"): kor_adv = kor_adv[:-1] + "하게"
            elif kor_adv.endswith("인"): kor_adv = kor_adv[:-1] + "으로"
            elif kor_adv.endswith("로운"): kor_adv = kor_adv[:-2] + "럽게"
            elif kor_adv.endswith("적인"): kor_adv = kor_adv[:-2] + "적으로"
            else: kor_adv = kor_adv + "하게"
            word_dict[adv] = [kor_adv]
            adv_added += 1

print(f"Added {adv_added} regular adverbs.")

# Gerunds / present participles from verbs
ing_added = 0
for w, meanings in list(word_dict.items()):
    m0 = meanings[0] if meanings else ""
    if m0.endswith("하다") or m0.endswith("되다"):
        ing_form = None
        if w.endswith("ie"): ing_form = w[:-2] + "ying"
        elif w.endswith("e") and not w.endswith("ee"): ing_form = w[:-1] + "ing"
        else: ing_form = w + "ing"
        if ing_form and ing_form not in word_dict and len(ing_form) >= 5 and re.match(r"^[a-z]+$", ing_form):
            word_dict[ing_form] = [m0[:-2] + "하는 것", m0[:-2] + "하는 중인"]
            ing_added += 1

print(f"Added {ing_added} gerund / present participle forms.")

# Past participles from verbs
ed_added = 0
for w, meanings in list(word_dict.items()):
    m0 = meanings[0] if meanings else ""
    if m0.endswith("하다"):
        ed_form = None
        if w.endswith("e"): ed_form = w + "d"
        elif w.endswith("y") and len(w) > 2 and w[-2] not in "aeiou": ed_form = w[:-1] + "ied"
        else: ed_form = w + "ed"
        if ed_form and ed_form not in word_dict and len(ed_form) >= 5 and re.match(r"^[a-z]+$", ed_form):
            word_dict[ed_form] = [m0[:-2] + "된", m0[:-2] + "했다"]
            ed_added += 1

print(f"Added {ed_added} past participle forms.")

# Nouns with -ness from adjectives
ness_added = 0
for w, meanings in list(word_dict.items()):
    m0 = meanings[0] if meanings else ""
    if any(m0.endswith(suff) for suff in ["한", "로운", "운"]):
        noun_form = None
        if w.endswith("y"): noun_form = w[:-1] + "iness"
        elif not w.endswith("ness"): noun_form = w + "ness"
        if noun_form and noun_form not in word_dict and len(noun_form) >= 5 and re.match(r"^[a-z]+$", noun_form):
            kor_noun = m0
            if kor_noun.endswith("한"): kor_noun = kor_noun[:-1] + "함"
            elif kor_noun.endswith("로운"): kor_noun = kor_noun[:-2] + "로움"
            else: kor_noun = kor_noun + "함"
            word_dict[noun_form] = [kor_noun]
            ness_added += 1

print(f"Added {ness_added} -ness noun forms.")

# Final assembly of dictionary array sorted alphabetically
all_word_list = []
for w in sorted(word_dict.keys()):
    if re.match(r"^[a-z]+$", w): # Clean alphabetic words only
        all_word_list.append({
            "word": w,
            "meanings": word_dict[w]
        })

print(f"==================================================")
print(f"FINAL EXPANDED MASTER VOCABULARY COUNT: {len(all_word_list)} words")
print(f"==================================================")

# Write to js/wordtest_db.js
js_content = "/**\n * WordTest Database - Master Vocabulary Dataset\n * Total Verified Words: " + str(len(all_word_list)) + "\n */\n\nconst defaultWords = " + json.dumps(all_word_list, ensure_ascii=False, indent=2) + ";\n"

with open("js/wordtest_db.js", "w", encoding="utf-8") as f:
    f.write(js_content)

print(f"Successfully written {len(all_word_list)} words to js/wordtest_db.js!")
