# -*- coding: utf-8 -*-
"""
generate_expansion_advanced.py
Advanced Passages a-31 to a-40
Sources: Stanford Encyclopedia of Philosophy, Nature Genetics, Nature Climate Change, Foreign Affairs, Communications of the ACM, Cell
"""

def get_advanced_expansion():
    a_extra = [
        ("a-31", "Gödel's Incompleteness Theorems and Mathematical Epistemology", "괴델의 불완전성 정리와 수학적 인식론의 한계", "Mathematical Logic & Epistemology", "Stanford Encyclopedia of Philosophy",
         "1931년 쿠르트 괴델이 입증한 무모순성과 완전성의 양립 불가능성과 힐베르트 프로그램의 좌절을 분석합니다.",
         [
             ("In 1931, the Austrian logician Kurt Gödel published two ground-breaking theorems that permanently dismantled David Hilbert's formalist agenda.", "1931년 오스트리아의 논리학자 쿠르트 괴델은 다비트 힐베르트의 형식주의 프로그램을 영구히 해체한 두 가지 획기적인 정리를 발표했습니다.", "In 1931, / the Austrian logician Kurt Gödel published / two ground-breaking theorems / that permanently dismantled / David Hilbert's formalist agenda."),
             ("Hilbert had envisioned establishing a complete, consistent axiomatic foundation from which all mathematical truths could be mechanistically deduced.", "힐베르트는 모든 수학적 진리가 기계적으로 연역될 수 있는 완전하고 무모순인 공리적 기초를 확립하고자 구상했었습니다.", "Hilbert had envisioned establishing / a complete, consistent axiomatic foundation / from which all mathematical truths / could be mechanistically deduced."),
             ("Gödel's First Incompleteness Theorem demonstrated that any sufficiently powerful consistent formal system necessarily contains propositions that are undecidable.", "괴델의 제1 불완전성 정리는 충분히 강력하고 무모순인 어떠한 형식 체계도 결정 불가능한 명제를 필연적으로 포함함을 증명했습니다.", "Gödel's First Incompleteness Theorem demonstrated / that any sufficiently powerful consistent formal system / necessarily contains propositions / that are undecidable."),
             ("By constructing an ingenious self-referential statement declaring its own unprovability, Gödel proved that mathematical truth transcends mere axiomatic provability.", "자신의 증명 불가능성을 선언하는 독창적인 자기참조적 문장을 구성함으로써, 괴델은 수학적 진리가 단순한 공리적 증명 가능성을 초월함을 입증했습니다.", "By constructing an ingenious self-referential statement / declaring its own unprovability, / Gödel proved that mathematical truth / transcends mere axiomatic provability."),
             ("His Second Theorem further proved that such a formal axiomatic system cannot establish its own consistency without generating circular contradictions.", "그의 제2 정리는 나아가 그러한 형식 공리 체계가 순환적 모순을 일으키지 않고서는 스스로의 무모순성을 입증할 수 없음을 증명했습니다.", "His Second Theorem further proved / that such a formal axiomatic system / cannot establish its own consistency / without generating circular contradictions."),
             ("Consequently, mathematical knowledge cannot be completely captured within any finite algorithmic apparatus, reorienting the philosophy of mind.", "결과적으로 수학적 지식은 어떠한 유한한 알고리즘 장치 안에도 완전히 포섭될 수 없으며, 이는 심리철학의 방향을 재정립했습니다.", "Consequently, / mathematical knowledge cannot be completely captured / within any finite algorithmic apparatus, / reorienting the philosophy of mind.")
         ],
         [("dismantle", "v.", "해체하다, 분해하다", "Engineers dismantled the decommissioned nuclear reactor piece by piece."), ("axiomatic", "adj.", "공리적인, 자명한", "Euclidean geometry rests upon a series of axiomatic assumptions."), ("undecidable", "adj.", "결정 불가능한", "The continuum hypothesis proved mathematically undecidable within standard set theory."), ("transcend", "v.", "초월하다, 능가하다", "Great musical works transcend cultural and temporal boundaries."), ("apparatus", "n.", "장치, 기구, 기제", "The bureaucratic apparatus delayed the release of humanitarian relief.")],
         [("과거완료 had envisioned", "Hilbert had envisioned establishing... 괴델의 발표 이전 시점의 구상을 나타내는 과거완료입니다."), ("전치사 without -ing", "...cannot establish its own consistency without generating circular contradictions... 가정/조건의 부정 표현입니다.")],
         [
             ("What ambitious project did David Hilbert advocate prior to Gödel's theorems?", "괴델의 정리 이전에 다비트 힐베르트가 옹호했던 야심 찬 프로젝트는 무엇이었나요?", ["A complete, consistent axiomatic foundation capable of proving all mathematical truths", "Eliminating all symbolic notation in favor of spoken poetry", "Proving that arithmetic is fundamentally an illusion of human language", "Restricting mathematical research to commercial accounting ledgers"], 0, "모든 수학적 진리를 기계적으로 연역할 수 있는 완전하고 무모순인 공리 체계를 확립하려 했다고 설명했습니다."),
             ("How did Gödel demonstrate the first incompleteness theorem?", "괴델은 어떻게 제1 불완전성 정리를 논증했나요?", ["By measuring the physical curvature of space using lasers", "By constructing a self-referential mathematical statement declaring its own unprovability", "By demonstrating an arithmetic error in Isaac Newton's calculus tables", "By surveying thousands of university professors about their personal beliefs"], 1, "자신의 증명 불가능성을 선언하는 자기참조적 문장을 구성함으로써 증명했다고 명시했습니다."),
             ("What philosophical implication follows from the second incompleteness theorem?", "제2 불완전성 정리로부터 도출되는 철학적 시사점은 무엇인가요?", ["A formal system cannot prove its own consistency without circularity.", "All computer programs will permanently crash every twelve hours.", "Geometry has zero practical application in engineering.", "Truth and falsehood are completely indistinguishable in human thought."], 0, "형식 체계가 순환 모순 없이 스스로의 무모순성을 입증할 수 없다는 점이라고 설명했습니다.")
         ]),

        ("a-32", "Epigenetic Reprogramming and Cellular Plasticity", "후성유전학적 재프로그래밍과 세포 가소성", "Molecular Genetics", "Nature Genetics",
         "DNA 염기서열 변화 없이 유전자 발현을 조절하는 후성유전학적 표지와 야마나카 인자의 세포 역분화 혁신을 다룹니다.",
         [
             ("While the linear genomic sequence of an organism remains essentially uniform across tissues, divergent cell types manifest vastly distinct identities.", "생명체의 선형 게놈 서열은 조직 전반에 걸쳐 본질적으로 동일하게 유지되지만, 서로 다른 세포 유형들은 판이하게 구별되는 정체성을 나타냅니다.", "While the linear genomic sequence of an organism / remains essentially uniform across tissues, / divergent cell types manifest / vastly distinct identities."),
             ("This developmental specialization is orchestrated by epigenetics, chemical modifications to DNA and histone proteins that modulate chromatin accessibility.", "이러한 발달적 분화는 염색질 접근성을 조절하는 DNA 및 히스톤 단백질의 화학적 변형인 후성유전학에 의해 조율됩니다.", "This developmental specialization is orchestrated / by epigenetics, / chemical modifications to DNA and histone proteins / that modulate chromatin accessibility."),
             ("Methylation of cytosine residues and histone acetylation dictate whether transcriptional machinery can transcribe specific lineage-defining genes.", "시토신 잔기의 메틸화와 히스톤 아세틸화는 전사 기구가 특정 계통 결정 유전자를 전사할 수 있는지 여부를 좌우합니다.", "Methylation of cytosine residues / and histone acetylation dictate / whether transcriptional machinery can transcribe / specific lineage-defining genes."),
             ("Historically, Conrad Waddington's epigenetic landscape conceptualized terminal cellular differentiation as an irreversible downhill progression.", "역사적으로 콘래드 와딩턴의 후성유전학적 지형은 최종 세포 분화를 비가역적인 내리막 진행으로 개념화했습니다.", "Historically, / Conrad Waddington's epigenetic landscape / conceptualized terminal cellular differentiation / as an irreversible downhill progression."),
             ("However, Shinya Yamanaka overturned this biological dogma in 2006 by demonstrating that introducing four transcription factors resets somatic cells into pluripotency.", "그러나 야마나카 신야는 2006년 네 가지 전사 인자를 도입함으로써 체세포를 다능성 상태로 리셋할 수 있음을 입증하여 이 생물학적 교리를 뒤엎었습니다.", "However, / Shinya Yamanaka overturned this biological dogma in 2006 / by demonstrating that introducing four transcription factors / resets somatic cells into pluripotency."),
             ("Induced pluripotent stem cells (iPSCs) have consequently unlocked regenerative medicine, enabling patient-specific autologous tissue fabrication.", "유도만능줄기세포(iPSC)는 결과적으로 재생의학의 문을 열어, 환자 맞춤형 자가 조직 제작을 가능하게 했습니다.", "Induced pluripotent stem cells (iPSCs) / have consequently unlocked regenerative medicine, / enabling patient-specific / autologous tissue fabrication.")
         ],
         [("divergent", "adj.", "갈라지는, 일치하지 않는", "Divergent evolutionary pressures produced varied beak morphologies."), ("modulate", "v.", "조절하다, 변조하다", "Hormones modulate the expression of neurotransmitter receptors."), ("irreversible", "adj.", "돌이킬 수 없는, 비가역적인", "Cellular senescence causes irreversible loss of proliferative capacity."), ("pluripotency", "n.", "다능성, 만능성", "Embryonic stem cells maintain pluripotency to generate any somatic lineage."), ("autologous", "adj.", "자가의, 동일 개체 유래의", "Autologous skin grafts avoid immunological rejection responses.")],
         [("동격 명사구", "...epigenetics, chemical modifications to DNA and histone proteins... epigenetics를 설명하는 동격 구조입니다."), ("명사절 유도 whether", "...dictate whether transcriptional machinery can transcribe... '~인지 아닌지를 결정한다'는 목적어절입니다.")],
         [
             ("What molecular mechanism regulates cell identity without altering DNA sequences?", "DNA 염기서열을 바꾸지 않고 세포 정체성을 조절하는 분자 메커니즘은 무엇인가요?", ["Random horizontal plasmid swapping between erythrocytes", "Epigenetic chemical modifications to DNA and histone chromatin structures", "Complete enzymatic digestion of mitochondrial ribosomes", "Physical stretching of actin microfilaments during mitosis"], 1, "DNA와 히스톤 염색질 구조에 대한 후성유전학적 화학 변형이라고 명시했습니다."),
             ("What long-standing dogma was overturned by Shinya Yamanaka in 2006?", "2006년 야마나카 신야에 의해 뒤집힌 오랜 생물학적 교리는 무엇이었나요?", ["That terminal somatic differentiation is irreversible", "That human beings possess twenty-three pairs of chromosomes", "That DNA contains four fundamental nucleotide bases", "That cellular respiration consumes glucose inside mitochondria"], 0, "최종 분화가 되돌릴 수 없는 내리막길이라는 교리를 뒤집고 다능성 역분화를 입증했다고 설명했습니다."),
             ("What major clinical application has been unlocked by induced pluripotent stem cells?", "유도만능줄기세포에 의해 열린 주요 임상적 응용 분야는 무엇인가요?", ["Synthetic biological weaponry for desert warfare", "Patient-specific autologous tissue fabrication in regenerative medicine", "Irradiating human genomes with gamma radiation", "Eliminating the need for sleep in mammalian mammals"], 1, "재생의학에서 환자 맞춤형 자가 조직 제작(patient-specific autologous tissue fabrication)이라고 서술했습니다.")
         ]),

        ("a-33", "The Dynamics of the Atlantic Meridional Overturning Circulation", "대서양 자오선 역전 순환(AMOC)의 역학과 기후 임계점", "Oceanography & Climatology", "Nature Climate Change",
         "열염순환의 거대한 컨베이어 벨트가 담수 유입으로 약화되며 초래할 수 있는 전 지구적 기후 급변을 경고합니다.",
         [
             ("The Atlantic Meridional Overturning Circulation (AMOC) constitutes one of Earth's most critical planetary heat redistribution mechanisms.", "대서양 자오선 역전 순환(AMOC)은 지구에서 가장 결정적인 전 지구적 열 재분배 메커니즘 중 하나를 구성합니다.", "The Atlantic Meridional Overturning Circulation (AMOC) / constitutes one of Earth's / most critical planetary heat redistribution mechanisms."),
             ("Driven by delicate density gradients between warm, saline subtropical surface waters and frigid, dense subpolar depths, it conveys massive thermal energy poleward.", "따뜻하고 염도가 높은 아열대 표층수와 차갑고 밀도가 높은 아극지 심층 사이의 미세한 밀도 기울기에 의해 구동되며, 이는 극지방을 향해 막대한 열에너지를 수송합니다.", "Driven by delicate density gradients / between warm, saline subtropical surface waters / and frigid, dense subpolar depths, / it conveys massive thermal energy poleward."),
             ("Upon releasing its heat into the North Atlantic atmosphere, the cooled hypersaline water sinks precipitously in deep convective chimneys off Greenland.", "북대서양 대기로 열을 방출하자마자, 냉각된 고염분 해수는 그린란드 인근의 심해 대류 굴뚝에서 급격히 침강합니다.", "Upon releasing its heat / into the North Atlantic atmosphere, / the cooled hypersaline water sinks precipitously / in deep convective chimneys off Greenland."),
             ("However, accelerated melting of the Greenland ice sheet and augmented Arctic precipitation are discharging immense volumes of buoyant fresh water.", "그러나 그린란드 빙상의 가속화된 융해와 증가된 북극 강수량은 막대한 양의 부력이 큰 담수를 방출하고 있습니다.", "However, / accelerated melting of the Greenland ice sheet / and augmented Arctic precipitation / are discharging immense volumes / of buoyant fresh water."),
             ("This influx of low-density fresh water freshens surface currents, inhibiting deep convective sinking and substantially attenuating AMOC velocity.", "이러한 저밀도 담수의 유입은 표층 해수의 염도를 낮추어 심해 대류 침강을 억제하고 AMOC 순환 속도를 실질적으로 약화시킵니다.", "This influx of low-density fresh water / freshens surface currents, / inhibiting deep convective sinking / and substantially attenuating AMOC velocity."),
             ("Paleoclimatic evidence suggests that crossing a critical tipping point could trigger abrupt northern cooling, disrupted monsoons, and accelerated sea-level rise.", "고기후학적 증거는 임계점을 넘어서는 것이 북반구의 급격한 한랭화, 몬순 기후 교란, 해수면 상승 가속화를 촉발할 수 있음을 시사합니다.", "Paleoclimatic evidence suggests / that crossing a critical tipping point / could trigger abrupt northern cooling, / disrupted monsoons, / and accelerated sea-level rise.")
         ],
         [("meridional", "adj.", "자오선의, 남북 방향의", "Meridional wind components drive atmospheric moisture transport."), ("precipitously", "adv.", "가파르게, 급격하게", "Global biodiversity declined precipitously over the twentieth century."), ("buoyant", "adj.", "부력이 있는, 뜨는", "Warm buoyant air masses ascend rapidly during thunderstorms."), ("attenuate", "v.", "약화시키다, 희석하다", "Earplugs attenuate acoustic noise levels significantly."), ("paleoclimatic", "adj.", "고기후의", "Paleoclimatic ice cores record atmospheric carbon dioxide across millennia.")],
         [("과거분사 수동 분사구문", "Driven by delicate density gradients..., it conveys... Being이 생략된 분사구문입니다."), ("Upon + -ing", "Upon releasing its heat into the North Atlantic atmosphere... '~하자마자'라는 접속사적 전치사구입니다.")],
         [
             ("What physical mechanism primarily powers the overturning circulation of AMOC?", "AMOC의 전도 순환을 구동하는 핵심적인 물리적 메커니즘은 무엇인가요?", ["Tectonic earthquakes lifting continental shelves", "Density gradients driven by temperature and salinity variations", "Nuclear reactions deep inside the Mariana Trench", "Centrifugal spinning of atmospheric hurricanes"], 1, "온도와 염분 차이에 의해 발생하는 밀도 기울기(density gradients)라고 설명했습니다."),
             ("Why does melting of the Greenland ice sheet weaken AMOC?", "그린란드 빙상의 융해가 왜 AMOC 순환을 약화시키나요?", ["It adds buoyant fresh water that inhibits deep convective sinking.", "It freezes the entire surface ocean into solid granite rock.", "It introduces millions of marine predators that absorb ocean heat.", "It blocks underwater sound waves emitted by navigation buoys."], 0, "부력이 큰 담수를 유입시켜 심해 대류 침강을 억제하기 때문입니다."),
             ("What systemic catastrophe could occur if AMOC crosses a critical tipping point?", "AMOC가 임계점을 넘을 경우 어떤 시스템적 재앙이 발생할 수 있나요?", ["Abrupt northern cooling, disrupted tropical monsoons, and accelerated sea-level rise", "Immediate loss of Earth's magnetic shielding field", "The total permanent cessation of the lunar orbit", "Complete global evaporation of all freshwater lakes"], 0, "북반구의 급격한 냉각, 열대 몬순 교란, 해수면 상승 가속화가 촉발될 수 있다고 명시했습니다.")
         ]),

        ("a-34", "The Post-Structuralist Semiotics of Deconstruction", "탈구조주의 기호학과 데리다의 해체주의", "Continental Philosophy & Semiotics", "Routledge Philosophy",
         "자크 데리다가 주창한 '차연(différance)' 개념과 서구 형이상학의 이항 대립 해체 과정을 심층 분석합니다.",
         [
             ("Jacques Derrida's deconstruction fundamentally destabilized the structuralist premise that signs possess stable, objective referential meanings.", "자크 데리다의 해체주의는 기호가 안정적이고 객관적인 지시 의미를 소유한다는 구조주의적 전제를 근본적으로 불안정화했습니다.", "Jacques Derrida's deconstruction / fundamentally destabilized the structuralist premise / that signs possess / stable, objective referential meanings."),
             ("Structural linguistics, pioneered by Ferdinand de Saussure, posits that linguistic signs derive meaning exclusively through differential contrast within a closed system.", "페르디낭 드 소쉬르가 개척한 구조 언어학은 언어 기호가 닫힌 체계 내의 차별적 대조를 통해서만 의미를 도출한다고 상정합니다.", "Structural linguistics, / pioneered by Ferdinand de Saussure, / posits that linguistic signs derive meaning / exclusively through differential contrast / within a closed system."),
             ("Derrida extended this insight by coining the neologism différance, a portmanteau capturing both temporal deferral and spatial differentiation.", "데리다는 시간적 유예와 공간적 차별화를 모두 포착하는 신조어인 '차연(différance)'을 고안함으로써 이 통찰을 확장했습니다.", "Derrida extended this insight / by coining the neologism différance, / a portmanteau capturing both temporal deferral / and spatial differentiation."),
             ("Because a signifier merely points to another signifier in an endless chain of signifiers, definitive presence or ultimate truth is eternally postponed.", "기표는 끝없는 기표의 연쇄 속에서 단지 또 다른 기표를 가리킬 뿐이므로, 확정적인 현존이나 궁극적 진리는 영원히 유예됩니다.", "Because a signifier merely points to another signifier / in an endless chain of signifiers, / definitive presence or ultimate truth / is eternally postponed."),
             ("Furthermore, deconstruction interrogates binary oppositions—such as speech/writing, nature/culture, and reason/madness—that privilege one term while repressing the other.", "나아가 해체주의는 한쪽 항을 특권화하고 다른 항을 억압하는 음성/문자, 자연/문화, 이성/광기와 같은 이항 대립들을 심문합니다.", "Furthermore, deconstruction interrogates binary oppositions / —such as speech/writing, nature/culture, and reason/madness— / that privilege one term / while repressing the other."),
             ("By identifying internal textual contradictions, deconstruction demonstrates that texts inevitably undermine their own authoritative philosophical claims.", "텍스트 내부의 모순을 식별함으로써, 해체주의는 텍스트가 필연적으로 자신의 권위적인 철학적 주장을 스스로 전복시킴을 증명합니다.", "By identifying internal textual contradictions, / deconstruction demonstrates / that texts inevitably undermine / their own authoritative philosophical claims.")
         ],
         [("destabilize", "v.", "불안정하게 만들다", "Rampant speculation destabilized the national currency."), ("premise", "n.", "전제", "The scientific hypothesis rests on a flawed empirical premise."), ("neologism", "n.", "신조어", "Internet culture constantly generates playful linguistic neologisms."), ("signifier", "n.", "기표, 표현 형태", "In semiotics, a printed word functions as a sensory signifier."), ("undermine", "v.", "서서히 약화시키다, 전복하다", "Persistent corruption undermined public confidence in the judicial court.")],
         [("동격 명사절 that", "...the structuralist premise that signs possess stable referential meanings... premise와 동격인 명사절입니다."), ("현재분사 병렬", "...a portmanteau capturing both temporal deferral and spatial differentiation... 앞 명사를 수식하는 분사구입니다.")],
         [
             ("What linguistic assumption did Derrida challenge through deconstruction?", "데리다는 해체를 통해 어떤 언어학적 가정을 비판했나요?", ["That signs possess stable, objective, and fixed referential meanings", "That spoken language should be completely eliminated from civilization", "That vowels contain mystical electromagnetic currents", "That alphabetical scripts were invented by computer algorithms"], 0, "기호가 안정적이고 객관적인 고정된 지시 의미를 가진다는 전제를 비판했습니다."),
             ("What two dual meanings are synthesized in Derrida's concept of différance?", "데리다의 '차연(différance)' 개념에 종합된 두 가지 의미는 무엇인가요?", ["Grammar and mathematical addition", "Spatial differentiation and temporal deferral", "Acoustic frequency and musical rhythm", "Biological respiration and photosynthesis"], 1, "공간적 차별화(differing)와 시간적 유예(deferring)의 결합이라고 설명했습니다."),
             ("How does deconstruction analyze hierarchical binary oppositions like speech/writing?", "해체주의는 음성/문자와 같은 위계적 이항 대립을 어떻게 분석하나요?", ["It affirms that speech is eternally superior in all philosophical contexts.", "It reveals how textually privileged terms rely upon and repress their opposites.", "It translates both terms into classical Latin syntax.", "It eliminates both concepts from dictionaries entirely."], 1, "한쪽 항이 특권화되는 반면 다른 항을 억압하는 구조를 드러내고 텍스트 내부 모순을 밝힌다고 설명했습니다.")
         ]),

        ("a-35", "The Microeconomic Foundations of Mechanism Design", "메커니즘 디자인의 미시경제학적 기초와 경매 이론", "Microeconomics & Game Theory", "Journal of Political Economy",
         "정보 비대칭 상황에서 행위자들의 사적 이익 추구가 공공의 최적 배분으로 귀결되도록 유인을 설계하는 역게임이론을 탐구합니다.",
         [
             ("Mechanism design, often described as 'reverse game theory,' addresses the challenge of engineering institutions when private information is dispersed.", "종종 '역게임이론'으로 묘사되는 메커니즘 디자인은 사적 정보가 분산되어 있을 때 제도를 엔지니어링하는 과제를 다룹니다.", "Mechanism design, / often described as 'reverse game theory,' / addresses the challenge of engineering institutions / when private information is dispersed."),
             ("Standard game theory predicts how strategic agents will behave within an existing, predefined set of rules.", "표준 게임이론은 전략적 행위자들이 기존에 미리 정의된 규칙 체계 내에서 어떻게 행동할지를 예측합니다.", "Standard game theory predicts / how strategic agents will behave / within an existing, predefined set of rules."),
             ("Conversely, mechanism design begins with a desired normative outcome—such as social welfare maximization—and seeks rules that incentivize agents to reveal true preferences.", "반대로, 메커니즘 디자인은 사회 복지 극대화와 같은 바람직한 규범적 결과에서 출발하여, 행위자들이 진정한 선호를 드러내도록 유도하는 규칙을 모색합니다.", "Conversely, / mechanism design begins with a desired normative outcome / —such as social welfare maximization— / and seeks rules / that incentivize agents to reveal true preferences."),
             ("A cornerstone principle is incentive compatibility, ensuring that participants maximize personal payoffs precisely by truthfully disclosing their private valuations.", "초석이 되는 원칙은 유인 일치성으로, 참가자들이 자신의 사적 가치 평가를 진실하게 공개함으로써 바로 개인적 보상을 극대화하도록 보장하는 것입니다.", "A cornerstone principle is incentive compatibility, / ensuring that participants maximize personal payoffs / precisely by truthfully disclosing their private valuations."),
             ("The Revelation Principle demonstrates mathematically that any equilibrium achieved under complex bargaining can be replicated by a direct, truthful mechanism.", "현시 원리는 복잡한 협상하에서 달성되는 모든 균형이 직접적이고 진실한 메커니즘에 의해 복제될 수 있음을 수학적으로 입증합니다.", "The Revelation Principle demonstrates mathematically / that any equilibrium achieved under complex bargaining / can be replicated / by a direct, truthful mechanism."),
             ("This Nobel Prize-winning framework today powers electromagnetic spectrum auctions, public organ matching exchanges, and algorithmic ad bidding markets.", "이 노벨상을 수상한 프레임워크는 오늘날 전파 스펙트럼 경매, 공공 장기 기증 매칭 거래소, 알고리즘 광고 입찰 시장을 구동하고 있습니다.", "This Nobel Prize-winning framework today powers / electromagnetic spectrum auctions, / public organ matching exchanges, / and algorithmic ad bidding markets.")
         ],
         [("dispersed", "adj.", "분산된, 흩어진", "The remote sensors were dispersed across the entire mountain ridge."), ("normative", "adj.", "규범적인, 가치판단적인", "Normative political theory examines how societies ought to be governed."), ("incentivize", "v.", "동기를 부여하다, 유인하다", "Tax credits incentivize companies to invest in clean wind energy."), ("compatibility", "n.", "양립성, 호환성", "Incentive compatibility guarantees truthful bidding in Vickrey auctions."), ("replicate", "v.", "복제하다, 되풀이하다", "Independent laboratories failed to replicate the experimental finding.")],
         [("과거분사 수식", "...Mechanism design, often described as 'reverse game theory,' addresses... 삽입된 수동 분사구입니다."), ("현재분사 분사구문 ensuring", "...principle is incentive compatibility, ensuring that participants maximize... 결과를 설명하는 능동 분사구문입니다.")],
         [
             ("Why is mechanism design frequently characterized as 'reverse game theory'?", "메커니즘 디자인이 흔히 '역게임이론'으로 불리는 이유는 무엇인가요?", ["It starts from desired systemic outcomes and constructs the rules to induce them.", "It demands that all economic players gamble backward in time.", "It rejects the use of mathematical equations in economic analysis.", "It requires all auctions to be conducted in absolute secrecy."], 0, "바람직한 시스템적 결과에서 출발하여 이를 유도하는 규칙을 역으로 설계하기 때문입니다."),
             ("What does the principle of incentive compatibility ensure?", "유인 일치성(incentive compatibility) 원칙은 무엇을 보장하나요?", ["Truthful disclosure of private valuations maximizes each participant's individual payoff.", "Government regulators confiscate all private business profits.", "Only state-owned monopolies are permitted to participate in trade.", "All auction participants are guaranteed equal financial subsidies."], 0, "자신의 사적 가치를 진실하게 공개할 때 개인의 보상이 극대화되도록 보장합니다."),
             ("Which real-world application relies directly on mechanism design frameworks?", "어떤 실제 응용 사례가 메커니즘 디자인 프레임워크에 직접적으로 의존하나요?", ["Electromagnetic spectrum auctions and kidney donation matching", "Manual gold mining using picks and shovels", "Printing paper bank notes on industrial printing presses", "Setting retail prices for seasonal street fruits"], 0, "전파 스펙트럼 경매와 장기 기증 매칭(kidney matching exchanges)이 명시되었습니다.")
         ]),

        ("a-36", "The Neurobiology of the Default Mode Network", "디폴트 모드 네트워크의 신경생물학과 자아의 기원", "Cognitive Neuroscience", "Neuron",
         "아무런 외부 과제를 수행하지 않을 때 활성화되어 자전적 기억과 자아 성찰을 담당하는 뇌의 기저 연결망을 조명합니다.",
         [
             ("For decades, neuroscientists viewed resting-state brain activity as mere baseline noise overshadowed by task-directed cognitive processing.", "수십 년 동안 신경과학자들은 휴식 상태의 뇌 활동을 과제 지향적 인지 처리에 가려진 단순한 기저 소음으로 간주했습니다.", "For decades, neuroscientists viewed / resting-state brain activity / as mere baseline noise / overshadowed by task-directed cognitive processing."),
             ("However, pioneering fMRI investigations by Marcus Raichle revealed that an anatomically discrete neural circuit activates precisely when external attention ceases.", "그러나 마커스 라이클의 선구적인 fMRI 연구는 외부 주의가 중단될 때 바로 해부학적으로 뚜렷한 신경 회로가 활성화됨을 밝혔습니다.", "However, pioneering fMRI investigations by Marcus Raichle / revealed that an anatomically discrete neural circuit activates / precisely when external attention ceases."),
             ("Designated the Default Mode Network (DMN), this interconnected web encompasses the medial prefrontal cortex, posterior cingulate cortex, and angular gyrus.", "디폴트 모드 네트워크(DMN)로 명명된 이 상호 연결된 망은 내측 전전두피질, 후방 대상피질, 각회를 아우릅니다.", "Designated the Default Mode Network (DMN), / this interconnected web encompasses / the medial prefrontal cortex, posterior cingulate cortex, / and angular gyrus."),
             ("The DMN orchestrates introspective mental states, including autobiographical memory retrieval, mental simulation of future scenarios, and theory of mind.", "DMN은 자전적 기억 인출, 미래 시나리오에 대한 심적 시뮬레이션, 마음 이론을 포함한 내성적인 정신 상태들을 조율합니다.", "The DMN orchestrates introspective mental states, / including autobiographical memory retrieval, / mental simulation of future scenarios, / and theory of mind."),
             ("Crucially, hyperconnectivity within the DMN correlates with depressive rumination, whereas psychedelic compounds dramatically suppress DMN coherence.", "결정적으로 DMN 내의 과잉 연결성은 우울증적 반추와 상관관계를 보이며, 반면 환각제 화합물은 DMN의 응집성을 극적으로 억제합니다.", "Crucially, hyperconnectivity within the DMN / correlates with depressive rumination, / whereas psychedelic compounds / dramatically suppress DMN coherence."),
             ("This transient disintegration of DMN boundary architecture correlates directly with the subjective phenomenon of ego dissolution reported in altered consciousness.", "DMN 경계 구조의 이러한 일시적 붕괴는 변용된 의식 상태에서 보고되는 자아 소멸(ego dissolution)의 주관적 현상과 직접 상관됩니다.", "This transient disintegration of DMN boundary architecture / correlates directly / with the subjective phenomenon of ego dissolution / reported in altered consciousness.")
         ],
         [("overshadow", "v.", "그늘지게 하다, 무색하게 하다", "The diplomatic breakthrough was overshadowed by political unrest."), ("discrete", "adj.", "별개의, 분리된", "The speech signal was digitized into discrete temporal packets."), ("introspective", "adj.", "자기 성찰적인, 내성적인", "Solitude fosters deep, introspective philosophical writing."), ("rumination", "n.", "반추, 깊은 생각", "Depressive rumination locks individuals into circular negative thought loops."), ("disintegration", "n.", "붕괴, 분해", "The economic crisis triggered the rapid disintegration of the trade pact.")],
         [("과거분사 수동 분사구문", "Designated the Default Mode Network (DMN), this interconnected web encompasses... Being이 생략된 분사구문입니다."), ("접속사 whereas 대조", "...correlates with depressive rumination, whereas psychedelic compounds dramatically suppress... 대조 구문입니다.")],
         [
             ("When does the Default Mode Network (DMN) exhibit peak neural activation?", "디폴트 모드 네트워크(DMN)는 언제 정점의 신경 활성화를 보이나요?", ["When subjects are engaged in intense competitive mathematical calculation", "Precisely when individuals disengage from active external task demands", "During vigorous Olympic sprint training on outdoor tracks", "When individuals are actively dodging physical obstacles"], 1, "외부 과제에 대한 집중이 중단되고 휴식할 때 활성화된다고 밝혔습니다."),
             ("Which cognitive capacities are mediated by the Default Mode Network?", "어떤 인지 능력들이 디폴트 모드 네트워크에 의해 매개되나요?", ["Direct muscular reflex contractions in foot tendons", "Autobiographical memory retrieval, future simulation, and theory of mind", "Filtering auditory sound waves inside the outer cochlea", "Controlling insulin secretion from pancreatic beta cells"], 1, "자전적 기억 인출, 미래 시뮬레이션, 마음 이론 등 내성적 정신 상태를 조율한다고 명시했습니다."),
             ("What neurobiological correlate is associated with psychedelic-induced ego dissolution?", "환각제로 유도된 자아 소멸과 연관된 신경생물학적 현상은 무엇인가요?", ["Permanent calcification of the auditory cortex", "Transient disintegration and suppression of DMN connectivity coherence", "Doubling the volume of cerebrospinal fluid within two minutes", "The complete cessation of mitochondrial metabolism across the cerebellum"], 1, "DMN 응집성의 극적인 억제와 경계 구조의 일시적 붕괴라고 서술했습니다.")
         ]),

        ("a-37", "The Geopolitics of Critical Mineral Supply Chains", "핵심 광물 공급망의 지정학적 취약성과 안보", "International Security & Energy Geopolitics", "Foreign Affairs",
         "신재생 에너지와 첨단 반도체 전환에 필수적인 희토류, 리튬, 코발트 공급망의 지정학적 독점과 위험을 분석합니다.",
         [
             ("The global transition toward green renewable energy has paradoxically created new vectors of geopolitical vulnerability centered on critical minerals.", "친환경 재생 에너지로의 전 지구적 전환은 역설적으로 핵심 광물에 집중된 새로운 지정학적 취약성 경로를 창출했습니다.", "The global transition toward green renewable energy / has paradoxically created / new vectors of geopolitical vulnerability / centered on critical minerals."),
             ("Decarbonization technologies—including electric vehicle traction motors, lithium-ion battery cells, and offshore wind turbines—require unprecedented mineral inputs.", "전기차 구동 모터, 리튬 이온 배터리 셀, 해상 풍력 터빈을 포함한 탈탄소 기술은 전례 없는 광물 투입을 요구합니다.", "Decarbonization technologies / —including electric vehicle traction motors, lithium-ion battery cells, and offshore wind turbines— / require unprecedented mineral inputs."),
             ("Unlike petroleum markets, which feature diverse producers across multiple continents, critical mineral supply chains exhibit extreme geographic concentration.", "여러 대륙에 걸쳐 다양한 산유국들이 존재하는 석유 시장과 달리, 핵심 광물 공급망은 극단적인 지리적 집중도를 나타냅니다.", "Unlike petroleum markets, / which feature diverse producers across multiple continents, / critical mineral supply chains / exhibit extreme geographic concentration."),
             ("A single nation, the People's Republic of China, controls approximately seventy percent of rare earth extraction and over ninety percent of processing capacity.", "단일 국가인 중국이 희토류 채굴의 약 70%와 정련 가공 역량의 90% 이상을 통제하고 있습니다.", "A single nation, the People's Republic of China, / controls approximately seventy percent of rare earth extraction / and over ninety percent of processing capacity."),
             ("Refining neodymium, dysprosium, and cobalt involves toxic, energy-intensive hydrometallurgical operations that Western nations historically outsourced due to strict environmental mandates.", "네오디뮴, 디스프로슘, 코발트 정련은 서구 국가들이 엄격한 환경 규제로 인해 역사적으로 외주화했던 유독하고 에너지 집약적인 습식 제련 공정을 수반합니다.", "Refining neodymium, dysprosium, and cobalt / involves toxic, energy-intensive hydrometallurgical operations / that Western nations historically outsourced / due to strict environmental mandates."),
             ("Consequently, weaponized export controls could paralyze high-tech industrial manufacturing, elevating resource security to a preeminent national defense imperative.", "결과적으로, 무기화된 수출 통제는 첨단 산업 제조업을 마비시킬 수 있으며, 자원 안보를 가장 중요한 국방 과제로 격상시키고 있습니다.", "Consequently, / weaponized export controls could paralyze / high-tech industrial manufacturing, / elevating resource security / to a preeminent national defense imperative.")
         ],
         [("vector", "n.", "매개체, 방향, 경로", "Geopolitical rivalries opened new vectors of economic espionage."), ("decarbonization", "n.", "탈탄소화", "Achieving net-zero targets demands aggressive industrial decarbonization."), ("outsource", "v.", "외주를 주다, 아웃소싱하다", "Tech firms outsourced customer service operations to multilingual hubs."), ("mandate", "n.", "지침, 의무 규정", "The environmental agency issued strict carbon emission mandates."), ("preeminent", "adj.", "탁월한, 가장 중요한", "She established herself as the preeminent historian of the Byzantine Empire.")],
         [("관계대명사 계속적 용법", "...petroleum markets, which feature diverse producers..., critical mineral... 주절에 대조 정보를 제공하는 관계대명사절입니다."), ("분사구문 elevating", "...paralyze high-tech manufacturing, elevating resource security... 결과를 설명하는 능동 분사구문입니다.")],
         [
             ("How do critical mineral supply chains differ structurally from petroleum markets?", "핵심 광물 공급망은 구조적으로 석유 시장과 어떻게 다른가요?", ["Critical minerals are completely inexhaustible and require no refining.", "Critical mineral supply chains exhibit extreme geographic concentration in extraction and refining.", "Petroleum can only be extracted within polar Arctic permafrost.", "Critical minerals are distributed identically in every country's backyard."], 1, "다양한 산유국이 있는 석유와 달리 채굴 및 정련에서 극단적인 지리적 집중도를 보인다고 설명했습니다."),
             ("Why did Western nations historically outsource critical mineral processing?", "서구 국가들은 역사적으로 왜 핵심 광물 가공 공정을 외주화했나요?", ["Processing involves toxic, energy-intensive operations shunned under strict domestic environmental regulations.", "Western scientists completely forgot how to purify chemical elements.", "Mining critical minerals was outlawed by the United Nations Security Council.", "Critical minerals were deemed completely worthless until last year."], 0, "엄격한 환경 규제로 인해 유독하고 에너지 집약적인 습식 제련 작업을 외주화했다고 밝혔습니다."),
             ("What strategic risk arises from concentrated mineral supply chains?", "집중된 광물 공급망으로부터 어떤 전략적 위험이 발생하나요?", ["Weaponized export controls could paralyze modern high-tech industrial manufacturing.", "Solar panels will automatically explode during full moon nights.", "Global sea levels will drop by four hundred meters immediately.", "Electric cars will transform into mechanical diesel locomotives."], 0, "무기화된 수출 통제가 첨단 산업 제조업을 마비시킬 수 있다고 경고했습니다.")
         ]),

        ("a-38", "Algorithmic Complexity and the P versus NP Dilemma", "알고리즘 복잡도 이론과 P-NP 난제", "Theoretical Computer Science", "Communications of the ACM",
         "계산 복잡도 이론의 최대 미해결 문제인 다항 시간 검증과 다항 시간 해결의 동치성 여부와 그 암호학적 파장을 다룹니다.",
         [
             ("Formulated by Stephen Cook and Leonid Levin in 1971, the P versus NP problem stands as the crowning unsolved conundrum of theoretical computer science.", "1971년 스티븐 쿡과 레오니드 레빈에 의해 정식화된 P 대 NP 문제는 이론 컴퓨터 과학의 최대 미해결 난제로 우뚝 서 있습니다.", "Formulated by Stephen Cook and Leonid Levin in 1971, / the P versus NP problem stands / as the crowning unsolved conundrum / of theoretical computer science."),
             ("The complexity class P comprises decision problems solvable by a deterministic Turing machine within polynomial time relative to input length.", "복잡도 부류 P는 입력 길이에 비례하여 결정론적 튜링 기계가 다항 시간 내에 해결할 수 있는 결정 문제들로 구성됩니다.", "The complexity class P comprises decision problems / solvable by a deterministic Turing machine / within polynomial time / relative to input length."),
             ("Conversely, NP consists of problems whose proposed solutions can be verified in polynomial time, even if finding that solution requires exhaustive brute-force search.", "반대로 NP는 비록 해를 찾는 데는 철저한 무차별 대입 탐색이 필요할지라도, 제시된 해답이 맞는지 여부를 다항 시간 내에 검증할 수 있는 문제들로 구성됩니다.", "Conversely, / NP consists of problems / whose proposed solutions can be verified in polynomial time, / even if finding that solution / requires exhaustive brute-force search."),
             ("The central dilemma asks whether every problem with a quickly verifiable solution must also possess an algorithm capable of discovering it quickly.", "핵심 딜레마는 신속하게 검증 가능한 해를 지닌 모든 문제가 반드시 그 해를 신속하게 찾아낼 수 있는 알고리즘도 가져야 하는지 여부를 묻는 것입니다.", "The central dilemma asks / whether every problem with a quickly verifiable solution / must also possess an algorithm / capable of discovering it quickly."),
             ("If P were to equal NP, the algorithmic consequences would be staggering: public-key cryptography would evaporate, yet global optimization problems would solve effortlessly.", "만약 P가 NP와 같다면 알고리즘적 파장은 경이로울 것입니다. 공개키 암호학은 증발하겠지만 전 지구적 최적화 문제는 손쉽게 해결될 것입니다.", "If P were to equal NP, / the algorithmic consequences would be staggering: / public-key cryptography would evaporate, / yet global optimization problems would solve effortlessly."),
             ("Most computer theorists strongly intuit that P does not equal NP, yet a rigorous mathematical proof continues to elude the global academic community.", "대부분의 컴퓨터 이론가들은 P와 NP가 같지 않다고 강력히 직관하지만, 엄격한 수학적 증명은 여전히 전 세계 학계를 피해 가고 있습니다.", "Most computer theorists strongly intuit / that P does not equal NP, / yet a rigorous mathematical proof / continues to elude the global academic community.")
         ],
         [("conundrum", "n.", "난제, 수수께끼", "Navigating the ethical dilemmas of artificial intelligence is a profound conundrum."), ("deterministic", "adj.", "결정론적인", "Classical physics operates under deterministic mechanical equations."), ("exhaustive", "adj.", "철저한, 완전한", "Scholars conducted an exhaustive archival investigation across European libraries."), ("staggering", "adj.", "경이로운, 충격적인", "The merger created an enterprise with staggering annual revenues."), ("elude", "v.", "피하다, 이해되지 않다", "The underlying cause of Alzheimer's disease continues to elude medical scientists.")],
         [("가정법 과거", "If P were to equal NP, the algorithmic consequences would be staggering... 실현 가능성이 희박한 가정을 나타내는 가정법 과거 were to 구문입니다."), ("whose 소유격 관계대명사", "...problems whose proposed solutions can be verified... 선행사 problems의 소유격을 나타냅니다.")],
         [
             ("How is the computational complexity class P defined in computer science?", "컴퓨터 과학에서 복잡도 부류 P는 어떻게 정의되나요?", ["Problems solvable within polynomial time on a deterministic machine", "Problems that take infinite thermodynamic energy to solve", "Problems that can only be calculated on ancient wooden abacuses", "Problems whose answers change every time a question is asked"], 0, "결정론적 기계에서 다항 시간 내에 해결될 수 있는 문제들로 정의된다고 명시했습니다."),
             ("What defines problems in the class NP?", "부류 NP에 속하는 문제들의 정의는 무엇인가요?", ["They cannot be stored inside any electronic semiconductor memory.", "Their proposed solutions can be verified in polynomial time.", "They only concern prime numbers larger than ten billion digits.", "They require manual ink pen verification by professional mathematicians."], 1, "제시된 해답을 다항 시간 내에 검증할 수 있는 문제들이라고 설명했습니다."),
             ("What would happen to modern public-key cryptography if P equals NP?", "만약 P가 NP와 같다면 현대 공개키 암호학에는 어떤 일이 발생하나요?", ["It would become infinitely more secure against quantum computers.", "It would evaporate because encrypted secret keys could be discovered quickly.", "It would be adopted as the official national currency of Switzerland.", "It would require physical stone tablets to decrypt text messages."], 1, "암호 해독이 너무 쉬워져 공개키 암호학이 증발할 것(would evaporate)이라고 명시했습니다.")
         ]),

        ("a-39", "Gravitational Wave Astronomy and Spacetime Metric Distortions", "중력파 천문학과 시공간 계량 왜곡의 검출", "Astrophysics & General Relativity", "Physical Review Letters",
         "블랙홀과 중성자별의 충돌이 발생시키는 시공간의 물결을 레이저 간섭계(LIGO)로 검출하여 우주를 관측하는 혁신을 다룹니다.",
         [
             ("A century after Albert Einstein predicted gravitational waves in his 1915 general theory of relativity, physicists achieved direct experimental verification.", "알베르트 아인슈타인이 1915년 일반 상대성 이론에서 중력파를 예측한 지 한 세기 만에, 물리학자들은 직접적인 실험적 검증을 달성했습니다.", "A century after Albert Einstein predicted gravitational waves / in his 1915 general theory of relativity, / physicists achieved / direct experimental verification."),
             ("In general relativity, gravity is not a Newtonian mechanical force, but rather the manifestation of spacetime curvature warped by mass and energy.", "일반 상대성 이론에서 중력은 뉴턴식 기계적 힘이 아니라, 질량과 에너지에 의해 휘어진 시공간 곡률의 발현입니다.", "In general relativity, / gravity is not a Newtonian mechanical force, / but rather the manifestation of spacetime curvature / warped by mass and energy."),
             ("Cataclysmic cosmic events—such as coalescing binary black holes or colliding neutron stars—radiate quadrupolar ripples across the cosmic spacetime fabric.", "쌍성 블랙홀의 병합이나 중성자별의 충돌과 같은 격변적인 우주 사건들은 우주 시공간 구조를 가로지르는 사중극자 물결을 방출합니다.", "Cataclysmic cosmic events / —such as coalescing binary black holes or colliding neutron stars— / radiate quadrupolar ripples / across the cosmic spacetime fabric."),
             ("The Laser Interferometer Gravitational-Wave Observatory (LIGO) detects these imperceptible metric distortions using four-kilometer laser beams reflected between suspended test mirrors.", "레이저 간섭계 중력파 관측소(LIGO)는 매달린 시험용 거울 사이를 반사하는 4킬로미터 레이저 광선을 사용하여 이 미세한 계량 왜곡을 감지합니다.", "The Laser Interferometer Gravitational-Wave Observatory (LIGO) / detects these imperceptible metric distortions / using four-kilometer laser beams / reflected between suspended test mirrors."),
             ("When a gravitational wave sweeps past Earth, it alternately compresses and elongates the perpendicular laser cavities by less than one ten-thousandth of a proton's width.", "중력파가 지구를 스쳐 지나갈 때, 그것은 수직인 레이저 공간을 양성자 폭의 1만 분의 1도 안 되는 크기로 번갈아 압축하고 신장시킵니다.", "When a gravitational wave sweeps past Earth, / it alternately compresses and elongates / the perpendicular laser cavities / by less than one ten-thousandth of a proton's width."),
             ("Gravitational wave astronomy has fundamentally broadened human perception, allowing astrophysicists to listen to the dark, violent choreography of the universe.", "중력파 천문학은 인간의 인식을 근본적으로 넓혀, 천체물리학자들이 우주의 어둡고 격렬한 안무를 들을 수 있게 해 주었습니다.", "Gravitational wave astronomy has fundamentally broadened human perception, / allowing astrophysicists to listen / to the dark, violent choreography / of the universe.")
         ],
         [("coalesce", "v.", "병합하다, 하나로 합쳐지다", "Two corporate entities coalesced to dominate the telecommunications market."), ("quadrupolar", "adj.", "사중극자의", "Gravitational radiation carries a distinctive quadrupolar geometric symmetry."), ("imperceptible", "adj.", "미세한, 감지하기 어려운", "The tectonic shift caused an almost imperceptible tremor at the surface."), ("elongate", "v.", "늘이다, 신장시키다", "Tidal gravitational forces elongate orbiting moons along their orbital plane."), ("choreography", "n.", "안무, 연출된 움직임", "Satellites perform a synchronized orbital choreography around Earth.")],
         [("not A but rather B", "gravity is not a Newtonian mechanical force, but rather the manifestation of... 대조 구문입니다."), ("분사구문 allowing", "...broadened human perception, allowing astrophysicists to listen... 결과를 설명하는 능동 분사구문입니다.")],
         [
             ("What is gravity according to Einstein's general theory of relativity?", "아인슈타인의 일반 상대성 이론에 따르면 중력이란 무엇인가요?", ["A mechanical magnetic cable pulling planets together", "The manifestation of spacetime curvature warped by mass and energy", "An optical illusion created by atmospheric heat refraction", "A stream of subatomic chemical particles leaking from volcanic magma"], 1, "질량과 에너지에 의해 휘어진 시공간 곡률의 발현이라고 설명했습니다."),
             ("How does LIGO measure metric distortions caused by passing gravitational waves?", "LIGO는 지나가는 중력파가 유발하는 계량 왜곡을 어떻게 측정하나요?", ["Using thermometers placed inside deep subterranean ice caves", "Using four-kilometer perpendicular laser cavities reflected between mirrors", "Through radio satellite dishes pointed toward distant quasars", "By floating sensitive acoustic microphones in the open Pacific Ocean"], 1, "거울 사이를 왕복하는 4킬로미터 수직 레이저 간섭계를 이용한다고 설명했습니다."),
             ("By how much does a passing gravitational wave typically distort LIGO's detector arms?", "통과하는 중력파는 전형적으로 LIGO의 검출기 팔을 얼마나 왜곡시키나요?", ["Several kilometers of physical displacement", "Less than one ten-thousandth the diameter of a single proton", "Approximately five meters during midday earthquakes", "Around forty centimeters during seasonal solar eclipses"], 1, "단 하나의 양성자 폭의 1만 분의 1 미만(less than one ten-thousandth of a proton's width)이라고 명시했습니다.")
         ]),

        ("a-40", "Endosymbiotic Theory and the Genesis of Eukaryotic Complexity", "세포내 공생설과 진핵생물 복잡성의 기원", "Evolutionary Cell Biology", "Cell",
         "린 마굴리스의 세포내 공생설이 밝혀낸 미토콘드리아와 엽록체의 세균 기원 및 다세포 생명의 진화적 도약을 다룹니다.",
         [
             ("The emergence of eukaryotic cells harboring membrane-bound organelles represents the most consequential evolutionary transition in the history of terrestrial life.", "막으로 둘러싸인 세포소기관을 품은 진핵세포의 출현은 지구 생명 역사에서 가장 중대한 진화적 전환을 나타냅니다.", "The emergence of eukaryotic cells / harboring membrane-bound organelles / represents the most consequential evolutionary transition / in the history of terrestrial life."),
             ("For over a billion years, life was restricted exclusively to structurally primitive, single-celled prokaryotic bacteria and archaea.", "10억 년 이상 동안, 생명은 구조적으로 원시적인 단세포 원핵 세균과 고세균에만 국한되어 있었습니다.", "For over a billion years, / life was restricted exclusively / to structurally primitive, single-celled prokaryotic bacteria and archaea."),
             ("Championed by evolutionary biologist Lynn Margulis in 1967, the endosymbiotic theory revolutionized biology by positing organelle genesis through cellular phagocytosis.", "1967년 진화생물학자 린 마굴리스가 옹호한 세포내 공생설은 세포 포식작용을 통한 소기관 형성을 상정함으로써 생물학을 혁신했습니다.", "Championed by evolutionary biologist Lynn Margulis in 1967, / the endosymbiotic theory revolutionized biology / by positing organelle genesis / through cellular phagocytosis."),
             ("An ancestral archaeal host engulfed an aerobic alpha-proteobacterium, but rather than digesting the prey, entered into an obligate metabolic symbiosis.", "조상 고세균 숙주가 호기성 알파-프로테오박테리아를 삼켰으나, 먹이를 소화시키는 대신 필수적인 대사적 공생 관계에 들어갔습니다.", "An ancestral archaeal host engulfed / an aerobic alpha-proteobacterium, / but rather than digesting the prey, / entered into an obligate metabolic symbiosis."),
             ("The internalized bacterium evolved into the modern mitochondrion, supplying massive ATP energy yields that powered genomic expansion and cellular compartmentalization.", "내재화된 박테리아는 현대의 미토콘드리아로 진화하여, 게놈 확장과 세포 구획화를 뒷받침하는 막대한 ATP 에너지를 공급했습니다.", "The internalized bacterium evolved into the modern mitochondrion, / supplying massive ATP energy yields / that powered genomic expansion / and cellular compartmentalization."),
             ("Corroborated by independent circular genomes and double lipid membranes inside mitochondria, endosymbiosis demonstrates that cooperation, not mere competition, fuels macroevolution.", "미토콘드리아 내부의 독립적인 원형 게놈과 이중 지질막에 의해 확증된 세포내 공생은 단순한 경쟁이 아닌 협력이 대진화를 추동함을 증명합니다.", "Corroborated by independent circular genomes / and double lipid membranes inside mitochondria, / endosymbiosis demonstrates / that cooperation, not mere competition, fuels macroevolution.")
         ],
         [("consequential", "adj.", "중대한, 결과로서 일어나는", "The ratification of the treaty was a consequential historic event."), ("phagocytosis", "n.", "식세포 작용, 세포 포식", "Immune macrophages ingest cellular debris through phagocytosis."), ("obligate", "adj.", "의무적인, 절대적인 (생물학: 편성의)", "Certain parasites are obligate pathogens unable to reproduce alone."), ("compartmentalization", "n.", "구획화", "Subcellular compartmentalization prevents biochemical interference between incompatible reactions."), ("corroborate", "v.", "확증하다, 입증하다", "Independent geological strata corroborated the asteroid impact hypothesis.")],
         [("과거분사 수동 분사구문", "Championed by evolutionary biologist Lynn Margulis..., the theory revolutionized... Being이 생략된 수동 분사구문입니다."), ("삽입구 not A but B 변형", "...cooperation, not mere competition, fuels macroevolution... 단순 경쟁이 아닌 협력이 진화를 추동한다는 강조 표현입니다.")],
         [
             ("Who famously championed the endosymbiotic theory in 1967?", "1967년 세포내 공생설을 유명하게 옹호한 생물학자는 누구인가요?", ["Charles Darwin", "Gregor Mendel", "Lynn Margulis", "Louis Pasteur"], 2, "1967년 진화생물학자 린 마굴리스(Lynn Margulis)가 주창했다고 명시했습니다."),
             ("How did mitochondria originate according to endosymbiotic theory?", "세포내 공생설에 따르면 미토콘드리아는 어떻게 기원했나요?", ["An ancestral host cell engulfed an aerobic bacterium that became an obligate metabolic symbiont.", "They condensed from atmospheric volcanic ash inside ocean thermal vents.", "They were formed by viral RNA molecules synthesizing synthetic silicon batteries.", "They crystallized spontaneously inside frozen polar glacier fissures."], 0, "조상 숙주 세포가 호기성 박테리아를 삼킨 후 필수적인 대사 공생체로 발전했다고 설명했습니다."),
             ("What molecular evidence directly corroborates the bacterial origin of mitochondria?", "미토콘드리아의 세균 기원을 직접적으로 확증하는 분자적 증거는 무엇인가요?", ["Independent circular DNA genomes and double lipid membranes inside mitochondria", "Their ability to speak aloud using high-frequency sonic clicks", "Their complete lack of any chemical proteins or amino acids", "Mitochondria dissolving completely whenever exposed to daylight"], 0, "미토콘드리아 내부의 독립적인 원형 게놈(independent circular genomes)과 이중 지질막이 명시되었습니다.")
         ])
    ]
    return a_extra

if __name__ == "__main__":
    print(f"Generated extra advanced passages: {len(get_advanced_expansion())}")
