# -*- coding: utf-8 -*-
"""
generate_expansion_180_inter.py
Intermediate passages i-51 to i-60
Sources: Nature, Science, Cell, The Economist, Neuron, Physical Review, Communications of the ACM
"""

def get_expansion_180_i():
    return [
        ("i-51", "The Evolutionary Origins of Human Bipedalism", "인류 직립보행의 진화적 기원과 신체적 변화", "Paleoanthropology & Evolutionary Biology", "Nature",
         "사바나 환경 적응, 체온 조절, 도구 운반 등 인류가 두 발로 걷게 된 진화적 동인과 골격 변화를 분석합니다.",
         [
             ("The transition from quadrupedal knuckle-walking to obligate bipedalism constitutes the defining evolutionary milestone of hominin lineage divergence.", "사지 너클 보행에서 완전한 직립보행으로의 전환은 호미닌 계통 분기의 결정적인 진화적 이정표를 구성합니다.", "The transition from quadrupedal knuckle-walking to obligate bipedalism / constitutes the defining evolutionary milestone / of hominin lineage divergence."),
             ("Fossil evidence from Australopithecus afarensis, notably the famous Lucy skeleton discovered in 1974, proves bipedalism preceded enlarged encephalization.", "1974년 발견된 유명한 루시 화석을 필두로 한 오스트랄로피테쿠스 아파렌시스의 화석 증거는 직립보행이 뇌의 대형화보다 앞섰음을 증명합니다.", "Fossil evidence from Australopithecus afarensis, / notably the famous Lucy skeleton discovered in 1974, / proves bipedalism preceded enlarged encephalization."),
             ("Multiple evolutionary pressures catalyzed this anatomical adaptation when eastern African rainforests retreated into open savanna grasslands.", "동아프리카 열대우림이 탁 트인 사바나 초원으로 후퇴했을 때 여러 진화적 압력이 이러한 해부학적 적응을 촉진했습니다.", "Multiple evolutionary pressures catalyzed this anatomical adaptation / when eastern African rainforests retreated / into open savanna grasslands."),
             ("Walking upright dramatically reduced solar radiation exposure while enhancing cooling convective airflow over the torso.", "직립하여 걷는 것은 상체 위로 흐르는 냉각 대류 기류를 강화하는 동시에 태양 복사열 노출을 극적으로 감소시켰습니다.", "Walking upright dramatically reduced solar radiation exposure / while enhancing cooling convective airflow / over the torso."),
             ("Crucially, freeing the forelimbs from locomotive burdens allowed early hominins to carry harvested food, nurse offspring, and manipulate stone cutting tools.", "결정적으로 앞다리를 이동 부담으로부터 해방시킨 것은 초기 호미닌이 수확한 음식을 운반하고 새끼를 돌보며 석기 절삭 도구를 조작할 수 있게 해주었습니다.", "Crucially, freeing the forelimbs from locomotive burdens / allowed early hominins to carry harvested food, / nurse offspring, / and manipulate stone cutting tools."),
             ("Skeletal restructuring—including a bowl-shaped pelvis, lordotic spinal curvature, and arched feet—permanently transformed ancestral locomotion.", "그릇 모양의 골반, 척추 전만 곡률, 아치형 발을 포함한 골격 재구조화는 조상의 이동 방식을 영구적으로 변화시켰습니다.", "Skeletal restructuring / —including a bowl-shaped pelvis, lordotic spinal curvature, and arched feet— / permanently transformed ancestral locomotion.")
         ],
         [("obligate", "adj.", "의무적인 (생물학: 전적인, 필수의)", "Obligate carnivores must consume meat to obtain essential taurine."), ("encephalization", "n.", "뇌의 대형화, 두화", "Hominin evolution is characterized by rapid progressive encephalization."), ("catalyze", "v.", "촉진하다, 촉매 작용을 하다", "Technological innovation catalyzed economic growth across the nation."), ("locomotive", "adj.", "이동의, 운동의", "Fin rays provide locomotive propulsion in swimming fishes."), ("lordotic", "adj.", "척추 전만의 (앞으로 휜)", "The human lumbar spine features a lordotic curve that cushions walking impacts.")],
         [("동명사 주어", "Walking upright dramatically reduced solar radiation... 동명사구 주어입니다."), ("분사구문 freeing", "Crucially, freeing the forelimbs..., allowed hominins to... 수단을 나타내는 분사구문입니다.")],
         [
             ("What fossil evidence demonstrated that bipedal walking evolved before large human brains?", "어떤 화석 증거가 직립보행이 인간의 거대한 뇌보다 먼저 진화했음을 증명했나요?", ["The Australopithecus afarensis skeleton named Lucy", "Neanderthal burial sites discovered in France", "Fossilized crocodile jawbones from the Nile River", "Mammoth ivory tusks found in Siberian permafrost"], 0, "1974년 발견된 오스트랄로피테쿠스 아파렌시스 화석인 루시(Lucy)라고 설명했습니다."),
             ("What thermal advantage was provided by walking upright on open savannas?", "탁 트인 사바나에서 직립보행이 제공한 열적 이점은 무엇이었나요?", ["Complete immunity from lightning strikes", "Reduced solar radiation absorption and enhanced convective airflow cooling", "Eliminating the need to drink water for three years", "Generating internal electrical currents to heat muscles in winter"], 1, "태양 복사열 흡수를 줄이고 대류 기류 냉각을 강화했다고 밝혔습니다."),
             ("What behavioral milestone was enabled by liberating the forelimbs from walking?", "앞다리가 걷는 일에서 해방됨으로써 가능해진 결정적인 행동적 이정표는 무엇이었나요?", ["Carrying food, holding nursing offspring, and manipulating stone tools", "Learning how to breathe underwater", "Flying between tall savanna acacia trees", "Digging ten-kilometer underground tunnels"], 0, "음식 운반, 새끼 양육, 석기 도구 조작이라고 명시했습니다.")
         ]),

        ("i-52", "The Economics of Carbon Pricing and Cap-and-Trade", "탄소 배출권 거래제와 탄소 가격 책정의 경제학", "Environmental Economics & Climate Policy", "The Economist",
         "온실가스 배출이라는 외부 불경제를 시장 메커니즘을 통해 내부화하여 청정 기술 투자를 유도하는 탄소 시장을 분석합니다.",
         [
             ("Global climate change represents the quintessential market failure—an unpriced negative externality where polluters shift environmental costs onto society.", "전 지구적 기후변화는 오염자가 환경 비용을 사회로 전가하는 가격이 매겨지지 않은 부정적 외부효과라는 대표적인 시장 실패를 나타냅니다.", "Global climate change represents the quintessential market failure / —an unpriced negative externality / where polluters shift environmental costs onto society."),
             ("To internalize these environmental damages, progressive economists advocate placing an explicit financial price on carbon emissions.", "이러한 환경 피해를 내부화하기 위해, 진보적인 경제학자들은 탄소 배출에 명시적인 재정적 가격을 매길 것을 옹호합니다.", "To internalize these environmental damages, / progressive economists advocate / placing an explicit financial price / on carbon emissions."),
             ("In a cap-and-trade architecture, governments establish an aggregate ceiling on permitted industrial emissions, which ratchets downward annually.", "배출권 거래제 구조에서 정부는 허용된 산업 배출량에 대한 총량 상한선을 설정하며, 이는 매년 하향 조정됩니다.", "In a cap-and-trade architecture, / governments establish an aggregate ceiling / on permitted industrial emissions, / which ratchets downward annually."),
             ("Regulated power plants and factories receive or purchase tradable emissions allowances, creating an active secondary market.", "규제 대상 발전소와 공장은 거래 가능한 배출권을 받거나 구매하여 활발한 2차 시장을 형성합니다.", "Regulated power plants and factories / receive or purchase tradable emissions allowances, / creating an active secondary market."),
             ("Enterprises that abate greenhouse emissions cheaply can sell surplus allowances to facilities facing prohibitive retrofitting expenses.", "온실가스 배출을 저렴하게 줄일 수 있는 기업은 엄청난 개보수 비용에 직면한 시설에 잉여 배출권을 판매할 수 있습니다.", "Enterprises that abate greenhouse emissions cheaply / can sell surplus allowances / to facilities facing prohibitive retrofitting expenses."),
             ("By harnessing flexible market incentives rather than rigid bureaucratic mandates, carbon pricing spurs least-cost technological decarbonization.", "경직된 관료적 명령 대신 유연한 시장 인센티브를 활용함으로써, 탄소 가격 책정은 최소 비용의 기술적 탈탄소화를 촉진합니다.", "By harnessing flexible market incentives / rather than rigid bureaucratic mandates, / carbon pricing spurs / least-cost technological decarbonization.")
         ],
         [("externality", "n.", "외부효과 (제3자에게 미치는 경제적 영향)", "Industrial smog is a classic negative externality affecting public health."), ("ratchet", "v.", "점진적으로 올리거나 내리다", "Central banks ratcheted interest rates upward to combat inflation."), ("allowance", "n.", "허용량, 배출권", "Firms must surrender one carbon allowance per metric ton emitted."), ("prohibitive", "adj.", "엄두가 안 나는, 지나치게 높은", "The prohibitive cost of experimental satellites delayed launch operations."), ("retrofit", "v.", "개보수하다, 사후 장착하다", "Engineers retrofitted the coal plant with sulfur scrubbing filters.")],
         [("to부정사 목적 부사구", "To internalize these environmental damages, economists advocate... 목적을 나타내는 to부정사입니다."), ("전치사 By + -ing", "By harnessing flexible market incentives..., carbon pricing spurs... 수단과 방법을 나타냅니다.")],
         [
             ("What economic concept describes industrial pollution that imposes uncompensated costs on society?", "사회에 보상되지 않은 비용을 전가하는 산업 오염을 설명하는 경제학적 개념은 무엇인가요?", ["An unpriced negative externality", "A sovereign gold bullion reserve", "A frictionless barter currency", "A government agricultural subsidy"], 0, "가격이 책정되지 않은 부정적 외부효과(negative externality)라고 설명했습니다."),
             ("How does a cap-and-trade regulatory system operate?", "배출권 거래제(cap-and-trade) 규제 시스템은 어떻게 작동하나요?", ["Governments ban all manufacturing operations permanently.", "An overall emissions cap is set and ratcheted down, while permits are traded in a market.", "Factories are allowed to emit infinite carbon if they pay a fixed parking fine.", "All electric power plants are nationalized under military control."], 1, "총량 상한선을 점진적으로 낮추면서 기업 간 배출권 거래를 허용하는 시장 메커니즘이라고 명시했습니다."),
             ("Why is market-based carbon pricing considered superior to rigid command-and-control mandates?", "시장 기반 탄소 가격 책정이 경직된 행정 명령보다 우수하다고 여겨지는 이유는 무엇인가요?", ["It achieves technological decarbonization at the lowest systemic economic cost.", "It completely eliminates the need for wind and solar energy.", "It guarantees that coal prices drop to zero dollars.", "It prevents all foreign corporations from trading across borders."], 0, "가장 저렴한 시스템적 비용으로 기술적 탈탄소화를 달성하기 때문이라고 밝혔습니다.")
         ]),

        ("i-53", "Dopamine and the Reward Prediction Error", "도파민 신경망과 보상 예측 오차(RPE)의 메커니즘", "Cognitive Neuroscience & Neurochemistry", "Neuron",
         "도파민이 단순한 쾌락 물질이 아니라 기대와 실제 보상의 격차를 계산하여 학습을 유도하는 신호임을 규명합니다.",
         [
             ("Popular culture routinely mischaracterizes dopamine as a chemical agent of pure physical pleasure.", "대중문화는 도파민을 순수한 육체적 쾌락의 화학 물질로 일상적으로 잘못 규정합니다.", "Popular culture routinely mischaracterizes dopamine / as a chemical agent of pure physical pleasure."),
             ("However, neurobiological research by Wolfram Schultz revealed that midbrain dopamine neurons actually encode reward prediction errors (RPE).", "그러나 볼프람 슐츠의 신경생물학 연구는 중뇌 도파민 뉴런이 실제로는 보상 예측 오차(RPE)를 부호화한다는 것을 밝혔습니다.", "However, neurobiological research by Wolfram Schultz / revealed that midbrain dopamine neurons / actually encode reward prediction errors (RPE)."),
             ("When an organism receives an unexpected reward, dopaminergic neurons in the ventral tegmental area fire in sharp, positive bursts.", "유기체가 예상치 못한 보상을 받을 때, 복측 피개 구역의 도파민성 뉴런은 날카롭고 긍정적인 신호 폭발을 일으킵니다.", "When an organism receives an unexpected reward, / dopaminergic neurons in the ventral tegmental area / fire in sharp, positive bursts."),
             ("If an anticipated reward arrives exactly as forecasted by sensory cues, dopamine firing remains entirely baseline.", "만약 예상된 보상이 감각적 단서에 의해 예측된 대로 정확하게 도착하면, 도파민 분사는 완전히 기저 상태를 유지합니다.", "If an anticipated reward arrives / exactly as forecasted by sensory cues, / dopamine firing remains / entirely baseline."),
             ("Conversely, if an expected reward fails to materialize, dopaminergic activity plummets sharply below resting levels, signaling disappointment.", "반대로, 기대했던 보상이 실현되지 않으면, 도파민 활동은 안정 상태 아래로 급격히 떨어지며 실망감을 신호합니다.", "Conversely, / if an expected reward fails to materialize, / dopaminergic activity plummets sharply / below resting levels, / signaling disappointment."),
             ("By calculating the mathematical gap between expectation and reality, dopamine functions as a biological reinforcement learning algorithm.", "기대와 현실 사이의 수학적 격차를 계산함으로써, 도파민은 생물학적 강화 학습 알고리즘으로 기능합니다.", "By calculating the mathematical gap / between expectation and reality, / dopamine functions / as a biological reinforcement learning algorithm.")
         ],
         [("mischaracterize", "v.", "잘못 규정하다, 오도하다", "Critics mischaracterized the defensive treaty as an act of aggression."), ("ventral", "adj.", "복측의, 배 쪽의", "The ventral tegmental area projects dopaminergic axons to the forebrain."), ("anticipate", "v.", "예상하다, 기대하다", "Economists anticipate a modest reduction in inflation this quarter."), ("materialize", "v.", "실현되다, 구체화되다", "The promised foreign investments failed to materialize during the crisis."), ("reinforcement", "n.", "강화, 보강", "Positive reinforcement encourages productive classroom behavior.")],
         [("분사구문 signaling", "...plummets sharply below resting levels, signaling disappointment... 결과를 나타내는 분사구문입니다."), ("전치사 By + -ing", "By calculating the mathematical gap..., dopamine functions as... 수단을 나타내는 구문입니다.")],
         [
             ("What common cultural myth regarding dopamine is debunked in the text?", "도파민에 관한 어떤 대중적 신화가 본문에서 논파되었나요?", ["That dopamine is directly identical to sleep hormones", "That dopamine is simply a chemical agent of pure physical pleasure", "That dopamine exists only inside plant roots", "That dopamine dissolves all brain synapses"], 1, "단순히 순수한 육체적 쾌락의 화학 물질이라는 통념을 바로잡았습니다."),
             ("How do midbrain dopamine neurons respond to an unexpected reward?", "중뇌 도파민 뉴런은 예상치 못한 보상에 어떻게 반응하나요?", ["They fire in sharp, positive burst activity above baseline.", "They permanently shut down and die immediately.", "They turn into red blood cells.", "They absorb all glucose from the bloodstream."], 0, "기저 수준을 뛰어넘는 날카롭고 긍정적인 신호 폭발(positive bursts)을 일으킨다고 설명했습니다."),
             ("What computational role does dopamine perform according to neurobiology?", "신경생물학에 따르면 도파민은 어떤 계산적 역할을 수행하나요?", ["Calculating the reward prediction error to drive reinforcement learning", "Encoding foreign language dictionaries into audio sounds", "Controlling heart valve contraction during deep sleep", "Preventing all headaches by numbing skull nerves"], 0, "기대와 현실의 오차를 계산하여 강화 학습을 추동하는 생물학적 알고리즘 역할을 한다고 명시했습니다.")
         ]),

        ("i-54", "The Physics of Superconductivity and the Meissner Effect", "초전도 현상의 양자역학: 저항 제로와 마이스너 효과", "Condensed Matter Physics", "Physical Review",
         "극저온에서 쿠퍼쌍이 형성되어 전기 저항이 0이 되고 자기장을 완전히 밀어내는 초전도의 원리를 다룹니다.",
         [
             ("Discovered in 1911 by Dutch physicist Heike Kamerlingh Onnes, superconductivity represents a macroscopic manifestation of quantum mechanics.", "1911년 네덜란드 물리학자 헤이커 카메를링 오네스에 의해 발견된 초전도는 양자역학의 거시적 발현을 나타냅니다.", "Discovered in 1911 by Dutch physicist Heike Kamerlingh Onnes, / superconductivity represents / a macroscopic manifestation / of quantum mechanics."),
             ("When certain metallic elements and alloys are chilled below a critical transition temperature, their electrical resistance vanishes to absolute zero.", "특정 금속 원소와 합금이 임계 전이 온도 아래로 냉각될 때, 그들의 전기 저항은 완전한 0으로 사라집니다.", "When certain metallic elements and alloys are chilled / below a critical transition temperature, / their electrical resistance vanishes / to absolute zero."),
             ("According to Bardeen-Cooper-Schrieffer (BCS) theory, lattice vibrations called phonons bind electrons into coordinated pairs known as Cooper pairs.", "바딘-쿠퍼-슈리퍼(BCS) 이론에 따르면, 포논이라 불리는 격자 진동이 전자를 '쿠퍼쌍'으로 알려진 조율된 쌍으로 결합시킵니다.", "According to Bardeen-Cooper-Schrieffer (BCS) theory, / lattice vibrations called phonons / bind electrons / into coordinated pairs known as Cooper pairs."),
             ("At cryogenic temperatures, these paired electrons condense into a unified macroscopic quantum state that flows through lattices without atomic collisions.", "극저온에서 이 짝지은 전자들은 원자 충돌 없이 격자를 통해 흐르는 통합된 거시적 양자 상태로 응축됩니다.", "At cryogenic temperatures, / these paired electrons condense / into a unified macroscopic quantum state / that flows through lattices / without atomic collisions."),
             ("Simultaneously, superconductors expel all interior magnetic flux lines, a phenomenon discovered by Walther Meissner in 1933.", "동시에 초전도체는 내부의 모든 자기력선을 밖으로 밀어내는데, 이는 1933년 발터 마이스너에 의해 발견된 현상입니다.", "Simultaneously, / superconductors expel all interior magnetic flux lines, / a phenomenon discovered by Walther Meissner in 1933."),
             ("This Meissner effect forces external magnetic fields around the specimen, causing permanent magnetic levitation utilized in MRI and maglev transit.", "이 마이스너 효과는 외부 자기장이 시료 주변으로 우회하도록 강제하여, MRI와 자기부상 교통에 활용되는 영구 자기부상을 유발합니다.", "This Meissner effect forces external magnetic fields around the specimen, / causing permanent magnetic levitation / utilized in MRI and maglev transit.")
         ],
         [("macroscopic", "adj.", "거시적인, 육안으로 보이는", "Superconductivity reveals macroscopic quantum coherence at room scale."), ("vanish", "v.", "사라지다, 소멸하다", "Electrical resistance vanishes completely below critical temperature."), ("lattice", "n.", "결정 격자", "Atoms in a metallic crystal form a periodic spatial lattice."), ("condense", "v.", "응축하다, 압축되다", "Bose-Einstein particles condense into a singular ground state."), ("expel", "v.", "밀어내다, 방출하다", "Superconductors actively expel interior magnetic flux lines.")],
         [("과거분사 수동 분사구문", "Discovered in 1911 by Onnes, superconductivity represents... 발견 과정을 서술하는 분사구문입니다."), ("분사구문 causing", "...forces magnetic fields around the specimen, causing permanent magnetic levitation... 결과를 이끄는 분사구문입니다.")],
         [
             ("What happens to electrical resistance inside a superconductor below its critical temperature?", "임계 온도 이하의 초전도체 내부에서 전기 저항은 어떻게 되나요?", ["It increases to infinite values, causing explosions.", "It drops to absolute zero, allowing lossless current flow.", "It fluctuates randomly with atmospheric wind speeds.", "It transforms into acoustic sound vibrations."], 1, "완전한 0으로 사라져 손실 없는 전류 흐름을 허용한다고 설명했습니다."),
             ("What subatomic mechanism enables frictionless electron flow in BCS theory?", "BCS 이론에서 무마찰 전자 흐름을 가능하게 하는 아원자 메커니즘은 무엇인가요?", ["Electrons binding into Cooper pairs mediated by lattice phonons", "Electrons transforming into heavy lead neutrons", "Protons escaping from the nucleus into atmospheric air", "Electrons being heated by coal furnaces"], 0, "격자 포논에 의해 매개되어 쿠퍼쌍(Cooper pairs)을 형성하는 것이라고 명시했습니다."),
             ("What is the Meissner effect?", "마이스너 효과(Meissner effect)란 무엇인가요?", ["The active expulsion of magnetic flux lines from a superconductor's interior", "The evaporation of liquid helium into solid diamond crystals", "The absorption of visible light causing total darkness", "The nuclear fission of copper wire atoms"], 0, "초전도체 내부에서 모든 자기력선을 밀어내는 현상이라고 밝혔습니다.")
         ]),

        ("b-55", "The Cryptography of the WWII Enigma Machine", "제2차 세계대전 에니그마 암호기와 튜링의 해독", "Historical Cryptography & Computation", "Imperial War Museums",
         "회전 로터와 플러그보드로 1억 5천만 가지 조합을 만들었던 독일 에니그마를 폴란드 수학자와 튜링이 무너뜨린 역사를 다룹니다.",
         [
             ("During the Second World War, the German military encrypted its most sensitive communications using the portable Enigma cipher machine.", "제2차 세계대전 동안 독일군은 휴대용 에니그마 암호기를 사용하여 가장 민감한 통신을 암호화했습니다.", "During the Second World War, / the German military encrypted its most sensitive communications / using the portable Enigma cipher machine."),
             ("Invented by Arthur Scherbius in 1918, the electromechanical apparatus resembled a standard commercial typewriter housed in a wooden case.", "1918년 아서 셰르비우스에 의해 발명된 이 전기기계식 장치는 나무 상자에 담긴 표준 상업용 타자기와 흡사했습니다.", "Invented by Arthur Scherbius in 1918, / the electromechanical apparatus resembled / a standard commercial typewriter / housed in a wooden case."),
             ("Inside, a battery of stepped rotating wheels, an electrical reflector, and a front plugboard scrambled typed letters through complex circuitry.", "내부에서 일련의 단계적 회전 바퀴, 전기 반사체, 전면 플러그보드가 복잡한 전기 회로를 통해 입력된 글자들을 뒤섞었습니다.", "Inside, / a battery of stepped rotating wheels, an electrical reflector, / and a front plugboard / scrambled typed letters through complex circuitry."),
             ("Because each rotor advanced with every keystroke, the polyalphabetic substitution produced over one hundred and fifty trillion possible configurations.", "키를 누를 때마다 각 로터가 전진했기 때문에, 다중 알파벳 치환은 150조 개가 넘는 가능한 구성을 만들어냈습니다.", "Because each rotor advanced with every keystroke, / the polyalphabetic substitution produced / over one hundred and fifty trillion possible configurations."),
             ("However, Polish mathematicians Marian Rejewski and Henryk Zygalski first broke the military cipher using permutation group theory.", "그러나 폴란드 수학자 마리안 레예프스키와 헨리크 지갈스키가 순열 군론을 사용하여 군용 암호를 처음으로 깼습니다.", "However, / Polish mathematicians Marian Rejewski and Henryk Zygalski / first broke the military cipher / using permutation group theory."),
             ("Building on Polish breakthroughs, British mathematician Alan Turing designed automated 'Bombe' decryption machines at Bletchley Park, shortening the war by years.", "폴란드의 돌파구를 토대로 영국 수학자 앨런 튜링은 블레츨리 파크에서 자동화된 '봄브' 해독기를 설계하여 전쟁을 수년 단축시켰습니다.", "Building on Polish breakthroughs, / British mathematician Alan Turing designed automated 'Bombe' decryption machines / at Bletchley Park, / shortening the war by years.")
         ],
         [("apparatus", "n.", "장치, 기구", "The electromechanical apparatus scrambled keyboard electrical signals."), ("rotor", "n.", "로터, 회전자", "Stepped rotors advanced cyclically with each pressed typewriter key."), ("polyalphabetic", "adj.", "다중 알파벳의", "Polyalphabetic ciphers defeat simple single-letter frequency analysis."), ("permutation", "n.", "순열, 치환", "Mathematical permutation matrices modeled the internal wiring of Enigma rotors."), ("decryption", "n.", "복호화, 암호 해독", "Automated decryption machines deciphered thousands of intercept messages daily.")],
         [("분사구문 using", "...encrypted communications using the portable Enigma machine... 수단을 나타내는 능동 분사구문입니다."), ("분사구문 shortening", "...designed automated Bombe machines..., shortening the war by years... 결과를 설명하는 분사구문입니다.")],
         [
             ("Who originally invented the Enigma cipher machine in 1918?", "1918년 에니그마 암호기를 원래 처음 발명한 사람은 누구인가요?", ["Arthur Scherbius", "Alan Turing", "Winston Churchill", "Alexander Graham Bell"], 0, "1918년 아서 셰르비우스(Arthur Scherbius)가 발명했다고 명시했습니다."),
             ("What mathematical breakthrough did Polish cryptanalysts achieve before WWII?", "제2차 대전 이전에 폴란드 암호학자들은 어떤 수학적 돌파구를 달성했나요?", ["They broke the military Enigma cipher using permutation group theory.", "They proved that all German radio broadcasts were fake.", "They created the first digital internet browser.", "They demonstrated that codes cannot be cracked by machines."], 0, "순열 군론을 사용하여 군용 에니그마 암호를 최초로 해독했다고 설명했습니다."),
             ("What automated machine did Alan Turing engineer at Bletchley Park?", "앨런 튜링이 블레츨리 파크에서 설계한 자동화된 암호 해독기는 무엇이었나요?", ["The Bombe decryption machine", "The steam powered locomotive", "The Apollo rocket guidance computer", "The mechanical cotton gin"], 0, "봄브(Bombe) 암호 해독 기계라고 밝혔습니다.")
         ]),

        ("i-56", "Keystone Predators and Trophic Cascades in Yellowstone", "옐로스톤의 핵심 포식자와 영양 연쇄의 생태학", "Ecosystem Ecology & Conservation", "Science",
         "1995년 옐로스톤 국립공원에 늑대가 재도입되자 사슴의 과도 방목이 줄고 강변 숲과 강줄기 지형까지 복원된 기적을 다룹니다.",
         [
             ("When gray wolves were systematically eradicated from Yellowstone National Park in the 1920s, the entire ecosystem unraveled.", "1920년대 회색늑대가 옐로스톤 국립공원에서 조직적으로 박멸되었을 때, 전체 생태계는 무너져 내렸습니다.", "When gray wolves were systematically eradicated / from Yellowstone National Park in the 1920s, / the entire ecosystem unraveled."),
             ("Free from predatory pressure, elk populations exploded, overbrowsing willow, aspen, and cottonwood saplings along fragile riverbanks.", "포식자 압력에서 벗어나자 엘크 사슴 개체수가 폭발적으로 증가하여 연약한 강둑을 따라 버드나무, 사시나무, 포플러 묘목을 과도하게 뜯어먹었습니다.", "Free from predatory pressure, / elk populations exploded, / overbrowsing willow, aspen, and cottonwood saplings / along fragile riverbanks."),
             ("Deprived of woody building materials, native beavers vanished, while bare riverbanks suffered catastrophic soil erosion.", "목재 건축 자재를 빼앗긴 토착 비버들이 자취를 감추었고, 헐벗은 강둑은 파멸적인 토양 침식을 겪었습니다.", "Deprived of woody building materials, / native beavers vanished, / while bare riverbanks suffered / catastrophic soil erosion."),
             ("In 1995, wildlife biologists initiated a historic ecological restoration by reintroducing thirty-one wild Canadian gray wolves.", "1995년 야생동물 생물학자들은 31마리의 야생 캐나다 회색늑대를 재도입함으로써 역사적인 생태 복원을 시작했습니다.", "In 1995, / wildlife biologists initiated a historic ecological restoration / by reintroducing thirty-one wild Canadian gray wolves."),
             ("The wolves instituted an ecology of fear: elk altered behavioral grazing patterns, avoiding vulnerable valleys and gorges.", "늑대들은 공포의 생태학을 확립했습니다. 엘크는 취약한 계곡과 협곡을 피하며 방목 행동 패턴을 바꾸었습니다.", "The wolves instituted an ecology of fear: / elk altered behavioral grazing patterns, / avoiding vulnerable valleys and gorges."),
             ("Streamside forests rapidly regenerated, beavers returned to construct wetlands, and stabilized riverbanks permanently altered the park's physical geography.", "개울가 숲이 빠르게 재생되었고, 비버들이 돌아와 습지를 건설했으며, 안정화된 강둑은 공원의 물리적 지형을 영구적으로 변화시켰습니다.", "Streamside forests rapidly regenerated, / beavers returned to construct wetlands, / and stabilized riverbanks / permanently altered the park's physical geography.")
         ],
         [("eradicate", "v.", "박멸하다, 뿌리 뽑다", "Public health campaigns eradicated smallpox globally."), ("unravel", "v.", "흐트러지다, 와해되다", "The international peace treaty unraveled amid border skirmishes."), ("overbrowse", "v.", "과도하게 뜯어먹다", "Overbrowsing by wild deer prevents forest canopy regeneration."), ("regenerate", "v.", "재생하다, 재건되다", "Burned pine forests regenerate naturally over subsequent decades."), ("keystone", "n.", "핵심, 쐐기돌", "A keystone predator exerts disproportionate control over community balance.")],
         [("분사구문 형용사 수식", "Free from predatory pressure, elk populations exploded... Being이 생략된 분사구문입니다."), ("과거분사 수동 분사구문", "Deprived of woody building materials, native beavers vanished... 자재 박탈을 나타내는 분사구문입니다.")],
         [
             ("What environmental degradation occurred after gray wolves were wiped out in Yellowstone?", "옐로스톤에서 회색늑대가 전멸된 후 어떤 환경 파괴가 일어났나요?", ["Glaciers melted completely within twelve days.", "Elk exploded in population, overbrowsing riverbank trees and driving out beavers.", "Wild desert cactus plants spread across the entire park.", "The Yellowstone supervolcano erupted violently."], 1, "엘크 개체수가 폭발하여 강둑 나무를 초토화시키고 비버가 사라졌다고 설명했습니다."),
             ("How did the reintroduction of wolves in 1995 alter elk behavior?", "1995년 늑대 재도입은 엘크의 행동을 어떻게 바꾸었나요?", ["Elk fled to live in major human cities.", "Elk adopted an 'ecology of fear,' avoiding vulnerable river valleys and allowing trees to regrow.", "Elk learned to hunt wolves using antlers.", "Elk stopped drinking water from rivers entirely."], 1, "'공포의 생태학'으로 취약한 계곡을 피해 숲이 다시 자라게 했다고 밝혔습니다."),
             ("What surprising physical landform change was stabilized by the trophic cascade?", "영양 연쇄에 의해 안정화된 놀라운 물리적 지형 변화는 무엇이었나요?", ["Riverbanks stabilized through regenerated roots, altering river geography.", "The Rocky Mountains flattened into coastal sand plains.", "The sun stayed in the sky for twenty-four hours.", "Active geysers transformed into solid gold fountains."], 0, "재생된 뿌리를 통해 강둑이 안정화되고 강 지형이 바뀌었다고 서술했습니다.")
         ]),

        ("i-57", "The Engineering of Modern High-Bypass Turbofan Jet Engines", "고바이패스 터보팬 제트 엔진의 항공 공학과 열역학", "Aerospace Engineering & Propulsion", "Rolls-Royce Aerospace",
         "연소 가스 추진 대신 거대한 전면 팬으로 차가운 공기를 우회시켜 연료 효율과 저소음을 달성한 고바이패스 기술을 다룹니다.",
         [
             ("Commercial intercontinental aviation is powered almost exclusively by massive high-bypass turbofan jet engines.", "상업용 대륙간 항공은 거의 전적으로 거대한 고바이패스 터보팬 제트 엔진에 의해 추진됩니다.", "Commercial intercontinental aviation is powered / almost exclusively by massive high-bypass turbofan jet engines."),
             ("Early military turbojets forced all ingested air through combustion chambers, consuming massive fuel while generating deafening acoustic noise.", "초기 군용 터보제트는 흡입된 모든 공기를 연소실로 밀어 넣어 막대한 연료를 소비하면서 귀를 찢는 음향 소음을 발생시켰습니다.", "Early military turbojets forced all ingested air / through combustion chambers, / consuming massive fuel / while generating deafening acoustic noise."),
             ("Modern turbofans achieve superior fuel efficiency by splitting incoming airflow around a core combustion gas generator.", "현대 터보팬은 유입되는 기류를 핵심 연소 가스 발생기 주변으로 분할함으로써 우수한 연료 효율을 달성합니다.", "Modern turbofans achieve superior fuel efficiency / by splitting incoming airflow / around a core combustion gas generator."),
             ("A massive front titanium fan directs over eighty percent of total air mass through an outer bypass duct without burning it.", "거대한 전면 티타늄 팬은 전체 공기 질량의 80% 이상을 연소시키지 않고 외부 바이패스 덕트를 통해 통과시킵니다.", "A massive front titanium fan directs / over eighty percent of total air mass / through an outer bypass duct / without burning it."),
             ("This cold bypass air envelopes the hot high-speed core exhaust jet, dampening turbulent acoustic shockwaves.", "이 차가운 우회 공기는 뜨거운 고속 코어 배기 제트를 감싸주어 난류 음향 충격파를 완화합니다.", "This cold bypass air envelopes / the hot high-speed core exhaust jet, / dampening turbulent acoustic shockwaves."),
             ("Single-crystal nickel superalloy turbine blades operating in temperatures exceeding melting points deliver immense thrust with extraordinary reliability.", "녹는점을 넘어서는 온도에서 작동하는 단결정 니켈 초합금 터빈 블레이드는 탁월한 신뢰성으로 막대한 추력을 전달합니다.", "Single-crystal nickel superalloy turbine blades / operating in temperatures exceeding melting points / deliver immense thrust / with extraordinary reliability.")
         ],
         [("combustion", "n.", "연소", "Internal combustion engines burn gasoline fuel to drive pistons."), ("deafening", "adj.", "귀청이 터질 듯한", "The roar of the rocket launch was deafening across the pad."), ("bypass", "n./v.", "우회(하다), 바이패스", "The high bypass duct routes cool air around the central engine core."), ("dampen", "v.", "약화시키다, 완화하다", "Acoustic insulation panels dampen engine roar in the aircraft cabin."), ("superalloy", "n.", "초합금", "Nickel-based superalloys maintain mechanical strength at extreme operating temperatures.")],
         [("전치사 by + -ing", "...achieve superior fuel efficiency by splitting incoming airflow... 수단을 나타내는 구문입니다."), ("분사구문 dampening", "...envelopes the hot exhaust jet, dampening acoustic shockwaves... 결과를 설명하는 분사구문입니다.")],
         [
             ("What architectural feature distinguishes a high-bypass turbofan from early turbojets?", "고바이패스 터보팬을 초기 터보제트와 구별 짓는 구조적 특징은 무엇인가요?", ["Splitting air so over eighty percent bypasses the core combustion chamber unburned", "Using wooden propeller blades carved from pine timber", "Replacing jet kerosene fuel with coal briquettes", "Operating without any rotating compressor components"], 0, "유입 공기의 80% 이상이 연소되지 않고 코어를 우회하도록 분할하는 것이라 설명했습니다."),
             ("How does cold bypass air reduce engine noise?", "차가운 우회 공기는 어떻게 엔진 소음을 줄이나요?", ["By freezing sound waves into solid ice pellets", "By enveloping the hot high-speed exhaust jet, dampening turbulent acoustic shockwaves", "By playing recorded calming music through the engine exhaust", "By reversing the direction of the aircraft flight"], 1, "뜨거운 고속 배기 제트를 감싸 난류 음향 충격파를 완화한다고 밝혔습니다."),
             ("What material enables turbine blades to operate at temperatures hotter than their melting point?", "터빈 블레이드가 녹는점보다 높은 온도에서 작동할 수 있게 해주는 재료는 무엇인가요?", ["Single-crystal nickel superalloys", "Standard window glass", "Hardened rubber polymers", "Compressed paper mache"], 0, "단결정 니켈 초합금(single-crystal nickel superalloys)이라고 명시했습니다.")
         ]),

        ("i-58", "Moral Hazard in Health Insurance Markets", "건강보험 시장의 도덕적 해이와 의료비 통제", "Health Economics & Public Policy", "Journal of Health Economics",
         "보험 가입으로 본인 부담이 줄어들 때 불필요한 의료 소비가 급증하는 도덕적 해이와 자기부담금의 역할을 분석합니다.",
         [
             ("In health economics, moral hazard refers to the tendency of individuals to consume more healthcare simply because they are insured.", "보건경제학에서 도덕적 해이는 개인이 단순히 보험에 가입되어 있다는 이유로 의료 서비스를 더 많이 소비하는 경향을 의미합니다.", "In health economics, / moral hazard refers to the tendency of individuals / to consume more healthcare / simply because they are insured."),
             ("When health insurance policies cover the overwhelming majority of medical costs, patients face a zero or negligible marginal price.", "건강보험 증권이 의료비의 압도적 다수를 보장할 때, 환자들은 0에 가깝거나 무시할 수 있는 한계 가격에 직면합니다.", "When health insurance policies cover the overwhelming majority of medical costs, / patients face a zero / or negligible marginal price."),
             ("Insulated from true economic costs, insured consumers demand low-value diagnostic scans, elective visits, and brand-name drugs.", "진정한 경제적 비용으로부터 차단되어, 보험에 가입된 소비자는 효용 가치가 낮은 진단 검사, 선택적 진료, 고가 브랜드 의약품을 요구합니다.", "Insulated from true economic costs, / insured consumers demand low-value diagnostic scans, / elective visits, and brand-name drugs."),
             ("Physicians may also overprescribe lucrative treatments, knowing patients will not bear the immediate financial burden.", "의사들 역시 환자가 즉각적인 재정적 부담을 지지 않는다는 것을 알고 수익성 높은 치료를 과잉 처방할 수 있습니다.", "Physicians may also overprescribe lucrative treatments, / knowing patients will not bear / the immediate financial burden."),
             ("To counter this distortion, insurers introduce cost-sharing mechanisms—including deductibles, copayments, and coinsurance percentages.", "이러한 왜곡에 대응하기 위해, 보험사들은 자기부담금, 정액 본인부담금, 정률제 비율을 포함한 비용 분담 기제를 도입합니다.", "To counter this distortion, / insurers introduce cost-sharing mechanisms / —including deductibles, copayments, and coinsurance percentages."),
             ("Designing optimal cost-sharing balances essential financial risk protection against the systemic inflation of excessive medical expenditures.", "최적의 비용 분담을 설계하는 것은 필수적인 재정 위험 보호와 과도한 의료비의 구조적 인플레이션 사이의 균형을 맞춥니다.", "Designing optimal cost-sharing balances / essential financial risk protection / against the systemic inflation / of excessive medical expenditures.")
         ],
         [("negligible", "adj.", "무시해도 될 정도의, 하찮은", "The minor clerical error produced a negligible financial discrepancy."), ("insulated", "adj.", "차단된, 격리된", "Diplomats were insulated from political violence inside the embassy."), ("lucrative", "adj.", "수익성이 좋은, 돈벌이가 되는", "The patent granted the university a highly lucrative licensing revenue stream."), ("deductible", "n.", "자기부담금 (보험금 청구 전 가입자가 부담하는 액수)", "High-deductible health plans feature lower monthly premium costs."), ("systemic", "adj.", "전체적인, 구조적인", "Unchecked banking defaults threatened a systemic economic crisis.")],
         [("과거분사 수동 분사구문", "Insulated from true economic costs, consumers demand... 원인을 나타내는 분사구문입니다."), ("to부정사 목적 부사구", "To counter this distortion, insurers introduce... 목적을 나타내는 to부정사입니다.")],
         [
             ("What is the definition of moral hazard in health economics?", "보건경제학에서 도덕적 해이의 정의는 무엇인가요?", ["Individuals consuming excess healthcare because insurance covers their financial costs", "Doctors committing deliberate physical surgery malpractice", "Patients refusing to take prescribed antibiotic medications", "Insurance companies going bankrupt during earthquakes"], 0, "보험이 비용을 보장해주기 때문에 의료를 과잉 소비하는 경향이라고 설명했습니다."),
             ("How do physicians sometimes contribute to moral hazard?", "의사들은 때때로 도덕적 해이에 어떻게 기여하나요?", ["By overprescribing lucrative diagnostic treatments knowing patients face low out-of-pocket costs", "By closing medical clinics permanently on weekends", "By refusing to treat patients who have health insurance", "By paying patients cash bonuses for staying healthy"], 0, "환자가 비용 부담을 지지 않음을 알고 수익성 높은 진단 및 치료를 과잉 처방함으로써 기여한다고 설명했습니다."),
             ("What mechanism do health insurers utilize to mitigate moral hazard?", "건강보험사들은 도덕적 해이를 완화하기 위해 어떤 기제를 활용하나요?", ["Cost-sharing tools such as deductibles, copayments, and coinsurance", "Banning all prescription medications nationwide", "Eliminating all hospitals from urban cities", "Requiring patients to pay exclusively in gold coins"], 0, "자기부담금(deductibles), 정액 본인부담금(copayments) 등 비용 분담 기제라고 명시했습니다.")
         ]),

        ("i-59", "Circadian Rhythms and the Suprachiasmatic Master Clock", "생체 24시간 일주기 리듬과 시교차상핵 마스터 시계", "Chronobiology & Molecular Genetics", "Cell",
         "빛 신호에 반응해 24시간 수면-각성 주기와 호르몬 분비를 총괄하는 뇌 시교차상핵(SCN)의 분자 시계를 설명합니다.",
         [
             ("Virtually all living organisms govern their daily physiological behavior through internal twenty-four-hour circadian biological clocks.", "사실상 모든 살아있는 유기체는 내재된 24시간 일주기 생물학적 시계를 통해 일상의 생리적 행동을 관장합니다.", "Virtually all living organisms govern their daily physiological behavior / through internal twenty-four-hour circadian biological clocks."),
             ("In mammals, master coordination is orchestrated by the suprachiasmatic nucleus (SCN), a cluster of twenty thousand neurons in the hypothalamus.", "포유류에서 마스터 조율은 시상하부의 2만 개 뉴런 군집인 시교차상핵(SCN)에 의해 지휘됩니다.", "In mammals, master coordination is orchestrated / by the suprachiasmatic nucleus (SCN), / a cluster of twenty thousand neurons in the hypothalamus."),
             ("The SCN receives direct photic input from specialized melanopsin-containing retinal ganglion cells that detect environmental sunlight.", "SCN은 환경의 햇빛을 감지하는 특화된 멜라놉신 함유 망막 신경절 세포로부터 직접적인 광학적 입력을 받습니다.", "The SCN receives direct photic input / from specialized melanopsin-containing retinal ganglion cells / that detect environmental sunlight."),
             ("At the cellular core, a self-sustaining transcriptional-translational feedback loop involving CLOCK and BMAL1 genes ticks autonomously.", "세포 수준의 핵심에서 CLOCK과 BMAL1 유전자를 포함하는 자립적인 전사-번역 피드백 루프가 자율적으로 똑딱거립니다.", "At the cellular core, / a self-sustaining transcriptional-translational feedback loop / involving CLOCK and BMAL1 genes / ticks autonomously."),
             ("The SCN synchronizes peripheral clocks in the liver, heart, and adipose tissues, dictating metabolic rhythms and sleep-wake cycles.", "SCN은 간, 심장, 지방 조직의 말초 시계들을 동기화하여 대사 리듬과 수면-각성 주기를 지시합니다.", "The SCN synchronizes peripheral clocks / in the liver, heart, and adipose tissues, / dictating metabolic rhythms / and sleep-wake cycles."),
             ("Artificial nocturnal blue light exposure disrupts this delicate molecular timing, contributing to chronic insomnia and metabolic disorders.", "야간의 인공적인 청색광 노출은 이 섬세한 분자 타이밍을 교란하여 만성 불면증과 대사 장애를 유발합니다.", "Artificial nocturnal blue light exposure / disrupts this delicate molecular timing, / contributing to chronic insomnia / and metabolic disorders.")
         ],
         [("circadian", "adj.", "24시간 일주기의", "Circadian rhythms regulate body temperature across day and night."), ("hypothalamus", "n.", "시상하부", "The hypothalamus controls endocrine hormone release and thirst."), ("ganglion", "n.", "신경절", "Retinal ganglion cells transmit visual impulses to the optic nerve."), ("autonomous", "adj.", "자율적인, 독립적인", "Cardiac pacemaker cells generate autonomous electrical contractions."), ("adipose", "adj.", "지방의, 지방성의", "Adipose tissue functions as an energy storage reservoir.")],
         [("동격 명사구", "...suprachiasmatic nucleus (SCN), a cluster of twenty thousand neurons... SCN을 설명하는 동격입니다."), ("분사구문 dictating", "...synchronizes peripheral clocks..., dictating metabolic rhythms... 결과를 나타내는 분사구문입니다.")],
         [
             ("What anatomical brain region functions as the master circadian pacemaker in mammals?", "포유류에서 마스터 일주기 보행조절기 역할을 하는 해부학적 뇌 부위는 어디인가요?", ["The suprachiasmatic nucleus (SCN) in the hypothalamus", "The auditory cochlea of the outer ear", "The sensory taste buds of the tongue", "The motor tendons of the knee"], 0, "시상하부의 시교차상핵(SCN)이라고 명시했습니다."),
             ("What environmental sensory cue synchronizes the SCN master clock?", "어떤 환경적 감각 단서가 SCN 마스터 시계를 동기화하나요?", ["Direct environmental sunlight detected by retinal ganglion cells", "Acoustic rock music played through headphones", "The scent of freshly ground black pepper", "Tasting sweet sugary desserts"], 0, "망막 신경절 세포가 감지하는 직접적인 햇빛(sunlight)이라고 설명했습니다."),
             ("What negative physiological effect stems from artificial nocturnal blue light exposure?", "야간의 인공 청색광 노출로부터 어떤 부정적인 생리적 영향이 발생하나요?", ["Immediate loss of fingernail growth", "Disruption of circadian molecular timing, contributing to insomnia and metabolic issues", "Instant conversion of brain cells into bone marrow", "Total paralysis of all facial muscles"], 1, "일주기 분자 타이밍을 교란하여 불면증과 대사 장애를 유발한다고 명시했습니다.")
         ]),

        ("i-60", "The Architecture of Search Engine Inverted Indexes", "검색 엔진 역색인(Inverted Index)의 자료구조와 랭킹", "Computer Science & Information Retrieval", "Communications of the ACM",
         "수백억 개 웹페이지에서 밀리초 만에 관련 문서를 찾아내는 역색인 자료구조와 벡터 의미 랭킹의 원리를 다룹니다.",
         [
             ("To return relevant search results across tens of billions of web pages within milliseconds, search engines rely upon an inverted index.", "수백억 개의 웹페이지 전반에서 수 밀리초 만에 관련 검색 결과를 반환하기 위해 검색 엔진은 역색인에 의존합니다.", "To return relevant search results across tens of billions of web pages / within milliseconds, / search engines rely upon / an inverted index."),
             ("A forward index maps each document to the words it contains, requiring an exhaustive, sluggish linear scan to find search queries.", "정방향 색인은 각 문서를 그것이 포함한 단어로 매핑하므로 검색어를 찾으려면 느린 선형 스캔을 철저히 수행해야 합니다.", "A forward index maps each document to the words it contains, / requiring an exhaustive, sluggish linear scan / to find search queries."),
             ("Conversely, an inverted index reverses this relationship by mapping every unique vocabulary token to a postings list of document IDs.", "반대로 역색인은 모든 고유한 어휘 토큰을 문서 ID들의 게시물 목록으로 매핑함으로써 이 관계를 뒤집습니다.", "Conversely, / an inverted index reverses this relationship / by mapping every unique vocabulary token / to a postings list of document IDs."),
             ("When a user inputs multiple search keywords, the search engine computes intersections of corresponding postings lists with lightning efficiency.", "사용자가 여러 검색 키워드를 입력할 때 검색 엔진은 해당 게시물 목록의 교집합을 번개 같은 효율성으로 계산합니다.", "When a user inputs multiple search keywords, / the search engine computes intersections of corresponding postings lists / with lightning efficiency."),
             ("Modern architectures enrich this sparse lexical index with dense semantic vector embeddings generated by neural language transformers.", "현대 아키텍처는 신경망 언어 트랜스포머에 의해 생성된 조밀한 의미 벡터 임베딩으로 이 희소 어휘 색인을 보강합니다.", "Modern architectures enrich this sparse lexical index / with dense semantic vector embeddings / generated by neural language transformers."),
             ("By synthesizing exact token matching with contextual semantic ranking, search engines decipher human intent with extraordinary speed and accuracy.", "정확한 토큰 일치와 문맥적 의미 랭킹을 종합함으로써 검색 엔진은 놀라운 속도와 정확성으로 인간의 의도를 해독합니다.", "By synthesizing exact token matching / with contextual semantic ranking, / search engines decipher human intent / with extraordinary speed and accuracy.")
         ],
         [("sluggish", "adj.", "느린, 부진한", "The economy struggled through a sluggish post-war recovery."), ("postings list", "n.", "포스팅 리스트 (색인어 출현 문서 목록)", "Search algorithms intersect postings lists to retrieve matching web pages."), ("lexical", "adj.", "어휘의, 사전의", "Lexical analysis tokenizes raw source code into semantic identifiers."), ("embedding", "n.", "임베딩 (고차원 벡터 표현)", "Vector embeddings encode contextual nuances of words into numerical spaces."), ("decipher", "v.", "해독하다, 판독하다", "Codebreakers deciphered intercepted diplomatic cables.")],
         [("to부정사 목적 부사구", "To return relevant search results..., search engines rely upon... 목적을 나타내는 to부정사입니다."), ("전치사 By + -ing", "By synthesizing exact matching..., search engines decipher... 수단과 방법을 나타냅니다.")],
         [
             ("How does an inverted index differ structurally from a forward index?", "역색인은 구조적으로 정방향 색인과 어떻게 다른가요?", ["It maps words to the list of documents containing them, rather than documents to words.", "It stores web pages exclusively on magnetic cassette tapes.", "It deletes all search keywords every twenty-four hours.", "It translates all text into binary Morse code."], 0, "문서에서 단어로 가는 것이 아니라 단어에서 그것을 포함하는 문서 목록으로 매핑한다고 설명했습니다."),
             ("How does an inverted index efficiently process multi-keyword search queries?", "역색인은 여러 키워드 검색어를 어떻게 효율적으로 처리하나요?", ["By computing mathematical intersections of the corresponding postings lists", "By sending postal letters to website owners for approval", "By reading every web page from the first word to the last", "By randomly guessing which page might contain the terms"], 0, "해당 포스팅 리스트들의 수학적 교집합(intersections)을 계산함으로써 처리한다고 밝혔습니다."),
             ("What modern AI enhancement enriches lexical inverted indexes today?", "오늘날 어떤 현대적 AI 강화가 어휘 역색인을 보강하나요?", ["Dense semantic vector embeddings generated by neural transformers", "Replacing computers with mechanical abacus counting", "Banning all search queries longer than three letters", "Limiting search results to local neighborhood libraries"], 0, "신경망 트랜스포머에 의해 생성된 조밀한 의미 벡터 임베딩(dense semantic vector embeddings)이라고 명시했습니다.")
         ])
    ]

if __name__ == "__main__":
    print(f"Generated extra intermediate passages for 180 target: {len(get_expansion_180_i())}")
