# -*- coding: utf-8 -*-
"""
generate_expansion_180.py
Produces 30 additional passages (b-51..60, i-51..60, a-51..60)
to elevate the collection to 180 passages (60 Beginner, 60 Intermediate, 60 Advanced).
"""

def get_expansion_180_b():
    return [
        ("b-51", "The Miraculous Flight of Hummingbirds", "벌새의 경이로운 정지 비행과 비행 역학", "Ornithology & Physics", "National Geographic",
         "1초에 80번 날개치며 공중 정지 비행과 후진 비행을 자유자재로 해내는 벌새의 비행 비밀을 알아봅니다.",
         [
             ("Hummingbirds are among the most agile and energetic fliers in the entire animal kingdom.", "벌새는 동물계 전체에서 가장 민첩하고 에너지가 넘치는 비행체 중 하나입니다.", "Hummingbirds are among the most agile / and energetic fliers / in the entire animal kingdom."),
             ("Unlike other avian species that flap wings up and down, hummingbirds rotate their wings in a continuous figure-eight pattern.", "날개를 위아래로 퍼덕이는 다른 조류 종들과 달리, 벌새는 날개를 연속적인 8자 패턴으로 회전시킵니다.", "Unlike other avian species / that flap wings up and down, / hummingbirds rotate their wings / in a continuous figure-eight pattern."),
             ("This unique stroke generates aerodynamic lift on both forward and backward movements, allowing motionless hovering.", "이 독특한 날갯짓은 앞뒤 움직임 모두에서 공기역학적 양력을 발생시켜, 공중 정지 비행을 가능하게 합니다.", "This unique stroke generates aerodynamic lift / on both forward and backward movements, / allowing motionless hovering."),
             ("They can even fly completely backward or upside down to evade predators or reach deep tubular blossoms.", "그들은 포식자를 피하거나 깊은 관 모양의 꽃에 닿기 위해 완전히 뒤로 또는 거꾸로 날 수도 있습니다.", "They can even fly completely backward / or upside down / to evade predators / or reach deep tubular blossoms."),
             ("Their wings beat up to eighty times per second, while their tiny hearts pump over twelve hundred times a minute.", "그들의 날개는 1초에 최대 80번 치며, 작은 심장은 1분에 1,200번 이상 뜁니다.", "Their wings beat up to eighty times per second, / while their tiny hearts pump / over twelve hundred times a minute."),
             ("To fuel this staggering metabolic output, hummingbirds must consume their own body weight in floral nectar every day.", "이 엄청난 대사 출력을 유지하기 위해, 벌새는 매일 꽃꿀로 자신의 체중에 맞먹는 양을 섭취해야 합니다.", "To fuel this staggering metabolic output, / hummingbirds must consume their own body weight / in floral nectar every day.")
         ],
         [("agile", "adj.", "민첩한, 날렵한", "The agile acrobat performed backflips on the narrow beam."), ("hover", "v.", "공중 정지 비행을 하다, 맴돌다", "The rescue helicopter hovered above the stormy sea."), ("tubular", "adj.", "관 모양의, 튜브 형태의", "Hummingbirds drink from bright tubular honeysuckle flowers."), ("metabolic", "adj.", "물질대사의, 대사율의", "Exercise increases your basal metabolic rate."), ("staggering", "adj.", "엄청난, 경이로운", "The charitable organization raised a staggering million dollars.")],
         [("Unlike 전치사구", "Unlike other avian species that flap wings..., hummingbirds rotate... 대조 전치사구입니다."), ("to부정사 목적 부사구", "To fuel this staggering metabolic output, hummingbirds must consume... 목적을 나타내는 to부정사입니다.")],
         [
             ("What unique wing motion enables hummingbirds to hover motionless?", "어떤 독특한 날개 움직임이 벌새의 공중 정지 비행을 가능하게 하나요?", ["Rotating wings in a continuous figure-eight pattern", "Flapping rigid wings strictly once every ten seconds", "Tucking wings tightly against the chest", "Gliding on warm thermal air currents without moving wings"], 0, "연속적인 8자 패턴(figure-eight pattern)으로 날개를 회전시키는 것이라고 명시했습니다."),
             ("How fast can a hummingbird's heart beat during active flight?", "활발한 비행 중 벌새의 심장은 얼마나 빠르게 뛸 수 있나요?", ["Over twelve hundred times per minute", "Ten beats per hour", "Exactly forty beats per day", "Around seventy beats per minute"], 0, "1분에 1,200번 이상(over 1,200 times a minute) 뛴다고 설명했습니다."),
             ("How much floral nectar must a hummingbird consume daily?", "벌새는 매일 얼마만큼의 꽃꿀을 섭취해야 하나요?", ["One tiny droplet per month", "Roughly its own body weight every single day", "A single grain of dry pollen", "One cup of seawater"], 1, "매일 자신의 체중에 맞먹는 양(its own body weight)을 먹어야 한다고 서술했습니다.")
         ]),

        ("b-52", "How Polar Bears Survive Arctic Winters", "북극곰이 극한의 북극 겨울을 견뎌내는 생체 적응", "Arctic Ecology & Zoology", "BBC Earth",
         "영하 40도의 혹한에서 방수 털, 두꺼운 피하지방, 검은 피부로 열을 가두는 북극곰의 단열 구조를 설명합니다.",
         [
             ("Polar bears are apex arctic predators exquisitely engineered to endure subzero temperatures plunging below minus forty degrees.", "북극곰은 영하 40도 아래로 떨어지는 영하의 기온을 견뎌내도록 정교하게 설계된 북극의 최상위 포식자입니다.", "Polar bears are apex arctic predators / exquisitely engineered / to endure subzero temperatures / plunging below minus forty degrees."),
             ("Beneath their visible white appearance, their actual skin is jet black, absorbing radiant heat from scarce polar sunlight.", "눈에 보이는 흰 외관 아래, 그들의 실제 피부는 칠흑같이 검어서 희박한 북극 햇빛으로부터 복사열을 흡수합니다.", "Beneath their visible white appearance, / their actual skin is jet black, / absorbing radiant heat / from scarce polar sunlight."),
             ("Covering this dark skin is a ten-centimeter layer of dense subcutaneous blubber that provides thermal insulation.", "이 검은 피부를 덮고 있는 것은 열 단열을 제공하는 10센티미터 두께의 조밀한 피하지방층입니다.", "Covering this dark skin / is a ten-centimeter layer / of dense subcutaneous blubber / that provides thermal insulation."),
             ("Over the fat layer rests two coats of fur: a soft woolly undercoat and long hollow guard hairs that trap warm air.", "지방층 위에는 두 겹의 털이 덮여 있는데, 부드러운 솜털 같은 속털과 따뜻한 공기를 가두는 길고 속이 빈 보호 털입니다.", "Over the fat layer rests two coats of fur: / a soft woolly undercoat / and long hollow guard hairs / that trap warm air."),
             ("These transparent guard hairs reflect ambient arctic light, providing magnificent camouflage across snow-covered pack ice.", "이 투명한 보호 털은 주변 북극광을 반사하여 눈 덮인 유빙 전반에 걸쳐 웅장한 위장을 제공합니다.", "These transparent guard hairs reflect ambient arctic light, / providing magnificent camouflage / across snow-covered pack ice."),
             ("Equipped with wide non-slip paws, polar bears roam hundreds of kilometers across frozen sea ice hunting ringed seals.", "미끄럼 방지 기능이 있는 넓은 발을 갖추고, 북극곰은 고리무늬물범을 사냥하며 얼어붙은 해빙을 수백 킬로미터씩 누빕니다.", "Equipped with wide non-slip paws, / polar bears roam hundreds of kilometers / across frozen sea ice / hunting ringed seals.")
         ],
         [("apex", "adj./n.", "최상위의; 정점", "Lions and polar bears function as apex predators in their ecosystems."), ("subcutaneous", "adj.", "피하의, 피부 밑의", "Subcutaneous fat shields marine mammals from icy waters."), ("blubber", "n.", "지방층, 고래기름", "Whales rely on thick blubber to maintain core body heat."), ("insulation", "n.", "단열, 절연", "Fiberglass batting provides thermal insulation for attic ceilings."), ("pack ice", "n.", "유빙군 (얼어붙은 바다 얼음 덩어리)", "The icebreaker carved a navigable channel through dense pack ice.")],
         [("도치 구문", "Covering this dark skin is a ten-centimeter layer... 분사구가 문두로 나와 주어와 동사가 도치되었습니다."), ("과거분사 수동 분사구문", "Equipped with wide non-slip paws, polar bears roam... 신체 장비를 나타내는 분사구문입니다.")],
         [
             ("What color is a polar bear's actual skin underneath its fur?", "털 아래에 있는 북극곰의 실제 피부는 무슨 색인가요?", ["Bright pink", "Jet black to absorb solar heat", "Pure snow white", "Neon yellow"], 1, "태양열을 흡수하기 위해 칠흑같이 검은색(jet black)이라고 설명했습니다."),
             ("What dual structure characterizes polar bear fur coats?", "북극곰 털 코트를 특징짓는 두 가지 구조는 무엇인가요?", ["Soft woolly underfur and long hollow guard hairs that trap air", "Feathers on the back and scales on the belly", "A single layer of metal wires", "Dry leaves glued together with sap"], 0, "부드러운 속털과 공기를 가두는 속이 빈 보호 털이라고 명시했습니다."),
             ("What is the primary prey hunted by polar bears across sea ice?", "북극곰이 해빙을 가로지르며 사냥하는 주된 먹이는 무엇인가요?", ["Wild Siberian tigers", "Ringed seals", "Desert scorpions", "Deep sea giant squids"], 1, "고리무늬물범(ringed seals)을 사냥한다고 밝혔습니다.")
         ]),

        ("b-53", "The History and Chemistry of Glassmaking", "유리 제조의 역사와 무기물 화학", "History of Technology & Chemistry", "Corning Museum of Glass",
         "모래의 실리카를 녹여 투명하고 단단한 무정형 고체로 만드는 4,000년 유리 기술의 화학적 원리를 다룹니다.",
         [
             ("Glass is one of the most versatile and ancient synthetic materials ever manufactured by human civilization.", "유리는 인류 문명이 제조한 가장 다재다능하고 유서 깊은 합성 물질 중 하나입니다.", "Glass is one of the most versatile / and ancient synthetic materials / ever manufactured by human civilization."),
             ("First developed in Mesopotamia and Egypt over four thousand years ago, glass began as beads and decorative vessels.", "4,000년 전 메소포타미아와 이집트에서 처음 개발된 유리는 구슬과 장식용 용기로 시작되었습니다.", "First developed in Mesopotamia and Egypt / over four thousand years ago, / glass began / as beads and decorative vessels."),
             ("The fundamental recipe combines silica sand, soda ash, and limestone heated in a roaring furnace to fifteen hundred degrees Celsius.", "기본 조리법은 규사 모래, 탄산나트륨, 석회석을 결합하여 이글거리는 화로 속에서 섭씨 1,500도로 가열하는 것입니다.", "The fundamental recipe combines silica sand, soda ash, and limestone / heated in a roaring furnace / to fifteen hundred degrees Celsius."),
             ("Soda ash reduces the melting point of sand, while limestone stabilizes the liquid so it does not dissolve in water.", "탄산나트륨은 모래의 녹는점을 낮춰주고, 석회석은 액체를 안정화하여 물에 녹지 않도록 해줍니다.", "Soda ash reduces the melting point of sand, / while limestone stabilizes the liquid / so it does not dissolve in water."),
             ("When the molten mixture cools rapidly, molecules freeze into a rigid, non-crystalline structure known as an amorphous solid.", "녹은 혼합물이 빠르게 냉각될 때, 분자들은 무정형 고체로 알려진 단단한 비결정질 구조로 얼어붙습니다.", "When the molten mixture cools rapidly, / molecules freeze into a rigid, non-crystalline structure / known as an amorphous solid."),
             ("This unique atomic disorder allows visible light photons to pass straight through without scattering, giving glass absolute clarity.", "이 독특한 원자적 무질서는 가시광선 광자가 산란되지 않고 곧바로 통과할 수 있게 하여 유리에 완전한 투명성을 부여합니다.", "This unique atomic disorder / allows visible light photons / to pass straight through without scattering, / giving glass absolute clarity.")
         ],
         [("versatile", "adj.", "다재다능한, 다용도의", "Stainless steel is a versatile metal used in kitchens and surgery."), ("silica", "n.", "규사, 이산화규소", "Quartz sand consists primarily of crystalline silica mineral."), ("amorphous", "adj.", "무정형의, 형태가 불분명한", "Unlike crystalline quartz, window glass is an amorphous solid."), ("disorder", "n.", "무질서, 혼란", "Thermodynamics states that entropy measures molecular disorder."), ("clarity", "n.", "명료함, 투명도", "Optical lenses must be polished to extreme optical clarity.")],
         [("접속사 While 대조", "Soda ash reduces melting point, while limestone stabilizes... 물질들의 역할 대조입니다."), ("so that 생략형", "...so it does not dissolve in water... 목적/결과를 나타내는 접속사 so입니다.")],
         [
             ("What three primary ingredients are melted together to manufacture standard glass?", "표준 유리를 제조하기 위해 녹이는 세 가지 핵심 원료는 무엇인가요?", ["Silica sand, soda ash, and limestone", "Clay, petroleum oil, and sea salt", "Powdered sulfur, charcoal, and saltpeter", "Pure iron dust, copper wires, and liquid milk"], 0, "규사 모래(silica sand), 탄산나트륨(soda ash), 석회석(limestone)이라고 명시했습니다."),
             ("Why does glass cool into an 'amorphous solid'?", "유리는 왜 '무정형 고체'로 굳어지나요?", ["Rapid cooling freezes molecules into a non-crystalline atomic arrangement.", "It contains active living bacterial colonies.", "It is mixed with transparent gelatin powders.", "Cold water turns liquid sand into wooden crystals."], 0, "급속한 냉각으로 인해 분자들이 비결정질 원자 배열로 얼어붙기 때문입니다."),
             ("What atomic property allows light to pass directly through glass?", "어떤 원자적 특성이 빛으로 하여금 유리를 곧장 통과하게 하나요?", ["Atomic disorder allows light photons to pass through without scattering.", "Heavy magnetic charges push all photons away.", "The glass is one hundred percent hollow vacuum inside.", "Radioactive atoms absorb all darkness."], 0, "원자적 무질서가 광자의 산란 없이 빛을 통과시키기 때문이라고 설명했습니다.")
         ]),

        ("b-54", "Why Dogs Have an Extraordinary Sense of Smell", "개의 후각이 인간보다 수만 배 뛰어난 생물학적 이유", "Canine Biology & Sensory Science", "American Kennel Club",
         "인간의 50배가 넘는 후각 수용체와 냄새 전용 공기 흐름 통로를 지닌 개의 경이로운 탐지 능력을 다룹니다.",
         [
             ("A dog's perception of the surrounding world is governed predominantly not by vision, but by aromatic scent.", "주변 세상에 대한 개의 인식은 시각이 아니라 주로 향기로운 냄새에 의해 지배됩니다.", "A dog's perception of the surrounding world / is governed predominantly / not by vision, but by aromatic scent."),
             ("While human noses contain approximately six million olfactory receptor cells, a canine snout houses up to three hundred million.", "인간의 코가 약 600만 개의 후각 수용체 세포를 포함하는 반면, 개의 코에는 최대 3억 개가 자리 잡고 있습니다.", "While human noses contain approximately six million olfactory receptor cells, / a canine snout houses / up to three hundred million."),
             ("Furthermore, the part of a dog's brain devoted to analyzing odors is proportionately forty times larger than ours.", "게다가, 냄새를 분석하는 데 할애된 개 뇌의 부위는 비례적으로 인간의 것보다 40배나 더 큽니다.", "Furthermore, the part of a dog's brain / devoted to analyzing odors / is proportionately forty times larger than ours."),
             ("Their nostrils are engineered with a special tissue flap that splits inhaled air into separate breathing and smelling pathways.", "개의 콧구멍은 흡입된 공기를 호흡 통로와 냄새 맡기 전용 통로로 분리하는 특수 조직 판막으로 설계되어 있습니다.", "Their nostrils are engineered with a special tissue flap / that splits inhaled air / into separate breathing and smelling pathways."),
             ("A specialized Jacobson's organ located above the roof of the mouth detects invisible pheromones released by other animals.", "입천장 위에 위치한 특화된 야콥슨 기관은 다른 동물들이 방출하는 눈에 보이지 않는 페로몬을 감지합니다.", "A specialized Jacobson's organ / located above the roof of the mouth / detects invisible pheromones / released by other animals."),
             ("Consequently, trained detection dogs can identify microscopic chemical traces diluted to parts per trillion, aiding search and rescue.", "결과적으로, 훈련된 탐지견은 1조 분의 1로 희석된 미세한 화학 흔적도 식별할 수 있어 수색 및 구조 작업을 돕습니다.", "Consequently, / trained detection dogs can identify / microscopic chemical traces diluted to parts per trillion, / aiding search and rescue.")
         ],
         [("predominantly", "adv.", "주로, 지배적으로", "The diet of pandas consists predominantly of bamboo shoots."), ("olfactory", "adj.", "후각의, 냄새의", "Olfactory nerves carry chemical sensory data directly to the limbic cortex."), ("snout", "n.", "주둥이, 코", "The hunting hound pressed its sensitive snout to the damp forest ground."), ("proportionately", "adv.", "비례하여, 비교적", "An ant can lift proportionately more weight than an adult elephant."), ("dilute", "v.", "희석하다, 묽게 하다", "Chemists diluted the concentrated acid with distilled water.")],
         [("not A but B", "...governed predominantly not by vision, but by aromatic scent... 감각 양식의 대조 구문입니다."), ("접속사 While 대조", "While human noses contain 6 million..., a canine snout houses 300 million... 수치 대조 구문입니다.")],
         [
             ("How many olfactory receptors do dogs possess compared to humans?", "인간과 비교하여 개는 대략 몇 개의 후각 수용체를 가지고 있나요?", ["Dogs have up to three hundred million compared to six million in humans.", "Dogs have zero receptors because they rely on ears.", "Dogs have the exact same number as human toddlers.", "Dogs have fifty thousand receptors."], 0, "인간의 600만 개에 비해 개는 최대 3억 개를 지닌다고 설명했습니다."),
             ("What unique anatomical feature splits air inside a dog's nose?", "개의 코 내부에서 공기를 분리하는 독특한 해부학적 특징은 무엇인가요?", ["A tissue flap that separates breathing and smelling pathways", "A series of copper magnetic wires", "A heating furnace that boils inhaled air", "A glass filter that reflects light photons"], 0, "호흡과 냄새 통로를 분리하는 특수 조직 판막(tissue flap)이라고 명시했습니다."),
             ("What is the function of the canine Jacobson's organ?", "개의 야콥슨 기관(Jacobson's organ)의 기능은 무엇인가요?", ["Detecting invisible chemical pheromones released by other animals", "Digesting bone fragments swallowed during meals", "Pumping blood to the wagging tail", "Vibrating to produce high-frequency barks"], 0, "다른 동물들이 방출하는 페로몬을 감지하는 것이라고 밝혔습니다.")
         ]),

        ("b-55", "The Architecture and Fragility of Coral Reefs", "산호초의 생태 건축과 백화 현상의 위험", "Marine Biology & Conservation", "NOAA",
         "바다 면적의 1% 미만이면서 해양 생물의 25%를 부양하는 산호초의 탄산칼슘 골격과 조류 공생을 다룹니다.",
         [
             ("Often hailed as the bustling rainforests of the sea, coral reefs harbor twenty-five percent of all marine species.", "흔히 바다의 번화한 열대우림으로 불리는 산호초는 모든 해양 생물 종의 25%를 품고 있습니다.", "Often hailed as the bustling rainforests of the sea, / coral reefs harbor / twenty-five percent of all marine species."),
             ("Remarkably, these sprawling marine metropolises cover less than one percent of the entire global ocean floor.", "놀랍게도, 이 광대한 해양 대도시는 전 세계 바다 밑바닥의 1% 미만을 덮고 있을 뿐입니다.", "Remarkably, / these sprawling marine metropolises cover / less than one percent / of the entire global ocean floor."),
             ("Reefs are constructed by tiny, soft-bodied colonial animals called coral polyps that secrete hard calcium carbonate skeletons.", "산호초는 단단한 탄산칼슘 골격을 분비하는 산호 폴립이라 불리는 작은 연체 군체 동물들에 의해 건설됩니다.", "Reefs are constructed / by tiny, soft-bodied colonial animals called coral polyps / that secrete hard calcium carbonate skeletons."),
             ("Living symbiotically inside polyp tissues are microscopic photosynthetic algae known as zooxanthellae.", "폴립 조직 내부에 공생하며 살고 있는 것은 조옥산텔레(zooxanthellae)로 알려진 미세 광합성 조류입니다.", "Living symbiotically inside polyp tissues / are microscopic photosynthetic algae / known as zooxanthellae."),
             ("These internal algae provide vital sugars and nutrients through photosynthesis, giving corals their dazzling kaleidoscopic colors.", "이 내부 조류는 광합성을 통해 필수적인 당분과 영양분을 제공하여, 산호에 눈부신 만화경 같은 색채를 부여합니다.", "These internal algae provide vital sugars and nutrients / through photosynthesis, / giving corals their dazzling kaleidoscopic colors."),
             ("However, warming seawater temperatures expel these symbiotic algae, causing severe coral bleaching and threatening marine collapse.", "그러나 따뜻해지는 바닷물 온도는 이 공생 조류를 방출시켜 심각한 산호 백화 현상을 일으키고 해양 붕괴를 위협합니다.", "However, warming seawater temperatures expel these symbiotic algae, / causing severe coral bleaching / and threatening marine collapse.")
         ],
         [("hail", "v.", "찬양하다, 환호하다", "Critics hailed the debut symphony as an orchestral masterpiece."), ("secrete", "v.", "분비하다", "Glands secrete digestive enzymes into the small intestine."), ("kaleidoscopic", "adj.", "만화경 같은, 변화무쌍한", "The autumn festival displayed kaleidoscopic floral colors."), ("bleaching", "n.", "백화, 탈색", "Ocean heatwaves trigger catastrophic coral bleaching events."), ("collapse", "n./v.", "붕괴(하다)", "Overfishing caused the sudden collapse of cod populations.")],
         [("도치 구문", "Living symbiotically inside polyp tissues are microscopic algae... 분사 보어구 문두 도치입니다."), ("분사구문 causing", "...expel these algae, causing severe coral bleaching... 결과를 이끄는 분사구문입니다.")],
         [
             ("What percentage of marine species depend on coral reefs for survival?", "해양 생물 종의 몇 퍼센트가 생존을 위해 산호초에 의존하나요?", ["Less than one percent", "Twenty-five percent", "Ninety-nine percent", "Exactly ten percent"], 1, "해양 생물의 25%(twenty-five percent)가 서식한다고 명시했습니다."),
             ("What microscopic organism lives symbiotically inside coral polyps?", "산호 폴립 내부에서 공생하며 살아가는 미세 생물은 무엇인가요?", ["Photosynthetic algae called zooxanthellae", "Bioluminescent deep sea anglerfish", "Toxic parasitic jellyfish larvae", "Anaerobic methane gas bacteria"], 0, "조옥산텔레(zooxanthellae)라 불리는 광합성 조류라고 설명했습니다."),
             ("What environmental hazard causes coral bleaching?", "어떤 환경적 위험이 산호 백화 현상을 유발하나요?", ["Warming ocean seawater temperatures expelling symbiotic algae", "Extreme subzero ice freezes in equatorial waters", "Ships dropping anchor chains onto sand beaches", "Excess moonlight shining during winter full moons"], 0, "바닷물 온도 상승으로 공생 조류가 방출되기 때문이라고 서술했습니다.")
         ]),

        ("b-56", "How the Human Heart Pumps Blood", "인간 심장의 4개 방과 혈액 순환의 기적", "Cardiovascular Anatomy", "Mayo Clinic",
         "우심방, 우심실, 좌심방, 좌심실이 협력하여 산소를 공급하고 온몸에 피를 순환시키는 이중 펌프 체계를 설명합니다.",
         [
             ("The human heart is an astonishing muscular pump that beats over one hundred thousand times every single day.", "인간의 심장은 매일 10만 번 이상 뛰는 놀라운 근육 펌프입니다.", "The human heart is an astonishing muscular pump / that beats over one hundred thousand times / every single day."),
             ("Roughly the size of a clenched fist, this tireless organ is divided into four specialized interior chambers.", "주먹을 쥔 크기만 한 이 지칠 줄 모르는 장기는 네 개의 특수화된 내부 방으로 나뉘어 있습니다.", "Roughly the size of a clenched fist, / this tireless organ is divided / into four specialized interior chambers."),
             ("The right side of the heart receives oxygen-depleted blood from exhausted bodily tissues and pumps it toward the lungs.", "심장의 오른쪽은 지친 신체 조직으로부터 산소가 고갈된 혈액을 받아 폐를 향해 뿜어냅니다.", "The right side of the heart / receives oxygen-depleted blood from exhausted bodily tissues / and pumps it toward the lungs."),
             ("Inside pulmonary alveoli, the blood releases waste carbon dioxide and absorbs fresh oxygen from inhaled atmospheric air.", "폐포 내부에서 혈액은 노폐물인 이산화탄소를 배출하고 흡입된 대기 공기로부터 신선한 산소를 흡수합니다.", "Inside pulmonary alveoli, / the blood releases waste carbon dioxide / and absorbs fresh oxygen / from inhaled atmospheric air."),
             ("This revitalized scarlet blood returns to the left atrium, which delivers it down into the powerful left ventricle.", "이 활력을 되찾은 진홍빛 혈액은 좌심방으로 돌아오고, 좌심방은 이를 강력한 좌심실로 내려보냅니다.", "This revitalized scarlet blood returns / to the left atrium, / which delivers it down / into the powerful left ventricle."),
             ("Contraction of the left ventricle surges oxygen-rich blood through the aorta, sustaining trillion living cells across the body.", "좌심실의 수축은 대동맥을 통해 산소가 풍부한 혈액을 뿜어내어 전신의 수조 개 살아있는 세포를 지탱합니다.", "Contraction of the left ventricle / surges oxygen-rich blood through the aorta, / sustaining trillion living cells / across the body.")
         ],
         [("clenched", "adj.", "꽉 쥔, 쥐어진", "He held the golden medal tightly in his clenched fist."), ("pulmonary", "adj.", "폐의", "The pulmonary artery delivers blood directly to lung tissues."), ("alveoli", "n.", "폐포 (허파꽈리)", "Gas exchange occurs across the delicate walls of pulmonary alveoli."), ("revitalize", "v.", "생기를 되찾게 하다", "A cool shower revitalized the marathon runner after the race."), ("aorta", "n.", "대동맥", "The aorta is the largest systemic blood vessel in the mammalian body.")],
         [("분사구문 형용사 수식", "Roughly the size of a clenched fist, this tireless organ is divided... Being이 생략된 형용사구 분사구문입니다."), ("관계대명사 계속적 용법", "...left atrium, which delivers it down... 좌심방의 역할을 설명하는 관계대명사절입니다.")],
         [
             ("How many times does the human heart beat during an ordinary day?", "평범한 하루 동안 인간의 심장은 대략 몇 번이나 뛰나요?", ["Around one thousand times", "Over one hundred thousand times", "Ten times per week", "Exactly fifty beats per hour"], 1, "매일 10만 번 이상(over 100,000 times) 뛴다고 설명했습니다."),
             ("What happens to oxygen-depleted blood inside pulmonary alveoli?", "폐포 내부에서 산소가 고갈된 혈액에는 어떤 일이 일어나나요?", ["It freezes into solid ice crystals.", "It releases carbon dioxide and absorbs fresh oxygen.", "It turns completely clear and loses all red cells.", "It is converted into digestive stomach acids."], 1, "이산화탄소를 배출하고 신선한 산소를 흡수한다고 명시했습니다."),
             ("Which chamber of the heart pumps oxygen-rich blood out through the aorta?", "심장의 어느 방이 대동맥을 통해 산소가 풍부한 혈액을 전신으로 뿜어내나요?", ["The right atrium", "The powerful left ventricle", "The outer skull sinus", "The pulmonary vena cava"], 1, "강력한 좌심실(the powerful left ventricle)이라고 서술했습니다.")
         ]),

        ("b-57", "The Engineering of the Great Wall of China", "만리장성의 축조 공학과 봉화 통신 체계", "History & Civil Engineering", "UNESCO",
         "수천 킬로미터 산악 능선을 따라 흙, 돌, 벽돌로 축조되어 연기와 불로 적의 침입을 알렸던 만리장성을 다룹니다.",
         [
             ("Spanning thousands of kilometers across rugged northern ridges, the Great Wall of China is a masterpiece of antiquity.", "험준한 북부 산등성이를 따라 수천 킬로미터를 뻗어 있는 만리장성은 고대의 걸작입니다.", "Spanning thousands of kilometers / across rugged northern ridges, / the Great Wall of China / is a masterpiece of antiquity."),
             ("Constructed over multiple centuries by successive imperial dynasties, the fortification shielded agrarian heartlands from nomadic raids.", "여러 세기에 걸쳐 연속된 제국 왕조들에 의해 건설된 이 요새는 농경 중심지를 유목민의 습격으로부터 보호했습니다.", "Constructed over multiple centuries / by successive imperial dynasties, / the fortification shielded agrarian heartlands / from nomadic raids."),
             ("While early walls were fashioned from tamped rammed earth, the Ming dynasty reinforced the battlements with fired bricks and stone mortar.", "초기 성벽이 다진 흙으로 만들어진 반면, 명나라는 구운 벽돌과 석회 모르타르로 흉벽을 보강했습니다.", "While early walls were fashioned from tamped rammed earth, / the Ming dynasty reinforced the battlements / with fired bricks and stone mortar."),
             ("Towering watchtowers were strategically positioned within line of sight, housing garrisons and weapons caches.", "우뚝 솟은 망루들은 시야선 내에 전략적으로 배치되어 수비대와 무기 은닉처를 수용했습니다.", "Towering watchtowers were strategically positioned / within line of sight, / housing garrisons and weapons caches."),
             ("To transmit military warnings across mountainous distances, guards ignited smoke signals by day and beacon fires by night.", "산악 거리를 가로질러 군사 경보를 전달하기 위해, 경비병들은 낮에는 연기 신호를, 밤에는 봉화 불을 피웠습니다.", "To transmit military warnings across mountainous distances, / guards ignited smoke signals by day / and beacon fires by night."),
             ("Today, this monumental stone rampart stands as an enduring symbol of Chinese civil engineering perseverance.", "오늘날 이 기념비적인 석조 성벽은 중국 토목 공학의 불굴의 인내를 상징하는 영원한 표상으로 서 있습니다.", "Today, this monumental stone rampart / stands as an enduring symbol / of Chinese civil engineering perseverance.")
         ],
         [("antiquity", "n.", "고대, 아득한 옛날", "Archaeologists uncovered magnificent bronzes from classical antiquity."), ("fortification", "n.", "요새, 방어 설비", "Military engineers strengthened coastal fortifications against naval artillery."), ("battlement", "n.", "성채의 흉벽, 총안", "Archers shot arrows through gaps in the stone battlements."), ("beacon", "n.", "봉화, 신호등", "A lighthouse functions as a guiding beacon for ships in fog."), ("perseverance", "n.", "인내, 끈기", "Success in scientific research demands patience and unwavering perseverance.")],
         [("현재분사 분사구문", "Spanning thousands of kilometers..., the Great Wall is... 능동 분사구문입니다."), ("접속사 While 대조", "While early walls were fashioned from earth, the Ming dynasty reinforced... 건축 재료의 시대적 대조입니다.")],
         [
             ("What was the primary historical purpose of the Great Wall of China?", "만리장성의 주된 역사적 축조 목적은 무엇이었나요?", ["Protecting agricultural heartlands from nomadic military invasions", "Preventing rivers from flooding into the Yellow Sea", "Serving as an elevated railway for steam engines", "Keeping wild panda bears inside mountain forests"], 0, "농경 중심지를 유목민의 침략으로부터 보호하기 위함이라고 설명했습니다."),
             ("How did guards transmit urgent messages between watchtowers?", "경비병들은 망루 사이에 긴급 메시지를 어떻게 전달했나요?", ["Using telephone telegraph copper wires", "By igniting smoke signals by day and beacon fires by night", "By sending trained homing pigeons across desert storms", "Through underwater hydraulic pipe channels"], 1, "낮에는 연기 신호, 밤에는 봉화 불(smoke by day, beacon fires by night)을 피웠다고 명시했습니다."),
             ("What building materials were utilized by the Ming dynasty to reinforce walls?", "명나라는 성벽을 보강하기 위해 어떤 건축 자재를 활용했나요?", ["Fired bricks and stone mortar", "Cardboard and bamboo reeds", "Plastic polymers and melted steel alloys", "Solid ice blocks from frozen winter lakes"], 0, "구운 벽돌과 석회 모르타르(fired bricks and stone mortar)라고 서술했습니다.")
         ]),

        ("b-58", "The Chemistry of Soap and Hand Hygiene", "비누의 양친매성 분자 구조와 바이러스 파괴 화학", "Chemistry & Public Health", "CDC",
         "친수성 머리와 소수성 꼬리를 가진 비누 분자가 바이러스의 지질막을 찢어 물로 씻어내는 위생의 과학을 설명합니다.",
         [
             ("Simple washing with soap and water remains the single most effective public health defense against infectious pathogens.", "비누와 물로 하는 단순한 손 씻기는 감염성 병원체에 맞서는 단 하나의 가장 효과적인 공중보건 방어선으로 남아 있습니다.", "Simple washing with soap and water / remains the single most effective public health defense / against infectious pathogens."),
             ("The secret to soap's cleansing potency lies in its dual-personality molecular architecture.", "비누의 세정력의 비밀은 이중적 성격을 지닌 분자 구조에 있습니다.", "The secret to soap's cleansing potency / lies in its dual-personality molecular architecture."),
             ("Each pin-shaped soap molecule features a water-loving hydrophilic head and an oil-seeking hydrophobic tail.", "각각의 핀 모양 비누 분자는 물을 좋아하는 친수성 머리와 기름을 찾는 소수성 꼬리를 특징으로 합니다.", "Each pin-shaped soap molecule features / a water-loving hydrophilic head / and an oil-seeking hydrophobic tail."),
             ("Many dangerous viruses, including influenza and coronaviruses, are encapsulated within a fragile outer envelope of fatty lipids.", "인플루엔자와 코로나바이러스를 포함한 많은 위험한 바이러스는 지방질 지질로 된 연약한 외부 외피 안에 갇혀 있습니다.", "Many dangerous viruses, / including influenza and coronaviruses, / are encapsulated / within a fragile outer envelope of fatty lipids."),
             ("When soap touches these pathogens, hydrophobic tails pry open the fatty membrane like tiny chemical crowbars.", "비누가 이 병원체에 닿을 때, 소수성 꼬리는 작은 화학 지렛대처럼 지방막을 비집어 엽니다.", "When soap touches these pathogens, / hydrophobic tails pry open the fatty membrane / like tiny chemical crowbars."),
             ("The virus shatters into inactive fragments, which are trapped in spherical bubbles called micelles and washed away harmlessly.", "바이러스는 비활성 파편으로 산산조각이 나고, 이는 미셀이라 불리는 구형 기포에 갇혀 무해하게 씻겨 내려갑니다.", "The virus shatters into inactive fragments, / which are trapped in spherical bubbles called micelles / and washed away harmlessly.")
         ],
         [("potency", "n.", "효력, 효능", "The antibiotic demonstrated remarkable clinical potency against bacteria."), ("hydrophilic", "adj.", "친수성의 (물을 좋아하는)", "Hydrophilic substances dissolve readily in water-based solutions."), ("hydrophobic", "adj.", "소수성의 (물을 싫어하는, 기름과 친한)", "Hydrophobic oil droplets coalesce on top of soup broth."), ("encapsulate", "v.", "캡슐에 넣다, 감싸다", "Gelatin shells encapsulate pharmaceutical powders for swallowing."), ("micelle", "n.", "미셀 (비누 분자가 형성하는 구형 응집체)", "Soap molecules form spherical micelles that trap greasy grime inside.")],
         [("전치사구 문두 삽입", "When soap touches these pathogens, hydrophobic tails pry open... 조건 부사절입니다."), ("관계대명사 계속적 용법", "...inactive fragments, which are trapped in spherical bubbles... 파편의 운명을 설명하는 관계대명사절입니다.")],
         [
             ("What two opposing structural parts comprise a soap molecule?", "비누 분자를 구성하는 두 가지 상반된 구조적 부위는 무엇인가요?", ["A water-loving hydrophilic head and an oil-seeking hydrophobic tail", "A copper battery and a steel spring", "An optical lens and a radio antenna", "A cold ice cube and a boiling steam bubble"], 0, "친수성 머리(hydrophilic head)와 소수성 꼬리(hydrophobic tail)라고 설명했습니다."),
             ("How does soap physically destroy lipid-enveloped viruses?", "비누는 지질 외피를 가진 바이러스를 어떻게 물리적으로 파괴하나요?", ["Hydrophobic tails pry open the virus's fatty membrane like molecular crowbars.", "By freezing the virus with liquid nitrogen droplets", "By shooting radioactive gamma rays from the bubbles", "By painting the virus bright red so it drowns in water"], 0, "소수성 꼬리가 화학 지렛대처럼 바이러스의 지방막을 찢어 열기 때문이라고 밝혔습니다."),
             ("What are the spherical cleansing structures that wash away trapped debris?", "갇힌 노폐물을 씻어내는 구형의 세정 구조체를 무엇이라 부르나요?", ["Micelles", "Platelets", "Polders", "Tannins"], 0, "미셀(micelles)이라 불리는 구형 거품이라고 명시했습니다.")
         ]),

        ("b-59", "How Solar Panels Convert Sunlight into Electricity", "태양광 패널이 빛을 전기로 바꾸는 광전효과", "Renewable Energy & Physics", "US Department of Energy",
         "반도체 실리콘 웨이퍼에 햇빛이 부딪혀 전자가 튀어나와 전류를 형성하는 광전효과의 원리를 설명합니다.",
         [
             ("Solar photovoltaic panels offer an elegant method for generating zero-emission electricity directly from ambient sunlight.", "태양광 패널은 주변 햇빛으로부터 직접 무배출 전기를 생성하는 우아한 방법을 제공합니다.", "Solar photovoltaic panels offer an elegant method / for generating zero-emission electricity / directly from ambient sunlight."),
             ("The basic building block of every panel is a silicon solar cell manufactured from refined beach sand.", "모든 패널의 기본 구성 단위는 정제된 해변 모래로 제조된 실리콘 태양 전지입니다.", "The basic building block of every panel / is a silicon solar cell / manufactured from refined beach sand."),
             ("Silicon is treated with minute chemical additives to create two distinct semiconductor layers: an n-type and a p-type.", "실리콘은 미량의 화학 첨가제로 처리되어 n형과 p형이라는 두 개의 구별되는 반도체 층을 형성합니다.", "Silicon is treated with minute chemical additives / to create two distinct semiconductor layers: / an n-type and a p-type."),
             ("At the junction where these layers meet, an invisible electric field forms, acting as a one-way gate for charges.", "이 층들이 만나는 접합부에서 보이지 않는 전기장이 형성되어 전하를 위한 일방통행 게이트 역할을 합니다.", "At the junction where these layers meet, / an invisible electric field forms, / acting as a one-way gate for charges."),
             ("When solar photons strike the cell, they knock electrons free from silicon atoms, energizing them into motion.", "태양 광자가 전지를 때릴 때, 광자는 실리콘 원자에서 전자를 튕겨내어 그것들을 운동 상태로 활성화합니다.", "When solar photons strike the cell, / they knock electrons free from silicon atoms, / energizing them into motion."),
             ("The built-in electric field channels these free electrons through metal conductive contacts, producing clean direct electric current.", "내장된 전기장은 이 자유 전자들을 금속 전도성 접점을 통해 흐르게 하여 깨끗한 직류 전기를 생산합니다.", "The built-in electric field channels these free electrons / through metal conductive contacts, / producing clean direct electric current.")
         ],
         [("photovoltaic", "adj.", "광전지의, 광기전력의", "Photovoltaic installations generate clean power atop commercial rooftops."), ("refined", "adj.", "정제된, 순화된", "Refined silicon ingots are sliced into wafer-thin circular disks."), ("semiconductor", "n.", "반도체", "Silicon and germanium are classic semiconductor materials."), ("photon", "n.", "광자 (빛의 입자)", "Photons carry discrete packets of electromagnetic energy."), ("conductive", "adj.", "전도성의", "Silver and copper are highly conductive electrical metals.")],
         [("분사구문 acting", "...an electric field forms, acting as a one-way gate... 결과를 설명하는 능동 분사구문입니다."), ("현재분사 분사구문 producing", "...channels free electrons..., producing clean direct current... 결과 분사구문입니다.")],
         [
             ("What raw elemental material forms the foundation of silicon solar cells?", "실리콘 태양 전지의 기초를 이루는 원재료 물질은 무엇인가요?", ["Refined silicon derived from sand", "Raw unrefined petroleum tar", "Compressed paper cardboard", "Solid volcanic lead metal"], 0, "모래에서 유래한 정제된 실리콘(silicon derived from sand)이라고 설명했습니다."),
             ("What happens at the atomic level when solar photons hit a solar cell?", "태양 광자가 태양 전지를 때릴 때 원자 수준에서 어떤 일이 발생하나요?", ["The silicon cell explodes into fire.", "Photons knock electrons free from silicon atoms, setting them in motion.", "The silicon turns into solid liquid water.", "The solar panel shrinks by fifty percent."], 1, "광자가 실리콘 원자에서 전자를 튕겨내어 운동하게 만든다고 설명했습니다."),
             ("What electrical current is directly generated by a solar cell?", "태양 전지에 의해 직접 생성되는 전류의 형태는 무엇인가요?", ["Clean direct current (DC)", "Steam pressure waves", "Explosive gunpowder sparks", "Radioactive alpha rays"], 0, "깨끗한 직류 전기(direct electric current)라고 명시했습니다.")
         ]),

        ("b-60", "The Lifecycle of a Star: From Nebula to Supernova", "별의 일생: 성운에서 초신성 폭발까지", "Astrophysics & Stellar Evolution", "NASA Space Place",
         "성간 가스구름이 중력으로 뭉쳐 별로 탄생하고 핵융합을 거쳐 초신성으로 생을 마감하는 우주적 여정을 다룹니다.",
         [
             ("Stars are born within colossal interstellar clouds of gas and cosmic dust known as stellar nebulae.", "별은 성간 성운으로 알려진 거대한 가스와 우주 먼지의 성간 구름 속에서 태어납니다.", "Stars are born / within colossal interstellar clouds of gas and cosmic dust / known as stellar nebulae."),
             ("As gravity pulls hydrogen atoms closer over millions of years, the core temperature reaches ten million degrees.", "중력이 수백만 년에 걸쳐 수소 원자들을 더 가까이 끌어당김에 따라, 중심부 온도는 섭씨 1,000만 도에 도달합니다.", "As gravity pulls hydrogen atoms closer over millions of years, / the core temperature reaches / ten million degrees."),
             ("At this threshold, nuclear fusion ignites: hydrogen nuclei fuse into helium, releasing ferocious radiant heat and light.", "이 임계점에서 핵융합이 점화됩니다. 수소 핵이 융합하여 헬륨이 되며 맹렬한 복사열과 빛을 방출합니다.", "At this threshold, nuclear fusion ignites: / hydrogen nuclei fuse into helium, / releasing ferocious radiant heat and light."),
             ("For billions of years, a star maintains equilibrium, balancing outward thermal expansion pressure against inward gravitational collapse.", "수십억 년 동안 별은 내부로 향하는 중력 붕괴에 맞서 외부로 향하는 열팽창 압력의 균형을 맞추며 평형을 유지합니다.", "For billions of years, a star maintains equilibrium, / balancing outward thermal expansion pressure / against inward gravitational collapse."),
             ("When hydrogen fuel exhausts, massive stars swell into red supergiants before violently detonating as dazzling supernovas.", "수소 연료가 소진되면, 거대한 별들은 적색 초거성으로 부풀어 오른 뒤 눈부신 초신성으로 격렬하게 폭발합니다.", "When hydrogen fuel exhausts, / massive stars swell into red supergiants / before violently detonating as dazzling supernovas."),
             ("The scattered star-stuff disperses across space, seeding future planets with heavy carbon, oxygen, and iron.", "흩뿌려진 별의 잔해는 우주 전역으로 퍼져나가 무거운 탄소, 산소, 철을 지닌 미래의 행성들을 잉태시킵니다.", "The scattered star-stuff disperses across space, / seeding future planets / with heavy carbon, oxygen, and iron.")
         ],
         [("nebula", "n.", "성운 (가스와 먼지로 이루어진 거대 구름)", "The Orion Nebula is a vibrant nursery for newborn stars."), ("threshold", "n.", "문턱, 임계점", "At threshold temperature, nuclear ignition commences."), ("equilibrium", "n.", "평형 상태", "Planetary atmospheres maintain delicate thermodynamic equilibrium."), ("detonate", "v.", "폭발하다, 터지다", "Massive dying stars detonate into blinding cosmic supernovas."), ("disperse", "v.", "흩어지다, 퍼뜨리다", "Wind dispersed seed pods across the open prairie.")],
         [("분사구문 balancing", "...maintains equilibrium, balancing outward pressure against inward collapse... 상태를 설명하는 분사구문입니다."), ("현재분사 분사구문 seeding", "...disperses across space, seeding future planets with... 결과를 설명하는 분사구문입니다.")],
         [
             ("Where do stars initially form according to astrophysics?", "천체물리학에 따르면 별은 처음에 어디에서 형성되나요?", ["Inside colossal interstellar clouds of gas called nebulae", "On the surface of cold rocky moons", "Inside the cores of dormant volcanoes", "From artificial space stations orbiting Earth"], 0, "성운(nebulae)이라 불리는 거대한 성간 가스구름 속에서 태어난다고 설명했습니다."),
             ("What nuclear reaction powers a star throughout its main lifetime?", "별의 주요 생애 동안 에너지를 공급하는 핵반응은 무엇인가요?", ["Hydrogen nuclei fusing into helium, releasing thermal energy", "Splitting uranium atoms in chain reactions", "Burning kerosene oil inside metallic engines", "Freezing liquid nitrogen into dry ice blocks"], 0, "수소 핵이 융합하여 헬륨이 되며 에너지를 방출하는 핵융합이라고 명시했습니다."),
             ("What catastrophic event concludes the life of a massive dying star?", "수명이 다한 거대한 별의 생애를 마감하는 격변적 사건은 무엇인가요?", ["A violent explosive detonation known as a supernova", "Shrinking silently into a drop of liquid water", "Turning into a solid diamond moon", "Dissolving into atmospheric oxygen inside clouds"], 0, "초신성(supernova)이라 불리는 격렬한 폭발이라고 서술했습니다.")
         ])
    ]

if __name__ == "__main__":
    print(f"Generated extra beginner passages for 180 target: {len(get_expansion_180_b())}")
