# -*- coding: utf-8 -*-
"""
generate_expansion_180_adv.py
Advanced passages a-51 to a-60
Sources: Nature, Reviews of Modern Physics, American Economic Review, Philosophy of Science, Annual Review of Neuroscience
"""

def get_expansion_180_a():
    return [
        ("a-51", "Karl Popper and the Criterion of Falsifiability", "칼 포퍼의 반증주의와 과학적 구획 기준", "Philosophy of Science & Epistemology", "The British Journal for the Philosophy of Science",
         "귀납적 검증의 한계를 지적하고 반증 가능성을 진정한 과학과 사이비 과학을 가르는 기준으로 제시한 포퍼의 철학을 다룹니다.",
         [
             ("In his seminal 1934 masterpiece 'The Logic of Scientific Discovery,' Karl Popper revolutionized the philosophy of science.", "1934년 그의 영향력 있는 명저 '과학적 발견의 논리'에서 칼 포퍼는 과학철학에 혁명을 일으켰습니다.", "In his seminal 1934 masterpiece 'The Logic of Scientific Discovery,' / Karl Popper revolutionized / the philosophy of science."),
             ("Popper directly attacked the logical positivist orthodoxy that scientific theories are verified through cumulative inductive observation.", "포퍼는 과학 이론이 누적적인 귀납적 관찰을 통해 검증된다는 논리실증주의적 통념을 정면으로 공격했습니다.", "Popper directly attacked the logical positivist orthodoxy / that scientific theories are verified / through cumulative inductive observation."),
             ("He demonstrated a fundamental logical asymmetry: no finite number of white swan observations can logically prove the proposition that all swans are white.", "그는 근본적인 논리적 비대칭성을 증명했습니다. 즉, 아무리 유한한 수의 흰 백조를 관찰하더라도 모든 백조가 희다는 명제를 논리적으로 증명할 수는 없습니다.", "He demonstrated a fundamental logical asymmetry: / no finite number of white swan observations / can logically prove the proposition / that all swans are white."),
             ("Conversely, observing a single black swan conclusively and permanently falsifies the universal hypothesis.", "반대로, 단 한 마리의 검은 백조를 관찰하는 것은 그 보편적 가설을 확정적이고 영구적으로 반증합니다.", "Conversely, / observing a single black swan / conclusively and permanently falsifies / the universal hypothesis."),
             ("Popper therefore proposed falsifiability as the supreme demarcation criterion separating genuine empirical science from unfalsifiable pseudoscience.", "따라서 포퍼는 반증 가능성을 진정한 실증 과학과 반증 불가능한 사이비 과학을 구별하는 최고의 구획 기준으로 제안했습니다.", "Popper therefore proposed falsifiability / as the supreme demarcation criterion / separating genuine empirical science / from unfalsifiable pseudoscience."),
             ("A scientific theory can never be coronated as absolute truth, but rather survives as an enduring conjecture that withstands rigorous falsification testing.", "과학 이론은 결코 절대적 진리로 대관될 수 없으며, 오히려 엄격한 반증 시험을 견뎌내는 끈질긴 추측으로서 존속합니다.", "A scientific theory can never be coronated as absolute truth, / but rather survives as an enduring conjecture / that withstands rigorous falsification testing.")
         ],
         [("seminal", "adj.", "중대한, 영향력이 큰", "Einstein published four seminal papers in the miracle year of 1905."), ("positivist", "adj.", "실증주의의", "Logical positivist philosophers equated meaning with empirical verifiability."), ("asymmetry", "n.", "비대칭성", "The asymmetry between verification and falsification is a core philosophical tenet."), ("demarcation", "n.", "구획, 구분", "The demarcation problem asks how to distinguish real science from astrology."), ("conjecture", "n.", "추측, 억측", "Scientific hypotheses begin as bold speculative conjectures.")],
         [("동격 명사절 that", "...the logical positivist orthodoxy that scientific theories are verified... orthodoxy와 동격인 명사절입니다."), ("not A but rather B", "...can never be coronated as absolute truth, but rather survives as... 과학 이론의 성격을 설명하는 대조 구문입니다.")],
         [
             ("What logical asymmetry did Karl Popper articulate regarding induction?", "칼 포퍼는 귀납에 관해 어떤 논리적 비대칭성을 명시했나요?", ["Millions of confirming observations cannot prove a universal rule, but a single counterexample conclusively disproves it.", "Mathematics can never calculate prime numbers.", "All historical facts are purely subjective opinions.", "Deduction is identical to guessing random numbers."], 0, "수백만 번의 확인 관찰도 보편 규칙을 증명할 수는 없지만, 단 하나의 반례가 그것을 반증한다는 비대칭성입니다."),
             ("What was Popper's demarcation criterion for distinguishing science from pseudoscience?", "과학과 사이비 과학을 구별하기 위한 포퍼의 구획 기준은 무엇이었나요?", ["Falsifiability: whether a theory makes testable predictions that can potentially be disproven", "Whether a theory is endorsed by political leaders", "The number of pages contained in a published manuscript", "How emotionally comforting a belief system feels to believers"], 0, "반증 가능성(falsifiability), 즉 반증될 수 있는 검증 가능한 예측을 내놓는가 여부라고 명시했습니다."),
             ("How did Popper view the status of surviving scientific theories?", "포퍼는 살아남은 과학 이론의 상태를 어떻게 보았나요?", ["As eternal, unchallengeable dogmatic truths", "As enduring conjectures that have provisionally withstood rigorous refutation", "As temporary legal decrees enforced by police", "As ancient myths completely disconnected from reality"], 1, "엄격한 반증 시험을 잠정적으로 견뎌낸 끈질긴 추측(enduring conjectures)으로 보았습니다.")
         ]),

        ("a-52", "Quantum Tunneling and Alpha Radioactive Decay", "양자 터널링과 알파 방사성 붕괴의 물리학", "Nuclear & Quantum Physics", "Reviews of Modern Physics",
         "고전 물리학으로는 탈출할 수 없는 핵력 전위 장벽을 파동함수가 뚫고 나가는 양자 터널링과 조지 가모프의 알파 붕괴 이론을 다룹니다.",
         [
             ("In classical Newtonian mechanics, a subatomic particle lacking sufficient kinetic energy can never overcome a potential energy barrier.", "고전 뉴턴 역학에서 충분한 운동 에너지가 결여된 아원자 입자는 위치 에너지 장벽을 결코 극복할 수 없습니다.", "In classical Newtonian mechanics, / a subatomic particle lacking sufficient kinetic energy / can never overcome a potential energy barrier."),
             ("However, quantum mechanics dictates that matter exhibits wave-particle duality described by Erwin Schrödinger's probabilistic wave equation.", "그러나 양자역학은 물질이 에르빈 슈뢰딩거의 확률론적 파동 방정식으로 묘사되는 파동-입자 이중성을 나타낸다고 규정합니다.", "However, quantum mechanics dictates / that matter exhibits wave-particle duality / described by Erwin Schrödinger's probabilistic wave equation."),
             ("When a matter wave encounters a finite potential barrier, its amplitude decays exponentially through the barrier rather than terminating abruptly.", "물질파가 유한한 전위 장벽을 만날 때, 그 진폭은 갑자기 끊어지는 대신 장벽을 통과하며 지수함수적으로 감쇠합니다.", "When a matter wave encounters a finite potential barrier, / its amplitude decays exponentially through the barrier / rather than terminating abruptly."),
             ("If the barrier is sufficiently thin, a finite non-zero probability amplitude emerges on the far side, an effect known as quantum tunneling.", "만약 장벽이 충분히 얇다면 반대편에서 0이 아닌 유한한 확률 진폭이 나타나는데, 이는 양자 터널링으로 알려진 효과입니다.", "If the barrier is sufficiently thin, / a finite non-zero probability amplitude emerges on the far side, / an effect known as quantum tunneling."),
             ("In 1928, physicist George Gamow applied tunneling to resolve the mystery of alpha radioactivity in heavy nuclei like uranium.", "1928년 물리학자 조지 가모프는 우라늄과 같은 무거운 원자핵에서 알파 방사능의 수수께끼를 해결하기 위해 터널링을 적용했습니다.", "In 1928, / physicist George Gamow applied tunneling / to resolve the mystery of alpha radioactivity / in heavy nuclei like uranium."),
             ("Alpha particles trapped behind formidable nuclear Coulomb barriers tunnel through with minuscule probabilities, explaining radioactive half-lives spanning billions of years.", "강력한 핵 쿨롱 장벽 뒤에 갇힌 알파 입자들은 극미한 확률로 터널을 뚫고 나오며, 이는 수십억 년에 걸친 방사성 반감기를 설명해 줍니다.", "Alpha particles trapped behind formidable nuclear Coulomb barriers / tunnel through with minuscule probabilities, / explaining radioactive half-lives / spanning billions of years.")
         ],
         [("barrier", "n.", "장벽, 장애물", "A massive concrete barrier shielded the coastal town from tidal storm surges."), ("duality", "n.", "이중성", "Wave-particle duality lies at the philosophical core of quantum physics."), ("amplitude", "n.", "진폭", "The amplitude of the sound wave determines its audible acoustic volume."), ("exponentially", "adv.", "지수함수적으로", "Bacterial colonies grow exponentially when provided abundant nutrients."), ("minuscule", "adj.", "극미한, 아주 작은", "Detectors registered a minuscule fluctuation in background cosmic temperature.")],
         [("명사절 목적어 that", "...dictates that matter exhibits wave-particle duality... 동사 dictates의 목적어절입니다."), ("과거분사 수동 분사구문", "Alpha particles trapped behind formidable barriers tunnel through... 입자의 상태를 수식하는 분사구입니다.")],
         [
             ("Why is a particle able to cross a potential barrier under quantum mechanics?", "양자역학에서 입자가 위치 에너지 장벽을 건널 수 있는 이유는 무엇인가요?", ["Because matter waves decay exponentially through barriers, leaving a non-zero probability on the other side", "Because subatomic particles physically melt into hot liquid oil", "Because nuclear forces pull the particle with mechanical chains", "Because the barrier evaporates whenever particles touch it"], 0, "물질파가 장벽을 통과하며 지수 감쇠하여 반대편에 0이 아닌 확률을 남기기 때문입니다."),
             ("Who successfully applied quantum tunneling to explain alpha radioactive decay in 1928?", "1928년 알파 방사성 붕괴를 설명하기 위해 양자 터널링을 성공적으로 적용한 물리학자는 누구인가요?", ["George Gamow", "Isaac Newton", "Albert Einstein", "Michael Faraday"], 0, "조지 가모프(George Gamow)라고 명시했습니다."),
             ("What macroscopic phenomenon does Gamow's tunneling theory explain in heavy elements?", "가모프의 터널링 이론은 무거운 원소에서 어떤 거시적 현상을 설명하나요?", ["The existence of radioactive half-lives spanning up to billions of years", "Why gold is heavier than aluminum metal", "The boiling point of liquid hydrogen", "The magnetic polarity of iron ore needles"], 0, "수십억 년에 달하는 방사성 반감기의 존재를 설명한다고 밝혔습니다.")
         ]),

        ("a-53", "The Microeconomics of Two-Sided Platform Markets", "양면 플랫폼 시장의 미시경제학과 교차 네트워크 외부성", "Platform Industrial Organization", "American Economic Review",
         "우버, 에어비앤비 등 한쪽 사용자 그룹의 규모가 반대편 가치를 증대시키는 양면 시장의 비대칭 가격 책정과 교차 보조금을 분석합니다.",
         [
             ("Pioneered by Nobel laureate Jean Tirole and Jean-Charles Rochet, two-sided market theory revolutionized industrial organization economics.", "노벨상 수상자 장 티롤과 장샤를 로셰에 의해 개척된 양면 시장 이론은 산업조직 경제학에 혁명을 일으켰습니다.", "Pioneered by Nobel laureate Jean Tirole and Jean-Charles Rochet, / two-sided market theory / revolutionized industrial organization economics."),
             ("Unlike traditional one-sided pipeline firms that purchase supplier inputs to sell downstream products, platform businesses act as multi-sided matchmakers.", "공급자 투입물을 구매하여 다운스트림 제품을 판매하는 전통적인 단면 파이프라인 기업과 달리, 플랫폼 비즈니스는 다면 중개자 역할을 합니다.", "Unlike traditional one-sided pipeline firms / that purchase supplier inputs to sell downstream products, / platform businesses act / as multi-sided matchmakers."),
             ("A platform—such as a ride-hailing application, payment card network, or mobile operating system—mediates interactions between distinct consumer groups.", "차량 호출 앱, 결제 카드 네트워크, 모바일 운영체제와 같은 플랫폼은 서로 다른 소비자 그룹 간의 상호작용을 중개합니다.", "A platform / —such as a ride-hailing application, payment card network, or mobile operating system— / mediates interactions / between distinct consumer groups."),
             ("The central economic dynamic is the cross-side network externality: the utility derived by agents on one side increases with participant volume on the opposing side.", "핵심적인 경제 역학은 교차 네트워크 외부성입니다. 즉, 한쪽 참여자가 얻는 효용은 반대편 참여자의 규모에 따라 증가합니다.", "The central economic dynamic is the cross-side network externality: / the utility derived by agents on one side / increases with participant volume / on the opposing side."),
             ("Consequently, optimal platform pricing frequently defies classical cost-plus models, adopting asymmetric cross-subsidization structures.", "결과적으로 최적의 플랫폼 가격 책정은 고전적인 원가 가산 모델을 자주 거부하며 비대칭적 교차 보조금 구조를 채택합니다.", "Consequently, / optimal platform pricing frequently defies classical cost-plus models, / adopting asymmetric cross-subsidization structures."),
             ("Platforms often subsidize the price-sensitive 'subsidy side'—even offering services free or at a loss—to monetize the lucrative 'money side.'", "플랫폼은 수익성이 높은 '수익 창출 측'을 현금화하기 위해 가격에 민감한 '보조금 측'에 서비스를 무료나 손실을 보며 제공하기도 합니다.", "Platforms often subsidize the price-sensitive 'subsidy side' / —even offering services free or at a loss— / to monetize the lucrative 'money side.'")
         ],
         [("pipeline", "adj./n.", "파이프라인의 (선형 가치 사슬)", "Traditional pipeline manufacturing models are being displaced by digital platform ecosystems."), ("matchmaker", "n.", "중개인, 매칭 플랫폼", "Digital platforms act as algorithmic matchmakers linking buyers with distributed sellers."), ("externality", "n.", "외부효과", "Positive cross-side network externalities create self-reinforcing winner-take-all markets."), ("subsidize", "v.", "보조금을 지급하다", "Governments subsidize electric vehicle purchases to reduce carbon emissions."), ("monetize", "v.", "수익화하다", "Search engines monetize free user queries through targeted sponsored advertising.")],
         [("과거분사 수동 분사구문", "Pioneered by Jean Tirole and Rochet, two-sided market theory revolutionized... 이론의 기원을 설명하는 분사구문입니다."), ("분사구문 adopting", "...defies classical cost-plus models, adopting asymmetric cross-subsidization... 결과를 나타내는 분사구문입니다.")],
         [
             ("What is a defining characteristic of a two-sided platform market?", "양면 플랫폼 시장의 결정적인 특징은 무엇인가요?", ["The business manufactures all physical goods inside one single state-owned factory.", "It mediates transactions between two distinct user groups linked by cross-side network effects.", "It is legally barred from using computer software or digital credit cards.", "It sells products exclusively to government military agencies."], 1, "교차 네트워크 효과로 연결된 서로 다른 두 사용자 그룹 간의 거래를 중개하는 것이라고 설명했습니다."),
             ("What is a cross-side network externality?", "교차 네트워크 외부성(cross-side network externality)이란 무엇인가요?", ["Value for users on one side grows as the number of participants on the opposing side expands.", "A tax imposed when crossing international maritime borders.", "Radio static interfering with mobile telephone conversations.", "A decrease in corporate profits caused by factory wage increases."], 0, "반대편 참여자의 수가 늘어날수록 한쪽 사용자가 얻는 가치가 커지는 현상입니다."),
             ("Why do platforms often offer services free or at a loss to one side of the market?", "플랫폼은 왜 종종 시장의 한쪽 면에 서비스를 무료나 손해를 보며 제공하나요?", ["To attract a critical mass of users on the subsidy side, enabling monetization of the lucrative money side", "Because the platform owners have taken an oath of permanent poverty", "To comply with international treaties banning corporate profits", "Because computer data costs zero dollars to transmit"], 0, "보조금 측에 대규모 사용자를 유치해야 반대편 수익 측에서 성공적으로 수익화할 수 있기 때문이라고 밝혔습니다.")
         ]),

        ("a-54", "Mirror Neurons and the Embodied Simulation of Action", "거울 뉴런과 행동 이해의 체화된 시뮬레이션", "Cognitive Neuroscience & Empathy", "Annual Review of Neuroscience",
         "자신이 행동할 때와 타인의 행동을 관찰할 때 똑같이 반응하여 공감과 모방 학습의 기반을 제공하는 거울 뉴런을 다룹니다.",
         [
             ("Discovered serendipitously in the early 1990s by Giacomo Rizzolatti at the University of Parma, mirror neurons fundamentally reshaped social neuroscience.", "1990년대 초 파르마 대학의 자코모 리촐라티에 의해 우연히 발견된 거울 뉴런은 사회 신경과학을 근본적으로 재편했습니다.", "Discovered serendipitously in the early 1990s / by Giacomo Rizzolatti at the University of Parma, / mirror neurons fundamentally reshaped / social neuroscience."),
             ("Recording single-unit extracellular potentials in macaque premotor area F5, researchers observed neurons discharging during specific goal-directed hand grasp actions.", "붉은털원숭이 전운동 영역 F5에서 단일 세포 세포외 전위를 기록하던 연구자들은 특정 목표 지향적 손 쥐기 행동 중에 뉴런이 방전되는 것을 관찰했습니다.", "Recording single-unit extracellular potentials in macaque premotor area F5, / researchers observed neurons discharging / during specific goal-directed hand grasp actions."),
             ("Astoundingly, identical neurons fired with equivalent intensity when the monkey merely observed a human experimenter perform that same grasping motion.", "놀랍게도, 원숭이가 인간 실험자가 바로 그 동일한 쥐기 동작을 수행하는 것을 단지 관찰하기만 할 때도 동일한 뉴런이 대등한 강도로 발화했습니다.", "Astoundingly, / identical neurons fired with equivalent intensity / when the monkey merely observed a human experimenter / perform that same grasping motion."),
             ("This mirror mechanism couples visual perception directly with internal motor representations, allowing observers to comprehend actions from within.", "이 거울 메커니즘은 시각적 인식을 내적 운동 표상과 직접 결합하여, 관찰자가 행동을 내부로부터 이해할 수 있게 해줍니다.", "This mirror mechanism couples visual perception directly / with internal motor representations, / allowing observers / to comprehend actions from within."),
             ("Vittorio Gallese formulated the theory of embodied simulation, positing that mirror circuits generate prereflective empathy by mirroring emotional facial expressions.", "비토리오 갈레세는 거울 회로가 감정적 표정을 모방함으로써 전반사적 공감을 생성한다고 상정하며 체화된 시뮬레이션 이론을 정립했습니다.", "Vittorio Gallese formulated the theory of embodied simulation, / positing that mirror circuits generate prereflective empathy / by mirroring emotional facial expressions."),
             ("By translating observed kinematics into somatic resonance, mirror systems provide the evolutionary neural architecture for imitation, culture, and human empathy.", "관찰된 운동학적 움직임을 신체적 공명으로 번역함으로써, 거울 시스템은 모방, 문화, 인간 공감을 위한 진화적 신경 구조를 제공합니다.", "By translating observed kinematics into somatic resonance, / mirror systems provide / the evolutionary neural architecture / for imitation, culture, and human empathy.")
         ],
         [("serendipitously", "adv.", "우연히, 뜻밖에", "Penicillin was discovered serendipitously when mold contaminated a petri dish."), ("discharge", "v.", "방전하다, 발화하다", "Motor neurons discharge electrical action potentials to contract skeletal fibers."), ("coupling", "n.", "결합, 연결", "Tight coupling between sensory inputs and motor outputs coordinates fast reflexes."), ("embodied", "adj.", "체화된, 구체화된", "Embodied cognition argues that thinking is deeply grounded in bodily physical states."), ("kinematics", "n.", "운동학 (물체의 운동 궤적과 속도 연구)", "Motion capture cameras recorded the precise kinematics of the athlete's jump.")],
         [("과거분사 수동 분사구문", "Discovered serendipitously in the 1990s, mirror neurons reshaped... 발견 배경을 설명하는 분사구문입니다."), ("지각동사 목적격 보어", "...observed a human experimenter perform that same motion... observe + 목적어 + 동사원형 구조입니다.")],
         [
             ("What unique firing pattern characterizes mirror neurons in premotor area F5?", "전운동 영역 F5에서 거울 뉴런을 특징짓는 독특한 발화 패턴은 무엇인가요?", ["They fire both when an individual executes an action and when observing another perform it.", "They fire exclusively when subjects are blindfolded in silent rooms.", "They fire only during deep dreamless sleep.", "They fire whenever an individual eats citrus fruit."], 0, "개인이 행동을 실행할 때와 다른 사람이 그 행동을 하는 것을 관찰할 때 모두 발화한다고 설명했습니다."),
             ("Who led the research team that originally discovered mirror neurons in macaques?", "붉은털원숭이에서 거울 뉴런을 원래 처음 발견한 연구팀을 이끈 학자는 누구인가요?", ["Giacomo Rizzolatti", "Sigmund Freud", "Ivan Pavlov", "B.F. Skinner"], 0, "자코모 리촐라티(Giacomo Rizzolatti)라고 명시했습니다."),
             ("What broader cognitive capacity is grounded in the mirror neuron system according to Gallese?", "갈레세에 따르면 거울 뉴런 시스템에 기초하고 있는 더 넓은 인지 능력은 무엇인가요?", ["Embodied simulation enabling prereflective empathy and action understanding", "Calculating advanced differential calculus problems", "Remembering telephone numbers for sixty years", "Controlling blood glucose levels via pancreatic hormones"], 0, "전반사적 공감과 행동 이해를 가능하게 하는 체화된 시뮬레이션(embodied simulation)이라고 밝혔습니다.")
         ]),

        ("a-55", "The Relativistic Thermodynamics of Hawking Radiation", "호킹 복사의 상대론적 열역학: 블랙홀 증발과 정보 역설", "Theoretical Gravitational Physics", "Nature",
         "양자 요동과 일반 상대성 이론의 경계에서 입자-반입자 쌍생성이 만들어내는 블랙홀의 열적 증발과 정보 보존 난제를 다룹니다.",
         [
             ("In classical general relativity, black holes are celestial trapdoors from which nothing—not even electromagnetic photons—can ever escape.", "고전 일반 상대성 이론에서 블랙홀은 그 어떤 것, 심지어 전자기적 광자조차 결코 탈출할 수 없는 천체적 함정 문입니다.", "In classical general relativity, / black holes are celestial trapdoors / from which nothing / —not even electromagnetic photons— / can ever escape."),
             ("However, in 1974, British theoretical physicist Stephen Hawking demonstrated that incorporating quantum field theory into curved spacetime overturns this permanence.", "그러나 1974년 영국의 이론물리학자 스티븐 호킹은 휘어진 시공간에 양자장론을 통합함으로써 이러한 영원성을 뒤집는다는 것을 입증했습니다.", "However, in 1974, / British theoretical physicist Stephen Hawking demonstrated / that incorporating quantum field theory into curved spacetime / overturns this permanence."),
             ("According to quantum mechanics, the vacuum is not void, but seethes with transient virtual particle-antiparticle pairs fluctuating continuously.", "양자역학에 따르면 진공은 텅 빈 공간이 아니라, 지속적으로 요동치는 일시적인 가상 입자-반입자 쌍으로 들끓고 있습니다.", "According to quantum mechanics, / the vacuum is not void, / but seethes with transient virtual particle-antiparticle pairs / fluctuating continuously."),
             ("Near the event horizon, tidal gravitational gradients can rip these pairs apart before they can annihilate back into the vacuum.", "사건의 지평선 근처에서 조석 중력 기울기는 이 쌍들이 다시 진공 속으로 소멸하기 전에 그것들을 찢어 분리할 수 있습니다.", "Near the event horizon, / tidal gravitational gradients can rip these pairs apart / before they can annihilate / back into the vacuum."),
             ("If the negative-energy virtual partner falls inward while the positive-energy particle escapes outward, the black hole steadily loses mass.", "만약 음의 에너지를 지닌 가상 입자가 안쪽으로 떨어지고 양의 에너지를 지닌 입자가 바깥으로 탈출한다면, 블랙홀은 꾸준히 질량을 잃게 됩니다.", "If the negative-energy virtual partner falls inward / while the positive-energy particle escapes outward, / the black hole steadily loses mass."),
             ("Emitting this thermal Hawking radiation, the black hole inexorably evaporates, igniting the fierce Black Hole Information Paradox.", "이 열적 호킹 복사를 방출하면서 블랙홀은 가차 없이 증발하며, 이는 격렬한 블랙홀 정보 역설을 촉발합니다.", "Emitting this thermal Hawking radiation, / the black hole inexorably evaporates, / igniting the fierce Black Hole Information Paradox.")
         ],
         [("permanence", "n.", "영구성, 영속성", "Stone monuments were erected to achieve architectural permanence."), ("seethe", "v.", "들끓다, 소용돌이치다", "The molten lava lake seethed inside the volcanic caldera."), ("annihilate", "v.", "소멸하다, 전멸시키다", "Matter and antimatter annihilate upon contact, releasing pure energy."), ("inexorably", "adv.", "가차 없이, 거침없이", "Geological time marches inexorably forward across millions of millennia."), ("paradox", "n.", "역설, 모순", "The information paradox challenges whether quantum mechanics preserves unitarity.")],
         [("not A but B", "...vacuum is not void, but seethes with transient pairs... 진공의 본질에 대한 대조적 설명입니다."), ("분사구문 igniting", "...inexorably evaporates, igniting the fierce Black Hole Information Paradox... 결과를 나타내는 분사구문입니다.")],
         [
             ("What revolutionary theoretical insight was proven by Stephen Hawking in 1974?", "1974년 스티븐 호킹에 의해 입증된 혁명적인 이론적 통찰은 무엇이었나요?", ["Black holes are not completely black, but emit thermal radiation and slowly evaporate.", "Black holes do not exert any gravitational attraction on surrounding planets.", "Black holes are made of frozen compressed liquid water.", "Light travels infinitely fast inside black hole singularities."], 0, "블랙홀이 완전히 검지 않고 열 복사를 방출하며 서서히 증발한다는 점입니다."),
             ("How does Hawking radiation originate at the quantum level near the event horizon?", "사건의 지평선 근처에서 호킹 복사는 양자 수준에서 어떻게 발생하나요?", ["Virtual particle-antiparticle pairs are separated, with negative energy falling in and positive energy escaping.", "Black holes burn combustible wood timber stored in their cores.", "Reflecting light from nearby orbiting stars like giant mirrors.", "Alien space satellites beaming laser light outward."], 0, "가상 입자-반입자 쌍이 조석력으로 분리되어 음의 에너지는 빨려 들어가고 양의 에너지는 탈출하기 때문입니다."),
             ("What profound theoretical conundrum was triggered by black hole evaporation?", "블랙홀 증발에 의해 어떤 심오한 이론적 난제가 촉발되었나요?", ["The Black Hole Information Paradox", "The discovery of flat earth geometry", "The cancellation of all laws of thermodynamics", "The immediate disappearance of quantum spin"], 0, "블랙홀 정보 역설(Black Hole Information Paradox)이라고 명시했습니다.")
         ]),

        ("a-56", "Louis Althusser and Ideological State Apparatuses", "루이 알튀세르와 이데올로기적 국가 기구의 구조주의적 마르크스주의", "Structuralist Political Philosophy", "New Left Review",
         "물리적 강제력(경찰, 군대)과 제도적 이데올로기(학교, 미디어, 종교)를 통해 지배 계급의 생산 관계가 재생산되는 메커니즘을 분석합니다.",
         [
             ("In his influential 1970 essay, French Marxist philosopher Louis Althusser redefined how modern sovereign power perpetuates itself.", "1970년 그의 영향력 있는 에세이에서 프랑스 마르크스주의 철학자 루이 알튀세르는 현대의 주권 권력이 스스로를 어떻게 영속화하는지를 재정의했습니다.", "In his influential 1970 essay, / French Marxist philosopher Louis Althusser redefined / how modern sovereign power / perpetuates itself."),
             ("Althusser argued that capitalist social formations cannot endure solely through the Repressive State Apparatus (RSA)—the military, police, and penal courts.", "알튀세르는 자본주의 사회 구성체가 군대, 경찰, 형벌 법원과 같은 억압적 국가 기구(RSA)에만 의존해서는 결코 존속할 수 없다고 주장했습니다.", "Althusser argued / that capitalist social formations cannot endure solely / through the Repressive State Apparatus (RSA) / —the military, police, and penal courts."),
             ("Because explicit physical violence provokes resistance, hegemony relies predominantly upon Ideological State Apparatuses (ISAs) to secure consent.", "노골적인 물리적 폭력은 저항을 유발하기 때문에, 헤게모니는 동의를 확보하기 위해 주로 이데올로기적 국가 기구(ISAs)에 의존합니다.", "Because explicit physical violence provokes resistance, / hegemony relies predominantly / upon Ideological State Apparatuses (ISAs) / to secure consent."),
             ("ISAs encompass pluralistic civilian institutions including schools, religious churches, legal systems, commercial media, and family units.", "이데올로기적 국가 기구는 학교, 종교 교회, 사법 체계, 상업 미디어, 가족 단위를 포함한 다원적인 민간 제도를 아우릅니다.", "ISAs encompass pluralistic civilian institutions / including schools, religious churches, / legal systems, commercial media, / and family units."),
             ("Central to Althusser's critique is interpellation: ideology 'hails' concrete individuals, transforming them into obedient, self-policing subjects.", "알튀세르 비판의 중심에는 호명(interpellation)이 있습니다. 즉, 이데올로기는 구체적인 개인을 '호명'하여 순종적이고 스스로를 검열하는 주체로 변형시킵니다.", "Central to Althusser's critique is interpellation: / ideology 'hails' concrete individuals, / transforming them / into obedient, self-policing subjects."),
             ("By instilling the ruling class's values as natural common sense, ISAs reproduce capitalist relations of production across generations.", "지배 계급의 가치관을 자연스러운 상식으로 주입함으로써, 이데올로기적 국가 기구는 자본주의적 생산 관계를 세대에 걸쳐 재생산합니다.", "By instilling the ruling class's values as natural common sense, / ISAs reproduce capitalist relations of production / across generations.")
         ],
         [("perpetuate", "v.", "영속화하다, 계속되게 하다", "Discriminatory laws perpetuate economic inequality across communities."), ("repressive", "adj.", "억압적인", "The military dictatorship imposed repressive censorship on journalism."), ("pluralistic", "adj.", "다원적인, 복합적인", "Democratic governance thrives within a pluralistic civil society."), ("interpellation", "n.", "호명 (이데올로기가 개인을 주체로 부르는 과정)", "Althusser defined interpellation as the ideological hailing of the subject."), ("instill", "v.", "주입하다, 스며들게 하다", "Parents strive to instill moral empathy and civic integrity in children.")],
         [("도치 구문", "Central to Althusser's critique is interpellation... 형용사 보어구 문두 도치입니다."), ("전치사 By + -ing", "By instilling ruling class values..., ISAs reproduce... 수단과 방법을 나타냅니다.")],
         [
             ("What distinction did Louis Althusser draw between RSAs and ISAs?", "루이 알튀세르는 억압적 국가 기구(RSA)와 이데올로기적 국가 기구(ISA) 사이에 어떤 구분을 두었나요?", ["RSAs function through direct physical force while ISAs function primarily through ideological indoctrination.", "RSAs are owned by foreign nations while ISAs are owned by local villages.", "RSAs operate only on weekends while ISAs operate during holidays.", "RSAs produce paper money while ISAs mint gold coins."], 0, "RSA는 직접적인 물리적 강제력으로 기능하는 반면, ISA는 주로 이데올로기적 주입을 통해 기능한다고 설명했습니다."),
             ("Which social institutions are classified as Ideological State Apparatuses (ISAs)?", "어떤 사회 제도들이 이데올로기적 국가 기구(ISA)로 분류되나요?", ["Schools, churches, commercial media, and family units", "Military fighter jet squadrons and submarine fleets", "Armed federal police squads and maximum-security prisons", "Nuclear weapons research testing laboratories"], 0, "학교, 교회, 상업 미디어, 가족 단위 등 민간 제도라고 명시했습니다."),
             ("What is the ideological process of 'interpellation' in Althusserian theory?", "알튀세르 이론에서 '호명(interpellation)'이라는 이데올로기적 과정은 무엇인가요?", ["The process by which ideology 'hails' individuals, transforming them into compliant subjects", "A method for auditing corporate tax returns with computers", "The mathematical calculation of factory assembly line speed", "The diplomatic negotiation of international trade treaties"], 0, "이데올로기가 개인을 불러 세워(호명하여) 순종적인 주체로 탈바꿈시키는 과정이라고 밝혔습니다.")
         ]),

        ("a-57", "Transposable Genetic Elements and Genomic Evolution", "전이 인자(트랜스포존)와 유전체 아키텍처의 진화", "Molecular Genetics & Evolutionary Genomics", "Nature Reviews Genetics",
         "바버라 매클린톡이 옥수수에서 발견한 '점핑 유전자'가 단순한 정크 DNA가 아니라 유전체 혁신을 이끄는 동력임을 규명합니다.",
         [
             ("When Barbara McClintock first proposed in the 1940s that genetic segments could physically move within chromosomes, skepticism was vehement.", "1940년대 바버라 매클린톡이 유전 구획들이 염색체 내에서 물리적으로 이동할 수 있다고 처음 제안했을 때 학계의 회의론은 맹렬했습니다.", "When Barbara McClintock first proposed in the 1940s / that genetic segments could physically move within chromosomes, / skepticism was vehement."),
             ("Established twentieth-century genetic orthodoxy viewed the genome as a static, unalterable linear blueprint.", "확립된 20세기 유전학적 통념은 게놈을 정적이고 변경 불가능한 선형 청사진으로 간주했습니다.", "Established twentieth-century genetic orthodoxy / viewed the genome / as a static, unalterable linear blueprint."),
             ("Observing mosaic pigmentation patterns in maize kernels, McClintock demonstrated mobile elements she termed 'transposons.'", "옥수수 알갱이의 모자이크 색소 침착 패턴을 관찰하면서, 매클린톡은 자신이 '트랜스포존'이라 명명한 이동성 인자들을 증명했습니다.", "Observing mosaic pigmentation patterns in maize kernels, / McClintock demonstrated mobile elements / she termed 'transposons.'"),
             ("Today, whole-genome sequencing reveals that transposable elements (TEs) constitute nearly half of the entire human genomic sequence.", "오늘날 전장 게놈 시퀀싱은 전이 인자(TE)가 인간 전체 유전체 서열의 거의 절반을 구성하고 있음을 밝혀냈습니다.", "Today, whole-genome sequencing reveals / that transposable elements (TEs) constitute / nearly half of the entire human genomic sequence."),
             ("Retrotransposons copy and paste through RNA intermediates, driving genomic expansion, exon shuffling, and novel regulatory rewiring.", "레트로트랜스포존은 RNA 중간체를 통해 복사하여 붙여넣기를 수행하며 게놈 확장, 엑손 셔플링, 새로운 조절 재배선을 주도합니다.", "Retrotransposons copy and paste through RNA intermediates, / driving genomic expansion, / exon shuffling, / and novel regulatory rewiring."),
             ("Far from being mere parasitic 'junk DNA,' transposable elements represent potent evolutionary catalysts fueling macroevolutionary innovation across taxa.", "단순한 기생적인 '쓰레기 DNA'이기는커녕, 전이 인자는 분류군 전반에 걸쳐 대진화적 혁신을 촉진하는 강력한 진화적 촉매를 나타냅니다.", "Far from being mere parasitic 'junk DNA,' / transposable elements represent potent evolutionary catalysts / fueling macroevolutionary innovation across taxa.")
         ],
         [("vehement", "adj.", "맹렬한, 격렬한", "Critics voiced vehement opposition to the proposed constitutional amendment."), ("transposon", "n.", "트랜스포존 (전이성 유전 인자, 점핑 유전자)", "Transposons insert into new chromosomal loci through transposase enzymes."), ("intermediate", "n./adj.", "중간체; 중간의", "Biochemical pathways synthesize short-lived reactive molecular intermediates."), ("catalyst", "n.", "촉매, 기폭제", "Economic deregulation acted as a catalyst for entrepreneurial growth."), ("taxa", "n.", "분류군 (taxon의 복수형)", "Comparative genomics examines conserved gene families across divergent biological taxa.")],
         [("분사구문 observing", "Observing mosaic pigmentation patterns..., McClintock demonstrated... 관찰 과정을 서술하는 분사구문입니다."), ("Far from being -ing", "Far from being mere parasitic 'junk DNA,' transposable elements represent... '~이기는커녕 오히려'라는 역접 강조 구문입니다.")],
         [
             ("Who discovered mobile genetic elements by studying pigmentation in maize kernels?", "옥수수 알갱이의 색소 침착을 연구하여 이동성 유전 인자를 발견한 학자는 누구인가요?", ["Barbara McClintock", "Gregor Mendel", "Rosalind Franklin", "Thomas Hunt Morgan"], 0, "바버라 매클린톡(Barbara McClintock)이라고 명시했습니다."),
             ("What proportion of the human genome is composed of transposable elements?", "인간 유전체의 대략 어느 정도 비율이 전이 인자로 구성되어 있나요?", ["Nearly half of the entire human genomic sequence", "Less than zero point zero one percent", "Exactly one hundred percent", "Ten individual nucleotide bases"], 0, "인간 게놈 서열의 거의 절반(nearly half)을 구성한다고 설명했습니다."),
             ("What evolutionary role do transposable elements play in modern genomics?", "현대 유전체학에서 전이 인자는 어떤 진화적 역할을 수행하나요?", ["Acting as evolutionary catalysts driving regulatory innovation and gene shuffling", "Freezing all evolution so species never change", "Preventing all cellular division in embryos", "Turning animal flesh into wooden cellulose"], 0, "유전자 조절 혁신과 엑손 셔플링을 추동하는 강력한 진화적 촉매 역할을 한다고 명시했습니다.")
         ]),

        ("a-58", "Mathematical Smoothness and the Navier-Stokes Millennium Problem", "나비에-스토크스 방정식의 매끄러움과 밀레니엄 난제", "Fluid Dynamics & Applied Mathematics", "Clay Mathematics Institute",
         "난류와 유체 흐름을 기술하는 비선형 편미분 방정식이 모든 시간에서 매끄러운 해를 항상 갖는지 묻는 100만 달러 난제를 다룹니다.",
         [
             ("Formulated in the nineteenth century by Claude-Louis Navier and George Gabriel Stokes, the Navier-Stokes equations govern fluid motion.", "19세기 클로드 루이 나비에와 조지 가브리엘 스토크스에 의해 정식화된 나비에-스토크스 방정식은 유체의 운동을 지배합니다.", "Formulated in the nineteenth century by Claude-Louis Navier and George Gabriel Stokes, / the Navier-Stokes equations govern / fluid motion."),
             ("These non-linear partial differential equations apply Newton's second law of motion to continuous viscous liquids and atmospheric gases.", "이 비선형 편미분 방정식은 뉴턴의 운동 제2법칙을 연속적인 점성 액체와 대기 기체에 적용합니다.", "These non-linear partial differential equations apply / Newton's second law of motion / to continuous viscous liquids / and atmospheric gases."),
             ("They model everything from ocean currents and hurricane aerodynamics to blood circulation through mammalian cardiovascular networks.", "그것들은 해류와 허리케인 공기역학에서부터 포유류 심혈관망을 통한 혈액 순환에 이르기까지 모든 것을 모델링합니다.", "They model everything / from ocean currents and hurricane aerodynamics / to blood circulation / through mammalian cardiovascular networks."),
             ("Yet, despite centuries of engineering utility, mathematicians cannot prove whether smooth, physically reasonable solutions mathematically exist for all time.", "그러나 수세기에 걸친 공학적 유용성에도 불구하고, 수학자들은 매끄럽고 물리적으로 합리적인 해가 모든 시간에 대해 수학적으로 존재하는지 여부를 증명할 수 없습니다.", "Yet, despite centuries of engineering utility, / mathematicians cannot prove / whether smooth, physically reasonable solutions / mathematically exist for all time."),
             ("The central dilemma asks whether finite kinetic energy can concentrate into infinitesimal vortex singularities, causing mathematical velocity gradients to blow up infinitely.", "핵심 딜레마는 유한한 운동 에너지가 극미한 소용돌이 특이점으로 집중되어 수학적 속도 기울기가 무한대로 폭주할 수 있는지 여부를 묻는 것입니다.", "The central dilemma asks / whether finite kinetic energy can concentrate / into infinitesimal vortex singularities, / causing mathematical velocity gradients / to blow up infinitely."),
             ("Designated one of the seven Millennium Prize Problems by the Clay Mathematics Institute, resolving this riddle commands a million-dollar bounty.", "클레이 수학 연구소에 의해 7대 밀레니엄 난제 중 하나로 지정된 이 수수께끼를 해결하는 것에는 100만 달러의 현상금이 걸려 있습니다.", "Designated one of the seven Millennium Prize Problems / by the Clay Mathematics Institute, / resolving this riddle / commands a million-dollar bounty.")
         ],
         [("viscous", "adj.", "점성의, 끈적끈적한", "Viscous fluids resist shear flow through internal molecular friction."), ("aerodynamics", "n.", "공기역학", "Aeronautical engineers optimize the aerodynamics of supersonic fuselages."), ("infinitesimal", "adj.", "극미한, 무한소의", "Calculus evaluates limits as step sizes approach infinitesimal values."), ("singularity", "n.", "특이점", "A mathematical singularity occurs where values diverge toward infinity."), ("bounty", "n.", "현상금, 보상금", "The foundation established a million-dollar bounty for solving the mathematical conjecture.")],
         [("과거분사 수동 분사구문", "Formulated in the nineteenth century..., the equations govern... 수식 분사구문입니다."), ("명사절 유도 whether", "...mathematicians cannot prove whether smooth solutions exist... prove의 목적어절입니다.")],
         [
             ("What physical phenomena are modeled by the Navier-Stokes equations?", "나비에-스토크스 방정식에 의해 모델링되는 물리적 현상은 무엇인가요?", ["Fluid motion of liquids and gases, including ocean currents and aerodynamics", "The decay of radioactive uranium nuclei inside reactors", "The financial volatility of digital cryptocurrencies", "The growth of fungal mycelia inside tree bark"], 0, "해류, 공기역학, 혈액 순환 등 액체와 기체의 유체 운동이라고 설명했습니다."),
             ("What is the core mathematical question posed by the Navier-Stokes Millennium Problem?", "나비에-스토크스 밀레니엄 난제가 묻는 핵심적인 수학적 질문은 무엇인가요?", ["Whether smooth, physically reasonable solutions always exist without velocity gradients blowing up", "Whether the number zero is an even or odd integer", "How to calculate the circumference of an equilateral triangle", "Whether computers can run without silicon microchips"], 0, "속도 기울기가 무한대로 폭주하지 않고 매끄러운 해가 항상 존재하는지 여부라고 밝혔습니다."),
             ("What bounty was established by the Clay Mathematics Institute for resolving this problem?", "이 문제를 해결하기 위해 클레이 수학 연구소가 책정한 현상금은 얼마인가요?", ["One million dollars", "Ten thousand silver coins", "One ounce of gold dust", "A lifetime supply of gasoline"], 0, "100만 달러(a million-dollar bounty)라고 명시했습니다.")
         ]),

        ("a-59", "Public Choice Theory and the Logic of Rent-Seeking", "공공선택론과 지대추구의 정치경제학", "Political Economy & Constitutional Economics", "Public Choice",
         "제임스 뷰캐넌이 정립한 정치인과 관료들의 사익 추구 행동 분석과 집중된 이익과 분산된 비용의 입법 왜곡을 다룹니다.",
         [
             ("Classical democratic theory traditionally romanticized elected politicians and state bureaucrats as benevolent custodians dedicated solely to the public welfare.", "고전 민주주의 이론은 전통적으로 선출된 정치인과 국가 관료들을 오로지 공공 복리에만 헌신하는 자애로운 수호자로 낭만화했습니다.", "Classical democratic theory traditionally romanticized / elected politicians and state bureaucrats / as benevolent custodians / dedicated solely to the public welfare."),
             ("In the 1960s, American political economist James Buchanan shattered this romanticism by formulating public choice theory.", "1960년대 미국 정치경제학자 제임스 뷰캐넌은 공공선택론을 정립함으로써 이러한 낭만주의를 산산조각 냈습니다.", "In the 1960s, / American political economist James Buchanan shattered this romanticism / by formulating public choice theory."),
             ("Buchanan applied microeconomic behavioral assumptions to the political sphere, positing that political actors remain self-interested utility maximizers.", "뷰캐넌은 미시경제학적 행동 가정을 정치 영역에 적용하여, 정치 행위자들도 여전히 사익을 추구하는 효용 극대화자라고 상정했습니다.", "Buchanan applied microeconomic behavioral assumptions / to the political sphere, / positing that political actors remain / self-interested utility maximizers."),
             ("A cornerstone concept is rent-seeking: corporations expend massive resources lobbying for government subsidies, tariffs, and regulatory monopolies.", "초석이 되는 개념은 지대추구(rent-seeking)입니다. 즉, 기업들이 정부 보조금, 관세, 규제적 독점을 로비하기 위해 막대한 자원을 지출합니다.", "A cornerstone concept is rent-seeking: / corporations expend massive resources / lobbying for government subsidies, / tariffs, and regulatory monopolies."),
             ("Because the benefits of targeted protectionist legislation are concentrated among organized interest groups while the costs are dispersed thinly across taxpayers, politicians readily acquiesce.", "표적화된 보호무역 입법의 혜택은 조직화된 이익 집단에 집중되는 반면 그 비용은 납세자들에게 얇게 분산되기 때문에 정치인들은 기꺼이 묵인합니다.", "Because the benefits of targeted protectionist legislation / are concentrated among organized interest groups / while the costs are dispersed thinly across taxpayers, / politicians readily acquiesce."),
             ("Awarded the Nobel Memorial Prize in 1986, Buchanan demonstrated that political failures frequently eclipse the very market failures government interventions purport to correct.", "1986년 노벨상을 수상한 뷰캐넌은 정부 개입이 시정하겠다고 공언하는 바로 그 시장 실패보다 정치적 실패가 더 심각한 경우가 빈번함을 입증했습니다.", "Awarded the Nobel Memorial Prize in 1986, / Buchanan demonstrated / that political failures frequently eclipse / the very market failures government interventions purport to correct.")
         ],
         [("benevolent", "adj.", "자애로운, 친절한", "The monarch cultivated a reputation as a benevolent paternal ruler."), ("custodian", "n.", "관리인, 수호자", "National park rangers act as custodians of pristine wilderness."), ("rent-seeking", "n.", "지대추구 (새로운 부 창출 없이 기존 부의 이전을 노리는 로비 행위)", "Rent-seeking squanders productive capital on political favoritism."), ("acquiesce", "v.", "묵인하다, 마지못해 따르다", "The beleaguered council acquiesced to the protesters' demands."), ("purport", "v.", "주장하다, ~체하다", "The fraudulent document purported to be a royal land grant.")],
         [("접속사 Because 인과", "Because benefits are concentrated while costs are dispersed, politicians acquiesce... 정치적 왜곡의 인과관계 분석입니다."), ("과거분사 수동 분사구문", "Awarded the Nobel Memorial Prize in 1986, Buchanan demonstrated... 수상을 나타내는 분사구문입니다.")],
         [
             ("What fundamental assumption about politicians does public choice theory make?", "공공선택론은 정치인에 대해 어떤 근본적인 가정을 내리나요?", ["They operate as self-interested utility maximizers rather than purely altruistic servants.", "They possess telepathic mind-reading powers.", "They refuse to accept any monetary salaries from government treasuries.", "They are controlled entirely by artificial intelligence computer chips."], 0, "순수하게 이타적인 공복이 아니라 사익을 추구하는 효용 극대화자라는 가정입니다."),
             ("What is economic rent-seeking according to James Buchanan?", "제임스 뷰캐넌에 따른 경제적 지대추구(rent-seeking)란 무엇인가요?", ["Expending resources lobbying government for monopolies, subsidies, or protective tariffs without creating new wealth", "Building rental apartment housing for low-income urban families", "Investing in research and development to manufacture better medicines", "Paying commercial store rent on time every month"], 0, "새로운 부 창출 없이 정부 보조금이나 독점 규제를 따내기 위해 로비 자원을 낭비하는 행위입니다."),
             ("Why do politicians readily pass special-interest legislation?", "정치인들은 왜 특수 이익 집단을 위한 법안을 손쉽게 통과시키나요?", ["Benefits are concentrated among organized lobby groups while costs are thinly dispersed across millions of taxpayers.", "Interest groups threaten politicians with physical violence.", "Special legislation is required by the United Nations charter.", "All politicians are required by law to obey corporate executives."], 0, "이익은 조직된 로비 집단에 집중되는 반면 비용은 수많은 납세자에게 얇게 분산되기 때문이라고 설명했습니다.")
         ]),

        ("a-60", "Scientific Realism and the Pessimistic Meta-Induction", "과학적 실재론과 비관적 메타 귀납의 인식론", "Philosophy of Science & Metaphysics", "Philosophy of Science",
         "과거의 가장 성공적이었던 과학 이론들도 결국 거짓으로 판명되어 폐기되었듯이 현재의 이론도 거짓일 수 있다는 래리 라우단의 도전을 다룹니다.",
         [
             ("Scientific realism asserts that our best empirical theories provide approximately true descriptions of an unobservable, objective reality.", "과학적 실재론은 우리의 최상의 실증 이론이 관찰 불가능한 객관적 실재에 대한 대략적으로 참인 설명을 제공한다고 주장합니다.", "Scientific realism asserts / that our best empirical theories provide / approximately true descriptions / of an unobservable, objective reality."),
             ("Realists invoke the 'No Miracles Argument,' contending that the immense predictive success of modern science would be a cosmic miracle unless theories were genuinely true.", "실재론자들은 '기적은 없다 논증'을 원용하여, 이론이 진정으로 참이 아니라면 현대 과학의 막대한 예측 성공은 우주적 기적일 것이라고 주장합니다.", "Realists invoke the 'No Miracles Argument,' / contending that the immense predictive success of modern science / would be a cosmic miracle / unless theories were genuinely true."),
             ("However, in 1981, philosopher of science Larry Laudan formulated a devastating counter-critique designated the Pessimistic Meta-Induction.", "그러나 1981년 과학철학자 래리 라우단은 '비관적 메타 귀납'으로 명명된 파괴적인 반론을 정립했습니다.", "However, in 1981, / philosopher of science Larry Laudan formulated / a devastating counter-critique / designated the Pessimistic Meta-Induction."),
             ("Laudan compiled a formidable historical catalogue of past scientific theories—including phlogiston chemistry, the luminiferous ether, and Ptolemaic epicycles—that were empirically triumphant in their eras yet ultimately discarded as false.", "라우단은 플로지스톤 화학, 발광 에테르, 프톨레마이오스 주전원 등 당대에는 실증적으로 대성공을 거두었으나 궁극적으로 거짓으로 폐기된 과거 과학 이론들의 방대한 역사적 목록을 집대성했습니다.", "Laudan compiled a formidable historical catalogue / of past scientific theories / —including phlogiston chemistry, the luminiferous ether, and Ptolemaic epicycles— / that were empirically triumphant in their eras / yet ultimately discarded as false."),
             ("By mathematical induction, if past predictive success did not guarantee truth, our current foundational theories are likely false as well.", "수학적 귀납에 의해, 과거의 예측 성공이 진리를 보장하지 않았다면 우리의 현재 근본 이론들 역시 거짓일 가능성이 높습니다.", "By mathematical induction, / if past predictive success did not guarantee truth, / our current foundational theories / are likely false as well."),
             ("This philosophical challenge has propelled structural realism, which argues that while theoretical entities may be abandoned, mathematical relations persist across scientific revolutions.", "이 철학적 도전은 이론적 실체는 폐기될 수 있을지라도 수학적 관계는 과학 혁명 전반에 걸쳐 지속된다고 주장하는 구조적 실재론을 촉발했습니다.", "This philosophical challenge has propelled structural realism, / which argues that while theoretical entities may be abandoned, / mathematical relations persist / across scientific revolutions.")
         ],
         [("realism", "n.", "실재론 (외부 세계가 인식과 무관하게 독립적으로 실재한다는 관점)", "Scientific realism contends that subatomic entities objectively exist."), ("invoke", "v.", "원용하다, 들먹이다", "Lawyers invoked the constitutional protection against self-incrimination."), ("cataclysmic", "adj.", "격변의, 파멸적인", "The asteroid collision triggered a cataclysmic extinction event."), ("induction", "n.", "귀납, 귀납법", "The pessimistic meta-induction infers the falsity of current science from historical precedents."), ("persist", "v.", "지속되다, 고집하다", "Mathematical equations often persist even when theoretical interpretations shift.")],
         [("가정법 과거", "...predictive success would be a miracle unless theories were genuinely true... 실현 불가능한 가정에 기초한 반박 구문입니다."), ("접속사 while 양보", "...which argues that while theoretical entities may be abandoned, mathematical relations persist... 양보와 대조 구문입니다.")],
         [
             ("What is the central premise of the 'No Miracles Argument' for scientific realism?", "과학적 실재론을 지지하는 '기적은 없다 논증'의 핵심 전제는 무엇인가요?", ["Science's immense predictive and technological success would be an inexplicable miracle unless theories were approximately true.", "Religious miracles are required to calibrate laboratory microscopes.", "Scientific experiments succeed only when conducted inside churches.", "All scientific discoveries are made by supernatural intervention."], 0, "과학의 막대한 예측 성공은 이론이 대략 참이 아니라면 설명 불가능한 기적일 것이라는 주장입니다."),
             ("What historical evidence did Larry Laudan assemble to formulate the Pessimistic Meta-Induction?", "래리 라우단은 비관적 메타 귀납을 정식화하기 위해 어떤 역사적 증거를 수집했나요?", ["A list of past theories (like phlogiston and ether) that were empirically successful but ultimately false", "A compilation of ancient musical instruments from Egypt", "Receipts from nineteenth-century coal mining operations", "Astrological charts discarded by medieval royalty"], 0, "플로지스톤이나 에테르처럼 당대에는 성공적이었으나 결국 거짓으로 폐기된 과거 이론들의 목록이라고 설명했습니다."),
             ("How does structural realism respond to the Pessimistic Meta-Induction?", "구조적 실재론은 비관적 메타 귀납에 어떻게 대응하나요?", ["By arguing that mathematical relations and structures persist across revolutions even if entity descriptions change", "By banning the teaching of science in public universities", "By claiming that no scientific revolution has ever occurred in history", "By asserting that all ancient theories were actually correct"], 0, "실체 개념은 바뀔지라도 수학적 구조와 관계는 과학 혁명을 넘어 보존된다고 주장함으로써 대응했다고 밝혔습니다.")
         ])
    ]

if __name__ == "__main__":
    print(f"Generated extra advanced passages for 180 target: {len(get_expansion_180_a())}")
