# -*- coding: utf-8 -*-
"""
generate_expansion_intermediate.py
Intermediate Passages i-31 to i-40
Sources: Nature Biotechnology, MIT Tech Review, Scientific American, Harvard Business Review, The Economist
"""

def get_intermediate_expansion():
    i_extra = [
        ("i-31", "The Mechanics of Gene Editing via CRISPR", "CRISPR 유전자 가위의 분자생물학적 작동 원리", "Genetics & Biotechnology", "Nature Biotechnology",
         "세균의 면역 방어 기전에서 유래한 CRISPR-Cas9 시스템이 정밀하게 DNA 서열을 교정하는 원리를 탐구합니다.",
         [
             ("CRISPR-Cas9 has revolutionized molecular biology by offering unprecedented precision in genome editing.", "CRISPR-Cas9은 게놈 편집에서 전례 없는 정밀성을 제공함으로써 분자생물학에 일대 혁신을 일으켰습니다.", "CRISPR-Cas9 has revolutionized molecular biology / by offering unprecedented precision / in genome editing."),
             ("Originally discovered in bacteria, the mechanism evolved naturally as an adaptive immune defense against invading viral pathogens.", "원래 박테리아에서 발견된 이 메커니즘은 침입하는 바이러스 병원체에 맞선 적응 면역 방어 기전으로 자연 진화했습니다.", "Originally discovered in bacteria, / the mechanism evolved naturally / as an adaptive immune defense / against invading viral pathogens."),
             ("The system employs a synthetic guide RNA strand that matches a specific twenty-base sequence within the target organism's genome.", "이 시스템은 표적 생명체 게놈 내의 특정 20개 염기 서열과 일치하는 합성 가이드 RNA 가닥을 활용합니다.", "The system employs a synthetic guide RNA strand / that matches a specific twenty-base sequence / within the target organism's genome."),
             ("The Cas9 endonuclease enzyme then acts as molecular scissors, creating a precise double-stranded break at that exact genetic locus.", "그런 다음 Cas9 엔도뉴클레아제 효소가 분자 가위 역할을 하여, 바로 그 정확한 유전적 위치에서 정밀한 이중 나선 절단을 생성합니다.", "The Cas9 endonuclease enzyme then acts / as molecular scissors, / creating a precise double-stranded break / at that exact genetic locus."),
             ("Cellular repair pathways subsequently mend the gap, allowing researchers to silence mutated genes or insert therapeutic sequences.", "이후 세포 복구 경로가 그 틈을 메우면서, 연구자들은 돌연변이 유전자를 비활성화하거나 치료용 서열을 삽입할 수 있게 됩니다.", "Cellular repair pathways subsequently mend the gap, / allowing researchers to silence mutated genes / or insert therapeutic sequences."),
             ("This technological breakthrough holds profound therapeutic potential for eliminating inherited monogenic disorders such as sickle cell anemia.", "이 기술적 돌파구는 겸상 적혈구 빈혈과 같은 유전성 단일 유전자 질환을 근절할 수 있는 심오한 치료 잠재력을 지니고 있습니다.", "This technological breakthrough holds / profound therapeutic potential / for eliminating inherited monogenic disorders / such as sickle cell anemia.")
         ],
         [("unprecedented", "adj.", "전례 없는, 유례없는", "The summit achieved unprecedented diplomatic cooperation."), ("pathogen", "n.", "병원체, 병원균", "Antibiotics target bacterial pathogens while sparing human cells."), ("locus", "n.", "유전적 위치, 장소", "The mutant gene resides at a specific chromosomal locus."), ("therapeutic", "adj.", "치료의, 치유력 있는", "The clinical trial demonstrated positive therapeutic outcomes."), ("monogenic", "adj.", "단일 유전자의", "Cystic fibrosis is a well-studied monogenic disorder.")],
         [("전치사 by + 동명사", "...by offering unprecedented precision in... 수단과 방식을 나타내는 by -ing입니다."), ("분사구문 allowing", "...mend the gap, allowing researchers to... 결과를 나타내는 분사구문입니다.")],
         [
             ("What natural origin did the CRISPR-Cas9 mechanism evolve from?", "CRISPR-Cas9 메커니즘은 본래 어떤 자연적 기원에서 진화했나요?", ["A defensive immune system in bacteria against viral pathogens", "A toxin produced by venomous marine mollusks", "A reproductive enzyme found only in deep-sea corals", "A chemical dye synthesized by desert mosses"], 0, "바이러스 병원체에 대항하는 박테리아의 적응 면역 방어 기전에서 유래했다고 설명했습니다."),
             ("What is the primary function of the Cas9 enzyme?", "Cas9 효소의 핵심 기능은 무엇인가요?", ["Synthesizing new glucose molecules from sunlight", "Acting as molecular scissors to cut double-stranded DNA", "Translating electrical pulses inside mammalian brain synapses", "Dissolving cell wall lipids during cellular division"], 1, "정확한 유전적 위치에서 이중 나선 절단을 만드는 분자 가위(molecular scissors) 역할을 한다고 밝혔습니다."),
             ("Which inherited condition is explicitly cited as having therapeutic potential?", "어떤 유전 질환이 치료 잠재력을 지닌 것으로 본문에 명시되었나요?", ["Sickle cell anemia", "Common seasonal influenza", "Bone fractures from sports injuries", "Type 1 acute food allergies"], 0, "겸상 적혈구 빈혈(sickle cell anemia)과 같은 유전성 단일 유전자 질환이 언급되었습니다.")
         ]),

        ("i-32", "The Architecture of Deep-Sea Hydrothermal Vents", "심해 열수구의 생태학적 구조와 화학합성", "Marine Biology & Geophysics", "Scientific American",
         "태양빛이 닿지 않는 칠흑 같은 심해 바닥에서 황화수소를 에너지원으로 삼는 극한 생물 군집을 조명합니다.",
         [
             ("Kilometers beneath the ocean surface where absolute darkness reigns, hydrothermal vents sustain astonishingly fertile biological communities.", "완전한 암흑이 지배하는 해수면 수 킬로미터 아래에서, 심해 열수구는 놀랍도록 풍요로운 생물 군집을 부양합니다.", "Kilometers beneath the ocean surface / where absolute darkness reigns, / hydrothermal vents sustain / astonishingly fertile biological communities."),
             ("These towering mineral chimneys, nicknamed black smokers, form along tectonic ridges where seawater meets subterranean volcanic magma.", "블랙 스모커라는 별명을 지닌 이 우뚝 솟은 광물 굴뚝은 바닷물이 지하 화산 마그마와 만나는 지각 능선을 따라 형성됩니다.", "These towering mineral chimneys, / nicknamed black smokers, / form along tectonic ridges / where seawater meets subterranean volcanic magma."),
             ("Superheated water exceeding three hundred degrees Celsius gushes upward, carrying dissolved hydrogen sulfide and metallic compounds.", "섭씨 300도를 넘는 과열된 물이 용출되어 올라오며, 용해된 황화수소와 금속 화합물을 실어나릅니다.", "Superheated water exceeding three hundred degrees Celsius / gushes upward, / carrying dissolved hydrogen sulfide / and metallic compounds."),
             ("Because sunlight cannot penetrate these abyss depths, photosynthesis is entirely absent from this alien ecosystem.", "햇빛이 이 심연의 깊이까지 침투할 수 없기 때문에, 이 기이한 생태계에서는 광합성이 완전히 결여되어 있습니다.", "Because sunlight cannot penetrate these abyss depths, / photosynthesis is entirely absent / from this alien ecosystem."),
             ("Instead, specialized chemotrophic bacteria harness the chemical energy of sulfur bonds to synthesize vital organic nutrients.", "대신에, 특화된 화학합성 세균이 황 결합의 화학 에너지를 활용하여 필수 유기 영양분을 합성합니다.", "Instead, / specialized chemotrophic bacteria harness / the chemical energy of sulfur bonds / to synthesize vital organic nutrients."),
             ("Giant red-tipped tube worms lacking digestive tracts rely entirely on billions of these symbiotic bacteria living inside their tissues.", "소화관이 없는 거대한 붉은 끝 관벌레는 자신의 조직 내부에 서식하는 수십억 마리의 공생 세균에 전적으로 의존합니다.", "Giant red-tipped tube worms lacking digestive tracts / rely entirely on billions / of these symbiotic bacteria / living inside their tissues.")
         ],
         [("subterranean", "adj.", "지하의, 땅속의", "Subterranean aquifers provide irrigation water to arid farms."), ("penetrate", "v.", "침투하다, 뚫고 들어가다", "Sunlight rarely penetrates the dense rainforest understory."), ("chemotrophic", "adj.", "화학영양성의, 화학합성의", "Chemotrophic microbes thrive near geothermal vents."), ("symbiotic", "adj.", "공생의, 공생하는", "Clownfish and sea anemones maintain a classic symbiotic relationship."), ("gush", "v.", "분출하다, 솟구치다", "High-pressure oil gushed from the exploratory drill site.")],
         [("관계부사 where", "...beneath the ocean surface where absolute darkness reigns... 선행사 ocean surface를 수식합니다."), ("분사구문 carrying", "...gushes upward, carrying dissolved hydrogen sulfide... 주절에 덧붙여진 능동 분사구문입니다.")],
         [
             ("What forms the towering chimneys known as black smokers?", "블랙 스모커라 알려진 우뚝 솟은 굴뚝은 어떻게 형성되나요?", ["Coral polyps secreting calcium carbonate shells", "Mineral deposits formed where seawater meets subterranean volcanic heat", "Fossilized shells of ancient sea turtles", "Volcanic ash cooled by polar glaciers"], 1, "바닷물이 지하 마그마와 만나는 지각 능선에서 광물이 침전되어 형성된다고 설명했습니다."),
             ("How is organic energy produced without sunlight in hydrothermal vents?", "열수구에서는 햇빛 없이 어떻게 유기 에너지가 생산되나요?", ["Through chemotrophic bacteria harnessing chemical energy from sulfur bonds", "By capturing cosmic microwave radiation from orbit", "Through deep-sea plants performing nocturnal photosynthesis", "By digesting floating microplastics drifting from the surface"], 0, "화학합성 세균이 황 결합의 화학 에너지를 활용하여 영양분을 합성한다고 명시했습니다."),
             ("What biological adaptation characterizes giant tube worms near vents?", "열수구 근처 거대 관벌레의 생물학적 특징은 무엇인가요?", ["They lack digestive tracts and rely on symbiotic internal bacteria.", "They possess four mechanical wings to swim against thermal currents.", "They have panoramic compound eyes to hunt glowing jellyfish.", "They migrate to coral reefs every spring to spawn."], 0, "소화관이 결여되어 있으며 조직 내 수십억 마리의 공생 세균에 의존한다고 밝혔습니다.")
         ]),

        ("i-33", "The Economics of Behavioral Nudges", "행동경제학의 넛지 이론과 공공정책", "Behavioral Economics", "The Economist",
         "선택의 자유를 박탈하지 않으면서도 미세한 구조 설계를 통해 사람들의 바람직한 결정을 유도하는 넛지 메커니즘을 다룹니다.",
         [
             ("Traditional neoclassical economics assumes that human agents behave as entirely rational utility maximizers.", "전통 신고전파 경제학은 인간 행위자가 전적으로 합리적인 효용 극대화자로서 행동한다고 가정합니다.", "Traditional neoclassical economics assumes / that human agents behave / as entirely rational utility maximizers."),
             ("However, empirical psychology shows that cognitive fatigue, default inertia, and emotional biases routinely distort decision-making.", "그러나 실증 심리학은 인지적 피로, 기본값 관성, 감정적 편향이 일상적으로 의사결정을 왜곡함을 보여줍니다.", "However, empirical psychology shows / that cognitive fatigue, default inertia, / and emotional biases / routinely distort decision-making."),
             ("In response, behavioral economists Richard Thaler and Cass Sunstein introduced the influential framework known as nudge theory.", "이에 대응하여, 행동경제학자 리처드 탈러와 카스 선스타인은 '넛지 이론'으로 알려진 영향력 있는 프레임워크를 도입했습니다.", "In response, / behavioral economists Richard Thaler and Cass Sunstein / introduced the influential framework / known as nudge theory."),
             ("A nudge alters the choice architecture so that desirable options become the default or intuitive path without forbidding any alternatives.", "넛지는 어떠한 대안도 금지하지 않으면서 바람직한 선택지가 기본값이나 직관적 경로가 되도록 선택 아키텍처를 변경합니다.", "A nudge alters the choice architecture / so that desirable options become the default or intuitive path / without forbidding any alternatives."),
             ("For example, changing workplace pension programs from an opt-in model to automatic enrollment radically increased retirement savings rates.", "예를 들어, 직장 퇴직연금 프로그램을 선택적 가입 모델에서 자동 가입으로 변경하자 퇴직 저축률이 급격히 증가했습니다.", "For example, / changing workplace pension programs / from an opt-in model to automatic enrollment / radically increased retirement savings rates."),
             ("By recognizing human cognitive vulnerabilities, policymakers can orchestrate superior social welfare outcomes at minimal economic cost.", "인간의 인지적 취약성을 인식함으로써, 정책 입안자들은 최소한의 경제적 비용으로 우수한 사회 복지 결과를 조직할 수 있습니다.", "By recognizing human cognitive vulnerabilities, / policymakers can orchestrate / superior social welfare outcomes / at minimal economic cost.")
         ],
         [("empirical", "adj.", "실증적인, 경험에 근거한", "Empirical data from clinical trials confirmed the hypothesis."), ("inertia", "n.", "관성, 무기력", "Bureaucratic inertia prevented immediate administrative reform."), ("architecture", "n.", "설계, 구조", "The choice architecture of the website guided users toward secure passwords."), ("enrollment", "n.", "등록, 입학", "University enrollment increased substantially after tuition subsidies."), ("orchestrate", "v.", "조직하다, 연출하다", "The conductor orchestrated a seamless transition between themes.")],
         [("so that 구문", "...alters the choice architecture so that desirable options become... 목적과 결과를 나타내는 so that 구문입니다."), ("전치사 without -ing", "...without forbidding any alternatives... 대안을 금지함이 없이 선택을 유도한다는 표현입니다.")],
         [
             ("What fundamental assumption of neoclassical economics is challenged by behavioral economists?", "행동경제학자들은 신고전파 경제학의 어떤 근본 가정을 비판하나요?", ["That all currencies should be backed by physical bullion", "That humans act as completely rational utility maximizers", "That free market trade always causes national inflation", "That manual labor creates more value than capital assets"], 1, "인간이 전적으로 합리적인 효용 극대화자라는 가정을 지적했습니다."),
             ("How does a nudge modify human choices according to the text?", "지문에 따르면 넛지는 인간의 선택을 어떻게 변경하나요?", ["By legally imprisoning individuals who select undesirable choices", "By altering choice architecture without forbidding alternatives", "By taxing healthy organic produce at ninety percent", "By eliminating all choices except one mandatory government program"], 1, "대안을 금지하지 않으면서 선택 구조를 변경하여 바람직한 옵션을 유도한다고 설명했습니다."),
             ("What real-world policy example demonstrated the power of a nudge?", "어떤 실제 정책 사례가 넛지의 위력을 입증했나요?", ["Banning all sugar consumption nationwide", "Switching retirement pensions to automatic enrollment defaults", "Confiscating private vehicles on odd-numbered calendar days", "Replacing all paper currency with digital gold tokens"], 1, "퇴직연금을 자동 가입(automatic enrollment) 기본값으로 전환하여 저축률을 대폭 높인 사례를 제시했습니다.")
         ]),

        ("i-34", "The Physics of Quantum Entanglement", "양자 얽힘의 물리학과 정보 통신", "Quantum Physics", "MIT Technology Review",
         "아인슈타인이 '유령 같은 원격 작용'이라 불렀던 두 입자 사이의 즉각적 상관관계와 양자 암호학을 설명합니다.",
         [
             ("Quantum entanglement describes a counterintuitive phenomenon where two paired subatomic particles share instantaneous states regardless of separation.", "양자 얽힘은 거리에 상관없이 쌍을 이룬 두 아원자 입자가 순간적인 상태를 공유하는 직관에 반하는 현상을 설명합니다.", "Quantum entanglement describes / a counterintuitive phenomenon / where two paired subatomic particles / share instantaneous states / regardless of separation."),
             ("When an observer measures the spin orientation of one entangled photon, the counterpart particle immediately registers the opposite value.", "관찰자가 얽힌 광자 하나의 스핀 방향을 측정할 때, 상대 입자는 즉각적으로 반대 값을 기록합니다.", "When an observer measures the spin orientation / of one entangled photon, / the counterpart particle / immediately registers the opposite value."),
             ("Albert Einstein famously dismissed this non-local connection, skepticism that led him to dub the effect 'spooky action at a distance.'", "알베르트 아인슈타인은 유명하게도 이 비국소적 연결을 일축했으며, 이러한 회의론은 그가 이 효과를 '원거리의 유령 같은 작용'이라 부르게 했습니다.", "Albert Einstein famously dismissed this non-local connection, / skepticism that led him / to dub the effect / 'spooky action at a distance.'"),
             ("However, rigorous laboratory tests of Bell's inequality theorem confirmed that quantum correlation cannot be explained by hidden classical variables.", "그러나 벨 부등식 정리에 대한 엄격한 실험실 검증은 양자 상관관계가 숨겨진 고전적 변수로 설명될 수 없음을 확인했습니다.", "However, / rigorous laboratory tests of Bell's inequality theorem / confirmed that quantum correlation / cannot be explained / by hidden classical variables."),
             ("Today, physicists leverage entanglement to pioneer uncrackable quantum key distribution protocols for state-level cybersecurity.", "오늘날 물리학자들은 국가 차원의 사이버 보안을 위해 도청이 불가능한 양자 키 분배 프로토콜을 개척하는 데 얽힘을 활용합니다.", "Today, / physicists leverage entanglement / to pioneer uncrackable quantum key distribution protocols / for state-level cybersecurity."),
             ("Any surreptitious interception attempt inevitably disrupts the fragile quantum waveform, alerting communicating parties to intrusion.", "어떠한 은밀한 도청 시도도 필연적으로 취약한 양자 파동 함수를 교란하여, 통신 당사자들에게 침입을 경고하게 됩니다.", "Any surreptitious interception attempt / inevitably disrupts the fragile quantum waveform, / alerting communicating parties / to intrusion.")
         ],
         [("counterintuitive", "adj.", "직관에 반하는, 반직관적인", "The mathematical result seemed counterintuitive at first glance."), ("entanglement", "n.", "얽힘, 복잡한 연루", "Quantum entanglement enables quantum teleportation protocols."), ("skepticism", "n.", "회의론, 의심", "Scientific skepticism requires repeatable empirical verification."), ("leverage", "v.", "활용하다, 지렛대로 쓰다", "The enterprise leveraged AI models to optimize warehouse logistics."), ("surreptitious", "adj.", "은밀한, 슬그머니 하는", "Security cameras recorded the surreptitious entry into the vault.")],
         [("where 관계부사", "...a counterintuitive phenomenon where two paired subatomic particles share... phenomenon을 상황적으로 수식합니다."), ("분사구문 alerting", "...disrupts the fragile quantum waveform, alerting communicating parties... 결과를 나타내는 분사구문입니다.")],
         [
             ("What phrase did Albert Einstein famously use to characterize quantum entanglement?", "아인슈타인은 양자 얽힘을 묘사하기 위해 어떤 문구를 사용했나요?", ["'Cosmic gravitational tides'", "'Spooky action at a distance'", "'Absolute mechanical predictability'", "'Thermal equilibrium of dead stars'"], 1, "원거리의 유령 같은 작용('spooky action at a distance')이라고 명명했습니다."),
             ("What did Bell's theorem experimental tests confirm?", "벨 부등식에 대한 실험 검증은 무엇을 확인했나요?", ["Hidden classical variables cannot explain quantum correlations.", "Light travels slower inside vacuum chambers than in water.", "All subatomic particles dissolve into pure heat.", "Quantum physics is completely identical to classical mechanics."], 0, "숨겨진 고전 변수로는 양자 상관성을 설명할 수 없음을 입증했습니다."),
             ("How does quantum key distribution detect unauthorized eavesdroppers?", "양자 키 분배는 어떻게 인가되지 않은 도청자를 감지하나요?", ["By measuring radioactive alpha decay on copper wires", "Interception inevitably collapses the fragile quantum waveform.", "By scanning photographic fingerprints left on fiber optic cables", "Through loud mechanical sirens installed along telephone poles"], 1, "도청 시도가 취약한 양자 파동 함수를 필연적으로 붕괴시켜 침입을 경고한다고 설명했습니다.")
         ]),

        ("i-35", "The Evolution of Antibiotic Resistance", "항생제 내성의 진화와 슈퍼박테리아의 위협", "Microbiology & Medicine", "Harvard Medical School",
         "과도한 항생제 처방과 가축 항생제 남용이 미생물의 자연선택을 가속해 글로벌 공중보건을 위협하는 양상을 다룹니다.",
         [
             ("The discovery of penicillin by Alexander Fleming in 1928 heralded a miraculous golden age in modern antimicrobial therapeutics.", "1928년 알렉산더 플레밍의 페니실린 발견은 현대 항균 치료의 기적적인 황금기의 시작을 알렸습니다.", "The discovery of penicillin by Alexander Fleming in 1928 / heralded a miraculous golden age / in modern antimicrobial therapeutics."),
             ("Previously fatal infections including tuberculosis, pneumonia, and bacterial sepsis suddenly succumbed to standardized chemical cures.", "결핵, 폐렴, 세균성 패혈증을 포함한 이전의 치명적인 감염들이 표준화된 화학 치료제에 갑자기 굴복했습니다.", "Previously fatal infections / including tuberculosis, pneumonia, and bacterial sepsis / suddenly succumbed / to standardized chemical cures."),
             ("Nevertheless, decades of widespread clinical overprescription and rampant agricultural use have accelerated microbial natural selection.", "그럼에도 불구하고, 수십 년간의 광범위한 임상적 과잉 처방과 무분별한 농축산업적 사용은 미생물의 자연선택을 가속화했습니다.", "Nevertheless, / decades of widespread clinical overprescription / and rampant agricultural use / have accelerated microbial natural selection."),
             ("Within bacterial colonies, rare spontaneous mutations or horizontal plasmid transfers impart biochemical shields against standard drugs.", "세균 군집 내에서, 드문 자발적 돌연변이나 수평적 플라스미드 전달은 표준 약물에 대항하는 생화학적 방어막을 부여합니다.", "Within bacterial colonies, / rare spontaneous mutations / or horizontal plasmid transfers / impart biochemical shields / against standard drugs."),
             ("While susceptible competitors are eradicated, surviving resistant mutants proliferate unhindered, creating formidable 'superbug' strains.", "취약한 경쟁자들은 박멸되는 반면, 살아남은 내성 돌연변이들은 방해받지 않고 증식하여 가공할 만한 '슈퍼박테리아' 변종을 만들어냅니다.", "While susceptible competitors are eradicated, / surviving resistant mutants proliferate unhindered, / creating formidable 'superbug' strains."),
             ("Combating this escalating crisis demands stringent global stewardship, novel bacteriophage therapies, and disciplined sanitation protocols.", "이 격화되는 위기에 맞서 싸우기 위해서는 엄격한 글로벌 관리 체계, 새로운 박테리오파지 요법, 규율 있는 위생 프로토콜이 요구됩니다.", "Combating this escalating crisis demands / stringent global stewardship, / novel bacteriophage therapies, / and disciplined sanitation protocols.")
         ],
         [("herald", "v.", "알리다, 예고하다", "The warm spring rain heralded the arrival of planting season."), ("succumb", "v.", "굴복하다, 무너지다", "The defending army finally succumbed to relentless siege pressure."), ("rampant", "adj.", "만연하는, 걷잡을 수 없는", "Wild rumors ran rampant across social media channels."), ("proliferate", "v.", "급증하다, 빠르게 번식하다", "Algae proliferated rapidly in the warm, nutrient-rich lake."), ("stringent", "adj.", "엄격한, 엄중한", "Aviation agencies enforce stringent safety inspections on aircraft.")],
         [("접속사 While의 대조", "While susceptible competitors are eradicated, surviving resistant mutants proliferate... 대조 구문입니다."), ("동명사 주어", "Combating this escalating crisis demands... 동명사 단수 주어 구문입니다.")],
         [
             ("What historic milestone did Alexander Fleming achieve in 1928?", "1928년 알렉산더 플레밍이 달성한 역사적 이정표는 무엇인가요?", ["The creation of the first synthetic heart valve", "The discovery of penicillin, launching antimicrobial medicine", "The total eradication of smallpox worldwide", "The invention of recombinant DNA sequencers"], 1, "페니실린의 발견으로 항균 치료의 황금기를 열었다고 서술했습니다."),
             ("How do resistant bacteria multiply in an environment saturated with antibiotics?", "항생제로 포화된 환경에서 내성균은 어떻게 증식하나요?", ["They freeze into dormant amber beads indefinitely.", "Susceptible rivals perish while resistant mutants thrive and proliferate unhindered.", "They convert antibiotic pills into pure water molecules.", "They flee through the bloodstream into oceanic water supplies."], 1, "취약한 경쟁자들이 사멸하는 동안 살아남은 내성 돌연변이들이 증식한다고 명시했습니다."),
             ("What novel biological approach is proposed to counter antibiotic resistance?", "항생제 내성에 대응하기 위해 어떤 새로운 생물학적 접근법이 제안되었나요?", ["Novel bacteriophage therapies", "Replacing all hospital beds with stainless steel cages", "Banning all medical handwashing protocols", "Boiling all antibiotics prior to prescription"], 0, "새로운 박테리오파지 요법(novel bacteriophage therapies)이 명시되었습니다.")
         ]),

        ("i-36", "The Mechanics of Global Container Shipping", "컨테이너 해운 물류가 창조한 현대 세계화", "Global Logistics & Economics", "The Financial Times",
         "1950년대 표준 규격 화물 컨테이너의 등장이 해상 물류 비용을 90% 이상 낮춰 글로벌 공급망을 연결한 과정을 다룹니다.",
         [
             ("Modern globalization is underpinned not merely by digital cables, but by steel rectangular shipping containers.", "현대 세계화는 단순히 디지털 케이블뿐만 아니라, 강철 직사각형 해상 운송 컨테이너에 의해 지탱됩니다.", "Modern globalization is underpinned / not merely by digital cables, / but by steel rectangular shipping containers."),
             ("Prior to Malcolm McLean's invention of intermodal containerization in 1956, dockworkers loaded cargo piece by laborious piece.", "1956년 말콤 맥린이 복합운송 컨테이너화를 발명하기 전에는, 부두 노동자들이 화물을 하나하나 힘겹게 실었습니다.", "Prior to Malcolm McLean's invention / of intermodal containerization in 1956, / dockworkers loaded cargo / piece by laborious piece."),
             ("Ships spent weeks berthed at ports while barrels, crates, and loose sacks were manually transferred into holds.", "나무통, 상자, 헐거운 포대들이 수작업으로 선창에 옮겨지는 동안 배들은 몇 주 동안 항구에 정박해 있어야 했습니다.", "Ships spent weeks berthed at ports / while barrels, crates, and loose sacks / were manually transferred into holds."),
             ("Standardized twenty-foot and forty-foot boxes allowed seamless transfer across cargo vessels, flatbed trains, and highway trucks.", "표준화된 20피트 및 40피트 규격 상자는 화물선, 평판 열차, 고속도로 트럭 간의 매끄러운 환적을 가능하게 했습니다.", "Standardized twenty-foot and forty-foot boxes / allowed seamless transfer / across cargo vessels, flatbed trains, / and highway trucks."),
             ("Handling productivity skyrocketed while terminal loading expenses plummeted by more than ninety percent almost overnight.", "하역 생산성은 치솟았고, 터미널 선적 비용은 거의 하룻밤 사이에 90% 이상 곤두박질쳤습니다.", "Handling productivity skyrocketed / while terminal loading expenses plummeted / by more than ninety percent / almost overnight."),
             ("By turning ocean freight into a friction-free logistical commodity, container ships forged interconnected international supply networks.", "해상 화물 운송을 마찰 없는 물류 상품으로 전환함으로써, 컨테이너선은 상호 연결된 국제 공급망 네트워크를 구축했습니다.", "By turning ocean freight / into a friction-free logistical commodity, / container ships forged / interconnected international supply networks.")
         ],
         [("underpin", "v.", "뒷받침하다, 지탱하다", "Sound scientific principles underpin all civil engineering."), ("intermodal", "adj.", "복합운송의", "Intermodal freight seamlessly links maritime vessels with freight trains."), ("laborious", "adj.", "힘든, 고된", "Carving statues from raw granite was a laborious process."), ("plummet", "v.", "폭락하다, 급락하다", "Share prices plummeted following the economic downturn."), ("forge", "v.", "구축하다, 단조하다", "Diplomats forged a bilateral trade treaty between both nations.")],
         [("not merely A but B", "Modern globalization is underpinned not merely by A, but by B... 'A뿐만 아니라 B에 의해서도'라는 상관접속사입니다."), ("spend + 시간 + -ing/분사", "Ships spent weeks berthed at ports... 배들이 항구에 정박된 채 몇 주를 보냈다는 표현입니다.")],
         [
             ("How was maritime cargo handled before modern containerization?", "현대 컨테이너화 이전에는 해상 화물이 어떻게 처리되었나요?", ["Automated drones lifted containers from floating docks.", "Dockworkers loaded loose barrels and crates manually piece by piece.", "Robotic magnets sorted magnetic ore directly from barges.", "Cargo was loaded exclusively during winter blizzards."], 1, "부두 노동자들이 통과 상자를 수작업으로 일일이 실었다고 설명했습니다."),
             ("What economic impact resulted from standardized container shipping?", "표준화된 컨테이너 해운으로 인해 어떤 경제적 영향이 나타났나요?", ["Terminal loading expenses plummeted by more than ninety percent.", "International ocean trade collapsed entirely for thirty years.", "Trucking companies were completely outlawed worldwide.", "All freight became eighty percent heavier due to metal weight."], 0, "터미널 선적 비용이 90% 이상 급락했다고 명시했습니다."),
             ("What transport modes are linked by intermodal containerization?", "복합운송 컨테이너화는 어떤 운송 수단들을 연결하나요?", ["Underground pneumatic tubes and horse buggies", "Submarines and hot air balloons", "Cargo vessels, flatbed freight trains, and highway trucks", "Bicycles and commercial passenger airplanes"], 2, "화물선, 평판 화물열차, 고속도로 트럭을 매끄럽게 연결한다고 서술했습니다.")
         ]),

        ("i-37", "The Psychology of Cognitive Dissonance", "인지부조화의 심리학과 자기합리화", "Psychology & Cognition", "Psychological Review",
         "자신의 행동과 신념이 모순될 때 발생하는 심리적 불쾌감과 이를 해소하기 위한 인간의 자기정당화 메커니즘을 탐구합니다.",
         [
             ("Leon Festinger formulated the theory of cognitive dissonance in 1957 to explain how humans manage conflicting beliefs.", "레온 페스팅거는 인간이 상충하는 신념들을 어떻게 처리하는지 설명하기 위해 1957년 인지부조화 이론을 정립했습니다.", "Leon Festinger formulated the theory / of cognitive dissonance in 1957 / to explain / how humans manage conflicting beliefs."),
             ("When individuals hold two mutually contradictory ideas, or act in ways that violate their internal values, distress arises.", "개인이 상호 모순되는 두 가지 생각을 품거나 자신의 내적 가치관에 위배되는 방식으로 행동할 때, 심리적 고통이 발생합니다.", "When individuals hold / two mutually contradictory ideas, / or act in ways / that violate their internal values, / distress arises."),
             ("Because the human psyche instinctively craves psychological consistency, people feel an urgent drive to eliminate this mental discomfort.", "인간의 정신은 본능적으로 심리적 일관성을 갈망하기 때문에, 사람들은 이러한 정신적 불편을 제거하려는 긴박한 충동을 느낍니다.", "Because the human psyche instinctively craves / psychological consistency, / people feel an urgent drive / to eliminate this mental discomfort."),
             ("Rather than adopting the painful effort of altering deep-seated habits, individuals frequently rationalize their questionable conduct.", "뿌리 깊은 습관을 바꾸는 고통스러운 노력을 택하기보다, 개인들은 자신의 미심쩍은 행동을 합리화하는 경우가 많습니다.", "Rather than adopting the painful effort / of altering deep-seated habits, / individuals frequently rationalize / their questionable conduct."),
             ("For instance, a heavy smoker who understands cancer risks may convince themselves that life stress poses an even greater threat.", "예를 들어, 암 위험을 이해하고 있는 골초 흡연자는 일상의 스트레스가 훨씬 더 큰 위협이라고 스스로를 납득시킬 수 있습니다.", "For instance, / a heavy smoker who understands cancer risks / may convince themselves / that life stress poses / an even greater threat."),
             ("Understanding dissonance reveals how cognitive biases protect fragile egos against uncomfortable objective truths.", "부조화를 이해하는 것은 인지적 편향이 불편한 객관적 진실로부터 취약한 자아를 어떻게 보호하는지를 보여줍니다.", "Understanding dissonance reveals / how cognitive biases protect fragile egos / against uncomfortable objective truths.")
         ],
         [("dissonance", "n.", "부조화, 불협화음", "Cognitive dissonance occurs when actions contradict moral values."), ("contradictory", "adj.", "모순되는, 양립할 수 없는", "Witnesses gave completely contradictory accounts of the accident."), ("consistency", "n.", "일관성, 지속성", "Long-term success requires daily consistency in practice."), ("rationalize", "v.", "합리화하다", "He rationalized his excessive spending as an investment."), ("fragile", "adj.", "취약한, 깨지기 쉬운", "A glass vase is extremely fragile and requires delicate handling.")],
         [("Rather than -ing", "Rather than adopting the painful effort..., individuals frequently... '~하기보다는'이라는 대비 구문입니다."), ("동명사 주어", "Understanding dissonance reveals how... 동명사 단수 주어 구조입니다.")],
         [
             ("Who originally formulated the theory of cognitive dissonance?", "인지부조화 이론을 처음 정립한 학자는 누구인가요?", ["Sigmund Freud", "Leon Festinger", "B.F. Skinner", "Carl Jung"], 1, "1957년 레온 페스팅거(Leon Festinger)가 정립했다고 명시했습니다."),
             ("Why do people experience psychological distress during cognitive dissonance?", "사람들은 인지부조화 상황에서 왜 심리적 고통을 경험하나요?", ["Because their body runs out of blood oxygen", "Because conflicting beliefs violate their instinct for mental consistency", "Because external laws impose immediate monetary fines", "Because memories are permanently deleted from the brain"], 1, "상충하는 신념들이 심리적 일관성을 바라는 본능을 위배하기 때문입니다."),
             ("How does a smoker in the text typically resolve cognitive dissonance?", "지문 속 흡연자는 전형적으로 인지부조화를 어떻게 해소하나요?", ["By quitting smoking within five seconds", "By rationalizing that daily life stress poses a greater danger than smoking", "By filing a lawsuit against tobacco manufacturers", "By moving to an uninhabited polar ice sheet"], 1, "일상 스트레스가 더 큰 위협이라고 스스로를 합리화(rationalize)함으로써 해소한다고 설명했습니다.")
         ]),

        ("i-38", "The Ecological Engineering of Beaver Dams", "비버 댐의 생태학적 수문 조절과 공학적 역할", "Ecology & Hydrology", "National Geographic",
         "생태계의 대표적 '생태 공학자'인 비버가 댐을 지어 습지를 조성하고 산불과 가뭄을 막는 과정을 다룹니다.",
         [
             ("Beavers are celebrated by ecologists as quintessential ecosystem engineers capable of transforming entire regional landscapes.", "비버는 전체 지역 경관을 완전히 탈바꿈시킬 수 있는 대표적인 생태계 공학자로서 생태학자들에게 찬사를 받습니다.", "Beavers are celebrated by ecologists / as quintessential ecosystem engineers / capable of transforming / entire regional landscapes."),
             ("Using robust chisel-like incisor teeth, a family of beavers fells alder and aspen trees along energetic riverbanks.", "튼튼한 끌 모양의 앞니를 사용하여, 비버 가족은 활기찬 강둑을 따라 오리나무와 사시나무를 쓰러뜨립니다.", "Using robust chisel-like incisor teeth, / a family of beavers / fells alder and aspen trees / along energetic riverbanks."),
             ("They interweave timber, stones, and river mud to construct resilient dams across swiftly rushing mountain streams.", "그들은 목재, 돌, 강 진흙을 엮어 빠르게 흐르는 산골 시내를 가로지르는 견고한 댐을 건설합니다.", "They interweave timber, stones, and river mud / to construct resilient dams / across swiftly rushing mountain streams."),
             ("The resulting ponds slow torrential runoff, trapping nutrient-rich sediment and creating sprawling biodiverse wetland reservoirs.", "그 결과 생겨난 연못은 격렬한 유출수를 늦추고, 영양분이 풍부한 퇴적토를 가두며, 생물다양성이 풍부한 광대한 습지 저수지를 만듭니다.", "The resulting ponds slow torrential runoff, / trapping nutrient-rich sediment / and creating sprawling biodiverse wetland reservoirs."),
             ("During arid summer droughts, these beaver wetlands remain lush green oasis corridors, serving as natural firebreaks against wildfires.", "건조한 여름 가뭄 동안에도 이 비버 습지는 푸른 오아시스 회랑으로 남아 산불에 맞서는 천연 방화벽 역할을 합니다.", "During arid summer droughts, / these beaver wetlands remain / lush green oasis corridors, / serving as natural firebreaks against wildfires."),
             ("Reintroducing beavers into degraded watersheds has proved far more cost-effective than building artificial concrete reservoirs.", "황폐해진 유역에 비버를 재도입하는 것은 인공 콘크리트 저수지를 짓는 것보다 훨씬 더 비용 효율적인 것으로 입증되었습니다.", "Reintroducing beavers into degraded watersheds / has proved far more cost-effective / than building artificial concrete reservoirs.")
         ],
         [("quintessential", "adj.", "전형적인, 본질적인", "A hot bowl of soup is the quintessential comfort food."), ("incisor", "n.", "앞니, 절치", "Rodents possess sharp incisors that grow continuously throughout life."), ("torrential", "adj.", "격렬한, 억수 같은", "Torrential rainfall caused flash floods in the river valley."), ("sprawling", "adj.", "널리 뻗어 나가는, 무질서하게 확장하는", "The city transformed into a sprawling metropolitan basin."), ("firebreak", "n.", "방화벽, 산불 차단선", "Bulldozers carved a wide firebreak through the dry pine timber.")],
         [("현재분사 병렬구문", "...slow torrential runoff, trapping sediment and creating reservoirs... 주절의 결과를 설명하는 병렬 분사구문입니다."), ("비교급 강조 far", "...has proved far more cost-effective than... 비교급 more를 강조하는 부사 far입니다.")],
         [
             ("Why are beavers classified by scientists as ecosystem engineers?", "비버는 왜 과학자들에 의해 생태계 공학자로 분류되나요?", ["They build solar-powered water purifiers for humans.", "They physically alter waterways to create brand new wetland habitats.", "They migrate across continents using satellite navigation.", "They consume stone boulders to manufacture limestone mortar."], 1, "물길을 물리적으로 변경하여 새로운 습지 서식지를 창조하기 때문입니다."),
             ("What benefit do beaver ponds provide during seasonal forest fires?", "비버 연못은 계절성 산불이 발생할 때 어떤 이점을 제공하나요?", ["They release chemical foam that extinguishes lightning strikes.", "They remain lush green oasis corridors that act as natural firebreaks.", "They evaporate completely within two minutes to produce rain clouds.", "They attract airborne water bombers using sound signals."], 1, "푸른 오아시스 회랑으로 남아 천연 방화벽(firebreaks) 역할을 한다고 설명했습니다."),
             ("How does reintroducing beavers compare to building concrete dams?", "비버를 재도입하는 것은 콘크리트 댐을 짓는 것과 비교해 어떠한가요?", ["It is far more cost-effective for restoring degraded watersheds.", "It costs ten times more than modern engineering projects.", "It causes rivers to dry up within forty-eight hours.", "It requires continuous diesel generators to support the rodents."], 0, "황폐해진 유역을 복원하는 데 훨씬 더 비용 효율적이라고 밝혔습니다.")
         ]),

        ("i-39", "The Mystery of the Voynich Manuscript", "보이니치 필사본의 암호학과 역사적 미스터리", "Historical Cryptography", "BBC Culture",
         "15세기 초 제작된 것으로 추정되나 현재까지 해독되지 않은 미지의 문자 필사본과 그 가설들을 살펴봅니다.",
         [
             ("Discovered in an Italian Jesuit villa in 1912 by antique book dealer Wilfrid Voynich, the manuscript remains an unsolved riddle.", "1912년 고서점상 윌프리드 보이니치에 의해 이탈리아 예수회 빌라에서 발견된 이 필사본은 여전히 풀리지 않은 수수께끼로 남아 있습니다.", "Discovered in an Italian Jesuit villa in 1912 / by antique book dealer Wilfrid Voynich, / the manuscript remains / an unsolved riddle."),
             ("Radiocarbon dating of its delicate vellum pages firmly establishes that the volume was produced in the early fifteenth century.", "연약한 양피지 페이지에 대한 방사성 탄소 연대 측정은 이 책이 15세기 초에 제작되었음을 확고히 증명합니다.", "Radiocarbon dating of its delicate vellum pages / firmly establishes / that the volume was produced / in the early fifteenth century."),
             ("The text is written in an elegant, flowing script comprising twenty to twenty-five unique glyphs found nowhere else on Earth.", "본문은 지구상 그 어느 곳에서도 발견되지 않는 20~25개의 독특한 상형 문자로 구성된 우아하고 유려한 필체로 쓰여 있습니다.", "The text is written in an elegant, flowing script / comprising twenty to twenty-five unique glyphs / found nowhere else on Earth."),
             ("Accompanying the unreadable passages are hundreds of intricate illustrations depicting bizarre alien flora and astronomical diagrams.", "읽을 수 없는 구문들에는 기이한 미지의 식물들과 천문학적 도해들을 묘사한 수백 점의 정교한 삽화들이 수반되어 있습니다.", "Accompanying the unreadable passages / are hundreds of intricate illustrations / depicting bizarre alien flora / and astronomical diagrams."),
             ("Renowned cryptanalysts, including Alan Turing's codebreaking colleagues during World War II, failed to decipher a single coherent sentence.", "제2차 세계대전 당시 앨런 튜링의 암호해독 동료들을 포함한 저명한 암호학자들도 단 하나의 일관된 문장조차 해독하지 못했습니다.", "Renowned cryptanalysts, / including Alan Turing's codebreaking colleagues during World War II, / failed to decipher / a single coherent sentence."),
             ("Theories range from a sophisticated medieval hoax to an esoteric pharmacological herbal enciphered in an artificial language.", "가설은 정교한 중세의 사기극에서부터 인공 언어로 암호화된 비밀스러운 약용 식물학 서적에 이르기까지 다양합니다.", "Theories range from a sophisticated medieval hoax / to an esoteric pharmacological herbal / enciphered in an artificial language.")
         ],
         [("vellum", "n.", "양피지, 고급 피지", "Medieval monks scribed precious manuscripts on calf vellum."), ("glyph", "n.", "상형 문자, 글리프", "Mayan temple stone walls are carved with intricate glyphs."), ("decipher", "v.", "해독하다, 판독하다", "Archaeologists spent decades deciphering the ancient cuneiform clay tablets."), ("hoax", "n.", "사기, 날조", "The photograph of the lake monster was exposed as an elaborate hoax."), ("esoteric", "adj.", "비전의, 난해한", "Quantum topology remains an esoteric field understood by few specialists.")],
         [("도치 구문", "Accompanying the unreadable passages are hundreds of intricate illustrations... 분사구가 문두로 나와 주어와 동사가 도치되었습니다."), ("range from A to B", "Theories range from a sophisticated medieval hoax to an esoteric... 범위가 A에서 B에 이른다는 구문입니다.")],
         [
             ("When was the Voynich Manuscript produced according to radiocarbon dating?", "방사성 탄소 연대 측정에 따르면 보이니치 필사본은 언제 제작되었나요?", ["In the tenth century BCE", "In the early fifteenth century", "In the late nineteenth century", "Around three thousand years ago"], 1, "15세기 초(in the early fifteenth century)에 제작되었다고 명시했습니다."),
             ("What visual elements accompany the text throughout the manuscript?", "필사본 전반에 걸쳐 본문에는 어떤 시각적 요소들이 수반되어 있나요?", ["Photographs of medieval printing presses", "Illustrations of bizarre flora and astronomical diagrams", "Anatomical drawings of modern automobiles", "Architectural blueprints for concrete suspension bridges"], 1, "기이한 식물상(bizarre alien flora)과 천문 도해 삽화들이 수반되어 있다고 서술했습니다."),
             ("Who attempted and failed to decipher the manuscript during World War II?", "제2차 세계대전 당시 누가 필사본 해독을 시도했다가 실패했나요?", ["Codebreaking colleagues of Alan Turing", "Renaissance Italian painters", "Ancient Roman cartographers", "French culinary chefs"], 0, "앨런 튜링의 2차 대전 암호해독 동료들을 포함한 전문가들도 실패했다고 명시했습니다.")
         ]),

        ("i-40", "The Mechanics of Semiconductor Photolithography", "반도체 포토리소그래피 공정의 극한 기술", "Microchips & Nanotechnology", "IEEE Spectrum",
         "극자외선(EUV)을 이용해 실리콘 웨이퍼 위에 나노미터 단위의 미세 회로를 새겨넣는 초정밀 제조 공정을 설명합니다.",
         [
             ("Modern microprocessors contain tens of billions of microscopic transistors packed onto a silicon chip no larger than a fingernail.", "현대 마이크로프로세서는 손톱만 한 크기의 실리콘 칩 위에 집적된 수백억 개의 미세 트랜지스터를 포함하고 있습니다.", "Modern microprocessors contain / tens of billions of microscopic transistors / packed onto a silicon chip / no larger than a fingernail."),
             ("Fabricating these nanoscale electronic pathways requires photolithography, the most intricate manufacturing process ever engineered.", "이러한 나노 규모의 전자 경로를 제조하려면 인류가 설계한 가장 복잡한 제조 공정인 포토리소그래피가 필요합니다.", "Fabricating these nanoscale electronic pathways / requires photolithography, / the most intricate manufacturing process / ever engineered."),
             ("The procedure begins by coating an ultra-pure circular silicon wafer with a light-sensitive chemical compound called photoresist.", "공정은 극도로 순수한 원형 실리콘 웨이퍼에 포토레지스트라 불리는 감광성 화합물을 코팅하는 것으로 시작됩니다.", "The procedure begins / by coating an ultra-pure circular silicon wafer / with a light-sensitive chemical compound called photoresist."),
             ("Next, extreme ultraviolet (EUV) light with a wavelength of just 13.5 nanometers projects circuit patterns through a photomask stencil.", "다음으로, 파장이 단 13.5나노미터에 불과한 극자외선(EUV) 빛이 포토마스크 스텐실을 통해 회로 패턴을 투사합니다.", "Next, / extreme ultraviolet (EUV) light with a wavelength of just 13.5 nanometers / projects circuit patterns / through a photomask stencil."),
             ("Chemical developers dissolve the exposed areas, leaving behind precise microscopic stencils for etching and conductive ion implantation.", "화학 현상액이 노출된 영역을 녹여내며, 식각과 전도성 이온 주입을 위한 정밀한 미세 스텐실을 남겨놓습니다.", "Chemical developers dissolve the exposed areas, / leaving behind precise microscopic stencils / for etching and conductive ion implantation."),
             ("Repeating this optical lithography cycle dozens of times constructs towering three-dimensional architectural cities of circuitry.", "이 광학 리소그래피 주기를 수십 번 반복함으로써 우뚝 솟은 3차원 회로 도시 구조를 구축하게 됩니다.", "Repeating this optical lithography cycle dozens of times / constructs towering three-dimensional architectural cities / of circuitry.")
         ],
         [("transistor", "n.", "트랜지스터", "Silicon transistors act as microscopic binary switches in computers."), ("nanoscale", "adj.", "나노 단위의, 극미세의", "Nanoscale engineering operates at the atomic level of matter."), ("photoresist", "n.", "감광액, 포토레지스트", "The photoresist chemically alters upon exposure to ultraviolet photons."), ("stencil", "n.", "형판, 스텐실", "A copper stencil guided the precise deposition of solder paste."), ("implantation", "n.", "주입, 이식", "Ion implantation alters the electrical conductivity of semiconductor layers.")],
         [("동명사 주어", "Fabricating these nanoscale electronic pathways requires... 단수 취급 동명사 주어입니다."), ("분사구문 leaving behind", "...dissolve the exposed areas, leaving behind precise microscopic stencils... 결과 분사구문입니다.")],
         [
             ("What is the primary role of photoresist in semiconductor manufacturing?", "반도체 제조에서 포토레지스트의 주된 역할은 무엇인가요?", ["Cooling the wafer using liquid nitrogen chills", "Acting as a light-sensitive chemical coating to receive circuit patterns", "Conducting high-voltage electrical current across chips", "Polishing the outer glass packaging of desktop processors"], 1, "회로 패턴을 투사받는 감광성 화학 코팅제 역할을 한다고 설명했습니다."),
             ("What is the wavelength of extreme ultraviolet (EUV) light mentioned in the text?", "본문에서 언급된 극자외선(EUV) 빛의 파장은 얼마인가요?", ["13.5 nanometers", "500 micrometers", "10 centimeters", "Two kilometers"], 0, "단 13.5나노미터(13.5 nanometers)의 파장을 지닌다고 명시했습니다."),
             ("How are complex 3D chip structures formed through lithography?", "리소그래피를 통해 복잡한 3차원 칩 구조는 어떻게 형성되나요?", ["By carving raw stones with diamond chisels", "By repeating the lithographic coating and etching cycle dozens of times", "By melting aluminum blocks into sand molds", "By assembling pre-cut glass shards with adhesive glue"], 1, "광학 리소그래피 주기를 수십 번 반복함으로써 3차원 회로 도시를 구축한다고 설명했습니다.")
         ])
    ]
    return i_extra

if __name__ == "__main__":
    print(f"Generated extra intermediate passages: {len(get_intermediate_expansion())}")
