# -*- coding: utf-8 -*-
"""
generate_expansion_150_inter.py
Intermediate passages i-41 to i-50
Sources: Science, Nature, MIT Tech Review, Journal of Economic Perspectives, IEEE Spectrum
"""

def get_intermediate_150():
    i_extra = [
        ("i-41", "Elinor Ostrom and Governing the Commons", "엘리너 오스트롬의 공유지의 비극 극복과 공동체 자치", "Institutional Economics", "Journal of Economic Perspectives",
         "정부 통제나 사유화 없이도 지역 공동체가 자치 규범을 통해 공유 자원을 지속 가능하게 관리할 수 있음을 증명한 오스트롬의 이론을 다룹니다.",
         [
             ("Garrett Hardin's 1968 essay 'The Tragedy of the Commons' asserted that shared resources inevitably suffer catastrophic depletion.", "개릿 하딘의 1968년 에세이 '공유지의 비극'은 공유 자원이 필연적으로 파멸적인 고갈을 겪는다고 주장했습니다.", "Garrett Hardin's 1968 essay 'The Tragedy of the Commons' / asserted that shared resources / inevitably suffer catastrophic depletion."),
             ("Hardin argued that rational individuals seeking personal gain would overgraze pastures or overfish oceans unless checked by state privatization.", "하딘은 합리적인 개인이 사적 이익을 추구하여 국가의 사유화 조치로 제어되지 않는 한 목초지를 과도 방목하거나 바다를 남획할 것이라고 주장했습니다.", "Hardin argued that rational individuals / seeking personal gain / would overgraze pastures or overfish oceans / unless checked by state privatization."),
             ("However, political economist Elinor Ostrom challenged this binary orthodoxy through exhaustive worldwide empirical fieldwork.", "그러나 정치경제학자 엘리너 오스트롬은 철저한 전 세계 실증 현장 조사를 통해 이러한 이분법적 통념에 도전했습니다.", "However, / political economist Elinor Ostrom / challenged this binary orthodoxy / through exhaustive worldwide empirical fieldwork."),
             ("Studying alpine pastures in Switzerland, irrigation networks in Nepal, and coastal fisheries in Turkey, she uncovered successful self-governance.", "스위스의 알프스 목초지, 네팔의 관개 수로망, 튀르키예의 연안 어장을 연구하며, 그녀는 성공적인 자치 모델을 발견했습니다.", "Studying alpine pastures in Switzerland, / irrigation networks in Nepal, / and coastal fisheries in Turkey, / she uncovered successful self-governance."),
             ("Communities developed intricate customary rules, reciprocal monitoring, and graduated sanctions that effectively sustained common-pool resources across generations.", "공동체들은 세대에 걸쳐 공유 자원을 효과적으로 유지하는 정교한 관습 규범, 상호 감시, 단계적 제재를 발전시켰습니다.", "Communities developed intricate customary rules, / reciprocal monitoring, and graduated sanctions / that effectively sustained common-pool resources / across generations."),
             ("Awarded the Nobel Memorial Prize in Economic Sciences in 2009, Ostrom proved that localized collective action can outperform centralized state bureaucracies.", "2009년 노벨 경제학상을 수상한 오스트롬은 지역화된 집단행동이 중앙 집권적 국가 관료제보다 우수한 성과를 낼 수 있음을 입증했습니다.", "Awarded the Nobel Memorial Prize in Economic Sciences in 2009, / Ostrom proved / that localized collective action / can outperform centralized state bureaucracies.")
         ],
         [("depletion", "n.", "고갈, 소모", "Over-extraction caused severe groundwater depletion in the basin."), ("orthodoxy", "n.", "통념, 정통", "The scientist's radical findings challenged established academic orthodoxy."), ("irrigation", "n.", "관개, 물대기", "Canals provide vital crop irrigation during the dry summer season."), ("reciprocal", "adj.", "상호적인, 호혜적인", "Both nations signed a reciprocal trade and tariff agreement."), ("sanction", "n.", "제재, 처벌", "Violating fishery quotas results in severe monetary sanctions.")],
         [("접속사 unless", "...would overgraze pastures unless checked by state privatization... '만약 ~하지 않는다면' 조건문입니다."), ("과거분사 수동 분사구문", "Awarded the Nobel Memorial Prize in 2009, Ostrom proved... 수상을 나타내는 분사구문입니다.")],
         [
             ("What conventional economic dogma was challenged by Elinor Ostrom?", "엘리너 오스트롬에 의해 도전받은 전통적인 경제학적 통념은 무엇이었나요?", ["That all currencies must be pegged to physical silver coins", "That shared resources must inevitably be privatized or regulated by the state", "That international trade always increases domestic employment", "That manual agricultural labor is less productive than factory machinery"], 1, "공유 자원은 반드시 국가 통제나 사유화를 거쳐야만 보존된다는 통념을 비판했습니다."),
             ("What institutional mechanisms enabled communities to preserve common resources?", "공동체들이 공유 자원을 보존할 수 있게 해 준 제도적 기제는 무엇이었나요?", ["Intricate customary rules, reciprocal monitoring, and graduated sanctions", "Immediate death penalties for minor administrative errors", "Relying on random astrological predictions to divide harvest", "Banning all community members from speaking to one another"], 0, "정교한 관습 규칙, 상호 감시, 단계적 제재라고 명시했습니다."),
             ("Which historic award did Ostrom receive in 2009 for her fieldwork?", "오스트롬은 이러한 연구로 2009년에 어떤 역사적 상을 수상했나요?", ["The Nobel Memorial Prize in Economic Sciences", "The Pulitzer Prize for Investigative Journalism", "The Fields Medal in Theoretical Geometry", "The Olympic Gold Medal in Equestrian Events"], 0, "2009년 노벨 경제학상을 수상했다고 밝혔습니다.")
         ]),

        ("i-42", "Mitochondrial DNA and Human Maternal Lineage", "미토콘드리아 DNA와 인류 모계 조상의 추적", "Evolutionary Genetics & Anthropology", "Nature",
         "재조합 없이 모계로만 유전되는 미토콘드리아 DNA 변이를 추적하여 약 20만 년 전 아프리카의 '미토콘드리아 이브'를 발견한 유전학을 설명합니다.",
         [
             ("Nuclear DNA represents a genetic mosaic shuffled each generation through sexual recombination between maternal and paternal chromosomes.", "핵 DNA는 모계와 부계 염색체 간의 성적 재조합을 통해 매 세대 뒤섞이는 유전적 모자이크를 나타냅니다.", "Nuclear DNA represents a genetic mosaic / shuffled each generation / through sexual recombination / between maternal and paternal chromosomes."),
             ("In stark contrast, mitochondrial DNA (mtDNA) is inherited almost exclusively through the maternal lineage inside the cytoplasm of the egg.", "극명한 대조적으로, 미토콘드리아 DNA(mtDNA)는 난자의 세포질 내부에서 거의 전적으로 모계 혈통을 통해서만 유전됩니다.", "In stark contrast, / mitochondrial DNA (mtDNA) is inherited / almost exclusively through the maternal lineage / inside the cytoplasm of the egg."),
             ("Because mtDNA bypasses chromosomal crossing-over, sequence variations accumulate solely through steady, random clock-like molecular mutations.", "mtDNA는 염색체 교차를 우회하기 때문에, 서열 변이는 오로지 꾸준하고 무작위적인 시계 같은 분자 돌연변이를 통해서만 축적됩니다.", "Because mtDNA bypasses chromosomal crossing-over, / sequence variations accumulate / solely through steady, random clock-like molecular mutations."),
             ("By sequencing mtDNA samples from diverse global populations in 1987, geneticists traced all modern human lineages back to a single maternal ancestor.", "1987년 다양한 전 세계 인구의 mtDNA 샘플을 분석함으로써, 유전학자들은 모든 현대 인류 혈통을 단 하나의 모계 조상으로 추적했습니다.", "By sequencing mtDNA samples from diverse global populations in 1987, / geneticists traced all modern human lineages / back to a single maternal ancestor."),
             ("Dubbed 'Mitochondrial Eve,' this woman lived in eastern or southern Africa roughly two hundred thousand years ago.", "‘미토콘드리아 이브’라 명명된 이 여성은 대략 20만 년 전 동아프리카 또는 남아프리카에서 살았습니다.", "Dubbed 'Mitochondrial Eve,' / this woman lived / in eastern or southern Africa / roughly two hundred thousand years ago."),
             ("This milestone discovery provided definitive genomic evidence supporting the Recent African Origin model of anatomically modern Homo sapiens.", "이 획기적인 발견은 해부학적 현대 인류인 호모 사피엔스의 '아프리카 기원설'을 뒷받침하는 결정적인 유전체 증거를 제공했습니다.", "This milestone discovery provided definitive genomic evidence / supporting the Recent African Origin model / of anatomically modern Homo sapiens.")
         ],
         [("mosaic", "n.", "모자이크, 복합체", "The city's cultural heritage is a vibrant ethnic mosaic."), ("cytoplasm", "n.", "세포질", "Glycolysis takes place in the fluid cytoplasm of the cell."), ("bypass", "v.", "우회하다, 건너뛰다", "The highway bypasses congested city traffic centers."), ("ancestor", "n.", "조상, 선조", "Fossil records link modern birds to reptilian dinosaur ancestors."), ("definitive", "adj.", "결정적인, 최종적인", "DNA testing provided definitive proof of innocence in the trial.")],
         [("In stark contrast", "In stark contrast, mitochondrial DNA is inherited... 극명한 대조를 나타내는 부사구입니다."), ("전치사 By + -ing", "By sequencing mtDNA samples..., geneticists traced... 수단/방법을 나타내는 표현입니다.")],
         [
             ("Why is mitochondrial DNA uniquely suited for tracing maternal lineages?", "미토콘드리아 DNA가 왜 모계 혈통을 추적하는 데 독보적으로 적합한가요?", ["It changes completely every time an individual drinks water.", "It is inherited solely through the maternal line without chromosomal recombination.", "It is located only inside masculine Y chromosomes.", "It can only be detected inside modern computer processors."], 1, "염색체 재조합 없이 오로지 모계를 통해서만 유전되기 때문입니다."),
             ("When and where did 'Mitochondrial Eve' live according to genomic evidence?", "유전체 증거에 따르면 '미토콘드리아 이브'는 언제 어디서 살았나요?", ["Roughly two hundred thousand years ago in Africa", "Ten thousand years ago in the European Alps", "Three million years ago on an Antarctic glacier", "Fifty years ago in a medical research laboratory"], 0, "대략 20만 년 전 아프리카에서 살았다고 명시했습니다."),
             ("What major evolutionary model was corroborated by Mitochondrial Eve research?", "미토콘드리아 이브 연구에 의해 확증된 주요 진화 모델은 무엇이었나요?", ["The Recent African Origin model of Homo sapiens", "The theory that humans evolved from aquatic cetaceans", "The hypothesis of simultaneous multi-continental alien seeding", "The idea that Neanderthals replaced modern humans"], 0, "현대 인류의 아프리카 기원설(Recent African Origin model)이라고 명시했습니다.")
         ]),

        ("i-43", "The Social Psychology of the Bystander Effect", "방관자 효과의 사회심리학과 책임 분산", "Social Psychology", "Journal of Personality and Social Psychology",
         "위급 상황에서 목격자가 많을수록 오히려 도움을 줄 확률이 낮아지는 책임 분산과 다수의 무지를 탐구합니다.",
         [
             ("Following the tragic 1964 murder of Kitty Genovese in New York, psychologists investigated why urban witnesses failed to intervene.", "1964년 뉴욕에서 일어난 키티 제노비스의 비극적인 살인 사건 이후, 심리학자들은 왜 도시 목격자들이 개입하지 못했는지 조사했습니다.", "Following the tragic 1964 murder of Kitty Genovese in New York, / psychologists investigated / why urban witnesses failed to intervene."),
             ("Social psychologists John Darley and Bibb Latané formulated the concept of the bystander effect through controlled laboratory simulations.", "사회심리학자 존 달리와 빕 라타네는 통제된 실험실 시뮬레이션을 통해 방관자 효과라는 개념을 정립했습니다.", "Social psychologists John Darley and Bibb Latané / formulated the concept of the bystander effect / through controlled laboratory simulations."),
             ("Their experiments revealed that the presence of other passive onlookers dramatically diminishes the likelihood that any single individual will offer aid.", "그들의 실험은 다른 수동적인 구경꾼들의 존재가 개별 개인이 도움을 제공할 가능성을 극적으로 감소시킨다는 것을 밝혔습니다.", "Their experiments revealed / that the presence of other passive onlookers / dramatically diminishes the likelihood / that any single individual will offer aid."),
             ("This counterintuitive paralysis is driven primarily by diffusion of responsibility: each bystander assumes someone else has already called authorities.", "이 반직관적인 마비는 주로 책임의 분산에 의해 유발됩니다. 즉, 각 방관자는 다른 누군가가 이미 당국에 신고했을 것이라고 가정합니다.", "This counterintuitive paralysis is driven primarily / by diffusion of responsibility: / each bystander assumes / someone else has already called authorities."),
             ("Additionally, pluralistic ignorance occurs when individuals look to others for behavioral cues; when others appear unbothered, people misinterpret the event as non-urgent.", "또한 다수의 무지는 개인이 행동 단서를 얻기 위해 타인을 쳐다볼 때 발생합니다. 남들이 무심해 보일 때, 사람들은 그 사건을 긴급하지 않은 것으로 오판합니다.", "Additionally, pluralistic ignorance occurs / when individuals look to others for behavioral cues; / when others appear unbothered, / people misinterpret the event as non-urgent."),
             ("Educating citizens on overcoming bystander paralysis—by explicitly assigning tasks to specific individuals—saves lives during acute public emergencies.", "구체적인 개인에게 과업을 명시적으로 부여함으로써 방관자 마비를 극복하도록 시민을 교육하는 것은 급성 공공 비상사태에서 생명을 구합니다.", "Educating citizens on overcoming bystander paralysis / —by explicitly assigning tasks to specific individuals— / saves lives / during acute public emergencies.")
         ],
         [("intervene", "v.", "개입하다, 끼어들다", "The referee intervened to prevent a fight between the players."), ("onlooker", "n.", "구경꾼, 방관자", "Curious onlookers gathered around the damaged sports car."), ("diffusion", "n.", "분산, 확산", "Diffusion of responsibility reduces individual accountability in large committees."), ("unbothered", "adj.", "신경 쓰지 않는, 태연한", "The cat slept quietly on the sofa, unbothered by the loud vacuum."), ("acute", "adj.", "급성의, 극심한", "The hospital admitted patients suffering from acute respiratory failure.")],
         [("동격 명사절 that", "...diminishes the likelihood that any single individual will offer aid... likelihood와 동격인 명사절입니다."), ("동명사 주어", "Educating citizens... saves lives... 동명사구 주어에 따른 단수 동사 saves입니다.")],
         [
             ("What real-world event originally prompted research into the bystander effect?", "원래 어떤 실제 사건이 방관자 효과에 관한 연구를 촉발했나요?", ["The 1964 murder of Kitty Genovese in New York", "The 1912 sinking of the Titanic in the North Atlantic", "The 1969 moon landing broadcast", "The creation of the first telephone exchange in Boston"], 0, "1964년 뉴욕의 키티 제노비스 사건이라고 명시했습니다."),
             ("What is diffusion of responsibility?", "책임의 분산(diffusion of responsibility)이란 무엇인가요?", ["Government taxes being divided among all citizens equally", "Each onlooker assuming that someone else will intervene or call for help", "Teaching responsibility to elementary school pupils", "Spreading emergency medical supplies across disaster zones"], 1, "다른 누군가가 이미 개입하거나 신고했을 것이라고 각자 가정하는 심리입니다."),
             ("How can bystander paralysis be effectively broken during an emergency?", "비상 상황에서 방관자 마비는 어떻게 효과적으로 깨질 수 있나요?", ["By shouting general screams into the sky", "By explicitly pointing to and assigning tasks to specific individuals", "By running away as fast as possible", "By turning off all emergency sirens"], 1, "구체적인 특정 개인을 지목하여 과업을 명시적으로 부여하는 방법이라고 설명했습니다.")
         ]),

        ("i-44", "The Mechanics of Modern Seawater Desalination", "현대 해수 담수화의 공학과 역삼투압 혁신", "Environmental Engineering & Hydrology", "MIT Technology Review",
         "극심한 물 부족에 직면한 세계에서 반투과성 폴리아미드 분리막을 이용해 바닷물을 식수로 바꾸는 역삼투 기술을 다룹니다.",
         [
             ("With freshwater aquifers depleting worldwide, seawater desalination has emerged as a lifeline for arid coastal metropolises.", "전 세계적으로 담수 대수층이 고갈됨에 따라, 해수 담수화는 건조한 해안 대도시의 생명선으로 떠올랐습니다.", "With freshwater aquifers depleting worldwide, / seawater desalination has emerged / as a lifeline / for arid coastal metropolises."),
             ("Historically, thermal distillation boiled ocean brine and condensed water vapor, an energy-intensive method reliant on fossil fuel furnaces.", "역사적으로 열 증류법은 해수 염수를 끓이고 수증기를 응결시켰으나, 이는 화석 연료 화로에 의존하는 에너지 집약적 방법이었습니다.", "Historically, / thermal distillation boiled ocean brine / and condensed water vapor, / an energy-intensive method reliant on fossil fuel furnaces."),
             ("Modern municipal desalination overwhelmingly relies upon reverse osmosis (RO), utilizing synthetic semipermeable polyamide membranes.", "현대 도시 담수화는 합성 반투과성 폴리아미드 분리막을 활용하는 역삼투(RO)에 압도적으로 의존합니다.", "Modern municipal desalination / overwhelmingly relies upon reverse osmosis (RO), / utilizing synthetic semipermeable polyamide membranes."),
             ("High-pressure pumps force pretreated seawater at pressures reaching seventy atmospheres against these microscopic membranes.", "고압 펌프는 전처리된 바닷물을 최대 70기압에 달하는 압력으로 이 미세 분리막에 밀어 넣습니다.", "High-pressure pumps force pretreated seawater / at pressures reaching seventy atmospheres / against these microscopic membranes."),
             ("While pure water molecules squeeze through the nanoscale pores, dissolved sodium, chloride, and heavy minerals are blocked.", "순수한 물 분자는 나노 규모의 기공을 통해 빠져나가는 반면, 용해된 나트륨, 염소, 중금속 광물들은 차단됩니다.", "While pure water molecules squeeze through the nanoscale pores, / dissolved sodium, chloride, / and heavy minerals are blocked."),
             ("Despite triumphs in drought resilience, managing hypersaline brine effluent and reducing electrical energy consumption remain urgent engineering priorities.", "가뭄 회복력에서의 승리에도 불구하고, 고염분 농축 폐수를 관리하고 전력 소비를 줄이는 것은 여전히 시급한 공학적 과제입니다.", "Despite triumphs in drought resilience, / managing hypersaline brine effluent / and reducing electrical energy consumption / remain urgent engineering priorities.")
         ],
         [("aquifer", "n.", "대수층 (지하수를 품은 지층)", "Deep sandstone aquifers supply irrigation water across the Great Plains."), ("distillation", "n.", "증류, 증류법", "Solar distillation purifies saline water in remote coastal villages."), ("semipermeable", "adj.", "반투과성의", "Cell membranes are semipermeable barriers regulating ion transport."), ("effluent", "n.", "폐수, 방출물", "Industrial effluent must be treated before entering municipal waterways."), ("resilience", "n.", "회복력, 탄력성", "The community demonstrated extraordinary economic resilience after the flood.")],
         [("with + 명사 + 분사", "With freshwater aquifers depleting worldwide... 부대상황을 나타내는 with 분사구문입니다."), ("접속사 While 대조", "While pure water molecules squeeze through..., dissolved minerals are blocked... 대조 구문입니다.")],
         [
             ("What technology dominates modern municipal seawater desalination?", "현대 도시 해수 담수화의 주류를 이루는 기술은 무엇인가요?", ["Thermal boiling powered by coal furnaces", "Reverse osmosis using synthetic semipermeable membranes", "Freezing seawater with dry ice blocks", "Filtering salt using coarse gravel and straw beds"], 1, "합성 반투과성 분리막을 이용하는 역삼투(reverse osmosis)라고 명시했습니다."),
             ("At what approximate pressure do high-pressure pumps force seawater against membranes?", "고압 펌프는 대략 몇 기압의 압력으로 바닷물을 분리막에 밀어 넣나요?", ["One atmosphere", "Up to seventy atmospheres", "Ten thousand atmospheres", "Zero pressure under vacuum"], 1, "최대 70기압(reaching seventy atmospheres)에 달하는 압력이라고 설명했습니다."),
             ("What environmental challenge is associated with desalination plants?", "담수화 플랜트와 관련된 주요 환경적 과제는 무엇인가요?", ["Managing hypersaline brine effluent and high electricity consumption", "Creating radioactive nuclear fallout in drinking water", "Freezing the surrounding ocean into permanent ice caps", "Eliminating all humidity from desert clouds"], 0, "고염분 농축수(hypersaline brine) 방출 관리와 전력 소비 저감이라고 서술했습니다.")
         ]),

        ("i-45", "The Evolution of Central Banking and Fiat Currency", "중앙은행의 진화와 법정통화 시스템의 역사", "Monetary Economics & History", "Federal Reserve History",
         "금본위제에서 벗어나 국가의 신용에 기반한 법정화폐와 최종 대부자로서의 중앙은행 금융안정 기능을 살펴봅니다.",
         [
             ("For centuries, economic trade rested upon commodity money—coins minted from physical precious metals like gold and silver.", "수세기 동안 경제적 무역은 금과 은 같은 물리적인 귀금속으로 주조된 주화인 상품 화폐에 기초했습니다.", "For centuries, / economic trade rested upon commodity money / —coins minted from physical precious metals like gold and silver."),
             ("However, metallic standards severely constrained economic expansion because the money supply was shackled to mining yields.", "그러나 금속 본위제는 통화 공급이 광산 채굴량에 묶여 있었기 때문에 경제적 확장을 심각하게 제약했습니다.", "However, / metallic standards severely constrained economic expansion / because the money supply was shackled / to mining yields."),
             ("The establishment of early central banks, notably the Bank of England in 1694, introduced modern fractional-reserve finance.", "1694년 잉글랜드 은행을 필두로 한 초기 중앙은행들의 설립은 현대의 부분 지급준비 금융을 도입했습니다.", "The establishment of early central banks, / notably the Bank of England in 1694, / introduced modern fractional-reserve finance."),
             ("Central banks assumed the pivotal responsibility of acting as lender of last resort during destabilizing banking panics.", "중앙은행은 금융 불안을 야기하는 은행 패닉 상황에서 '최종 대부자'로서 행동하는 중추적인 책임을 맡았습니다.", "Central banks assumed the pivotal responsibility / of acting as lender of last resort / during destabilizing banking panics."),
             ("In 1971, the collapse of the Bretton Woods agreement severed the US dollar's link to gold, inaugurating the era of fiat currency.", "1971년 브레턴우즈 체제의 붕괴는 미국 달러의 금 연계를 단절시키며 법정통화의 시대를 열었습니다.", "In 1971, / the collapse of the Bretton Woods agreement / severed the US dollar's link to gold, / inaugurating the era of fiat currency."),
             ("Today, fiat money derives its value not from tangible vaults of gold, but from legal sovereign authority and market confidence.", "오늘날 법정통화는 만질 수 있는 금고 속 금이 아니라, 법적 주권 당국의 권위와 시장의 신뢰로부터 그 가치를 도출합니다.", "Today, / fiat money derives its value / not from tangible vaults of gold, / but from legal sovereign authority / and market confidence.")
         ],
         [("commodity", "n.", "상품, 원자재", "Gold functioned historically as a universal commodity currency."), ("shackle", "v.", "족쇄를 채우다, 구속하다", "Strict trade tariffs shackled the growth of domestic export manufacturing."), ("pivotal", "adj.", "중추적인, 극히 중요한", "Central bank interest decisions play a pivotal role in curbing inflation."), ("sever", "v.", "단절하다, 끊다", "Diplomatic relations were severed following the naval incident."), ("sovereign", "adj.", "주권의, 독립적인", "Sovereign nations possess legal authority to issue domestic legal tender.")],
         [("분사구문 inaugurating", "...severed the link to gold, inaugurating the era of fiat currency... 결과를 이끄는 분사구문입니다."), ("not A but B", "...derives its value not from tangible vaults of gold, but from legal authority... 가치 원천의 대조 구문입니다.")],
         [
             ("Why did metallic gold standards constrain economic expansion?", "금속 본위제는 왜 경제적 확장을 제약했나요?", ["Because gold is physically toxic to touch", "Because the money supply was restricted by physical mining yields", "Because gold coins melt during summer temperatures", "Because all gold was confiscated by ancient temples"], 1, "통화 공급이 광산 채굴량에 묶여 있었기 때문이라고 설명했습니다."),
             ("What critical stabilization role do central banks fulfill during banking panics?", "은행 패닉 시 중앙은행은 어떤 중요한 안정화 역할을 수행하나요?", ["Acting as the lender of last resort", "Printing advertisements for commercial retail brands", "Closing all public borders to international travelers", "Confiscating all paper bank notes from citizens"], 0, "최종 대부자(lender of last resort) 역할을 수행한다고 밝혔습니다."),
             ("From what does modern fiat currency derive its value?", "현대 법정통화는 어디에서 그 가치를 도출하나요?", ["From physical tons of silver stored in mountain vaults", "From legal sovereign authority and institutional market confidence", "From the weight of ink printed onto each note", "From electromagnetic radio signals sent by weather satellites"], 1, "법적 주권 권위와 시장의 제도적 신뢰로부터 가치가 나온다고 명시했습니다.")
         ]),

        ("i-46", "The Decipherment of the Rosetta Stone", "로제타석의 해독과 고대 이집트 문명의 부활", "Archaeology & Epigraphy", "The British Museum",
         "1799년 발견된 비석의 3개 문자(그리스어, 민중문자, 상형문자)를 통해 샹폴리옹이 상형문자의 음소 체계를 풀어낸 과정을 다룹니다.",
         [
             ("For over a millennium, the meaning of ancient Egyptian hieroglyphic inscriptions remained an impenetrable linguistic mystery.", "천 년이 넘는 세월 동안, 고대 이집트 상형문자 비문의 의미는 난공불락의 언어학적 수수께끼로 남아 있었습니다.", "For over a millennium, / the meaning of ancient Egyptian hieroglyphic inscriptions / remained an impenetrable linguistic mystery."),
             ("In 1799, French soldiers fortifying a redoubt in the Nile Delta city of Rosetta unearthed a heavy granodiorite slab.", "1799년 나일강 삼각주 도시 로제타에서 보루를 보강하던 프랑스 군인들이 육중한 화강섬록암 석판을 발굴했습니다.", "In 1799, / French soldiers fortifying a redoubt / in the Nile Delta city of Rosetta / unearthed a heavy granodiorite slab."),
             ("The stone bore an identical royal decree issued in 196 BCE carved in three distinct scripts: Hieroglyphic, Demotic, and Ancient Greek.", "이 비석에는 기원전 196년에 공포된 동일한 왕실 칙령이 상형문자, 민중문자, 고대 그리스어라는 세 가지 뚜렷한 문자로 새겨져 있었습니다.", "The stone bore an identical royal decree issued in 196 BCE / carved in three distinct scripts: / Hieroglyphic, Demotic, and Ancient Greek."),
             ("Because scholars could readily read Ancient Greek, the stone offered a bilingual Rosetta key to deciphering the forgotten script.", "학자들은 고대 그리스어를 손쉽게 읽을 수 있었기 때문에, 이 비석은 잊힌 문자를 해독할 수 있는 2개 언어의 로제타 열쇠를 제공했습니다.", "Because scholars could readily read Ancient Greek, / the stone offered a bilingual Rosetta key / to deciphering the forgotten script."),
             ("In 1822, French polymath Jean-François Champollion cracked the code by analyzing royal name cartouches, discovering that hieroglyphs represented phonetic sounds.", "1822년 프랑스의 박학다식한 학자 장 프랑수아 샹폴리옹은 왕의 이름을 둘러싼 카르투슈를 분석하여 상형문자가 음소적 소리를 나타냄을 발견함으로써 암호를 풀었습니다.", "In 1822, / French polymath Jean-François Champollion cracked the code / by analyzing royal name cartouches, / discovering that hieroglyphs represented phonetic sounds."),
             ("His breakthrough transformed hieroglyphs from mystical picture puzzles into readable historical chronicles of Pharaohs.", "그의 돌파구는 상형문자를 신비주의적 그림 퍼즐에서 파라오들의 읽을 수 있는 역사적 연대기로 탈바꿈시켰습니다.", "His breakthrough transformed hieroglyphs / from mystical picture puzzles / into readable historical chronicles of Pharaohs.")
         ],
         [("impenetrable", "adj.", "꿰뚫을 수 없는, 이해할 수 없는", "Dense jungle foliage created an impenetrable green wall."), ("slab", "n.", "석판, 두꺼운 조각", "Archaeologists uncovered an inscribed limestone slab near the temple."), ("decree", "n.", "칙령, 포고령", "The emperor issued an imperial decree ordering a national census."), ("polymath", "n.", "박학다식한 사람, 박물학자", "Leonardo da Vinci was a celebrated Renaissance polymath."), ("chronicle", "n.", "연대기, 역사적 기록", "Monks kept detailed chronicles of medieval kings and wars.")],
         [("동명사 전치사 to -ing", "...a bilingual key to deciphering the forgotten script... 'to'가 전치사이므로 동명사가 옵니다."), ("분사구문 discovering", "...cracked the code..., discovering that hieroglyphs represented phonetic sounds... 결과를 설명하는 분사구문입니다.")],
         [
             ("What three scripts were carved on the face of the Rosetta Stone?", "로제타석 표면에는 어떤 세 가지 문자가 새겨져 있었나요?", ["Hieroglyphic, Demotic, and Ancient Greek", "Latin, Hebrew, and Sanskrit", "Cuneiform, Arabic, and Phoenician", "Mayan glyphs, Chinese pictograms, and English"], 0, "상형문자(Hieroglyphic), 민중문자(Demotic), 고대 그리스어(Ancient Greek)라고 명시했습니다."),
             ("How did Jean-François Champollion finally crack the hieroglyphic code in 1822?", "1822년 샹폴리옹은 어떻게 상형문자 암호를 마침내 풀었나요?", ["By analyzing royal name cartouches and realizing symbols represented phonetic sounds", "By matching hieroglyphs to ancient telephone numbers", "By holding the stone up to a magnifying mirror in moonlight", "By feeding the inscription into an electronic translation algorithm"], 0, "왕의 이름을 둘러싼 카르투슈를 분석해 기호가 음소(phonetic sounds)를 나타냄을 깨달았다고 설명했습니다."),
             ("Why was Ancient Greek on the stone so critical for linguists?", "비석에 새겨진 고대 그리스어는 언어학자들에게 왜 그렇게 결정적이었나요?", ["It was an entirely unknown extraterrestrial dialect.", "Scholars could already read Ancient Greek, providing a known translation baseline.", "It explained how to manufacture gunpowder.", "It instructed archaeologists where to dig for hidden gold treasures."], 1, "학자들이 이미 읽을 수 있어서 번역의 기준선을 제공했기 때문이라고 밝혔습니다.")
         ]),

        ("i-47", "The Physics of Magnetic Levitation (Maglev) Trains", "자기부상열차(자기부상)의 물리학과 무마찰 추진", "High-Speed Transit & Electromagnetism", "IEEE Spectrum",
         "바퀴와 레일 간의 물리적 마찰을 없애고 초전도 자석의 반발력과 부상력을 이용해 시속 600km를 주파하는 자기부상 기술을 다룹니다.",
         [
             ("Conventional high-speed rail faces physical limits imposed by mechanical friction, wheel wear, and steel rail adhesion.", "전통적인 고속철도는 기계적 마찰, 바퀴 마모, 강철 레일 점착력에 의해 부과되는 물리적 한계에 직면합니다.", "Conventional high-speed rail faces physical limits / imposed by mechanical friction, / wheel wear, and steel rail adhesion."),
             ("Magnetic levitation, or maglev, circumvents these constraints by lifting the entire passenger train above guideway tracks.", "자기부상(Maglev)은 안내 궤도 레일 위로 승객 열차 전체를 들어 올림으로써 이러한 제약을 우회합니다.", "Magnetic levitation, or maglev, / circumvents these constraints / by lifting the entire passenger train / above guideway tracks."),
             ("Electrodynamic suspension (EDS) utilizes powerful onboard superconducting electromagnets cooled to cryogenic temperatures.", "전기역학적 부상(EDS)은 극저온으로 냉각된 강력한 차량 탑재 초전도 전자석을 활용합니다.", "Electrodynamic suspension (EDS) / utilizes powerful onboard superconducting electromagnets / cooled to cryogenic temperatures."),
             ("As the train accelerates, moving magnetic fields induce opposing eddy currents in the guideway's aluminum coils.", "열차가 가속함에 따라, 움직이는 자기장은 안내 궤도의 알루미늄 코일에 반대 방향의 와전류를 유도합니다.", "As the train accelerates, / moving magnetic fields induce opposing eddy currents / in the guideway's aluminum coils."),
             ("The resulting repulsive magnetic forces push the train up, levitating it ten centimeters in midair with zero mechanical contact.", "그 결과 생겨난 반발 자기력이 열차를 위로 밀어 올려, 기계적 접촉 없이 공중에 10센티미터를 띄웁니다.", "The resulting repulsive magnetic forces push the train up, / levitating it ten centimeters in midair / with zero mechanical contact."),
             ("Propelled by linear synchronous motors, maglev trains achieve cruising velocities surpassing six hundred kilometers per hour in whisper silence.", "선형 동기 모터에 의해 추진되어, 자기부상열차는 속삭이듯 조용하게 시속 600킬로미터를 능가하는 순항 속도를 달성합니다.", "Propelled by linear synchronous motors, / maglev trains achieve cruising velocities / surpassing six hundred kilometers per hour / in whisper silence.")
         ],
         [("circumvent", "v.", "우회하다, 피하다", "Software patches circumvent security vulnerabilities in code."), ("cryogenic", "adj.", "극저온의", "Cryogenic liquid helium cools the MRI scanner's magnetic coils."), ("eddy", "n.", "와류, 소용돌이", "Opposing magnetic eddy currents create electromagnetic braking forces."), ("repulsive", "adj.", "밀어내는, 반발하는", "Like magnetic poles exert repulsive forces against one another."), ("synchronous", "adj.", "동기의, 동기화된", "Synchronous motors rotate in lockstep with the driving alternating current frequency.")],
         [("과거분사 수동 분사구문", "Propelled by linear synchronous motors, maglev trains achieve... 추진 방식을 설명하는 분사구문입니다."), ("전치사 by + -ing", "...circumvents these constraints by lifting the entire train... 수단을 나타내는 by -ing입니다.")],
         [
             ("What fundamental physical barrier of traditional trains is eliminated by maglev?", "자기부상열차에 의해 제거되는 전통 열차의 근본적인 물리적 장벽은 무엇인가요?", ["Atmospheric gravitational pull", "Mechanical wheel-rail friction and wear", "The necessity of carrying passengers", "All electrical battery currents"], 1, "바퀴와 레일 간의 기계적 마찰과 마모라고 설명했습니다."),
             ("How does electrodynamic suspension (EDS) achieve magnetic levitation?", "전기역학적 부상(EDS)은 어떻게 자기부상을 달성하나요?", ["Using high-powered diesel jet thrusters pointed down", "Superconducting magnets induce opposing eddy currents in guideway coils that push up", "By pumping helium gas underneath each passenger carriage", "Through mechanical hydraulic scissor jacks installed along tracks"], 1, "초전도 자석이 궤도 코일에 반발 와전류를 유도하여 열차를 밀어 올린다고 설명했습니다."),
             ("What cruising velocity can modern maglev trains surpass?", "현대 자기부상열차는 얼마를 넘어서는 순항 속도를 달성할 수 있나요?", ["One hundred kilometers per hour", "Six hundred kilometers per hour", "Three thousand meters per second", "The speed of light in vacuum"], 1, "시속 600킬로미터(surpassing 600 km/h)를 능가한다고 명시했습니다.")
         ]),

        ("i-48", "The Wood Wide Web and Mycorrhizal Networks", "숲의 균근 네트워크: 나무들의 비밀스러운 지하 통신", "Plant Ecology & Mycology", "Science",
         "숲속 나무들이 버섯 균사체망을 통해 서로 영양분을 나누고 병충해 경고 신호를 주고받는 공생 생태계를 조명합니다.",
         [
             ("Beneath the quiet floor of an ancient forest lies an astonishing, subterranean biological internet.", "고대 숲의 고요한 바닥 아래에는 놀라운 지하 생물학적 인터넷이 자리 잡고 있습니다.", "Beneath the quiet floor of an ancient forest / lies an astonishing, / subterranean biological internet."),
             ("Trees do not exist as isolated individuals locked solely in fierce Darwinian competition for canopy light.", "나무들은 수관의 햇빛을 얻기 위한 치열한 다윈식 경쟁에만 갇힌 고립된 개체로 존재하지 않습니다.", "Trees do not exist as isolated individuals / locked solely in fierce Darwinian competition / for canopy light."),
             ("Instead, their root tips are colonized by vast, interwoven webs of beneficial mycorrhizal fungal hyphae.", "대신에, 그들의 뿌리 끝은 유익한 균근 곰팡이 균사의 거대하고 얽히고설킨 그물망에 의해 군락을 이룹니다.", "Instead, / their root tips are colonized / by vast, interwoven webs / of beneficial mycorrhizal fungal hyphae."),
             ("In exchange for energy-rich photosynthetic sugars from trees, the fungi deliver crucial phosphorus, nitrogen, and moisture from deep soil.", "나무로부터 에너지가 풍부한 광합성 당분을 공급받는 대가로, 균류는 깊은 흙 속의 필수적인 인, 질소, 수분을 전달합니다.", "In exchange for energy-rich photosynthetic sugars from trees, / the fungi deliver crucial phosphorus, nitrogen, / and moisture from deep soil."),
             ("Furthermore, elder 'mother trees' use this subterranean network to funnel carbon nutrients to shaded juvenile saplings.", "나아가 어미 나무들은 그늘진 어린 묘목들에게 탄소 영양분을 전달하기 위해 이 지하 네트워크를 사용합니다.", "Furthermore, / elder 'mother trees' use this subterranean network / to funnel carbon nutrients / to shaded juvenile saplings."),
             ("When pest insects attack an oak, warning chemical compounds travel through fungal conduits, alerting neighboring trees to produce defensive tannins.", "해충이 참나무를 공격할 때 경고 화학물질이 균류 통로를 통해 이동하여, 이웃 나무들이 방어용 타닌을 생성하도록 경고합니다.", "When pest insects attack an oak, / warning chemical compounds travel through fungal conduits, / alerting neighboring trees / to produce defensive tannins.")
         ],
         [("mycorrhizal", "adj.", "균근의 (곰팡이와 식물 뿌리의 공생체)", "Mycorrhizal associations enhance drought tolerance in desert pine trees."), ("hyphae", "n.", "균사 (곰팡이의 실 같은 균체)", "Microscopic fungal hyphae form vast underground mycelial networks."), ("sapling", "n.", "어린 묘목, 어린나무", "Foresters planted oak saplings to reforest the cleared valley."), ("conduit", "n.", "도관, 통로", "Fiber optic cables are run through protective underground conduits."), ("tannin", "n.", "타닌 (식물의 떫은 방어 화합물)", "Bitter plant tannins deter browsing herbivores from eating leaves.")],
         [("전치사구 문두 도치", "Beneath the quiet floor of an ancient forest lies an astonishing internet... 장소 부사구 도치입니다."), ("분사구문 alerting", "...travel through fungal conduits, alerting neighboring trees to produce... 결과를 설명하는 분사구문입니다.")],
         [
             ("What is the primary reciprocal exchange between trees and mycorrhizal fungi?", "나무와 균근 곰팡이 사이의 주된 상호 교환은 무엇인가요?", ["Trees provide photosynthetic sugars while fungi supply soil minerals and moisture.", "Trees provide oxygen while fungi pump liquid petroleum to branches.", "Trees shade fungi from rain while fungi manufacture plastic bark.", "Trees eat the fungi while fungi eat the tree roots."], 0, "나무는 광합성 당을 주고 균류는 인, 질소, 수분을 공급한다고 설명했습니다."),
             ("How do 'mother trees' support juvenile saplings in shaded forests?", "어미 나무들은 그늘진 숲에서 어린 묘목들을 어떻게 돕나요?", ["By dropping heavy boulders onto competing animal burrows", "By funneling carbon nutrients through the underground fungal network", "By cutting their own roots to create compost", "By growing robotic solar lamps on lower branches"], 1, "지하 균류 네트워크를 통해 탄소 영양분을 전달한다고 명시했습니다."),
             ("What happens across the fungal network when insects attack a tree?", "해충이 나무를 공격할 때 균류 네트워크를 통해 어떤 일이 발생하나요?", ["The fungi poison the surrounding soil immediately.", "Warning chemicals travel to alert neighboring trees to synthesize defensive tannins.", "The trees drop all their leaves within five seconds.", "The forest turns completely blue to frighten insects away."], 1, "경고 화학물질이 전달되어 이웃 나무들이 방어 물질인 타닌을 생성하게 한다고 서술했습니다.")
         ]),

        ("i-49", "Prospect Theory and the Asymmetry of Loss Aversion", "전망 이론과 손실 회피의 심리경제학", "Behavioral Economics", "Econometrica",
         "다니엘 카너먼과 아모스 트버스키가 규명한 이득보다 손실을 2배 이상 더 고통스럽게 느끼는 비합리적 의사결정 구조를 다룹니다.",
         [
             ("Neoclassical utility theory presumed that economic agents weigh gains and losses symmetrically along a linear scale.", "신고전파 효용 이론은 경제 행위자가 선형 척도를 따라 이득과 손실을 대칭적으로 가늠한다고 상정했습니다.", "Neoclassical utility theory presumed / that economic agents weigh gains and losses / symmetrically along a linear scale."),
             ("In 1979, psychologists Daniel Kahneman and Amos Tversky dismantled this axiom by formulating prospect theory.", "1979년 심리학자 다니엘 카너먼과 아모스 트버스키는 전망 이론을 정립함으로써 이 공리를 해체했습니다.", "In 1979, / psychologists Daniel Kahneman and Amos Tversky dismantled this axiom / by formulating prospect theory."),
             ("Empirical experiments demonstrated that humans evaluate financial outcomes relative to a subjective reference point, not absolute wealth.", "실증 실험은 인간이 절대적 부가 아니라 주관적인 기준점을 기준으로 금융 결과를 평가한다는 것을 입증했습니다.", "Empirical experiments demonstrated / that humans evaluate financial outcomes / relative to a subjective reference point, / not absolute wealth."),
             ("Crucially, the subjective pain of losing one hundred dollars is psychologically twice as intense as the joy of winning that same sum.", "결정적으로, 100달러를 잃는 주관적인 고통은 같은 금액을 얻는 기쁨보다 심리적으로 2배나 더 강렬합니다.", "Crucially, / the subjective pain of losing one hundred dollars / is psychologically twice as intense / as the joy of winning that same sum."),
             ("This cognitive asymmetry, termed loss aversion, causes investors to irrationally hold losing stocks while hastily selling winners.", "손실 회피라 명명된 이 인지적 비대칭은 투자자들이 손실 중인 주식은 비합리적으로 보유하는 반면 이익 난 주식은 성급히 매도하게 만듭니다.", "This cognitive asymmetry, termed loss aversion, / causes investors to irrationally hold losing stocks / while hastily selling winners."),
             ("Prospect theory revolutionized economic modeling, demonstrating that predictable psychological biases systematically drive global markets.", "전망 이론은 예측 가능한 심리적 편향이 전 세계 시장을 체계적으로 움직임을 입증하며 경제 모델링을 혁신했습니다.", "Prospect theory revolutionized economic modeling, / demonstrating that predictable psychological biases / systematically drive global markets.")
         ],
         [("symmetrically", "adv.", "대칭적으로, 균형 있게", "The wings of the aircraft are designed symmetrically for stability."), ("axiom", "n.", "공리, 자명한 이치", "Euclid formulated foundational geometric axioms."), ("reference", "n.", "기준, 참조", "The thermostat adjusts heating according to a preset reference temperature."), ("aversion", "n.", "회피, 혐오", "Risk aversion leads conservative investors to buy government treasury bonds."), ("hastily", "adv.", "성급하게, 서둘러", "The treaty was signed hastily before negotiations were finalized.")],
         [("배수사 비교급 as ~ as", "...twice as intense as the joy of winning... 2배 더 강렬하다는 배수사 동등비교입니다."), ("동명사 주어", "...pain of losing one hundred dollars is psychologically twice as intense... 동명사구 주어입니다.")],
         [
             ("What is the central finding regarding loss aversion in prospect theory?", "전망 이론에서 손실 회피에 관한 핵심 발견은 무엇인가요?", ["The pain of a loss is psychologically roughly twice as intense as an equivalent gain.", "Gains are celebrated five times more intensely than losses.", "Humans have zero emotional reaction to losing money.", "Financial profits are always given to government tax authorities."], 0, "손실의 고통이 같은 금액의 이득에 따른 기쁨보다 심리적으로 약 2배 더 강렬하다는 점입니다."),
             ("How do humans evaluate economic outcomes according to Kahneman and Tversky?", "카너먼과 트버스키에 따르면 인간은 경제적 결과를 어떻게 평가하나요?", ["Against absolute cosmic energy levels", "Relative to a subjective psychological reference point rather than absolute wealth", "Based entirely on gold bars held in foreign banks", "By calculating square roots of stock prices on paper"], 1, "절대적 부가 아니라 주관적 기준점(reference point)에 대비하여 평가한다고 밝혔습니다."),
             ("What market behavior is driven by loss aversion among stock investors?", "주식 투자자들 사이에서 손실 회피에 의해 유발되는 시장 행동은 무엇인가요?", ["Holding depreciating losing stocks too long while selling winning stocks prematurely", "Refusing to buy any stocks unless company directors visit their home", "Donating all corporate dividends to overseas charities", "Trading only during midnight hours on Sundays"], 0, "손실 종목을 너무 오래 붙들고 있고 이익 난 종목은 성급히 파는 비합리적 행태라고 설명했습니다.")
         ]),

        ("i-50", "The Nanotechnology of Carbon Nanotubes", "탄소 나노튜브의 나노 기술과 양자 탄도 수송", "Materials Science & Nanotechnology", "Nature Materials",
         "강철보다 100배 강하면서 구리보다 전기를 더 잘 통하는 원자 1겹의 원통형 탄소 나노튜브의 특성을 다룹니다.",
         [
             ("Carbon nanotubes (CNTs) represent one of the most mechanically robust and electrically conductive nanomaterials ever discovered.", "탄소 나노튜브(CNT)는 지금까지 발견된 가장 기계적으로 견고하고 전기 전도성이 뛰어난 나노물질 중 하나입니다.", "Carbon nanotubes (CNTs) represent / one of the most mechanically robust / and electrically conductive nanomaterials / ever discovered."),
             ("Structurally, they consist of seamless cylindrical tubes formed by rolling single-atom-thick sheets of carbon known as graphene.", "구조적으로, 그것들은 그래핀으로 알려진 단일 원자 두께의 탄소 시트를 말아서 형성된 이음매 없는 원통형 튜브로 구성됩니다.", "Structurally, they consist of seamless cylindrical tubes / formed by rolling single-atom-thick sheets of carbon / known as graphene."),
             ("The covalent sp2 carbon-carbon bonds within the hexagonal molecular lattice impart a tensile strength over one hundred times greater than steel.", "육각형 분자 격자 내의 공유 sp2 탄소-탄소 결합은 강철보다 100배 이상 더 큰 인장 강도를 부여합니다.", "The covalent sp2 carbon-carbon bonds / within the hexagonal molecular lattice / impart a tensile strength / over one hundred times greater than steel."),
             ("Remarkably, despite this staggering mechanical resilience, carbon nanotubes possess a fraction of steel's bulk density.", "놀랍게도, 이러한 엄청난 기계적 탄력성에도 불구하고 탄소 나노튜브는 강철 부피 밀도의 일부에 불과한 가벼움을 지닙니다.", "Remarkably, / despite this staggering mechanical resilience, / carbon nanotubes possess / a fraction of steel's bulk density."),
             ("Electrically, electrons travel along the ballistic conduction pathways of pristine nanotubes without encountering scattering resistance.", "전기적으로, 전자는 산란 저항을 겪지 않고 순수한 나노튜브의 탄도 전도 경로를 따라 이동합니다.", "Electrically, electrons travel / along the ballistic conduction pathways / of pristine nanotubes / without encountering scattering resistance."),
             ("These extraordinary physical attributes make carbon nanotubes promising candidates for aerospace composites, biosensors, and next-generation transistors.", "이러한 비범한 물리적 특성은 탄소 나노튜브를 항공우주 복합재, 바이오센서, 차세대 트랜지스터를 위한 유망한 후보로 만듭니다.", "These extraordinary physical attributes / make carbon nanotubes promising candidates / for aerospace composites, biosensors, / and next-generation transistors.")
         ],
         [("robust", "adj.", "견고한, 튼튼한", "The bridge was engineered with robust steel suspension cables."), ("graphene", "n.", "그래핀 (탄소 원자 1개 층의 2차원 벌집 격자)", "Graphene displays extraordinary thermal and electrical conductivity."), ("tensile", "adj.", "인장의, 잡아당기는 힘의", "Carbon fibers exhibit phenomenal tensile strength under load."), ("pristine", "adj.", "완전한, 티 없는, 초기 상태의", "The research team isolated pristine crystals in a vacuum chamber."), ("composite", "n.", "복합재료", "Carbon composites reduce the fuselage weight of modern airliners.")],
         [("과거분사 수식", "...seamless cylindrical tubes formed by rolling single-atom-thick sheets... 튜브를 수식하는 분사구입니다."), ("전치사 without -ing", "...without encountering scattering resistance... 저항을 겪지 않고 이동한다는 표현입니다.")],
         [
             ("What is the basic molecular structure of a single-walled carbon nanotube?", "단일벽 탄소 나노튜브의 기본 분자 구조는 무엇인가요?", ["A seamless cylindrical tube formed by rolling a single-atom-thick graphene sheet", "A solid sphere made of liquid petroleum oil", "A triangular prism composed of copper and zinc alloys", "A hollow rectangular box made of compressed timber cellulose"], 0, "단일 원자 두께의 그래핀 시트를 만 이음매 없는 원통형 튜브라고 설명했습니다."),
             ("How does the tensile strength of carbon nanotubes compare to structural steel?", "탄소 나노튜브의 인장 강도는 구조용 강철과 비교해 어떠한가요?", ["It is ten times weaker than plastic wrap.", "It is over one hundred times greater than steel.", "It is exactly identical to aluminum foil.", "It dissolves completely in ambient air."], 1, "강철보다 100배 이상 더 크다고 명시했습니다."),
             ("How do electrons travel through pristine carbon nanotubes?", "전자는 순수한 탄소 나노튜브를 통해 어떻게 이동하나요?", ["They freeze into solid metal pellets inside the tube.", "Along ballistic conduction pathways without encountering scattering resistance", "They must be manually pushed by magnetic copper wires", "They escape immediately as toxic atmospheric gases"], 1, "산란 저항을 겪지 않고 탄도 전도 경로(ballistic conduction pathways)를 따라 이동한다고 설명했습니다.")
         ])
    ]
    return i_extra

if __name__ == "__main__":
    print(f"Generated extra intermediate passages for 150 target: {len(get_intermediate_150())}")
