# -*- coding: utf-8 -*-
"""
generate_expansion_150_adv.py
Advanced passages a-41 to a-50
Sources: Philosophy of Science, Annual Review of Neuroscience, Harvard University Press, Astrophysical Journal, Molecular Cell
"""

def get_advanced_150():
    a_extra = [
        ("a-41", "Bayesian Epistemology and the Logic of Inductive Updating", "베이즈주의 인식론과 귀납적 신념 갱신의 논리", "Philosophy of Science & Probability", "Philosophy of Science",
         "새로운 관찰 증거가 주어질 때 사전 확률을 사후 확률로 수학적으로 갱신하는 베이즈 추론의 인식론적 정당성을 다룹니다.",
         [
             ("Bayesian epistemology conceptualizes human belief not as a binary state of acceptance or rejection, but as a continuous spectrum of subjective credences.", "베이즈주의 인식론은 인간의 신념을 수용이냐 거부냐의 이분법적 상태가 아니라 주관적 확신도의 연속적인 스펙트럼으로 개념화합니다.", "Bayesian epistemology conceptualizes human belief / not as a binary state of acceptance or rejection, / but as a continuous spectrum / of subjective credences."),
             ("These subjective degrees of belief are formally quantified as probabilities adhering strictly to the classical Kolmogorov axioms.", "이러한 주관적 신념도는 고전 콜모고로프 공리를 엄격히 준수하는 확률로서 형식적으로 정량화됩니다.", "These subjective degrees of belief / are formally quantified as probabilities / adhering strictly / to the classical Kolmogorov axioms."),
             ("Central to this normative framework is Bayes' Theorem, a mathematical formula dictating how rational agents must update beliefs upon encountering empirical evidence.", "이 규범적 프레임워크의 중심에는 합리적 행위자가 실증 증거를 마주했을 때 신념을 어떻게 갱신해야 하는지를 지시하는 수학 공식인 베이즈 정리가 있습니다.", "Central to this normative framework is Bayes' Theorem, / a mathematical formula dictating / how rational agents must update beliefs / upon encountering empirical evidence."),
             ("An agent assigns an initial prior probability to a theoretical hypothesis before observing any experimental data.", "행위자는 어떠한 실험 데이터를 관찰하기 전에 이론적 가설에 초기 사전 확률을 할당합니다.", "An agent assigns an initial prior probability / to a theoretical hypothesis / before observing any experimental data."),
             ("When novel evidence arises, multiplying the prior by the likelihood of that evidence generates the updated posterior probability.", "새로운 증거가 발생할 때, 사전 확률에 그 증거의 우도를 곱함으로써 갱신된 사후 확률이 생성됩니다.", "When novel evidence arises, / multiplying the prior by the likelihood of that evidence / generates the updated posterior probability."),
             ("Bayesianism resolves long-standing philosophical dilemmas surrounding inductive inference by demonstrating how divergent beliefs converge toward objective truth given sufficient empirical observation.", "베이즈주의는 충분한 실증 관찰이 주어질 때 서로 다른 신념들이 어떻게 객관적 진리로 수렴하는지 보여줌으로써 귀납 추론을 둘러싼 오랜 철학적 딜레마를 해결합니다.", "Bayesianism resolves long-standing philosophical dilemmas / surrounding inductive inference / by demonstrating how divergent beliefs converge toward objective truth / given sufficient empirical observation.")
         ],
         [("credence", "n.", "확신도, 신빙성", "The unexpected fossil discovery lent credence to the evolutionary migration hypothesis."), ("normative", "adj.", "규범적인", "Normative epistemology dictates how rational agents ought to reason."), ("prior", "n./adj.", "사전 확률; 이전의", "Assigning an objective prior probability distribution remains contentious."), ("likelihood", "n.", "우도(가능도), 공산", "The statistical likelihood function quantifies the probability of observing data under a hypothesis."), ("converge", "v.", "수렴하다, 모여들다", "Independent experimental measurements converged toward a single gravitational constant.")],
         [("not A but B", "...not as a binary state..., but as a continuous spectrum... 신념의 본질을 대조적으로 정의하는 구문입니다."), ("도치 구문", "Central to this normative framework is Bayes' Theorem... 보어 형용사구가 문두로 나와 도치되었습니다.")],
         [
             ("How does Bayesian epistemology model human belief states?", "베이즈주의 인식론은 인간의 신념 상태를 어떻게 모델링하나요?", ["As rigid binary states of absolute certainty or rejection", "As a continuous spectrum of subjective probability credences", "As random astrological mood fluctuations", "As physical neurological scars on bone surfaces"], 1, "주관적 확신도(credences)의 연속적인 확률 스펙트럼으로 모델링한다고 설명했습니다."),
             ("What is the role of Bayes' Theorem in this epistemological framework?", "이 인식론적 프레임워크에서 베이즈 정리의 역할은 무엇인가요?", ["Prescribing how rational agents mathematically update prior beliefs using new evidence", "Eliminating all mathematics from university curricula", "Predicting winning lottery tickets using horoscopes", "Proving that physical reality does not exist outside language"], 0, "새로운 증거를 사용해 합리적 행위자가 사전 신념을 어떻게 수학적으로 갱신해야 하는지 규정한다고 명시했습니다."),
             ("How does Bayesianism address the classical problem of induction?", "베이즈주의는 고전적인 귀납의 문제를 어떻게 다루나요?", ["By showing that divergent beliefs mathematically converge toward truth with sufficient data", "By banning all experimental laboratory testing", "By declaring that induction is completely impossible and useless", "By replacing human scientists with mechanical coin-toss algorithms"], 0, "충분한 관찰 데이터가 주어지면 서로 다른 신념들이 진리로 수렴함을 보여준다고 설명했습니다.")
         ]),

        ("a-42", "Synaptic Plasticity and Long-Term Potentiation", "시냅스 가소성과 장기 강화(LTP)의 신경생물학", "Cellular Neuroscience", "Annual Review of Neuroscience",
         "학습과 기억 형성의 세포적 기초인 해마 시냅스의 장기 강화(LTP)와 NMDA 수용체 칼슘 유입 메커니즘을 규명합니다.",
         [
             ("The neurobiological foundation of learning and long-term memory formation is mediated by synaptic plasticity—the capacity of neural junctions to modulate connection strength.", "학습과 장기 기억 형성의 신경생물학적 기초는 시냅스 가소성, 즉 연결 강도를 조절하는 신경 접합부의 능력에 의해 매개됩니다.", "The neurobiological foundation of learning and long-term memory formation / is mediated by synaptic plasticity / —the capacity of neural junctions to modulate connection strength."),
             ("The most thoroughly characterized molecular mechanism underlying this adaptation is Long-Term Potentiation (LTP), first discovered in the mammalian hippocampus by Terje Lømo in 1966.", "이러한 적응의 기저에 있는 가장 철저히 규명된 분자 메커니즘은 1966년 테르예 뢰모가 포유류 해마에서 처음 발견한 장기 강화(LTP)입니다.", "The most thoroughly characterized molecular mechanism underlying this adaptation / is Long-Term Potentiation (LTP), / first discovered in the mammalian hippocampus / by Terje Lømo in 1966."),
             ("Induction of classical LTP requires intense, high-frequency stimulation of presynaptic axons, causing sustained depolarization of the postsynaptic dendritic membrane.", "고전적 LTP의 유도는 시냅스 전 축삭의 강렬한 고주파 자극을 필요로 하며, 이는 시냅스 후 수상돌기 막의 지속적인 탈분극을 유발합니다.", "Induction of classical LTP / requires intense, high-frequency stimulation of presynaptic axons, / causing sustained depolarization / of the postsynaptic dendritic membrane."),
             ("This voltage shift displaces magnesium ions blocking the pore of NMDA glutamate receptors, permitting an influx of calcium ions into the dendritic spine.", "이 전압 변화는 NMDA 글루탐산 수용체의 기공을 막고 있던 마그네슘 이온을 밀어내어, 칼슘 이온이 수상돌기 가시 내부로 유입되도록 허용합니다.", "This voltage shift displaces magnesium ions / blocking the pore of NMDA glutamate receptors, / permitting an influx of calcium ions / into the dendritic spine."),
             ("Intracellular calcium triggers protein kinase cascades that recruit additional AMPA receptors to the postsynaptic density, amplifying future synaptic responsiveness.", "세포 내 칼슘은 시냅스 후 치밀질로 추가적인 AMPA 수용체를 동원하는 단백질 키나아제 연쇄반응을 촉발하여, 향후 시냅스 반응성을 증폭시킵니다.", "Intracellular calcium triggers protein kinase cascades / that recruit additional AMPA receptors / to the postsynaptic density, / amplifying future synaptic responsiveness."),
             ("Persistent late-phase LTP necessitates gene transcription and de novo protein synthesis, physically remodeling dendritic spines into stable engram architectures.", "지속적인 후기 단계 LTP는 유전자 전사와 신규 단백질 합성을 필요로 하며, 수상돌기 가시를 안정적인 기억 흔적 구조로 물리적으로 리모델링합니다.", "Persistent late-phase LTP / necessitates gene transcription and de novo protein synthesis, / physically remodeling dendritic spines / into stable engram architectures.")
         ],
         [("junction", "n.", "접합부, 교차로", "Synaptic junctions transfer electrical and chemical information between neurons."), ("depolarization", "n.", "탈분극", "Action potentials initiate when membrane depolarization crosses threshold voltage."), ("displace", "v.", "밀어내다, 대체하다", "Membrane depolarization displaces magnesium ions from the NMDA receptor pore."), ("cascade", "n.", "연쇄 반응", "Intracellular biochemical cascades amplify microscopic cellular signals."), ("engram", "n.", "기억 흔적, 인그램", "Neuroscientists seek physical engrams of consolidated memory inside neural networks.")],
         [("분사구문 causing", "...stimulation of presynaptic axons, causing sustained depolarization... 결과를 설명하는 능동 분사구문입니다."), ("분사구문 permitting", "...displaces magnesium ions..., permitting an influx of calcium... 연속 결과를 나타내는 분사구문입니다.")],
         [
             ("What is the primary biological definition of synaptic plasticity?", "시냅스 가소성의 주된 생물학적 정의는 무엇인가요?", ["The permanent death of cortical brain cells during sleep", "The ability of neural synaptic junctions to modulate their functional connection strength", "The total replacement of all brain tissue with synthetic silicon wires", "The physical migration of neurons from the skull to the stomach"], 1, "신경 접합부가 기능적 연결 강도를 조절할 수 있는 능력이라고 설명했습니다."),
             ("What critical event unblocks NMDA receptors during LTP induction?", "LTP 유도 과정에서 NMDA 수용체의 차단을 해제하는 결정적 사건은 무엇인가요?", ["Voltage-dependent displacement of magnesium ions caused by postsynaptic depolarization", "The freezing of all intracellular water molecules", "Injecting external potassium chloride into the spinal cord", "Complete destruction of all presynaptic vesicles"], 0, "시냅스 후 막의 탈분극으로 인해 마그네슘 이온이 기공에서 밀려나는 것이라 밝혔습니다."),
             ("What is required for the persistence of late-phase LTP?", "후기 단계 LTP의 장기 지속을 위해 무엇이 필수적인가요?", ["Gene transcription and de novo protein synthesis that remodel dendritic spines", "Refraining from sleeping for seventy-two hours", "Complete starvation of glucose from astrocytes", "Dismantling all AMPA receptors from the synapse"], 0, "유전자 전사와 신규 단백질 합성을 통한 수상돌기 가시의 물리적 리모델링이라고 명시했습니다.")
         ]),

        ("a-43", "John Rawls and the Justice of the Original Position", "존 롤스의 원초적 입장과 '무지의 베일' 정의론", "Political Philosophy & Ethics", "Harvard University Press",
         "자신의 사회적 위치를 알지 못하는 '무지의 베일' 가상 상태에서 도출되는 공정으로서의 정의와 차등 원칙을 분석합니다.",
         [
             ("In his monumental 1971 treatise 'A Theory of Justice,' American philosopher John Rawls revitalized normative political philosophy.", "1971년 그의 기념비적인 저작 '정의론'에서 미국 철학자 존 롤스는 규범 정치철학을 재활성화했습니다.", "In his monumental 1971 treatise 'A Theory of Justice,' / American philosopher John Rawls / revitalized normative political philosophy."),
             ("Rawls sought a principled alternative to utilitarianism, which he critiqued for subordinating individual basic liberties to aggregate collective happiness.", "롤스는 개인의 기본적 자유를 총체적인 집단적 행복에 종속시킨다는 이유로 비판했던 공리주의에 대한 원칙적 대안을 모색했습니다.", "Rawls sought a principled alternative to utilitarianism, / which he critiqued / for subordinating individual basic liberties / to aggregate collective happiness."),
             ("To construct an impartial social contract, Rawls introduced a hypothetical thought experiment designated the 'original position.'", "공정한 사회 계약을 구성하기 위해, 롤스는 '원초적 입장'으로 명명된 가상적 사고실험을 도입했습니다.", "To construct an impartial social contract, / Rawls introduced a hypothetical thought experiment / designated the 'original position.'"),
             ("In this deliberative scenario, representative citizens choose constitutional principles behind a conceptual 'veil of ignorance.'", "이 심의 시나리오에서 대표 시민들은 개념적인 '무지의 베일' 뒤에서 헌법적 원칙들을 선택합니다.", "In this deliberative scenario, / representative citizens choose constitutional principles / behind a conceptual 'veil of ignorance.'"),
             ("Deprived of knowledge regarding their own wealth, social status, race, gender, and natural talents, rational parties operate with radical impartiality.", "자신의 부, 사회적 지위, 인종, 성별, 타고난 재능에 대한 지식을 박탈당한 채, 합리적 당사자들은 근본적인 공정성을 가지고 행동합니다.", "Deprived of knowledge regarding their own wealth, / social status, race, gender, and natural talents, / rational parties operate / with radical impartiality."),
             ("Under these risk-averse conditions, parties embrace the Difference Principle: socioeconomic inequalities are permissible only if they maximize the welfare of the least-advantaged.", "이러한 위험 회피적 조건하에서 당사자들은 차등 원칙을 수용합니다. 즉, 사회경제적 불평등은 최소 수혜자의 복지를 극대화할 때에만 허용됩니다.", "Under these risk-averse conditions, / parties embrace the Difference Principle: / socioeconomic inequalities are permissible / only if they maximize the welfare of the least-advantaged.")
         ],
         [("treatise", "n.", "논문, 전문 서적", "Locke published an influential philosophical treatise on government."), ("subordinate", "v.", "종속시키다, 하위에 두다", "The general refused to subordinate national security to commercial interests."), ("impartial", "adj.", "공정한, 치우치지 않은", "Judges must render completely impartial verdicts based on law."), ("deliberative", "adj.", "심의하는, 신중한", "A democratic legislature functions as a supreme deliberative assembly."), ("permissible", "adj.", "허용되는", "Overtime work is legally permissible under strict labor guidelines.")],
         [("과거분사 수동 분사구문", "Deprived of knowledge regarding their own wealth..., rational parties operate... 수동 분사구문입니다."), ("조건절 only if", "...socioeconomic inequalities are permissible only if they maximize... 유일한 허용 조건을 나타냅니다.")],
         [
             ("Why did John Rawls critique classical utilitarianism?", "존 롤스는 고전적 공리주의를 왜 비판했나요?", ["Because it subordinating individual rights and liberties to aggregate collective welfare", "Because utilitarianism demands the abolition of all monetary currency", "Because utilitarianism was invented by ancient military dictators", "Because it prohibits all citizens from owning agricultural land"], 0, "개인의 기본적 권리와 자유를 총체적인 집단적 복지에 종속시켰기 때문입니다."),
             ("What is the function of the 'veil of ignorance' in Rawls' thought experiment?", "롤스의 사고실험에서 '무지의 베일'의 기능은 무엇인가요?", ["Blinding citizens with chemical gas so they cannot read newspapers", "Depriving parties of knowledge of their personal wealth, status, and talents to ensure impartiality", "Preventing citizens from participating in democratic elections", "Hiding military defense budgets from public oversight"], 1, "자신의 부, 지위, 재능을 알지 못하게 하여 원칙 선택의 공정성을 보장하는 장치입니다."),
             ("What does Rawls' famous Difference Principle dictate regarding inequality?", "롤스의 유명한 차등 원칙은 불평등에 관해 무엇을 규정하나요?", ["All citizens must receive mathematically identical financial salaries every day.", "Inequalities are justified only if they maximize advantages for the least-advantaged group.", "Inequalities are strictly determined by physical athletic strength.", "The government must confiscate one hundred percent of all private income."], 1, "사회경제적 불평등은 사회의 최소 수혜자 집단의 이익을 극대화할 때에만 정당화된다고 명시했습니다.")
         ]),

        ("a-44", "Fast Radio Bursts and the Magnetar Engine Hypothesis", "고속 전파 폭발(FRB)과 마그네타 엔진 가설", "Relativistic Astrophysics", "Astrophysical Journal Letters",
         "밀리초 동안 태양이 수일간 방출하는 에너지를 전파로 뿜어내는 수수께끼의 천체 현상과 초강력 자기장 중성자별을 설명합니다.",
         [
             ("First identified by Duncan Lorimer in 2007, Fast Radio Bursts (FRBs) represent one of the most enigmatic cosmic phenomena discovered in modern astrophysics.", "2007년 던컨 로리머에 의해 처음 식별된 고속 전파 폭발(FRB)은 현대 천체물리학에서 발견된 가장 수수께끼 같은 우주 현상 중 하나입니다.", "First identified by Duncan Lorimer in 2007, / Fast Radio Bursts (FRBs) represent / one of the most enigmatic cosmic phenomena / discovered in modern astrophysics."),
             ("These transient astrophysical events unleash immense electromagnetic luminosities—equivalent to the sun's weekly radiant output—within a span of milliseconds.", "이 일시적인 천체물리학적 사건은 수 밀리초의 시간 동안 태양의 일주일 치 방사 에너지 출력에 필적하는 막대한 전자기적 광도를 방출합니다.", "These transient astrophysical events unleash / immense electromagnetic luminosities / —equivalent to the sun's weekly radiant output— / within a span of milliseconds."),
             ("Because the signals propagate across cosmological distances, intergalactic plasma disperses the radio waves, delaying lower frequencies relative to higher ones.", "신호가 우주론적 거리를 가로질러 전파되기 때문에, 은하간 플라스마가 전파를 분산시켜 높은 주파수에 비해 낮은 주파수를 지연시킵니다.", "Because the signals propagate across cosmological distances, / intergalactic plasma disperses the radio waves, / delaying lower frequencies / relative to higher ones."),
             ("This dispersion measure allows astrophysicists to calculate the vast quantity of missing baryonic matter inhabiting the tenuous cosmic web.", "이 분산 측정치는 천체물리학자들이 희박한 우주 거미줄에 서식하는 막대한 양의 '실종된 바리온 물질'을 계산할 수 있게 해줍니다.", "This dispersion measure allows astrophysicists / to calculate the vast quantity / of missing baryonic matter / inhabiting the tenuous cosmic web."),
             ("In 2020, observations established that magnetars—ultradense neutron stars possessing magnetic fields exceeding one hundred trillion gauss—generate repeating FRB bursts.", "2020년 관측은 100조 가우스를 초과하는 자기장을 보유한 극초고밀도 중성자별인 마그네타가 반복되는 FRB 폭발을 생성함을 입증했습니다.", "In 2020, / observations established that magnetars / —ultradense neutron stars possessing magnetic fields exceeding one hundred trillion gauss— / generate repeating FRB bursts."),
             ("Catastrophic crustal fractures or magnetic reconnection shocks trigger coherent relativistic maser emission, illuminating the violent frontier of high-energy physics.", "격변적인 지각 파열이나 자기 재연결 충격파가 결맞는 상대론적 메이저 방출을 촉발하여 고에너지 물리학의 격렬한 최전선을 밝힙니다.", "Catastrophic crustal fractures or magnetic reconnection shocks / trigger coherent relativistic maser emission, / illuminating the violent frontier / of high-energy physics.")
         ],
         [("enigmatic", "adj.", "수수께끼의, 불가사의한", "The Mona Lisa's enigmatic smile has fascinated viewers for centuries."), ("transient", "adj.", "일시적인, 순간적인", "Transient meteor trails vanish within seconds in the night sky."), ("propagate", "v.", "전파하다, 번식하다", "Seismic waves propagate through the solid mantle of the Earth."), ("tenuous", "adj.", "희박한, 가느다란", "The lunar atmosphere is extraordinarily tenuous compared to Earth's."), ("coherent", "adj.", "결맞는, 일관된", "Laser light consists of coherent photons marching in step.")],
         [("과거분사 수동 분사구문", "First identified by Duncan Lorimer in 2007, FRBs represent... 최초 식별을 나타내는 분사구문입니다."), ("분사구문 delaying", "...disperses the radio waves, delaying lower frequencies... 결과를 나타내는 능동 분사구문입니다.")],
         [
             ("What temporal duration characterizes a Fast Radio Burst (FRB)?", "고속 전파 폭발(FRB)의 시간적 지속시간의 특징은 무엇인가요?", ["Several millennia of steady acoustic sound waves", "A transient burst lasting merely milliseconds", "Exactly four months of constant infrared heating", "Twenty-four hours synchronized with Earth's rotation"], 1, "불과 수 밀리초 동안 지속되는 일시적 폭발이라고 명시했습니다."),
             ("How do astrophysicists use the dispersion measure of FRBs?", "천체물리학자들은 FRB의 분산 측정치를 어떻게 활용하나요?", ["To calculate missing baryonic matter distributed throughout the intergalactic medium", "To transmit commercial radio broadcast music across planets", "To steer lunar exploration vehicles across moon craters", "To predict the daily weather over the Pacific Ocean"], 0, "은하간 공간에 분포하는 실종된 바리온 물질을 계산하는 데 활용한다고 밝혔습니다."),
             ("What astronomical object was confirmed in 2020 as a source engine for FRBs?", "2020년에 FRB의 원천 엔진으로 확인된 천체는 무엇이었나요?", ["A magnetar: an ultradense neutron star with extreme magnetic fields", "A frozen asteroid orbiting the rings of Saturn", "An artificial radio satellite launched during the Cold War", "A biological swarm of deep-space glowing microbes"], 0, "극초고자기장 중성자별인 마그네타(magnetar)라고 명시했습니다.")
         ]),

        ("a-45", "Gayatri Spivak and the Problem of the Subaltern Voice", "가야트리 스피박과 '하위주체는 말할 수 있는가'의 탈식민주의", "Post-Colonial Theory & Cultural Studies", "Columbia University Press",
         "서구 학술 담론과 제국주의 지식 체계 속에서 제3자에게 대변당하며 침묵을 강요받는 탈식민 하위주체의 인식론적 폭력을 분석합니다.",
         [
             ("Gayatri Chakravorty Spivak's 1988 canonical essay 'Can the Subaltern Speak?' represents a foundational intervention in post-colonial critical theory.", "가야트리 차크라보르티 스피박의 1988년 대표 에세이 '하위주체는 말할 수 있는가?'는 탈식민 비판 이론의 기초적인 개입을 나타냅니다.", "Gayatri Chakravorty Spivak's 1988 canonical essay 'Can the Subaltern Speak?' / represents a foundational intervention / in post-colonial critical theory."),
             ("Drawing on Antonio Gramsci's concept of the subaltern, Spivak interrogates the condition of marginalized classes denied access to institutional hegemony.", "안토니오 그람시의 '하위주체' 개념을 원용하여, 스피박은 제도적 헤게모니에 대한 접근이 박탈된 소외 계층의 조건을 심문합니다.", "Drawing on Antonio Gramsci's concept of the subaltern, / Spivak interrogates the condition / of marginalized classes / denied access to institutional hegemony."),
             ("She rigorously critiques Western intellectuals who paternalistically claim to speak on behalf of oppressed third-world subjects.", "그녀는 억압받는 제3세계 주체들을 대변한다고 온정주의적으로 주장하는 서구 지식인들을 엄격하게 비판합니다.", "She rigorously critiques Western intellectuals / who paternalistically claim / to speak on behalf of / oppressed third-world subjects."),
             ("Spivak argues that such well-intentioned representation perpetuates epistemic violence by imposing dominant Western conceptual categories onto heterogeneous local experiences.", "스피박은 그러한 선의의 대의 행위가 지배적인 서구 개념 범주를 이질적인 지역 경험에 덧씌움으로써 인식론적 폭력을 영속화한다고 주장합니다.", "Spivak argues / that such well-intentioned representation / perpetuates epistemic violence / by imposing dominant Western conceptual categories / onto heterogeneous local experiences."),
             ("Analyzing the colonial British prohibition of Hindu widow-burning (sati), she demonstrates how subaltern women were co-opted between imperialist rescue narratives and native patriarchal traditions.", "힌두 과부 화장(사티)에 대한 영국 식민 당국의 금지령을 분석하면서, 그녀는 하위주체 여성이 제국주의적 구원 서사와 토착 가부장적 전통 사이에서 어떻게 포섭되었는지를 증명합니다.", "Analyzing the colonial British prohibition of Hindu widow-burning (sati), / she demonstrates / how subaltern women were co-opted / between imperialist rescue narratives / and native patriarchal traditions."),
             ("Her provocative conclusion—that the subaltern cannot speak—highlights not literal muteness, but the structural impossibility of being heard within dominant epistemic frameworks.", "하위주체는 말할 수 없다는 그녀의 도발적인 결론은 문자 그대로의 벙어리 상태가 아니라, 지배적인 인식론적 틀 내에서 경청되는 것의 구조적 불가능성을 강조합니다.", "Her provocative conclusion / —that the subaltern cannot speak— / highlights not literal muteness, / but the structural impossibility / of being heard within dominant epistemic frameworks.")
         ],
         [("canonical", "adj.", "고전적인, 권위 있는", "Shakespeare's tragedies occupy a canonical place in Western literature."), ("hegemony", "n.", "헤게모니, 패권", "The superpower maintained technological hegemony through patent enforcement."), ("paternalistic", "adj.", "가부장적인, 온정주의적인", "Paternalistic colonial policies treated indigenous populations like helpless children."), ("epistemic", "adj.", "인식론적인, 지식의", "Epistemic injustice occurs when a speaker's testimony is discredited due to prejudice."), ("co-opt", "v.", "포섭하다, 가로채다", "The corporate establishment quickly co-opted the revolutionary fashion movement.")],
         [("전치사 on behalf of", "...claim to speak on behalf of oppressed subjects... '~를 대변하여'라는 표현입니다."), ("not A but B", "...highlights not literal muteness, but the structural impossibility of being heard... 핵심 주장의 대조적 강조입니다.")],
         [
             ("What is the primary target of Gayatri Spivak's critique in 'Can the Subaltern Speak?'", "스피박의 에세이 '하위주체는 말할 수 있는가?'에서 주요 비판 대상은 누구인가요?", ["Western intellectuals who paternalistically claim to transparently represent marginalized subjects", "Ancient Greek philosophers who translated Sanskrit poetry", "Medical doctors working in third-world surgical clinics", "Engineers building subways in urban India"], 0, "소외된 주체를 투명하게 대변한다고 주장하는 서구 지식인들의 온정주의적 태도를 비판했습니다."),
             ("What does Spivak mean by 'epistemic violence'?", "스피박이 말하는 '인식론적 폭력'이란 무엇을 의미하나요?", ["Throwing physical stone tablets at students", "Imposing dominant Western conceptual frameworks that erase heterogeneous local subaltern realities", "Refusing to translate textbooks into Latin syntax", "Deleting recorded digital files from university archives"], 1, "지배적인 서구 개념 틀을 부과하여 이질적인 지역 하위주체의 현실을 지워버리는 행위라고 설명했습니다."),
             ("Why does Spivak conclude that 'the subaltern cannot speak'?", "스피박은 왜 '하위주체는 말할 수 없다'고 결론지었나요?", ["Because marginalized groups lack biological vocal cords", "Because dominant institutional structures make it impossible for subaltern voices to be genuinely heard", "Because indigenous laws completely prohibit speech", "Because subaltern populations refuse to communicate with scholars"], 1, "문자 그대로 말을 못 해서가 아니라, 지배적 인식 구조 내에서 진정으로 경청되는 것이 구조적으로 불가능하기 때문이라고 설명했습니다.")
         ]),

        ("a-46", "Information Asymmetry and the Lemons Market Collapse", "정보 비대칭성과 중고차 시장의 역선택", "Microeconomic Information Theory", "Quarterly Journal of Economics",
         "조지 애커로프가 규명한 판매자와 구매자 간의 정보 격차가 어떻게 우량 상품을 시장에서 몰아내고 시장 붕괴로 이어지는지를 다룹니다.",
         [
             ("In 1970, economist George Akerlof published 'The Market for Lemons,' a revolutionary paper exploring the market consequences of asymmetric information.", "1970년 경제학자 조지 애커로프는 정보 비대칭성의 시장적 결과를 탐구하는 혁명적인 논문 '레몬 시장'을 발표했습니다.", "In 1970, / economist George Akerlof published 'The Market for Lemons,' / a revolutionary paper exploring the market consequences / of asymmetric information."),
             ("Neoclassical general equilibrium models classically presumed that all market buyers and sellers possess identical, frictionless access to product quality data.", "신고전파 일반 균형 모델은 전통적으로 모든 시장 구매자와 판매자가 제품 품질 데이터에 동일하고 마찰 없는 접근권을 갖는다고 상정했습니다.", "Neoclassical general equilibrium models classically presumed / that all market buyers and sellers possess identical, / frictionless access to product quality data."),
             ("Akerlof dismantled this assumption by modeling the pre-owned automobile industry, where sellers possess intimate knowledge of vehicle defects while buyers see only generic exterior conditions.", "애커로프는 판매자는 차량 결함에 대한 깊은 지식을 지닌 반면 구매자는 일반적인 외관 상태만 보는 중고차 시장을 모델링함으로써 이 가정을 해체했습니다.", "Akerlof dismantled this assumption / by modeling the pre-owned automobile industry, / where sellers possess intimate knowledge of vehicle defects / while buyers see only generic exterior conditions."),
             ("Because buyers cannot distinguish good cars ('peaches') from defective ones ('lemons'), they rationally will pay only an average blended price.", "구매자는 좋은 차('복숭아')와 결함 있는 차('레몬')를 구별할 수 없기 때문에, 합리적으로 평균 혼합 가격만 지불하려 할 것입니다.", "Because buyers cannot distinguish good cars ('peaches') from defective ones ('lemons'), / they rationally will pay / only an average blended price."),
             ("This discounted average price undercompensates sellers of high-quality vehicles, driving them to withdraw their superior cars from the marketplace entirely.", "이 할인된 평균 가격은 고품질 차량 판매자에게 과소 보상하여, 그들이 자신의 우수한 차량을 시장에서 완전히 철수하도록 만듭니다.", "This discounted average price undercompensates sellers of high-quality vehicles, / driving them to withdraw their superior cars / from the marketplace entirely."),
             ("Consequently, bad products drive out good products in a vicious spiral termed adverse selection, which can ultimately culminate in complete market collapse.", "결과적으로 '역선택'이라 불리는 악순환 속에서 불량 상품이 좋은 상품을 몰아내며, 이는 궁극적으로 완전한 시장 붕괴로 귀결될 수 있습니다.", "Consequently, / bad products drive out good products / in a vicious spiral termed adverse selection, / which can ultimately culminate / in complete market collapse.")
         ],
         [("asymmetric", "adj.", "비대칭의, 불균형의", "Asymmetric information confers strategic advantages upon the informed party."), ("equilibrium", "n.", "균형", "Supply and demand intersect to establish market equilibrium price."), ("generic", "adj.", "일반적인, 포괄적인", "Generic brand medications contain identical active pharmaceutical ingredients."), ("undercompensate", "v.", "과소 보상하다", "Low flat salaries undercompensate exceptional engineering talent."), ("culminate", "v.", "결국 ~로 끝나다, 절정에 달하다", "Decades of boundary friction culminated in open warfare.")],
         [("관계부사 where", "...automobile industry, where sellers possess intimate knowledge... 산업을 상황적으로 수식하는 관계부사입니다."), ("관계대명사 계속적 용법", "...adverse selection, which can ultimately culminate in complete collapse... 선행사 adverse selection을 부연 설명합니다.")],
         [
             ("What economic assumption did George Akerlof challenge in 'The Market for Lemons'?", "조지 애커로프는 '레몬 시장'에서 어떤 경제학적 가정을 비판했나요?", ["That all currencies are backed by physical gold deposits", "That buyers and sellers possess symmetric, perfect product quality information", "That used automobiles never experience mechanical breakdowns", "That free market prices are dictated solely by government decrees"], 1, "구매자와 판매자가 대칭적이고 완벽한 제품 품질 정보를 갖는다는 가정을 비판했습니다."),
             ("Why do buyers in an asymmetric market offer only an average blended price?", "정보 비대칭 시장에서 구매자는 왜 오직 평균 혼합 가격만 제시하나요?", ["Because government tax rules forbid paying higher sums", "Because they cannot differentiate high-quality vehicles from defective lemons", "Because sellers refuse to accept paper bank notes", "Because all buyers want to destroy the automotive industry"], 1, "좋은 품질의 차와 결함 있는 레몬을 구별할 수 없기 때문이라고 설명했습니다."),
             ("What is adverse selection according to the text?", "본문에 따른 역선택(adverse selection)이란 무엇인가요?", ["A process where bad products progressively drive out high-quality goods, potentially collapsing the market", "A democratic procedure for electing municipal mayors", "An algorithmic method for compressing computer software files", "Selecting investment stocks by tossing a random copper coin"], 0, "불량 상품이 고품질 상품을 점진적으로 몰아내어 시장을 붕괴시킬 수 있는 과정이라고 명시했습니다.")
         ]),

        ("a-47", "Autophagy and the Molecular Machinery of Proteostasis", "자가포식(오토파지)과 세포 내 단백질 항상성 기전", "Cellular Biology & Medicine", "Molecular Cell",
         "2016년 노벨 생리의학상을 수상한 오스미 요시노리의 자가포식 연구와 리소좀을 통한 손상 소기관의 분해 및 재활용을 다룹니다.",
         [
             ("Eukaryotic cells must continuously maintain cellular proteostasis by synthesizing new macromolecules while eliminating damaged structures.", "진핵세포는 새로운 거대 분자를 합성하는 동시에 손상된 구조를 제거함으로써 세포 단백질 항상성을 지속적으로 유지해야 합니다.", "Eukaryotic cells must continuously maintain cellular proteostasis / by synthesizing new macromolecules / while eliminating damaged structures."),
             ("Autophagy—derived from the Greek for 'self-eating'—constitutes the primary lysosomal degradation pathway responsible for clearing worn-out organelles.", "그리스어로 '자기 먹기'에서 유래한 자가포식(오토파지)은 노후한 세포소기관을 청소하는 주요 리소좀 분해 경로를 구성합니다.", "Autophagy / —derived from the Greek for 'self-eating'— / constitutes the primary lysosomal degradation pathway / responsible for clearing worn-out organelles."),
             ("Elucidated by Japanese cell biologist Yoshinori Ohsumi in pioneering yeast genetic screens, autophagy relies upon conserved ATG protein complexes.", "선구적인 효모 유전학 스크리닝을 통해 일본의 세포생물학자 오스미 요시노리에 의해 규명된 자가포식은 보존된 ATG 단백질 복합체에 의존합니다.", "Elucidated by Japanese cell biologist Yoshinori Ohsumi / in pioneering yeast genetic screens, / autophagy relies upon / conserved ATG protein complexes."),
             ("Under nutrient deprivation or cellular stress, an isolation membrane nucleates in the cytoplasm, gradually engulfing cytosolic targets.", "영양 결핍이나 세포 스트레스 상황에서, 격리막이 세포질 내에서 형성되어 점차 세포질 표적들을 삼켜나갑니다.", "Under nutrient deprivation or cellular stress, / an isolation membrane nucleates in the cytoplasm, / gradually engulfing cytosolic targets."),
             ("The membrane seals to form a double-membraned vesicle called an autophagosome, which subsequently docks and fuses with an acidic lysosome.", "이 막은 밀폐되어 자가포식소체라 불리는 이중막 소포를 형성하며, 이는 뒤이어 산성 리소좀과 도킹하여 융합합니다.", "The membrane seals / to form a double-membraned vesicle called an autophagosome, / which subsequently docks and fuses / with an acidic lysosome."),
             ("Hydrolases digest the internal cargo into elemental amino acids and lipids, recycling cellular building blocks to sustain viability during starvation.", "가수분해효소들이 내부 화물을 기본 아미노산과 지질로 분해하여, 기아 상태 동안 생존력을 유지하기 위한 세포 구성 요소를 재활용합니다.", "Hydrolases digest the internal cargo / into elemental amino acids and lipids, / recycling cellular building blocks / to sustain viability during starvation.")
         ],
         [("proteostasis", "n.", "단백질 항상성", "Disrupted proteostasis leads to toxic protein aggregation in neurodegenerative diseases."), ("degradation", "n.", "분해, 저하", "Enzymatic degradation of waste polymers cleans up cellular debris."), ("elucidate", "v.", "명명백백히 밝히다, 규명하다", "X-ray crystallography elucidated the double helix architecture of DNA."), ("nucleate", "v.", "핵을 형성하다, 발생하다", "Ice crystals nucleate around microscopic dust particles in subzero clouds."), ("vesicle", "n.", "소포 (세포 내 주머니 구조)", "Synaptic vesicles store neurotransmitters prior to exocytosis.")],
         [("과거분사 수동 분사구문", "Elucidated by Yoshinori Ohsumi in pioneering screens, autophagy relies upon... 규명 과정을 설명하는 분사구문입니다."), ("현재분사 병렬 분사구문", "...into elemental amino acids, recycling cellular building blocks... 결과를 설명하는 분사구문입니다.")],
         [
             ("What biological process is described by the term autophagy?", "자가포식(autophagy)이라는 용어로 설명되는 생물학적 과정은 무엇인가요?", ["The cellular self-digestion and recycling of damaged organelles through lysosomal pathways", "The division of single bacteria into four identical viral particles", "The transmission of voluntary pain signals along spinal nerves", "The photosynthesis of glucose crystals inside plant roots"], 0, "리소좀 경로를 통해 손상된 세포소기관을 자가 분해하고 재활용하는 과정이라고 명시했습니다."),
             ("Who was awarded the Nobel Prize for elucidating the molecular genetics of autophagy?", "자가포식의 분자 유전학을 규명하여 노벨상을 수상한 학자는 누구인가요?", ["Yoshinori Ohsumi", "Louis Pasteur", "Alexander Fleming", "James Watson"], 0, "오스미 요시노리(Yoshinori Ohsumi)라고 명시했습니다."),
             ("What structural vesicle forms to encapsulate damaged cellular components before lysosomal fusion?", "리소좀과 융합하기 전에 손상된 세포 성분을 감싸기 위해 형성되는 구조적 소포는 무엇인가요?", ["A double-membraned vesicle called an autophagosome", "A single-walled plastic capsule", "A solid calcium carbonate crystal bead", "An extracellular lipid droplet floating in blood"], 0, "자가포식소체(autophagosome)라 불리는 이중막 소포라고 설명했습니다.")
         ]),

        ("a-48", "General Relativistic Frame Dragging and Lense-Thirring Precession", "일반 상대성 이론의 좌표계 끌림과 렌제-티링 세차 운동", "Theoretical Gravitational Physics", "Physical Review D",
         "회전하는 거대한 질량이 주변 시공간을 소용돌이치듯 함께 끌고 가는 아인슈타인 시공간 왜곡 현상과 관측 검증을 다룹니다.",
         [
             ("In Albert Einstein's general theory of relativity, a rotating massive astronomical body does not merely warp static surrounding spacetime.", "알베르트 아인슈타인의 일반 상대성 이론에서, 회전하는 거대한 천체는 단순히 정적인 주변 시공간을 휘어지게 할 뿐만이 아닙니다.", "In Albert Einstein's general theory of relativity, / a rotating massive astronomical body / does not merely warp static surrounding spacetime."),
             ("Instead, its rotational momentum actively drags the local spacetime fabric along with its spin, an effect termed frame-dragging.", "대신에, 그 회전 운동량은 국소 시공간 구조를 자신의 자전과 함께 능동적으로 끌어당기며, 이는 '좌표계 끌림(frame-dragging)'이라 불리는 효과입니다.", "Instead, / its rotational momentum actively drags the local spacetime fabric / along with its spin, / an effect termed frame-dragging."),
             ("Formulated theoretically by Austrian physicists Josef Lense and Hans Thirring in 1918, the phenomenon implies that space itself swirls like viscous molasses.", "1918년 오스트리아 물리학자 요제프 렌제와 한스 티링에 의해 이론적으로 정식화된 이 현상은 공간 자체가 끈적끈적한 당밀처럼 소용돌이침을 암시합니다.", "Formulated theoretically by Austrian physicists Josef Lense and Hans Thirring in 1918, / the phenomenon implies / that space itself swirls / like viscous molasses."),
             ("Consequently, a freely falling gyroscope placed in orbit around a rotating planet will inevitably experience relativistic orbital precession.", "결과적으로, 자전하는 행성 주위의 궤도에 놓인 자유 낙하 자이로스코프는 필연적으로 상대론적 궤도 세차 운동을 겪게 됩니다.", "Consequently, / a freely falling gyroscope placed in orbit around a rotating planet / will inevitably experience / relativistic orbital precession."),
             ("NASA's landmark Gravity Probe B satellite mission directly confirmed this subtle Lense-Thirring precession in Earth's gravitational field with exquisite precision.", "NASA의 획기적인 그래비티 프로브 B 위성 미션은 지구 중력장에서 이 미세한 렌제-티링 세차 운동을 정교한 정밀도로 직접 확인했습니다.", "NASA's landmark Gravity Probe B satellite mission / directly confirmed this subtle Lense-Thirring precession / in Earth's gravitational field / with exquisite precision."),
             ("Around supermassive Kerr black holes, frame dragging becomes extreme, creating an ergosphere where nothing can remain at rest relative to distant stars.", "초거대 케어 블랙홀 주변에서 좌표계 끌림은 극단화되어, 먼 별들에 대해 그 어떤 것도 정지 상태를 유지할 수 없는 에르고 영역을 형성합니다.", "Around supermassive Kerr black holes, / frame dragging becomes extreme, / creating an ergosphere / where nothing can remain at rest relative to distant stars.")
         ],
         [("viscous", "adj.", "점성의, 끈적끈적한", "Heavy crude oil is thick and viscous at cold temperatures."), ("precession", "n.", "세차 운동 (회전축이 흔들리며 도는 현상)", "The gravitational pull of the moon causes Earth's axial precession."), ("exquisite", "adj.", "정교한, 극상의", "The watchmaker assembled the clockwork with exquisite craftsmanship."), ("supermassive", "adj.", "초거대 질량의", "A supermassive black hole resides at the center of the Milky Way galaxy."), ("ergosphere", "n.", "에르고 영역 (회전 블랙홀 외부의 시공간 끌림 영역)", "Objects inside the ergosphere are compelled to co-rotate with the black hole.")],
         [("not merely A instead B", "...does not merely warp... Instead, its rotational momentum actively drags... 강조 대조 구문입니다."), ("과거분사 수동 분사구문", "Formulated theoretically by Lense and Thirring..., the phenomenon implies... 이론 정립을 설명하는 분사구문입니다.")],
         [
             ("What is the physical essence of the relativistic frame-dragging effect?", "상대론적 좌표계 끌림 효과의 물리적 본질은 무엇인가요?", ["A rotating massive body dragging surrounding spacetime along with its spin", "Planets emitting electromagnetic radio waves from their polar caps", "Comets losing orbital velocity due to friction with interstellar gas", "Tectonic continental plates drifting across oceanic mantles"], 0, "회전하는 거대 질량이 주변 시공간 구조를 자신의 자전과 함께 능동적으로 끌고 가는 현상이라고 설명했습니다."),
             ("Which satellite mission experimentally confirmed Lense-Thirring precession around Earth?", "어떤 위성 미션이 지구 주변의 렌제-티링 세차 운동을 실험적으로 확인했나요?", ["NASA's Gravity Probe B", "The Hubble Space Telescope", "The Voyager 1 deep space probe", "The Apollo 11 lunar excursion module"], 0, "NASA의 그래비티 프로브 B(Gravity Probe B) 위성 미션이라고 명시했습니다."),
             ("What is the ergosphere surrounding a rotating Kerr black hole?", "회전하는 케어 블랙홀을 둘러싼 에르고 영역(ergosphere)이란 무엇인가요?", ["A region of extreme frame dragging where nothing can remain at rest relative to distant stars", "A solid metal shield constructed by extraterrestrial engineers", "An orbital belt where light travels backwards in time forever", "A frozen chamber of absolute zero thermodynamic temperature"], 0, "시공간 끌림이 극단화되어 먼 별들에 대해 그 어떤 것도 정지 상태로 머무를 수 없는 영역이라고 밝혔습니다.")
         ]),

        ("a-49", "Evolutionary Game Theory and the Dynamics of ESS", "진화 게임 이론과 진화적으로 안정된 전략(ESS)", "Theoretical Evolutionary Biology", "Journal of Theoretical Biology",
         "존 메이너드 스미스가 확립한 생물학적 게임이론과 돌연변이 침입을 방어하는 진화적 안정 전략의 수학적 균형을 분석합니다.",
         [
             ("Classical game theory assumed that players possess cognitive agency, rationally computing optimal strategies to maximize utility payoffs.", "고전 게임이론은 플레이어들이 효용 보상을 극대화하기 위해 최적의 전략을 합리적으로 계산하는 인지적 행위성을 지닌다고 가정했습니다.", "Classical game theory assumed / that players possess cognitive agency, / rationally computing optimal strategies / to maximize utility payoffs."),
             ("In 1973, evolutionary biologist John Maynard Smith reconceptualized game theory by eliminating conscious rationality in favor of natural selection.", "1973년 진화생물학자 존 메이너드 스미스는 의식적인 합리성을 배제하고 자연선택을 도입함으로써 게임이론을 재개념화했습니다.", "In 1973, / evolutionary biologist John Maynard Smith reconceptualized game theory / by eliminating conscious rationality / in favor of natural selection."),
             ("In this evolutionary synthesis, strategies represent inherited behavioral phenotypes, while payoffs are measured strictly in Darwinian reproductive fitness.", "이 진화적 종합에서 전략은 유전된 행동 표현형을 나타내며, 보상은 오로지 다윈식 번식 적합도로 측정됩니다.", "In this evolutionary synthesis, / strategies represent inherited behavioral phenotypes, / while payoffs are measured strictly / in Darwinian reproductive fitness."),
             ("Central to this framework is the Evolutionarily Stable Strategy (ESS)—a strategy that, if adopted by a population, cannot be invaded by any rare mutant.", "이 프레임워크의 중심에는 진화적으로 안정된 전략(ESS)이 있습니다. 즉, 한 집단에 의해 채택될 경우 어떠한 드문 돌연변이 전략에 의해서도 침입당할 수 없는 전략입니다.", "Central to this framework is the Evolutionarily Stable Strategy (ESS) / —a strategy that, if adopted by a population, / cannot be invaded by any rare mutant."),
             ("Through the classic Hawk-Dove matrix, Maynard Smith demonstrated why animal conflicts often settle into restrained ritualized combat rather than lethal escalation.", "고전적인 매-비둘기 행렬을 통해, 메이너드 스미스는 왜 동물들의 갈등이 치명적인 확전 대신 절제된 의례적 전투로 자주 귀결되는지를 증명했습니다.", "Through the classic Hawk-Dove matrix, / Maynard Smith demonstrated / why animal conflicts often settle into restrained ritualized combat / rather than lethal escalation."),
             ("Evolutionary game theory today provides rigorous explanatory power for the emergence of reciprocal altruism, sexual selection, and cooperative biological societies.", "진화 게임 이론은 오늘날 호혜적 이타주의, 성선택, 협동적 생물 사회의 출현에 대해 엄격한 설명력을 제공합니다.", "Evolutionary game theory today provides rigorous explanatory power / for the emergence of reciprocal altruism, / sexual selection, / and cooperative biological societies.")
         ],
         [("phenotype", "n.", "표현형 (유전자가 발현된 신체/행동적 특성)", "Environmental conditions influence the observable physical phenotype of organisms."), ("fitness", "n.", "적합도 (번식 성공도)", "Natural selection favors genetic variations that enhance reproductive fitness."), ("invade", "v.", "침입하다, 침탈하다", "An evolutionarily stable strategy resists invasion by mutant strategies."), ("restrained", "adj.", "절제된, 자제하는", "The diplomat delivered a calm and restrained response to the provocation."), ("altruism", "n.", "이타주의, 이타심", "Eusocial worker bees display extreme reproductive altruism for the hive queen.")],
         [("in favor of", "...eliminating conscious rationality in favor of natural selection... '~을 택하여/대신하여'라는 표현입니다."), ("도치 구문", "Central to this framework is the Evolutionarily Stable Strategy... 형용사 보어구 문두 도치입니다.")],
         [
             ("How does evolutionary game theory replace conscious rationality in classical game theory?", "진화 게임 이론은 고전 게임이론의 의식적 합리성을 무엇으로 대체하나요?", ["With natural selection acting on inherited behavioral phenotypes measured by reproductive fitness", "With superstitious tarot card readings conducted by elders", "With strict government legislation enforced by police forces", "With mathematical calculus calculated by animal brains"], 0, "번식 적합도로 측정되는 유전된 행동 표현형에 작용하는 자연선택으로 대체했다고 설명했습니다."),
             ("What is an Evolutionarily Stable Strategy (ESS)?", "진화적으로 안정된 전략(ESS)이란 무엇인가요?", ["A strategy that cannot be invaded or displaced by any rare mutant strategy once established", "A military battle plan guaranteed to defeat any human army", "A financial strategy for investing in foreign real estate", "A computer code that prevents all software viruses"], 0, "일단 확립되면 어떠한 드문 돌연변이 전략에 의해서도 침입되거나 대체될 수 없는 전략이라고 명시했습니다."),
             ("What behavioral puzzle does the Hawk-Dove matrix explain in animal conflicts?", "매-비둘기 행렬은 동물 간 갈등에서 어떤 행동적 수수께끼를 설명하나요?", ["Why animals frequently engage in restrained, ritualized combat rather than fighting to the death", "Why birds migrate exclusively during hurricane season", "Why predators consume rocks instead of grass in winter", "Why fish refuse to swim in salt water during daylight"], 0, "왜 동물들이 죽을 때까지 싸우는 대신 절제된 의례적 전투를 벌이는지 설명한다고 밝혔습니다.")
         ]),

        ("a-50", "Quantum Decoherence and the Many-Worlds Interpretation", "양자 결어긋남과 다세계 해석의 양자역학", "Quantum Foundations & Metaphysics", "Reviews of Modern Physics",
         "측정 시 파동함수의 신비로운 붕괴를 배제하고 환경과의 얽힘을 통해 평행 우주들이 분기된다는 에버렛 다세계 해석을 탐구합니다.",
         [
             ("The central foundational paradox of quantum mechanics is the measurement problem: how do probabilistic quantum superpositions yield singular macroscopic realities?", "양자역학의 핵심적인 근본 역설은 측정 문제입니다. 즉, 어떻게 확률적인 양자 중첩이 단일한 거시적 현실을 산출하는가 하는 점입니다.", "The central foundational paradox of quantum mechanics / is the measurement problem: / how do probabilistic quantum superpositions / yield singular macroscopic realities?"),
             ("Niels Bohr's orthodox Copenhagen interpretation posited an ad hoc wave function collapse triggered by an external classical observation apparatus.", "닐스 보어의 정통 코펜하겐 해석은 외부의 고전적 관측 장치에 의해 촉발되는 임시방편적인 파동함수 붕괴를 상정했습니다.", "Niels Bohr's orthodox Copenhagen interpretation / posited an ad hoc wave function collapse / triggered by an external classical observation apparatus."),
             ("In 1957, physicist Hugh Everett III proposed a radical resolution known today as the Many-Worlds Interpretation (MWI).", "1957년 물리학자 휴 에버렛 3세는 오늘날 '다세계 해석(MWI)'으로 알려진 급진적인 해결책을 제안했습니다.", "In 1957, / physicist Hugh Everett III proposed a radical resolution / known today as the Many-Worlds Interpretation (MWI)."),
             ("Everett eliminated mysterious non-unitary wave collapse, positing that the universal Schrödinger wave equation applies unceasingly to all physical systems.", "에버렛은 신비주의적인 비유니타리 파동 붕괴를 제거하고, 보편 슈뢰딩거 파동 방정식이 모든 물리 체계에 끊임없이 적용된다고 상정했습니다.", "Everett eliminated mysterious non-unitary wave collapse, / positing that the universal Schrödinger wave equation / applies unceasingly to all physical systems."),
             ("When a microscopic quantum particle interacts with its surrounding thermal environment, quantum decoherence irreversibly entangles the two systems.", "미시적 양자 입자가 주변의 열적 환경과 상호작용할 때, 양자 결어긋남(decoherence)은 두 시스템을 비가역적으로 얽히게 만듭니다.", "When a microscopic quantum particle interacts / with its surrounding thermal environment, / quantum decoherence irreversibly entangles / the two systems."),
             ("This decoherence effectively branches the universal wave function into mutually unobservable, non-interacting parallel macroscopic worlds, preserving determinism across the multiverse.", "이 결어긋남은 보편 파동함수를 상호 관측 불가능하고 상호작용하지 않는 평행한 거시 세계들로 효과적으로 분기시켜, 다중우주 전반에 걸쳐 결정론을 보존합니다.", "This decoherence effectively branches the universal wave function / into mutually unobservable, non-interacting parallel macroscopic worlds, / preserving determinism across the multiverse.")
         ],
         [("superposition", "n.", "중첩", "Quantum bits exist in simultaneous superpositions of zero and one."), ("orthodox", "adj.", "정통의, 전통적인", "He challenged the orthodox cosmological view of an expanding universe."), ("unitary", "adj.", "유니타리의 (양자역학에서 확률의 총합이 1로 보존되는)", "Schrödinger time evolution is strictly deterministic and unitary."), ("decoherence", "n.", "결어긋남, 탈결맞음", "Environmental decoherence destroys quantum superpositions in macroscopic objects."), ("multiverse", "n.", "다중우주", "The multiverse hypothesis implies an ensemble of co-existing parallel realities.")],
         [("분사구문 positing", "...eliminated wave collapse, positing that the equation applies... 부연 설명을 제공하는 능동 분사구문입니다."), ("분사구문 preserving", "...branches the wave function..., preserving determinism across the multiverse... 결과를 나타내는 분사구문입니다.")],
         [
             ("What is the core measurement problem in quantum mechanics?", "양자역학에서 핵심적인 '측정 문제'란 무엇인가요?", ["How probabilistic quantum superpositions translate into singular macroscopic observations", "How to measure the weight of planets with mechanical spring scales", "Why batteries run out of chemical power in winter", "How to count the exact number of atoms in a gold bar"], 0, "확률적인 양자 중첩이 어떻게 단일한 거시적 관찰 결과로 전환되는가 하는 문제라고 설명했습니다."),
             ("How does Hugh Everett III's Many-Worlds Interpretation resolve wave function collapse?", "휴 에버렛 3세의 다세계 해석은 파동함수 붕괴를 어떻게 해결하나요?", ["By eliminating physical wave collapse and positing that the Schrödinger equation applies unceasingly", "By proving that microscopic quantum particles are made of solid iron", "By establishing that observers must wear polarized sunglasses in labs", "By deleting the Schrödinger equation from physics textbooks"], 0, "인위적 파동 붕괴를 배제하고 슈뢰딩거 방정식이 모든 물리 체계에 끊임없이 적용된다고 상정함으로써 해결했습니다."),
             ("What role does quantum decoherence play in the branching of parallel realities?", "양자 결어긋남(decoherence)은 평행 현실의 분기에서 어떤 역할을 하나요?", ["It freezes all parallel universes into absolute darkness.", "It entangles quantum states with the environment, branching the wave function into non-interacting worlds.", "It fuses all parallel universes into one single atomic particle.", "It reverses the flow of cosmological time backwards toward the Big Bang."], 1, "환경과의 얽힘을 통해 파동함수를 상호작용하지 않는 평행 거시 세계들로 분기시킨다고 설명했습니다.")
         ])
    ]
    return a_extra

if __name__ == "__main__":
    print(f"Generated extra advanced passages for 150 target: {len(get_advanced_150())}")
